apiVersion: v1
kind: Namespace
metadata:
  name: newt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newt
  namespace: newt
  labels:
    app.kubernetes.io/name: newt
  annotations:
    secret.reloader.stakater.com/reload: newt
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: newt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: newt
    spec:
      containers:
        - name: newt
          image: fosrl/newt:1.18.1@sha256:7fed6605e0a104a337e1cb903bbb1225f80c7f6e5e56ff1eb1d70c57740d8e0f
          env:
            - name: PANGOLIN_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: newt
                  key: PANGOLIN_ENDPOINT
            - name: NEWT_ID
              valueFrom:
                secretKeyRef:
                  name: newt
                  key: NEWT_ID
            - name: NEWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: newt
                  key: NEWT_SECRET
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
