apiVersion: v1
kind: Namespace
metadata:
  name: newt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newt
  namespace: newt
  labels:
    app: newt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newt
  template:
    metadata:
      labels:
        app: newt
    spec:
      containers:
        - name: newt
          image: fosrl/newt:1.10.3@sha256:41a269865ed59dc16a8412b292380b15bf506d2a3a386eca024ffb29e0d18cd5
          env:
            - name: PANGOLIN_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: newt
                  key: PANGOLIN_ENDPOINT
            - name: NEWT_ID
              valueFrom:
                secretKeyRef:
                  name: newt
                  key: NEWT_ID
            - name: NEWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: newt
                  key: NEWT_SECRET
          resources:
            requests:
              memory: '256Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '200m'
