apiVersion: v1
kind: Namespace
metadata:
  name: newt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newt
  namespace: newt
  labels:
    app.kubernetes.io/name: newt
  annotations:
    secret.reloader.stakater.com/reload: newt
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: newt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: newt
    spec:
      containers:
        - name: newt
          image: fosrl/newt:1.16.0@sha256:345fdeb369be6608d82c41d70637636c78b2c04a6112ff6ec20fc21c48afc899
          env:
            - name: PANGOLIN_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: newt
                  key: PANGOLIN_ENDPOINT
            - name: NEWT_ID
              valueFrom:
                secretKeyRef:
                  name: newt
                  key: NEWT_ID
            - name: NEWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: newt
                  key: NEWT_SECRET
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
