apiVersion: v1
kind: Secret
metadata:
  name: newt
  namespace: newt
type: Opaque
stringData:
  NEWT_ID: ENC[AES256_GCM,data:FW/XPEtwGCj3P9UfPSlR,iv:zhP1EcJBkxAMgXAu/pNNvNik/oiV42+gjVChb7G6nkw=,tag:3kJiROT1kdHzn8Cz9whFCg==,type:str]
  NEWT_SECRET: ENC[AES256_GCM,data:rFKCfElghf28lUt4RtS6RH1zE7X3Y7d3XcKfoySp+iXCe+HV1QfLSEcB2sd/kfgJ,iv:gek+L0g0xDTjZ42FkbuV9ElBzIpr8CmyO6JQaB2TDrM=,tag:1TuCRNBd0yh+sUbSiIYfLg==,type:str]
  PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:PuG6DkCguquLi1u7L4bXBQdNtm0bNCAHcMIu,iv:h8RPfbCOEqbj/EeSmtzH0Wule7vBjmfyD/vgcv3wPIQ=,tag:JUdqQhxck5W6FFZKwm364w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpL0hGWTV3Q0Y1Slc1NERz
        bHBHczhTU21mTUpMMG9QQXVhelZTZWNjM1U0CkhpZHpBVkdCc1p3OXdKL2UwOW9S
        MjdnQ1p2S0Nzc002VmJFMk1waW54dG8KLS0tIHk5Yk9MT1NkQ3FUY2x4bXEwQXJH
        aXkrbXh3SFl2aTZneGZINHlidkJXOEkKTnnhu8DKFVi3SaFDO2bYGPj4TzWqYB8x
        M4XwgU4WoeO/5g7q3+HE0WZhpUs+2YYQ4fKWas5VHA1X8FKFhzowWw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZEl5Z0szN0c1ZW5iekdI
        S2g3Y2tVaWhGOUtBaUdlMFdLWFo0ZHl0WlVzCmxCSnZDRklHNGowSHlLcXpkbHVC
        MHpwVkcrTFpXaUNaLzluNm0vY0d0MDAKLS0tIE5UQnhtc0w0Z2c0SnJUaHBhZExu
        eDJhVGQ2L2FYa3pndVZvYnJGM24rZlkKcMZ9Dg1i4TrxEzcUtsIR78438gzAdAnp
        1SZqxWi7e4ibW3+a0xXUj8QF/Kfckb1BDiQAux1kF3TGRYbZi9OD8Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T16:56:38Z"
  mac: ENC[AES256_GCM,data:akwSMbjeq/PpcukmnaMa9hMWxSecDJDtB2mKhOLBfxzw1FnnuLOu1zK7b+aDxv9lIJHf0hzCP/kDq9lgYFbOXbm1/4/F0/skwqra9r1oG9YsWKPNAF9YvVBVe3LiIWt8tfr2ANrSPht163ORvUM8GdYtGBbl4uk5mciR2DFpkUc=,iv:DB+41maHy4xEP9dW9NFs7ij7x5R69P+jzLCRElZMQaw=,tag:1IEpe0c7rp5xsOCxX/wzpw==,type:str]
  version: 3.13.1
