apiVersion: v1
data:
    NEWT_ID: ENC[AES256_GCM,data:M/Tn6XbOFm3W3J6AmGu9avabr9A=,iv:PwazrJjTKk9nPZ4Y7O0VRrL7rTBt9DQHE+m8Hwm1yWE=,tag:PbGWunfULE6T5GOsrAPO/A==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:NmuTdWmwXhpAPmJ/+srTAZGGCj0n4g8gGdUGTyQ8gKMJQrwLy576hMeEehlPYrI/v1BgBmzDGgoKvg1+1/UeIQ==,iv:J+XlgBvc2vZwtklcYOQM74qPHDPCJxBCDOv37XQFuYc=,tag:bG145RFAoC5SL1aTq1LqIg==,type:str]
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:lMMNHXMYcFdsNmE5UOdmylXWo1SxNyJL8uatRr1W9VCtNnt3,iv:J3d43gQAUV+BLmI5O70DDN02IM9UXRvYzbeWD91Qlp0=,tag:Y4jMzUG2qE+q6QW63yPvKA==,type:str]
kind: Secret
metadata:
    name: newt
    namespace: newt
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV2gybitxTVlRSGVnN3h2
            Tkd1YTV3MlRMdXU4RC9jTzZsQXJwbG5kbnk4Cm1xMVZjRm5FY2xsWnJkUkFuN3dV
            SHB6Rkd5TmZBREd1V3hvdHZSZU90dncKLS0tIGQrenJUUEhYWGxoYkxoSDdMTDY3
            ejh6bWtiWWlTekxMYXp0dXBCUTRocUEKqWJxqJHowQQOQ2kuSIqIu3KmCRxFtu4J
            zS6T9x9qWK7C8uWC99EFe1IMiyszdENO8VOJST7/UpPpB7/mxTPZ+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:C4NiL+LCd/oMrUc2Q8HHgJzyXgyrbijSF7W9Si0IFznEYME9zGNyjr7Zd9jTPYiKSF03aQ/mZTR5qSPCNASZbQqtYw/ZzI+5utQz37LVn/nHli982uQKXAx6rpNVkR7EZBb1tY4jZusoYGEn/I/dVInqEU5FUSnJIM+PJM1xySU=,iv:YQ3s7ntUoksTiB6SsFS1b64+IwTwxrkhOdOINntgUMg=,tag:tq015QnhjdDQd/8b7DL29g==,type:str]
    version: 3.13.1
