apiVersion: v1
kind: Secret
metadata:
  name: newt
  namespace: newt
type: Opaque
stringData:
  NEWT_ID: ENC[AES256_GCM,data:FW/XPEtwGCj3P9UfPSlR,iv:zhP1EcJBkxAMgXAu/pNNvNik/oiV42+gjVChb7G6nkw=,tag:3kJiROT1kdHzn8Cz9whFCg==,type:str]
  NEWT_SECRET: ENC[AES256_GCM,data:rFKCfElghf28lUt4RtS6RH1zE7X3Y7d3XcKfoySp+iXCe+HV1QfLSEcB2sd/kfgJ,iv:gek+L0g0xDTjZ42FkbuV9ElBzIpr8CmyO6JQaB2TDrM=,tag:1TuCRNBd0yh+sUbSiIYfLg==,type:str]
  PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:PuG6DkCguquLi1u7L4bXBQdNtm0bNCAHcMIu,iv:h8RPfbCOEqbj/EeSmtzH0Wule7vBjmfyD/vgcv3wPIQ=,tag:JUdqQhxck5W6FFZKwm364w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZTFUa3J4WGMrWm8zOUpr
        YTQ4SWVHeW1NZjRoWFdpQk5MY1RpUFYraENNCmpkZ1dkZkcybjI2YStub00rYmZP
        cEQrRXZMMGl0dk11WWQrdWx3VW5IMUkKLS0tIC9Fc2paRjBObDFKVTlnTFNReDk1
        dGN5eFBFN2FSeUhBemtRWW4zMzhxUlUKZKJdTof+ooxbf2xAeGrOV+ZhLgXts7/e
        XUjAIcr0lzbtg4Y7Io/KoY/O7qzCahpDpNADldd2sUTWEEvYPWDT4g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T16:56:38Z"
  mac: ENC[AES256_GCM,data:akwSMbjeq/PpcukmnaMa9hMWxSecDJDtB2mKhOLBfxzw1FnnuLOu1zK7b+aDxv9lIJHf0hzCP/kDq9lgYFbOXbm1/4/F0/skwqra9r1oG9YsWKPNAF9YvVBVe3LiIWt8tfr2ANrSPht163ORvUM8GdYtGBbl4uk5mciR2DFpkUc=,iv:DB+41maHy4xEP9dW9NFs7ij7x5R69P+jzLCRElZMQaw=,tag:1IEpe0c7rp5xsOCxX/wzpw==,type:str]
  version: 3.13.1
