apiVersion: v1
data:
    PORKBUN_API_KEY: ENC[AES256_GCM,data:XyAbpNsQrMzkS9xqZwiVzlW8A7iPmmQ129u+/aDNHEF3JuvNfqSAYjLUWvNwLb+JP78Whx265jVInqDW37BwQAO6UugfMnusuGzGkLw9MW9ljFvhlGaVVYIlSVs=,iv:37CXk43hpD2GftCdFrW51esSVfhaFfyW0TC2JnKKB88=,tag:qSIU4eKxUiiSBwAKFE8onA==,type:str]
    PORKBUN_SECRET_API_KEY: ENC[AES256_GCM,data:4eLF7bTosKeHa1Ytmpee+beFtTh3MCHO6uUV43FITxGxAKv7Tiur5tbGuAPuhKCooKc46owmLsS/5pS0IfbsG0KjFNDNuXIcKimCjVMn42JMSA0uLdCaUGtynfc=,iv:nOGKScXPTqgrAUmzJpQqFpN6jHju6eiefcBqnTz0GP0=,tag:/VWQKPLb6E5XZjKqBoJJnQ==,type:str]
kind: Secret
metadata:
    name: porkbun-api-credentials
    namespace: cert-manager
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNm5jRi9YSHZoUVFZZUJm
            Q21wSEVzRHRhbDdWQ0hkNTVLUHFVTVZVeFFJCmtPdzNndUtScnhXMTFUZElNOHUv
            M2NqWm83YUlXVFpRS0ROeFNVbU1uQUUKLS0tIHlHKzBKMk85c1k4UDFSRlFMaGhC
            eTkwNC9KM3FhNk85NVZocjhSajdPc2cK6LCmLgsWJOqr02FlnNUavcbzGOEGjuCl
            mXJbid5TB37vJR2n68rzWya2jdxE8k/TeS4rnI8yKXkkj5+wA2mNTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:Xh91O0D+lOl9p4ZDir/tS5C5J3dkpFFJbQz5TXBxJrp+6StZAJedkeW/Es/I3ikpWnFMQAkB/S0GmKmHUcodHJ++/W05wUz64HqqWKUmQ67D/LlClTMLcsXdCL8dymsMnany68tvDAp5Z+n12OFr5f8jNq1010d51CDgY2CCFUw=,iv:vvMn3oyHKhzoj564H/unBDTRR08dd3AMDKVJBu4N0eg=,tag:2lcjz3W4tzvmtGaLvBqzKw==,type:str]
    version: 3.13.1
