apiVersion: v1
kind: Secret
metadata:
    name: porkbun-api-credentials
    namespace: cert-manager
type: Opaque
stringData:
    PORKBUN_API_KEY: ENC[AES256_GCM,data:B2zIaeNX2HW2JlR2utwp/VSyGAIV411yOSFxqbQdQxmaVvSTt+bUfTmNOcKwqgVkuH+S+1czDt5Hg7Tlkx2Hp52exsw=,iv:cTkgGQUaDBwVHQ0VBkB4YVIkGvLSKszPJsng5ikGyno=,tag:w4+Kcb4+IY7BFHbFaN9l+g==,type:str]
    PORKBUN_SECRET_API_KEY: ENC[AES256_GCM,data:I7aqHTgSI53RLA7+t17jDudsBGQ3jkF4ymmJXV6oVnsBgUDAPXhlRfh/23gmtXBqSnvCsmigcShNiH28q+vmTAcCdCM=,iv:OWRozf7+9g4Jw3wRIgBxV5qXSzqfVSyWMrJBMHKAqDw=,tag:3BPsejuyOSzpNNI0bRaM7g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRFRkTm0ybFFRdyt3VEpO
            VG1YRzRRaTl2Tlk3dFhjM3RmNXByYzMrS1FrCkZHS25YZjdPVWhqQWZTQjF0UWZU
            NjhjNXorY0NFeWtrVmJTSHRsMm9sRWsKLS0tIHFUT09MZnJTY3p6aGIra0k2U3RR
            K2lIMkFmWkozTkdmTDk4MFpGN09TWmsKxf5yRBverjiOWv/asDrCmAUHg0XjHcEF
            1oMpc78dztt2XfeVlhObOGvO/F88dBH5Bl32kng+lM1lvFm0xARWJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T16:56:38Z"
    mac: ENC[AES256_GCM,data:P0sEHsM8hZoHwEe+f6m3SVtgmkhIJaCAe/4G65WkCS1tXJRm07wthXE+w17V9UtdGOyoutO0Z/cw5T7w2BqL5VGvJPRPn9mr+4eUCm0TJEJsHIvSFai/8hvL/BCfCjrz51iYWpz7PkEs2hcOHSDLVECgEabmV/zI5cCOq3X0f2w=,iv:yOSDFk5DmHcqkXlHAg05brprnnICPktG+DKGzPMUWTg=,tag:p5/OtS91WKTHDU2AX6orWw==,type:str]
    version: 3.13.1
