---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: porkbun-api-credentials
  namespace: cert-manager
spec:
  encryptedData:
    PORKBUN_API_KEY: AgBEeu3+e7gnriHhCJfLrrq5CX3ojKmR7vTsqeDTpRpG7Tdm0CPI6Wpc7MA1wfDYJFlfw5uWGfhO0RfP7KwgrYsrU/1tTaMluorEX/WxyXRG43rG8fTv4Bbk8WgQcfn3SMWNSWjk6tNTSdjyHKZnyr2LSLRqjZ2/q6hC1JBr2q/mFTQZ5FRd3w8F1P7Rhge7zXCyyWI3PN+gDQZgQfW5cKEHkyCGhJW08OQ7puBJhVL3Z00lnPMHuAzyV1qXS7P/JXUdtRsGcgwvAVssBQBEtTQ7KrNOl17dF7LdrP9vUy+pKjC8ZUvA5f+1ceuZF1f5DYYhkgJzc6/nPmuNg4vuMVjKj3vS96uFNSXOuLdH4PAaIlSP1wYBwCmzQgw2kQatnMVvyjH/MA0KLAoPdr5nx1aoHE5LGJ/mpYmkaaqbzpU++C/5+Mha3dE3npAP0PczxSdvA4e54YEFah+KbIMZVlhSUUPLuEe/7T7S0Xfi/RJoBfmHjvfLXNAdJ0I8GjRV4HZ24vAkUD0SydiEXeeF0G1jp27+fdqaOq4Km6HKA1qlwf9KxDk1sjm2DJFe3373H1C5/k2A1M2l+K56u4AgJZN6yWhbf39msvlsoi9Wnpd/N4VLpOqeaKrL1uulNYVFwbZIe973wL1MklHEqpIpDsYrEn7ZE3m9pEJ+f7WS0/lSHqpKzK6IxZbUXFuWKrU4vq6obs8JvMIwpbUMbJgbGV3kJuwCH3loukSkU65kbFsrgKXHztcmLTq52qHD+e7LVAz0xvntYkUhO6AXVwAkhsjlpn2P5Q==
    PORKBUN_SECRET_API_KEY: AgCBPza0bXxFDDeCxFzJlocNV9kY2G0cdMIFzf40fxeM9In5ekqrxxcOa/xzba8ba24xHCSZLgNarcKMN/na8tEwxQEj0eS56BlWPUGJRCsUrIuOd9/E8tb0lXsTmXAqaqS53+kIeGC03XXNc2a5iCaZjGzqpVHTvBK5f77LUNkmErmkg/Ys7DSyPPUhTE/UCRjcisctS35/OBmTJbyf7r1vZac926rVL1v4h7b8FRUr1hVXVFVvUj+UmBfsAtczAPPsiNut5nXzl+8QLVss06zZ8EqhK86GpHAok/YtAwJbrDKjZxlTRSfLC+VFk7nzNFAjTJr55rPXxkIXcS3FFM/D14tTT0h4K1R7SvHRIKNLoEnD1r4u9yiK0VF9Xdq8IW3Y8kCLNb4n1mUySN+Hy0vgiDElWSgFgapgbvMv6T/nUk5w86CnXExx0GoK7Ms7Tw03pIQQ95yLePBxUzQUkxwLh/6sgpfZpw86ONqjR3kqJgLWrhAGak7dsyEHh/a9nSQE4fK4/T4mmolRwsfuxtcyRL+ux6QCGt7gWWEITJGa3rvqpnv1M84KfGf1hdyXSFP0yMg6/cXWprOKgRW2Pcxin8Jp+QLxr0DwaRzAuoPl568QrJCigMMAjAFaXI+ObYiTbFnTnwLyd8L8LdsdfIxs0vMfcGy9v7QnUGD4SArEwG7iaWz9WM0+7MC4D8AXVUX5Y15FHmUSP7rZq8yxhpXEk7vpCTsjbV/ghNKq46yrv5NFpjkOfaOP3aY/u0CWAcOdG2fRv9SN8+6Xvp/o7c05FDwl+A==
  template:
    metadata:
      name: porkbun-api-credentials
      namespace: cert-manager
    type: Opaque
# apiVersion: v1
# kind: Secret
# metadata:
#   name: porkbun-api-credentials
#   namespace: cert-manager
# type: Opaque
# stringData:
#   PORKBUN_API_KEY: fixme
#   PORKBUN_SECRET_API_KEY: fixme
