apiVersion: v1
kind: Secret
metadata:
  name: authentik-vars
  namespace: flux-system
type: Opaque
stringData:
  SECRET_AUTHENTIK_GRAFANA_CLIENT_SECRET: ENC[AES256_GCM,data:K6C56clSlhexWVO3kXnJ5iQppX8qXb2vZle5wcEee8lR2kcbiNjCKTRoUpNDltYOo5dXEL3oGkojN5no4cOPFA==,iv:LSVgWEWFuUf6evSnG+IA3cmaGisfQl7OslIv6vES1qA=,tag:aIY4P5/xZVPgEzBecLZqOw==,type:str]
  SECRET_AUTHENTIK_TANDOOR_CLIENT_SECRET: ENC[AES256_GCM,data:YYm0KehsK2k4v0qM95GDt1LmlgilQ8bwbPBNNWpUGmGvvAGXS6SFsJ15FDaSkrB24Vq+avi4mYoTYnZWEelgMA==,iv:p0z3GgxqbVHWPZD94SxU9PgpdgkqGTm+C1CsYKGqF+Y=,tag:qyiBlsy+a8cGgsKaHxUmpQ==,type:str]
  SECRET_AUTHENTIK_WALLOS_CLIENT_SECRET: ENC[AES256_GCM,data:rRMPHNAvzq9d2M6vjd6YsZ/r5uNwulJUTwpOzrIq3nwHjyZHJW2+TQX0V0HhV82kj1A7sCkF/13dZhZLOORVfw==,iv:+/YxBNAoCrd+MiOYE/jT/fxFW2LgwasiDpszcMXwifE=,tag:dZfuu6Fm0P1aHmoPRoAzzA==,type:str]
  SECRET_AUTHENTIK_DAWARICH_CLIENT_SECRET: ENC[AES256_GCM,data:TSPZI+tqO1HHmQNE7l1BTQEXqKkem/e/kPVVdqezJkw7g+Uouy7NQEw3iCMm/DuVDsvUF7bSAJRNe15ZhMmpNg==,iv:wppKq0H2Ve8WdGwbt/c8rfC9Kxh1tfdQ1af6QqkST3Y=,tag:iS3RuaX1gLJ9C/mwWv555g==,type:str]
  SECRET_AUTHENTIK_PAPERLESS_NGX_CLIENT_SECRET: ENC[AES256_GCM,data:onauiaerTWQh+hLCe4s2UjMAUqnYeXfsfifUYPdOkyLaK9Yrws/iOj7e234xQhYQREstxd6pvV4WepnxX50g+g==,iv:e4N5pEFfd6uPNo7wJ8K4H1T3Yb3Px6XWCNY/5gnTi60=,tag:flDyriwjM7GMdvbfRrgXCA==,type:str]
  SECRET_AUTHENTIK_AUDIOBOOKSHELF_CLIENT_SECRET: ENC[AES256_GCM,data:rPbtpKhfJvmgeDR0dz/McFSOgaouI9RNeN2h+NGHhkFYFysfdUCpjiluQ2Q=,iv:pVt6dDT/KEx0lIjXWGv9ZBBzyhT+RXOO7qhAI13tz5M=,tag:R2n6ZRHzogG9jGvEw6DyyA==,type:str]
  SECRET_AUTHENTIK_FORGEJO_CLIENT_SECRET: ENC[AES256_GCM,data:/eQTX3rH06avuejwAo+N/Hd60KV0q63FrbIMVcrjprN3ht68fSVP8aKbnY4=,iv:RoHKqlQ0Tql6h7GGciwyECcVKqWBrlbXbz749WRYLLI=,tag:MudE4Le27B8G3mlG8kAsuQ==,type:str]
  SECRET_AUTHENTIK_AKMIN_EMAIL: ENC[AES256_GCM,data:wBpPMAww6H8rLV8ny1ZbvUpnpYJIGEZq,iv:aJcTIjS1/G/EiZhn4f9tOznZUvNmNeIB5lwtgltFpvM=,tag:ar0eF8CUcL6/rOD1Xzxuag==,type:str]
  SECRET_AUTHENTIK_AKMIN_PASSWORD: ENC[AES256_GCM,data:c9S+dMgRVnF77E2GrEdKoUSbDc0=,iv:T0E8xF4g53tgm33x11jDXe8xS7Dcw1EoeMzwykCO06Y=,tag:2RWC10jVrwe9F7qBvguQ9Q==,type:str]
  SECRET_AUTHENTIK_IMMICH_CLIENT_SECRET: ENC[AES256_GCM,data:MJUfgA1eAN9b910LyiOpcbaypgek5ipIO8AZ9YDlTZxGPdWdHaa0qUZ/UbJ9nkFfeQ34Vd1GxSxRoIAzkftRCQ==,iv:rROMLuStv4kui9/NhORLiUk1IaMkgK7h0kfOkvvM2p0=,tag:aS8ejdXl0XU6o0Ck+7TA0g==,type:str]
  SECRET_AUTHENTIK_CLEANUPARR_CLIENT_SECRET: ENC[AES256_GCM,data:xwVzlxtqXIYLP7ZAoJN/ZWaltTDWunasNSHcVtQ7aCpXuo687bmBxn9svB8YbkaWBWm03vPAMAzHgk5lHPxHFA==,iv:zR9NgzCgWYDRxv2///5aKPA8lGgX+TmKohyiTkwhFTs=,tag:oxjK8BmTJpSqOQtwlQnMdA==,type:str]
  SECRET_AUTHENTIK_JELLYFIN_CLIENT_SECRET: ENC[AES256_GCM,data:FoFJwsgALsKgMqSC68z/QuoYfvZt5rnVp9M0ck22qAZHPRAbXrSG9RDU0hXH1nulZUhdu0it92rKGj7bikS1nA==,iv:ohtPv32L3SnikCcVilb6+iYCsaf8bJNCgrT93hrl6Xc=,tag:VCL5hBOr46vrwQIQEqsrQQ==,type:str]
  SECRET_AUTHENTIK_TREK_CLIENT_SECRET: ENC[AES256_GCM,data:b+6mXY9q7xxX2UOspgupJ+fPQXPyh8Ml5oRKRCcdawy3FJFMjx8H5UHftzpkzz/TetH7cEHuOh2WG8YBTZdyJQ==,iv:24hqsOlTW4bwoBGHwXnLTfgXYSgDr5XUMhwU9Sj40CU=,tag:SqR3YzZG3fJslhliidp7+g==,type:str]
  SECRET_AUTHENTIK_ROMM_CLIENT_SECRET: ENC[AES256_GCM,data:3HLfrQ9xk+YqDaAbSL+pbTO3vYTLSavtamR48O/CXJAMP0lr+TR3gaqJ4xgxGdS02AiYuWUbxnVAyVvghlgH4g==,iv:Kc9eg7l9FRE8XB6fo5Dsh8DaCC/AlP/QVudFKHUKidU=,tag:+G2glOzyO2VB1XSsrP98YA==,type:str]
  SECRET_AUTHENTIK_YAMTRACK_CLIENT_SECRET: ENC[AES256_GCM,data:CUH8rCx6uno0nlDyRRw7NmohZR56mLA8lXkvfgLebsRhFaG78Djrf4IO+ek5CX5IhovPR/aCaZeXC/XEFYrA/Q==,iv:OC++wqm89m5hftY5awWnyqOdCeFgWkMQVpC5onpovK8=,tag:fR2As9Yn80JBYfGYkkaVlA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRnBsV095c3lmZjZ3MXBj
        MzFvUG9EZENiWmduRFh2OVJ5cnB0UU90MUcwCmt2RFJXbmIycjlXa3B2NWp5Sk5D
        WkExWnhPdUNCemFUMjJkaU8zWFQ0cG8KLS0tIENwd2w4K3FxQ01wMUVScS8zeGlX
        ZXMrUk44VGJkSkkzS0l4MFhUZXN4VFEKB+6UpApxx+B3OApBDaCjuxr9cQ6qLrQ+
        OXnuRqGzC43GAMalAv/T1Qd2GypkF0MmO4UZXjVkDwbpHkCmlT5wdw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMzFkeEVTMnUvYmJjdm90
        V0hoQVFXRmhQa0VIZWtJaFJVRWF3QjB4ZGtjCmVUcmNxYndFN3JwdFlyUm1WSUpK
        NkM4ZVRWOTFoMHBrL3huYURsQVpJL0EKLS0tIGN3K2tvcnpLN3lVZ1NpMXZQRzRW
        UGJkcVREQW11SlZjU3lORnREWFRhdncKbN3D0zbmsykzR5mSL4mOoLMNMMTMf/qG
        gHts0eaCiOxS7iYy0FhTHUEoRzTbn33YiDhCMliIFyFH5EbNwKa9/g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-02T20:29:01Z"
  mac: ENC[AES256_GCM,data:BY2JRtI/Mmf7vusWo47WPkRjNZBSftzttJa2te/FvHX2MGhdzjjodp9r6LR21frmE+aP5icZwIP2FH9A5Uo0WSJlqkO4C06r5WDLzfMa0AsmF6omFDtkfm1padRA+a/VnNkmqnCydZU56oXWHOGbzmGYROr02xtU65D8Y3lcIIk=,iv:KHgen7mYT26yp9pn4uNQ2GSSK0iqpdGlXdssctNzfXU=,tag:qprS0hVAJAAqCoxEYU3abA==,type:str]
  version: 3.13.1
