apiVersion: v1
kind: Secret
metadata:
  name: authentik-vars
  namespace: flux-system
type: Opaque
stringData:
  SECRET_AUTHENTIK_GRAFANA_CLIENT_SECRET: ENC[AES256_GCM,data:yRLat+o80O07k7bUaPrbF2pKZQUxiQjcnsmXaxd8qUcaRXJuB/DjcbcuWr/pga5/1LIsjnQF3j0zLUin/QZjEnA=,iv:m2wYty8eMSxDla7T9qU8O1vYvNe091XAHlXzW5LeKmE=,tag:xH9emL/d/98h1mNtgvLyFQ==,type:str]
  SECRET_AUTHENTIK_TANDOOR_CLIENT_SECRET: ENC[AES256_GCM,data:YYm0KehsK2k4v0qM95GDt1LmlgilQ8bwbPBNNWpUGmGvvAGXS6SFsJ15FDaSkrB24Vq+avi4mYoTYnZWEelgMA==,iv:p0z3GgxqbVHWPZD94SxU9PgpdgkqGTm+C1CsYKGqF+Y=,tag:qyiBlsy+a8cGgsKaHxUmpQ==,type:str]
  SECRET_AUTHENTIK_WALLOS_CLIENT_SECRET: ENC[AES256_GCM,data:rRMPHNAvzq9d2M6vjd6YsZ/r5uNwulJUTwpOzrIq3nwHjyZHJW2+TQX0V0HhV82kj1A7sCkF/13dZhZLOORVfw==,iv:+/YxBNAoCrd+MiOYE/jT/fxFW2LgwasiDpszcMXwifE=,tag:dZfuu6Fm0P1aHmoPRoAzzA==,type:str]
  SECRET_AUTHENTIK_DAWARICH_CLIENT_SECRET: ENC[AES256_GCM,data:TSPZI+tqO1HHmQNE7l1BTQEXqKkem/e/kPVVdqezJkw7g+Uouy7NQEw3iCMm/DuVDsvUF7bSAJRNe15ZhMmpNg==,iv:wppKq0H2Ve8WdGwbt/c8rfC9Kxh1tfdQ1af6QqkST3Y=,tag:iS3RuaX1gLJ9C/mwWv555g==,type:str]
  SECRET_AUTHENTIK_PAPERLESS_NGX_CLIENT_SECRET: ENC[AES256_GCM,data:weBGJ8BWn3pgPo3n8zzbuNnT86hjFXVsZvhO0d7eTvX1Ci5AE4N7XHhdzTfQwNk3UATEgGUfq+//fiO94Yn3Rps=,iv:22tBU/l6bdgaEiDqbyZrxI63uBqt3L2HUQU8puoG9cA=,tag:n2jSV73teeKF9MLnoAmFWQ==,type:str]
  SECRET_AUTHENTIK_AUDIOBOOKSHELF_CLIENT_SECRET: ENC[AES256_GCM,data:rPbtpKhfJvmgeDR0dz/McFSOgaouI9RNeN2h+NGHhkFYFysfdUCpjiluQ2Q=,iv:pVt6dDT/KEx0lIjXWGv9ZBBzyhT+RXOO7qhAI13tz5M=,tag:R2n6ZRHzogG9jGvEw6DyyA==,type:str]
  SECRET_AUTHENTIK_FORGEJO_CLIENT_SECRET: ENC[AES256_GCM,data:/eQTX3rH06avuejwAo+N/Hd60KV0q63FrbIMVcrjprN3ht68fSVP8aKbnY4=,iv:RoHKqlQ0Tql6h7GGciwyECcVKqWBrlbXbz749WRYLLI=,tag:MudE4Le27B8G3mlG8kAsuQ==,type:str]
  SECRET_AUTHENTIK_AKMIN_EMAIL: ENC[AES256_GCM,data:wBpPMAww6H8rLV8ny1ZbvUpnpYJIGEZq,iv:aJcTIjS1/G/EiZhn4f9tOznZUvNmNeIB5lwtgltFpvM=,tag:ar0eF8CUcL6/rOD1Xzxuag==,type:str]
  SECRET_AUTHENTIK_AKMIN_PASSWORD: ENC[AES256_GCM,data:c9S+dMgRVnF77E2GrEdKoUSbDc0=,iv:T0E8xF4g53tgm33x11jDXe8xS7Dcw1EoeMzwykCO06Y=,tag:2RWC10jVrwe9F7qBvguQ9Q==,type:str]
  SECRET_AUTHENTIK_IMMICH_CLIENT_SECRET: ENC[AES256_GCM,data:MJUfgA1eAN9b910LyiOpcbaypgek5ipIO8AZ9YDlTZxGPdWdHaa0qUZ/UbJ9nkFfeQ34Vd1GxSxRoIAzkftRCQ==,iv:rROMLuStv4kui9/NhORLiUk1IaMkgK7h0kfOkvvM2p0=,tag:aS8ejdXl0XU6o0Ck+7TA0g==,type:str]
  SECRET_AUTHENTIK_CLEANUPARR_CLIENT_SECRET: ENC[AES256_GCM,data:xwVzlxtqXIYLP7ZAoJN/ZWaltTDWunasNSHcVtQ7aCpXuo687bmBxn9svB8YbkaWBWm03vPAMAzHgk5lHPxHFA==,iv:zR9NgzCgWYDRxv2///5aKPA8lGgX+TmKohyiTkwhFTs=,tag:oxjK8BmTJpSqOQtwlQnMdA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWjJQQ3BtMzgzT21sY0Mr
        N1Nad25SSk9SOFBFbWV6SFlXaHpZQnd0bmdJCkQ5VFFwaUx1MjkrVFdBaW9IUWtj
        aXRTT2dnMURkRjJXYmxvUW9SODlFLzQKLS0tIDQ1SVhhTHJMcEFWb0pOMkswblVE
        VnlzSHJKOWhqaWpJK2x1M1FzeERHVzgKzwbpjcZ+3iOkccJ8uLdSjRqRz/8SpQsI
        p0JCp2fvX7Ck2qTC5mmn3pu+7N4jl0wv23GLCxecFFd/kD3hy27E+Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T05:44:06Z"
  mac: ENC[AES256_GCM,data:u1d8cNh6QNpQc2SMJVyK75AP7wOHKVZRvbNsPQxSOi0wITF7AZ8HmOVzxcPtBgBzDQDWR0r+IHI2Z0K95fvcWP+Lia4mOPqewPLmIHFlWyk4dOmn97pzQAMSFoQcuoAuSa7Kvey2yBY1gZVVqEwBHyUUkmjb3ZJ6ZpVzeJdnUjw=,iv:YYFaJOD+TX6gz0yZaRPDiBjQ6moVk6cKCyVFbO+8yTQ=,tag:h+xQvZWZSpM+K/o14OFANg==,type:str]
  version: 3.13.1
