apiVersion: v1
kind: Secret
metadata:
  name: trek
  namespace: trek
type: Opaque
stringData:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:DFKtHq2EF0OXA4yvduNT8zmC9WR0dIIhPvEUc09uTMOkVuzp0j3UaInPx1ZSSIVBwdavp2nSMlgcLpv4aG19Kg==,iv:ECan3nNQIQVNPaXUoe+ti//2AORroIz7CGkZX7psqKQ=,tag:+GpM5VKyDWooww9U4mg+NA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:jiPLZmMofdBwgeBI2RfiK1l4rPn28Lr6qKenzADx5J7/Ae4Nv2gtV1qERdTs++5yaOOAWEUV17+grlxktNCz1Q==,iv:bmchFAyDVgnPqekUGMKU7oPePJWNJO6vzc9M07lBHdA=,tag:ZjRxDVHVzj0U6RKX8sodXw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqc2tqSG9vQWQ1VjZzL2lp
        MWNNWWYzTldUNG8xZzQxNnNpR3dHMGx0czFvCnR3OGhyVU1DTXMwbnF0eUxhM3dP
        TlRVRk9GTzVwcXh0SUthUWR4RTQ0a1UKLS0tIGxJakRWSnlRa0xTa1Y4ZGJmZ29x
        YjIzU1M4bENLUzNHTkNWbFhJeXQ5SWcKdlHN5CO0kYnFHYEyn80t3lyb2/3nbgbB
        YKmQBORXux5PmJmZRGCbaAI5/KfeSF5pDPNHFQMS0WDaBCeTxeptew==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0akFoMW9EZzZLQTJlV0J3
        Q1Nja01xSWlUam5TK3VsM0JxRHhqVC9lQ3lzCk1sQWtWeFdDM3NROVhLTWFhQndV
        d0g1TUV1dDhLdnNwbDdDbEtJU2p4enMKLS0tIHhCTkFiUnJuR3IxTXc1MzJuZHo0
        TDZXbnpjRUFvNWRmakVFMW1pVGxpOGMK7oAQcSx96EPmoCwjxi6nbbKsOtkrerXN
        DkoGHJ9p6vDDJZ0zReCU3/KWegLDFOZjaTeAI/2VWXzvty69QUlmtA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-27T23:03:50Z"
  mac: ENC[AES256_GCM,data:8+WknVN2FJoY/AiU63g8d1fECr7FUijoRoaPGWS2oYbkDZ3iHbgzJB5HYy7kDY8ZFiX79mwObrgLV0XZq0z4jWjeTqt5AI5bl3h5DSmQcQjVY9nWhl3d4ZUz7ekdzfl2Qnl91tFwgpauHHCjFZtj+JL5zusW4uWUVikIgfE4C3M=,iv:jEG+NtMo3ewAhVEq/1h2G9Kc1qmpsdngR357zgdQCvU=,tag:npU8S/lBtb9h2HdqW95Hxg==,type:str]
  version: 3.13.2
