apiVersion: v1
kind: Secret
metadata:
  name: trek
  namespace: trek
type: Opaque
stringData:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:DFKtHq2EF0OXA4yvduNT8zmC9WR0dIIhPvEUc09uTMOkVuzp0j3UaInPx1ZSSIVBwdavp2nSMlgcLpv4aG19Kg==,iv:ECan3nNQIQVNPaXUoe+ti//2AORroIz7CGkZX7psqKQ=,tag:+GpM5VKyDWooww9U4mg+NA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YXZ0MGFHUDFrQWxLY1lM
        UEM1dDNkSjJHeENTSUdFVGdSK3RjMzJmREJvCjBaVmR0MytPNVZzYzZLaGg0VUJk
        d1M1WFNZRkJTbHovZjNBNXpkZmY0aWsKLS0tIFA4cndmdzJpS2tUa0V4WitPMURZ
        TnpGSlB4TkRPcGdiWlpUeHdDazVKU1UKakdXdHXiW7577EnFw9fUDVp+u/0acKxa
        oQHCXE/MDxR4NtRLYZZsjhkfc33jSifYfmqwQ6NvYDMb8XRQ+rpT6w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-27T22:20:03Z"
  mac: ENC[AES256_GCM,data:+eUYLnxnIH04bNbXMvM4433phCEW7uDwr7CBYuq4ikPn/HaELCP5nwZrhJ6oy97qzhaH8uE0mCg7JKPB1vCStRjg+TtyPEGl7IcGTA++KbcuhfWaHitcQZcBRLMJFLo0HOr1mzNd5wMokQqL/QzopInOvtJgfztXdptEwgjRsvg=,iv:rbLObwF4ikHcyCFvSrwpuBV2aHCozZxEodNXnnsU/w0=,tag:qLqbLq6Nfywcif35kjJ7Uw==,type:str]
  version: 3.13.2
