apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seerr
  namespace: seerr
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Seerr"
    gethomepage.dev/description: "Media request management"
    gethomepage.dev/group: "media"
    gethomepage.dev/icon: "overseerr.png"
    gethomepage.dev/href: "https://seerr.item.fyi"
    gethomepage.dev/siteMonitor: "http://seerr.seerr.svc.cluster.local"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=seerr"
    gethomepage.dev/widget.type: "seerr"
    gethomepage.dev/widget.url: "http://seerr.seerr.svc.cluster.local"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_SEERR_TOKEN}}"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`seerr.item.fyi`)
      services:
        - name: seerr
          port: 80
  tls: {}
