apiVersion: v1
kind: Secret
metadata:
    name: dawarich
    namespace: dawarich
type: Opaque
stringData:
    DATABASE_PASSWORD: ENC[AES256_GCM,data:e+tclAsoQUi+nar8Ja4N6JvkRcY=,iv:sQwIvuSukrw4wkTxYeUwj3ZtzQP5nkXn8Bbs2RQwR2E=,tag:hGd+JXQBvais7TQ4BUXVnQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:rXt4xhBjDqM=,iv:G1MBZZ71xv+WBINTgJx/zB0gRKMatJh2ZXVSj8qeR2A=,tag:YRXouCR8sP/3Guo8wa7ZRw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:UCYUO81xUvv0PgNRAc8TkjAgiDYFIw4dDZLMOw/cu97A8rSXPAzYKbGOVoEp4LzE3hVkzEDfQXth7LWjBgDwog==,iv:KOulY393SCZnuEMkLwCDLgOsHeDl3flvVFTzXOM3m8U=,tag:157PJJTctzGKH/9FO923aA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZ1JSa1pjelFRaFkrY2Vp
            Zk5ZSm5mbG8wK0EzdlhLVGJwTmltTHI2SzMwCnp4WVMvT2ovWXRxS2J6c001L1c3
            bjUzUS9VU0dNQTJNdHl2bSs0alJoQlkKLS0tIE9ZSGFJMFFhcG5ZQ2hZMUZJbjdN
            U21xSVJvMlpuQjZ5eUhNbTJhcGlFRWMK4k7mP08ymC4YBo4OxH6jo6sR1Gx4ABkv
            IRU9j24JFveGV0fMCVCKf3YULGsjBJbUjJOQUeEsG+VcdFQtPRU8Iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T16:56:38Z"
    mac: ENC[AES256_GCM,data:s7A9Nh13e8F+G5vMFGs4JM+ulLNpMJ5pS57e3o0w2xMIMOP12SOc1av7yjGCuDReo6j1FH8t1MrUOJi5/QcQ8tusJ0SHL8tbFckBcs48sZr9nuVake/bB7TkrUYwlp/J1c5+Dthn79SPVV3MmrWq5awqM/NsejWaxdHpoPQSZXw=,iv:dlwnJplnUyRVSb1ZJmR2f0vSVFEB3I4M6HGwGLbiIBo=,tag:6dDewuTW5x07D8yia53F6g==,type:str]
    version: 3.13.1
