---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dawarich
  namespace: dawarich
spec:
  encryptedData:
    DATABASE_PASSWORD: AgCYDdFolSVF6yNAKWmEZd+1+VMF6XA6BqtgVGSrYrGQxthcPiX/o4VmnSwu9NPcO4PQKBDpT3sD100ryB+nHeWAT0mXL8/6+CQqCIi4sY0I54d/nKHkXwQf3VwvmcZ4Z51ewTCmEzJbKlN140LvUvDX5hHxrSot5dksA0fctglvVSriTnfzSnZhKZ9rzuEo+PUvmhDuv+LiTV1+WytqTGTt44YANJp9yFdqQln+tNlAVo8jVjAdPXgCFr6Sq6MV3TTXDF6wEpb2rB7EvibsMNTXR8I2JR4EcFntvNrKWxM2VFAN02d0R1b9uCOCU0ZKDBO/SKHzVvB3K+MThy267CAwzKgjyMe6RzwdKQ+AfBNEZONgxbxsy6XsUspqwZAYz6NSZLelACAzOzl/3daNxITFQdKgPqIBuX6HS7BoC483RATmaWS/8JDeeNrTexgX/PBRyn6uDLNsR47y1TRLFxxjLe9O86evocokl7cpT1qDUjA2yURZzah9ZGe18UjZug6y/8JhPXPDI/GhD+Ebad7GB6vWiP/o6kSZLBAXDRHJCd4Y5syvSALBCEFRxrzo+fscp/SkB5nIEq8EQo+BybMkICRah5WkE1xixVa63VPo6ySFP6fB+VHHHCkMZ4SBWnUS8GgzlJhLWaWGaTyCwXmtEPOrgRssvXF8ZjmDQ8h2Q6Zi+0Pq/Tfqq8D9PSj0D++MEcUvH76Byf7tSbC7rHTvaEPiww==
    OIDC_CLIENT_ID: AgCWQ/yRxa0iAx9KqYoZZV1H7rPpcQJvkVDIi9/Fn8S2KaQlSZFRvFYdwceT6GUv83uuAgeVoBoB+5Y86OB1idyghyOTk6XfQe02tSXyqBsE997TrQAzRYZs+u2h6CSVDiZSlzIWAqVogBVKWcS0sAMlfubvYPTZVHnPBUOX5dYjYjZTA3+SFExKLs8bddF3a5vMTyJ+bBqDosW0bn9jg1ingwciy/qjekACBcDr18aX7JV03M+1MnbUeZPP0tBOwe4FAExDfqr5GGdJKsr75NxC2VRRNGmo2SrS5aiKaaepzn3MueeEPy/RBv4kvWlt+tDPuoXPBLcFvbZCeL2PQbKjdnkZ44DoqR96REeYP5REz0qvzEZVDbacaEJN4zd+Ou3WDiSYu4QGCkuTVVT+R54Pa0Sz++XQtLA1iWfKMknVbbamoK7M7kquUs6IZp77E1DoIjjFGGdljM0xaZ85aSf6FnkMlqqvsLI8yzg2xKiUD59buOwSmLxHpP7uBI0GkJVTLTMk+b0e+JHKtjJdSqvJlUw8LClnuBXDA2LNskVZOSB6FDS7yFeGbcj3s803WzYaAFBkmn/666/GxO3TThaigQdQeeL6dJNtcws/uiYPmILJY8k8lDg1PoTC+ZYeQH0HuN3fTf3hSo2fRneJuUWSFZc6NxbAAEjnaYcICzk8s+wInZOKw8lMARqP3PhsDKcYvLJlM3vNkSMYg7T40DzJ5adgRg5EtW8C7XeOtHsrcBR4xsA=
    OIDC_CLIENT_SECRET: AgBSAuVYUHDYJj3ORfcHWfIbqLneRhqoXv678OstKsF/SqvC6e6yB0yOvu6Z6bhOLddMLCPRrPAG537Ucvd3jdGvwrmVZ4Qe7dCNQ2mdl4Mnplb+ftI5y9TB2010skU5V8O6SvBjud1A/9LyvoiGTVnAXz0DuRXsigymVWYnlOIQmSjRnho9jfA71wYE7u2U5wznYnVBAQFEk4yeTvgQX+Lhlfj/BiLlhhtUgHamuGZ+7S6jTgE12zmi8/sWteJtIE9nXIG67Vz1KtN8JPzQ8ttak57UiFT+G31WOB0GgINopo7pGkbBjGgkAIUAbgx812c4rJAa8/4RBv3CeSGAklbcGY4P7yk0JZoMKWgvn7qSX3lGiDrPfM0vsHiF6OrZpkvQvA4WwMSGikHb+nUn8lOwneA0Jv7m4bThz8EfYnJR8faoCEv/IYrpOONg6U8AZBkd2+cKEb2Avt/7REx9vy8qAc7JcDwJ9fK1g7wKieTXKlWjoWY+CUwVlNK0sGj8dkJ7ZO5I/j6Sr1uqKsczUSzIYZly+sEHFNpYutmdZmkcrBiVLoba9Cs84yhn6kQLeWjuKTOdIbHWKbYwMhY0p+faXV/4qZaNlrYPYPkNtupqay6ex8W83weqCKicwMZ+Q5ZQehtoLKP0Z122g83sr9AtkPzMvqeWckqttdAcFu5hSVrJhiOoI0RLlk4fhDW2GdNw0nujF82aoDshKwUQeZ9t/uBd84BhjVA5T0F/PzTw3w==
  template:
    metadata:
      name: dawarich
      namespace: dawarich
    type: Opaque
# apiVersion: v1
# kind: Secret
# metadata:
#   name: dawarich
#   namespace: dawarich
# type: Opaque
# stringData:
#   DATABASE_PASSWORD: fixme
#   OIDC_CLIENT_ID: fixme
#   OIDC_CLIENT_SECRET: fixme
