---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dawarich
  namespace: dawarich
spec:
  encryptedData:
    DATABASE_PASSWORD: AgCYDdFolSVF6yNAKWmEZd+1+VMF6XA6BqtgVGSrYrGQxthcPiX/o4VmnSwu9NPcO4PQKBDpT3sD100ryB+nHeWAT0mXL8/6+CQqCIi4sY0I54d/nKHkXwQf3VwvmcZ4Z51ewTCmEzJbKlN140LvUvDX5hHxrSot5dksA0fctglvVSriTnfzSnZhKZ9rzuEo+PUvmhDuv+LiTV1+WytqTGTt44YANJp9yFdqQln+tNlAVo8jVjAdPXgCFr6Sq6MV3TTXDF6wEpb2rB7EvibsMNTXR8I2JR4EcFntvNrKWxM2VFAN02d0R1b9uCOCU0ZKDBO/SKHzVvB3K+MThy267CAwzKgjyMe6RzwdKQ+AfBNEZONgxbxsy6XsUspqwZAYz6NSZLelACAzOzl/3daNxITFQdKgPqIBuX6HS7BoC483RATmaWS/8JDeeNrTexgX/PBRyn6uDLNsR47y1TRLFxxjLe9O86evocokl7cpT1qDUjA2yURZzah9ZGe18UjZug6y/8JhPXPDI/GhD+Ebad7GB6vWiP/o6kSZLBAXDRHJCd4Y5syvSALBCEFRxrzo+fscp/SkB5nIEq8EQo+BybMkICRah5WkE1xixVa63VPo6ySFP6fB+VHHHCkMZ4SBWnUS8GgzlJhLWaWGaTyCwXmtEPOrgRssvXF8ZjmDQ8h2Q6Zi+0Pq/Tfqq8D9PSj0D++MEcUvH76Byf7tSbC7rHTvaEPiww==
    OIDC_CLIENT_ID: AgBaL6zwGxkvTo4ExoYGxsO3zF/pEajuWTGRLT9CN8c2f8uXLI0NfH7IC7++syBFUizquBLV5QV038bCp9qoJXTtW9q92qwCjY4/GKjSm8k0yfz0yIRD0vYJX/ks4oEl4Thy9i1P/WWmW9dKabTw5/nxdQdk2wp7dXDgnyU4V3bqqjJ7PV8Dk7F7V4eq7W9Cha75GcLmRDA6YTvQSpiu++JG+abWwFP3Cu9+7Cby+Ga3+PvTURu4VV/x33rVqr0MKm4dNiD22KZGKdLFDZKALktaNL3ou+q74UVcxP4pjtjIN5SJtvDMPyYaapk9Ji/Z3HMZwBPEhJ5Xb20XpM6BPyi4dAIgFSvD5oJSuJ3o/FRVlUnU2qib8Vksy/anPgjgbnLXpKaGO+gJ8n3JF4m+Eyo1WP76xSKB5tWZJVX6rfadlda8oBRvnfUCWGIl70z6lji4XD+bMXlEqnFnCWSCDM1aL9xkstY0nL77tFgk/zzjkatsQApnPcO2ul1qtWpRCD6crPw0Qksk8kihefwuPkjvFnpJMP/WZsPZWkDpyR+AXn2G2v0Q+qrb8ZF1s3Ymqfl/9/5cMVnBJIgV30GxdjnnrIMwrv5GOGHG1lvgwf5VTkVngXZdvGahgANvFS4ELfxM5v4YoftH+yuQrBip864UVN3QAmg6LJvJDqZcxS1u3Ww3aaGWpBVh/+/WZD6t2XpgXO4tXhEM9A==
    OIDC_CLIENT_SECRET: AgCWvVSIS+6aLyq0kCbC2GqHX2xA4NuWznQlr0/mcX4rZjLy12xjpWAbMyYDQ9aitqFiOzJtPQrR0qvfImSmiABg6Mbhi9ZZhUTARKLRTYOfqJuJt7tbCTn3nK1kvwdf6y5Or0FFrYMXZnh0l05tPDxIK8uizd0e8qnIRvg6EnfqgPqoHkts2awpCX7LP1YqNcI9sNWnKpr2svchpSidc4jV3safvtluYNT/+cSLoCz9yx9+wm3HaYJ4VfLmqSmewjTeQdwlNKGQjRK2xP4SIOJe/NyNc1L6wShfRo2XevGdBT9OFakvx9UBm+JZydbgPE/S5pC68sRS4PlvdDgW6e4+05k5dSil6ixuiMa9xHQ2L+QKulOJQrePSS/SSxkN5kGtved86hGwvOhVaEMpWGzhmHygyUNBzQ7OtZtkHQyRKcyWYWgxB1zdQoXd1d8hlPe2t9gWuxG759+HCZF0Io74wJOnW93WbDyXodY7jpYr5BxM93C7zHXvsFmUaveMqkmj1+bEkDn53JW4vDXsav5K8vPvHHKH5ffdh5xEZHAN0ysoFu9OEWDgRUfHoVTp4FbMXriixmosq3iVzw4apHurYbkjGt2xAyuiQmwrncCmVXuzKdbmrZIHD5X3XRdXTJdJf9nha58Xi1S5HWdqG3muwu74rrDC4NQaUe8Mx2v8FGcS4NIxrPzBo/1gA9ZSdzf19Jp5S4MgKHdmxFXEViNF4VuLhw3fXXJFGMW19qXLGe9wVaEAG6+dfZlgX/IzdACncmFBpqTr4Rrp7faNXDv0
  template:
    metadata:
      name: dawarich
      namespace: dawarich
    type: Opaque
# apiVersion: v1
# kind: Secret
# metadata:
#   name: dawarich
#   namespace: dawarich
# type: Opaque
# stringData:
#   DATABASE_PASSWORD: fixme
#   OIDC_CLIENT_ID: fixme
#   OIDC_CLIENT_SECRET: fixme
