apiVersion: v1
data:
    DATABASE_PASSWORD: ENC[AES256_GCM,data:vl4ARQLCecsvTynQ16/Bd2nVikH+FBLgn2h8sQ==,iv:+DYPtwM1NSsoL47EpStnA7wT3qhUesW4nkYYUHHRgq4=,tag:RLeuYwQ/pieoDZ9nKvj9dg==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:WJjQhZ13JPM7OCwk,iv:r2ZObIFPo8pfNGE20c9ek41fkHKvwh+a/qmiNFnA/uU=,tag:hoY3tA/9Bd03NuEnW1KWpw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:X7qP6Ly4rjYs+D18BP5j5JE3QKLlLGyKHMjq1hW2ilIvuGe7SfrGKZ2KoQWf5O4VVhgaU7lY6eYYkC3LLPJafKXw4t1mwhoIa59irbdS7SZGjN5dxWdacQ==,iv:Me/jm4O0rAwVTyStBvseGHUzL84caSMh0+jleQenISs=,tag:UjfWxxCDkClk1ns88NN4+w==,type:str]
kind: Secret
metadata:
    name: dawarich
    namespace: dawarich
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoa0twbi9VdWhSVmpLMnFU
            VURWbTJPK3ljMzhjcWx6VXhSUW01VnZocEJzCmNHQktpamo5cDdkM3BnMldONTl4
            YTlRZU9HQ3VJYkNjMzRpclg5aE15OEEKLS0tIFQvMGpRaDRNTkQxYmFudDB1dGtI
            UVdoUUZXc2pjOWd5SS96UkhTb1VKMFkKkM0qfFbjT0Jeh1et9je0d14cNI0jJl3k
            gcpnuHqv9dFVgduhHm3S8vYnJw4jHL0If+bU8Wu04Ipf18QLNEoDzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:PDwTVCwM//FYHeJkAs7elxw7OK18i4Eu3nmukU9vOzHJ70kk7VliMaKiQYG0wyPIMPO1rP1AQmhuBnM98DnOcvTXn69EWsmrohHo/kmWIoNrUxjuU1Aj92LUOiQ4DmZMSld3zu4haBu7TohN2vdEkmWIc8sZ7b8VjE2VH3ttFFA=,iv:CYcWwbQyUpA3ffy5yrYeEy+CaacPVw/SKhhneMB+pUM=,tag:RyhCAoUvO3orlzhZKJS8oQ==,type:str]
    version: 3.13.1
