apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: dawarich
  namespace: dawarich
spec:
  target:
    service: dawarich
    port: 80
  rules:
    - hosts:
        - dawarich.item.fyi
  scalingMetric:
    concurrency:
      targetValue: 50
  timeouts:
    request: 120s
    responseHeader: 60s
    readiness: 90s
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: dawarich-app
  namespace: dawarich
spec:
  scaleTargetRef:
    name: dawarich-app
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 600
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
        interceptorRoute: dawarich
