apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yamtrack-db
  namespace: yamtrack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yamtrack-redis
  namespace: yamtrack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
