apiVersion: v1
kind: Secret
metadata:
  name: yamtrack
  namespace: yamtrack
type: Opaque
stringData:
  SECRET: ENC[AES256_GCM,data:UaQ63fSLnZA5aeOlEvU2DBlhzvqHsdhaQpgZ5P2L1uGvh7Nzw2kG65e9h7dobXkeZqa64AkfFhPiPRK4zOO1yw==,iv:cw5xJ7HhezCR612p80MMMwg2bc+KXs79vADBjmbDqxA=,tag:lF4f3PS+9S1mLrK49ttw4A==,type:str]
  SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:eVYestn0CQluhIcoHLUE8QpcqDuAhQqDfCt1yigONPpSAWXfXfsBYHGZ7lJR1AoMZpOtNOlHRoe3lz8agvWnpq5lYfq5a7w0e/3PcgE8/U8s/hRUMnzvtdE0dhvs9IGOm2PB1MF2DleHgHGEJB8TRRTzTfu7dN/leN94y7HwATHEW7vTZt+dy1BEG5hIxcqjoOq4bbv53xx1iciWnWNzviOY/oN+2U1GslVhuxL5MdL9/shEzM3K2v5rBihHk3qJY88N16Q/SiKpuoImgC5kYdoRjNHv9RlWlUkhdJ8L6DBgM0lSZFIosdRmdEi08dh2aJ5R8Q1o6Y+aR5iSoEALJJdhNSWf,iv:3Zud508+4OXDEuDsl0pJSxzd0wN/NdLdrNSCsJHC6Oc=,tag:U7p0su7Zb8YzuL5sXqzvKw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBET3ZIdVV6RzhSOHJGZ2NQ
        MnMwL3pLeVRTdE9POVovV05OZkJJMU0rNUdzCkNmRmZoMldMZ3VOZlphTHpZK1gz
        Wm5XcTRQWWxMaG9DSFRlWDIySVh0bm8KLS0tIHgxL08vLzhZNFRWWU9PQTFBakRi
        RXZoRDZicml0bkduMkgvUFdaa1l2b2MK2+LENiji9exfpjUiV0XSD7C4awWCvQxP
        5i4Dfwp1eqfUB6KKf857e/O/iP3JR+bwxsOpNaO87MQsYB1R7KSnhg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-02T20:36:24Z"
  mac: ENC[AES256_GCM,data:qw85Fl1iCp3gMRrcXAZZ6TTzbuc/tCkMFOuhQ8c2RVw4xgV9sQuIw7pwLKR6ht35c+GvQRR1ExBUjwIOmst9atgT6L3GdZqVPWOW9gPzh1fAS/7uqxWnvwBuHZv8jj6cZbugZBjrulLAUEJRBAU3KDncipkfA6bNrG7vvggmhQ8=,iv:uw1v/9S0ENJ3QpFLSjd9R7J20BCRoxIitndrWhp3XMo=,tag:7ZNO836sZFve+oUrUpPQjw==,type:str]
  version: 3.13.3
