apiVersion: v1
kind: Secret
metadata:
  name: yamtrack
  namespace: yamtrack
type: Opaque
stringData:
  SECRET: ENC[AES256_GCM,data:CXNbQZxSJf7MCgCdtAKOoygcLCYBQCTVibGkCKokZ2w5M8OY6imzG27IYfA2bze7N7R4h8qXGTpvNLefDAdpuQ==,iv:7A61juW/cCWpQDqJ0MyBuizW6J9/quV+phhrIB4/JSA=,tag:PJmo5c2JbOW0DI+9fw1piw==,type:str]
  SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:eVYestn0CQluhIcoHLUE8QpcqDuAhQqDfCt1yigONPpSAWXfXfsBYHGZ7lJR1AoMZpOtNOlHRoe3lz8agvWnpq5lYfq5a7w0e/3PcgE8/U8s/hRUMnzvtdE0dhvs9IGOm2PB1MF2DleHgHGEJB8TRRTzTfu7dN/leN94y7HwATHEW7vTZt+dy1BEG5hIxcqjoOq4bbv53xx1iciWnWNzviOY/oN+2U1GslVhuxL5MdL9/shEzM3K2v5rBihHk3qJY88N16Q/SiKpuoImgC5kYdoRjNHv9RlWlUkhdJ8L6DBgM0lSZFIosdRmdEi08dh2aJ5R8Q1o6Y+aR5iSoEALJJdhNSWf,iv:3Zud508+4OXDEuDsl0pJSxzd0wN/NdLdrNSCsJHC6Oc=,tag:U7p0su7Zb8YzuL5sXqzvKw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSekZjU0phb3VlN2JJdm5h
        S08ySHJGSnpIVExvNFVndDlyUXJjajA0MGdjCmhCSFlFSG5PeXY5dFBXcDdqakRa
        d2g5VTlUR1RzYmJkcmdrUko5N3BnaW8KLS0tIGIzMWpZM2VCaTlpRkZQV2pVK1VF
        dHF2eC8vc0FTaXlYekxsT2pYSXZrMDAKwRwnpT2USVtBdJVh1xmXdNdfT5V9yvm0
        4TcKfFWUXtx3/dg7iWe3w0wMLZpaL9YIYE0WNd/U5TajF+pap3TnKA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNWI2NVVYQU5PQ3RkM0hN
        bWNaM21WcmY2d2RyVUZnMXNnQTQ4SkFMZ3lJCjBBOVd4RGZMKzlPUlJZTzJtSWh5
        WWlRb0xMMXJDOC9uSGVLSFIzQ0JVajQKLS0tIGt2OWpSZU41OEI2d0J2WC93Vjkr
        SEtLakt5TXc1Nit1RjVCb1ZYSWhCd2MKsHrBmAXp9UGDzAb8IXJYg224T0w28POf
        H8j7gkR5bMBPjjtWZ4ByxJg8/7J6RkdBb220UJ+NENVGVjXcDl6DKQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-18T01:09:46Z"
  mac: ENC[AES256_GCM,data:Yoe7Vc6kq3klDgj3DfPqP52pTLluEtgx4IujmityB62GMlrVe4bapknBLyuSXIKyeHOaEKVjUuOuDJ9SWrxNOTmehslmu+oF+lzwXbEJiOdOFOzrxzw5hQmAiqUTDny1RhxnqrMBZGge/yh3KVL2BrqBTGEJNaCKqMSGdVZMtq0=,iv:m3oTgPHySjcX/WfOy/brnZ//xbLQeC3P5q3eD34aLrs=,tag:kzWmwrEMB8yU8b9t04VH+A==,type:str]
  version: 3.13.3
