apiVersion: v1
kind: Secret
metadata:
  name: yamtrack
  namespace: yamtrack
type: Opaque
stringData:
  SECRET: ENC[AES256_GCM,data:QlOex8WFKIdQHLtPftHv25a3squbYYg/3TJGy0bRHROj3x6Qj+fhDd7GVeXWuRvTAaMp8PIT24sy9wWCMUp5Lg==,iv:q96Upr/1EARMPB8LnJ06RBWjdvgf4pfx+EaQbgE1lGg=,tag:KqaBFWhjh0aBMJIi8bV63w==,type:str]
  # ENC[AES256_GCM,data:crnvm31gj8jTTkYITQK+iROITNVlHO8K4YB3a8U/mUPyeGgxxYs0Mmf6VynSRJh9y+Nyx6Z0KbziUdJRj5VO3madVKTN022G3Re1tySqEQTcKW63c3/E2OI+Zq26f7kwUw==,iv:3UpnlgiLduzMG1iI0aI9S0YOUcX6mIOWh0s/TwC2qek=,tag:Ji6A1f3AS//EiT4fnNqDNw==,type:comment]
  # ENC[AES256_GCM,data:x2lRNCJYBkX2XlDTbcwIITG99EmN1BIxRo1QgrEltUW5ddYeaIKiuKzPk+4kyhDD596zS58zBvZ4UXVa6H890LOsaNSL52jcP1i+9T7F6Oo=,iv:G7d7Lt4720NnomUmwn9llB6V2ltx1TuBa71kZ2og+BQ=,tag:SkuFlCZdCYG3PN+sYuSU+A==,type:comment]
  # ENC[AES256_GCM,data:4XOMoGWTmLG+ZRieX/T+U1UzN1W3u3jvTQS4R/bkpC3oLXSPdxFNYXwYmplFOEOnpmKx2s7rhygFb4454Q==,iv:xCtxoUChfj6qf7pClsRrcuBcLPh3vPzGWcYoONaMPEo=,tag:OebXUn+19iGsTNbVykngmw==,type:comment]
  SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:wdvOrIDxVC3baAff+86+UNLFAlrDHLH6cZ1EZE6Te9kXyfuW1jfqHUaNRTkc+enk83nIebyRwxaAWdssPnGHavpGesxgCnjU1j8cgBX4l+7KIK/pjro/YEZTIwpB3vVLLYfmPLtaVhVkFAoQ7MujFpJ128HIkZnuiLba+EaGW29eclvw/l7mPHU0spfk1LzWY8/xDY5jy9B2G0SjH+bpSLx0AViKGqahMkrLj08TSTAyM/JzVjNHVscxOO8ho+WlTbO0hMNNAJOC69CkW1z7vQUU9xbNgYqgKDbnnTEYbMn+iP3xRufmhI4irqItIItb47br6unRPPA+6BmoaHos3z8hv/E=,iv:HumimZ9Y6aHOhPdVMBRl1LB/WLZ3KeV9jLc26VxDClo=,tag:fOea+KMEtML7n9k58gPXfA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Y08xYlJuZ3IwSEUyVmty
        bHV3RHNHZmYrbE04Sm5UUS8wS1lEbTc0WG1rCkQ3UnoxRkQxRDJUSEZNd3M2TVlh
        amdyU0wrK0RRM05udi8xbWh5T3cyaTQKLS0tIElXVEIva1R4Z3N5VTRYVzZGSktm
        bElNWUR1RmJXUGdwdVhSWFV0MHZMemsKogAYqpgFxt/j94hEGfA7iWMi3N/QbNj0
        O3HwtHfmDf4qSJokr+DoMap8YghjjUXPN/oiim8xuqxVahTqNlWUkw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T18:30:02Z"
  mac: ENC[AES256_GCM,data:NehguSt1ANvtabDdXfMtNZhTBcs0TFfcGeopN0KqYXck+F+i1vy4E7EZuM4TKCQrv2Tud1XAAH34uq2zT2OeSjrYEoNQ8XejAAIsXM6x4suBPW1PNwnDoRvC7NBV2uPUtbMRf4BIQOOu9sEEolJQMCxC3iHrIES3kIG0wTM9pGw=,iv:t6SpGr8OakZTeU0W5uYBEbCSfqkRvP1rbcUk0o11WkU=,tag:h4L7zAwB5ik/6Rty+1Brqw==,type:str]
  version: 3.13.2
