apiVersion: v1
kind: Secret
metadata:
  name: convertx
  namespace: convertx
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:hNkD8pBcjvRNjnUc8KYYoVtX8BwkI2V12ofy9Uavt9F+bkOX4EnFrwByncbqqOUutA52Im9YDdisH5/T6sp9sg==,iv:qBcSTNIDYsRg7JxUkHA5cQ5Zt7HL5G30w6pZ2sc8Des=,tag:QV9ZFOlUWDrg/hWbr2J6vw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYVE4c1AvcEx3dE5zamdL
        cHFKVEZYUnBqTnhtZ2hQQmRuRGhuRDJ2RkFnCjF3dU83MHBLTGJNVkcvWEdnMm5t
        TGVkVWtBcGdtZzhmelVHM3ZYM3F5SVUKLS0tIEhCMlpPY1Q0ZkY4S1EvYVFpcEM5
        MGZDcEtlQlJaRWFVZVRJRU1xNE9IaVkKT+YaFkfAiqU9YnpEn2mhZQx2VMB/Fkkp
        iROQH9w/4uUbQoVvQo1KdijECtqz0dHHRIR9mf2LEYAaoGsr0Dn9LA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTE9HNXd3YVV4NzdiMkMv
        ZHZQZktwVmlrSXV4clovU2IrWXdoS3VuT2xNCkg1ekNsdXRzYno2TFBGVVgxVmE3
        M0lOS3JUZlQwNnBnRit2RFlvaEpsRGcKLS0tIE1NVitqOXJtNUVkRVRTMlc3aG0y
        REdTWmJwSjF6a01XSU9ubi94eFJlRnMK8/MTkQE0CfGrw5/x5qPSpHON58MUr09r
        bOnbY+eiR0sPxc8hobXR6+QEQi2ETRNy1RLI0T1cnLBQ9t+dqiDwEQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T14:59:17Z"
  mac: ENC[AES256_GCM,data:SeM/J29hQZOqtj3xURQVqfRc95ZVoiUKyooDPxEKFzQXUh5nhBUELOWgz/aQ72UzCEHZS+MSBjl8BoUv/AjC+438Q9janIgQB1ieL3Vc2fK30CSFxSnPJJQ8wHxzS42JIeRq1Y3GuA4Mz2EYU9gStGIBk42OXYJX9Ph+/2GEQPI=,iv:m9qFWJgUQCNQf2k0mfUHmPvM2TISp+8ulqCWZMnzHJE=,tag:TjhSuCWEFaIRJZGdBm1fQQ==,type:str]
  version: 3.13.2
