apiVersion: v1
kind: Secret
metadata:
  name: convertx
  namespace: convertx
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:hNkD8pBcjvRNjnUc8KYYoVtX8BwkI2V12ofy9Uavt9F+bkOX4EnFrwByncbqqOUutA52Im9YDdisH5/T6sp9sg==,iv:qBcSTNIDYsRg7JxUkHA5cQ5Zt7HL5G30w6pZ2sc8Des=,tag:QV9ZFOlUWDrg/hWbr2J6vw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RFE5ZlB5Q3JUYzdudG1l
        eUVuRllEK0ozVDU2WDVNWE9NekJacUw3aHhjCmdvamRVeUc5cGY3Ym1ra0xNZmV3
        Uklkem1PZDZleGZFL25BeTY4Si9FSUUKLS0tIGNvRzZkUXhwVXRBaUpkeUZtY1ow
        b3B6SlZIeUpXcmpTSERFR1JYVzVxK3MKUj3EkSNtX7N4RC6Qho+HWWr4Z7DXmcR4
        5OrA9Ivw2tDWiarsqWx+go5ZkAi2ja17DOEs+K5xVDEWKVln0cScOw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T14:59:17Z"
  mac: ENC[AES256_GCM,data:SeM/J29hQZOqtj3xURQVqfRc95ZVoiUKyooDPxEKFzQXUh5nhBUELOWgz/aQ72UzCEHZS+MSBjl8BoUv/AjC+438Q9janIgQB1ieL3Vc2fK30CSFxSnPJJQ8wHxzS42JIeRq1Y3GuA4Mz2EYU9gStGIBk42OXYJX9Ph+/2GEQPI=,iv:m9qFWJgUQCNQf2k0mfUHmPvM2TISp+8ulqCWZMnzHJE=,tag:TjhSuCWEFaIRJZGdBm1fQQ==,type:str]
  version: 3.13.2
