apiVersion: v1
kind: Secret
metadata:
  name: convertx
  namespace: convertx
type: Opaque
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:ETRy8gL62oa26IUkCmtrLeoR+RlsTwmO7Wj72+Jerc3JCvkjKUFKCAXpIxz1fd6NEA9T+Z1cZW7VVAf+6vYRnQ==,iv:VugLdtbZF0cs5oaBGxaLq2NHDmohl75qDQxxSX/Qq+g=,tag:AM1qYI29rMrCsrh7nf7oEg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYVE4c1AvcEx3dE5zamdL
        cHFKVEZYUnBqTnhtZ2hQQmRuRGhuRDJ2RkFnCjF3dU83MHBLTGJNVkcvWEdnMm5t
        TGVkVWtBcGdtZzhmelVHM3ZYM3F5SVUKLS0tIEhCMlpPY1Q0ZkY4S1EvYVFpcEM5
        MGZDcEtlQlJaRWFVZVRJRU1xNE9IaVkKT+YaFkfAiqU9YnpEn2mhZQx2VMB/Fkkp
        iROQH9w/4uUbQoVvQo1KdijECtqz0dHHRIR9mf2LEYAaoGsr0Dn9LA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTE9HNXd3YVV4NzdiMkMv
        ZHZQZktwVmlrSXV4clovU2IrWXdoS3VuT2xNCkg1ekNsdXRzYno2TFBGVVgxVmE3
        M0lOS3JUZlQwNnBnRit2RFlvaEpsRGcKLS0tIE1NVitqOXJtNUVkRVRTMlc3aG0y
        REdTWmJwSjF6a01XSU9ubi94eFJlRnMK8/MTkQE0CfGrw5/x5qPSpHON58MUr09r
        bOnbY+eiR0sPxc8hobXR6+QEQi2ETRNy1RLI0T1cnLBQ9t+dqiDwEQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-17T23:22:54Z"
  mac: ENC[AES256_GCM,data:ApmuPTA3fHrd5rp7lsaVSSGBlJnsT9It+P45M1chTo/nEQuiSn5lLZjsYZ6q79TtEfxRbRlMO2hiYkcd5tcKsuTjITAuYUKzZHr/q9S1WII0b/w9HKmpz3yErWHGFRUGNmQET07MJtiMPxX1aigl+sPU3Y+yuZpNdvWu4fSrhqk=,iv:i40DI1KalY/BfX7yw7ueh69AvQCWRn8P17e5AGbe1ao=,tag:ljMv5Tpt+DcCGbvKDbiNQA==,type:str]
  version: 3.13.2
