apiVersion: v1
data:
    LASTFM_APIKEY: ENC[AES256_GCM,data:oGX1zolxd7YeRqKh6GbfTN9EPvtgoQdNBOriSxkhVOJ40hUG1QwYjXX8YJo=,iv:/xvsmQCsnx3cBt8Cc71DsIb8JxAFJwfCh78u6R9vMx4=,tag:2bCsms2VmsHIEwDx2sJcJQ==,type:str]
    LASTFM_SECRET: ENC[AES256_GCM,data:A/ryjJL5cnoJ6ibHSesJ4SbwS8PYAbv+MeFLCVRAYqR8UrXGmvCdPTut214=,iv:ntym0dYligzA+Zq7mNAiNvdPOkurP+XKRw3SPFfqVs0=,tag:MaxRDjcJBQSdW71iadmqlg==,type:str]
kind: Secret
metadata:
    name: navidrome
    namespace: navidrome
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTTRwVk0vY0RLMlYzT2xx
            UE05dUhaM0FXYUZENU9kZjl5K2FFSkhIOUZRCmRTbWZNM1dpZlpMK1pMYkVHdjBv
            RG16ZmhvRWNjMmFZeHl2Zm52V1R2OU0KLS0tIGE1bEo2S0Q1dDNIZStjZS93eEJ5
            T29oV2pHT1V4QzdOalJvV294VHlUYXMKMVXZqFg4n+YVQOAVm4F/IpUMYz2JdSho
            QPEYONExPuLFzruSQtpTcDaJpBwPw7sePQQnklxG2WPAC1ToAn7iKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:I1Tr3UImzr4cskctStKP8c6E7IykVezdVdBA9UNR8YDdgaFGdEQRrNLHdEK03qGEQZeSVr3KMa24uMDrgRZZZ0Ahx5tgzq9NXCxeQwRNbYPwgzrENEnr/YKvC753/k6+f8RYxfjnXAJ3IYF+WwSNZEmMno1L63/Q/AWF971M3/M=,iv:FcSI6+/a57sSzYu01a6YN2dROD76/Lk+zMdy9rFUlTs=,tag:KF9sRDvWOo1W228byvkmEQ==,type:str]
    version: 3.13.1
