apiVersion: v1
kind: Secret
metadata:
    name: navidrome
    namespace: navidrome
type: Opaque
stringData:
    LASTFM_APIKEY: ENC[AES256_GCM,data:Nv3R35WCbjQsy9svLrlVE7zXMjdBHni9DPWD9kI0Fas=,iv:hnmCmRa2ZHoDtWyo3/aRm5XH9ckBcUPyo6B9Q9fr4U0=,tag:C6SPjk2avGcHzOKEVJd6Vw==,type:str]
    LASTFM_SECRET: ENC[AES256_GCM,data:L7tK3rcRYcc1cXpIzHXVUBDORbgeaMom4CUgz8yjp1Q=,iv:/av9QkAjc5RkwpIrqf2/Id1XpKG0Lm8SsRbK+6Fpfy8=,tag:sV217tZQ19c7VrdlBDmyOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSm1LZ21GS1NsbjRxQTV4
            VFdHU1BRUTdFT0IzWjlUc0JnNnlKcE5MWWtrCjhNbHJvaUhUQWVBOWRTSStveEVO
            KzdWZmNwUVh3VWo4MEFtRVlES1cyMDAKLS0tIC9iWmhaV012SDllbzJlYkxzc1hD
            RXZSRm1MVmMwNVVIZ0FsMWZSOGhNRjQKHtfItSkjd23Lgi9iiisk1yyJNXSi5+wy
            ymLzhG7T8XD8Xv8ropDuLU3fb62gcvJXVQj4+n+1odfcXPBV4Fu2bQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T16:56:38Z"
    mac: ENC[AES256_GCM,data:GZdttQbqNMWbXVaNux6eTsuI/jjJP5HvC7++/DYYhS1W97D4AvUxXZ+/1+/fmKh3JdbWDwj/HneyOM3fKq4SZz6erDY2KaDrSJaPz9unSvkNsKLIp0/kcLsvBaia8FGs6+5H0Zr5lr4w6m3io0QquN7iEnJQU3cKqMSfEDe82qM=,iv:ljdMNLjReb2JTi1C6V2We4On/CXz92x/UXILUR0tcOY=,tag:ORvmiiGbj6kPOYlb9H/CjQ==,type:str]
    version: 3.13.1
