apiVersion: v1
kind: Secret
metadata:
    name: navidrome
    namespace: navidrome
type: Opaque
stringData:
    LASTFM_APIKEY: ENC[AES256_GCM,data:V1wugrUxsgDH0HQe/jB/c1m+aEXi0zFl628qCozPnBY=,iv:gn88mxHA9Z2EdPf+W0Zjnt190QOpD3C7b9hmOa5FjFw=,tag:cNcjO4CmPNw4L0b8jQOzWA==,type:str]
    LASTFM_SECRET: ENC[AES256_GCM,data:WDJ+3Za94ZVzl80MwDl4XaRZoLZ5zPPL6RGqZYqMIww=,iv:ePOZrXabMmeOyFMxzfeax0XacJfLtsbuOLSCB58AN80=,tag:vAaEAg0JsIKpLNcKlW2B2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUFBvVldGM0JvV2ZyeGlC
            NW94d3AwTVFHNER6NXE1K1JzWW5KT2ZUZHpvClUyZ2NLaHdhK2dEMjRuUk82algw
            YmE5YXNBRk5wS0FMdk42SWQxZUZ4SEEKLS0tIHlHNUFsK3lCMG90ekRBYkZjNVB0
            dUhmYlRObXVUd0JnNmd4UDF4MzNjNEUKwfTGX1B98wSu6lkMjNudhDDeKhivemHv
            xrNO6eURfYsSggAoH/rnySo50v8HXNaMnS2wAPByMncMeqRIBxwk3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNVBZdlh0VDJWcTJPTTI1
            TEI0TVVvQnJDb2JnQ051bmRoMkF2c3hVNHp3ClRDdEVMbGl4eGd3eVIxRzExcnk1
            dW80ZzBVYzhWUSt3bDU1WWhuQ1Jjbm8KLS0tIEdEVng5ODN0bmc2V1RUdU1MRGw3
            Mm43bXY1WEVjcFh1U09YVHVwNjQ2cVUK+DySvtinSUF1jhoVrnAHDOs9KoOMDRog
            OOYIeyEnarbUevEgc8SMa0MZBfNC8Dio0H2cIIghgbrl8JX4Dp0LSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T02:52:04Z"
    mac: ENC[AES256_GCM,data:tQoo8APc+vNNNZrrzn8m3cChtxjcaASAoHaeLCE56MiaUgKlto/rS6DT5msO58X4dAw4uvbPuZAwOzGc3CsBPfjc4VOFkaTEYYtmMpuXJeVojMyhRPvw6FkrVurJIaYKWjJjK7x4895pR2zyP4e7fPdAjMiKbFFbsugujTBvxJ0=,iv:BdIhk5fnuwIXorJZ9mXOMS7kX0qdSb/toSWi0mRcPGs=,tag:Ajo1Vvlye4rDmcjF7bT9Sw==,type:str]
    version: 3.13.3
