---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: navidrome
  namespace: navidrome
spec:
  encryptedData:
    LASTFM_APIKEY: AgBiGeCZ2sJRMGElAAftkJ6xfnLNN8mzn+VcFzt/jI3dJh9HAHVhptYCmxqXDvJn9Jra+MQTojI6ty0KwOZsOPtZkyv6lQwjiNdKnhEefl+OXWnYlK8gbIo8Y+Ovocb7dH9+waOWoFAGsFheH+6ZFH0h7H2MbuYxVgktQA8vLU5iCyh40JqAlJuOAaNvPaeOAbIjUVipEeBto6qoI0EiGSPefAMSwTgBu4Jw4FLwpgx2ZPbUrJaswYux7cl7rUlet297dJ+1FgsxW48Xjm3ueYuAXrHm4Fbp2FsQLrPkh97Gdh3YWPL91HmkHZV7nJtv1GXtYMpvwK4ZaCvknguaWJgHQRgQ0tZ7RuRRutcgEBbUCpzYlw5pwSxjyV5cs0qP/kRTk/feT7OJdmCLiNM32Fjcqo0zTb5TuaFghsfy51VW9hTkjKUdvvlRbXmAdXptWkCv5Rbe/HaBGYJfG625YNPAGPdpbuaMVvHQSpQqytS4K2Iy6wcEymCJ73FmSZosnEAxzuh2gLf8CX6EOEgwGmbAJuzmgBzgz2lJlxYc7T6Lco/Af/MIErtk6ioCvu/OKb7cm3FEJU2N1nCh3jExBVOqKJZRbr7AYoMA3Hb5rYhXqrjew7WxjL+OixUxsOFutNgDDoeZ5yza/sFQgCTlwpjjVfljwvtGE0OHY82oGJ+nf6gzBbfEzkU4deFJekePrCX62VhLn842i3LVQfv6NiBBfU8NbvLqYfsImwYrFc7Ajg==
    LASTFM_SECRET: AgCxXB/qTplPVhu+UjIZ9U1xV8kAhNvbj1/VJxGirffe6As6mnUEmxHFpJjFWh2fGboqhzUHHaMoVDC6gdc3509/KkuPNkNxxKCN3EvFIJcdDjMJDjbIEysmBpkoa/bTDmsGfKjmwMV0Oq/cuCEG+AApFvmBiIXlj4m347p8bDgGd2+jaV+GjNnGZIG+hJ9NzqtBFy8Y7XdhSoygaxJTMm7geF7959606ZUeczj/88U9Zw7Au5NFw5wEBi5bq0/DV3rwpUoujnLSGay4MoJeAsBfXo1JbADkMCSYe3zJpnrHl4RGcT8UOE0FzI9zJxzGHAinBt0Om4tDxKiBHYx5Rx0An5K1nISanMj2EuJbpkdtNYQ0mIAEg6U7YG2NOOpXaJDGlaOQzEnrfkz+Nya9ztObthlbJmpjhZngVGx78igHwOrBSNmfCTXEObFN9zojrpL5C03nICqtu0EIWC7bnNbkgfuhZowGyhY0zLlZBNMynkHwogDZMxOE6MZK9ndEMm4jdQek5keLW2hO6uIBpmPLHFNd7nhuR6jWEjIUBpz0p2f585ciDFLay984KqHUkFKKk4K9QradZpIme2CG8qbTfBDLJWSbV7J+ow17uIFGBnJ3KkcuocoqMkalpenORiHWxUWDmUcMs7/ooWxKkp7oO7iOpUrf3vNRmZ/RtSPxAhINpWF64EnPX8iL56DJmSMmNoMZwgO3Dk+OjOW8xSmcpnfAe4RNKZDLSyHLNzInJw==
  template:
    metadata:
      name: navidrome
      namespace: navidrome
    type: Opaque
