apiVersion: v1
kind: Secret
metadata:
  name: slaanesh
  namespace: slaanesh
type: Opaque
# IGDB API credentials - register at https://api-docs.igdb.com/#account-creation
stringData:
  IGDB_CLIENT_ID: ENC[AES256_GCM,data:Q7FeCGpah5OKuQoU5SgbQ4LIab0/NZOefS0Pb/8F,iv:lwwav29R/cTqmayHcMtxA9EL7kr5rraXesj4NXucsdg=,tag:tBQezqUEtJhGFasM4FnJ1g==,type:str]
  IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:xMuGqBTwBmY+LHrCv40dbjTYYFKfLBwmi5mV8Qxc,iv:YI3eIifwrDbkBHPXFXak0M69KU/ARV/aNLhiumx0BLQ=,tag:Mfqf6eu7ouENA/4A4qhSHg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTDd4aTFmMWVFMkZ1V0tT
        MFFTWGhhbGJUNVhsNU5NTjcxQ09kR1pnZkdNCmdQSkRyeEc3Z2NIMGFhRDFrdll2
        R3pmd2xTNlpNV21waVRDSWxzNFRtSUkKLS0tIG9DK1FVdXBNamRmYjljV3JPVExz
        OWZXaElKSVYyR2l2bUdMRFdENEswOVEKuUdh8AsJHNOnm2lnr/2HS5ltH8D6wO1r
        2HcCP5JOdoyZqPzB/ESBds5oShmyl/pj/7I03avjWQS5YNkrX5Myyg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcDl2YUk2UU52WGdjY2px
        K25vdjI2aFgvMWp1YUVLUHl0RmhjdmM4NHhZCks4RjJjdEp0Z29TY0NlYmR5VXVz
        UzhQVUFqNlQ0K2xtTkd0OU44SkxUZHMKLS0tIEQ3aDlxaldHQXZlUnlFMWZYMWgw
        R203OXFqWWdPck1WaVY3UnByR2JlQ0UKdT0Vbn11MNFq9fCNOBL6GkwpZdIVYAbK
        OYENKhIh+HrWCTtOddRj1YsW5Gy5sKIauoQHlDzuA2yHCWJNGMFddA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-23T19:21:23Z"
  mac: ENC[AES256_GCM,data:Z7vsnopKN05vEPQdTgy6d8G6TZ23gbylRPZ0893DT3ZyVesHa4M+2KPU/YBFLHQr++16n1DsN01BGdTK6SnVSgq04B6crv31pogCWu3oRJv48v9tfA9x89tJw/d6fWgpDDZrrFQXy+YzG/+lRFIb66eJdkbor7UCakTNe5OS2hE=,iv:Ge7zXQJBi8frAFViRMoZYp4wSApOSbfmBHHeuYNSeyQ=,tag:fEhbfBV/ohMqaZ8Mip78NA==,type:str]
  version: 3.13.3
