apiVersion: v1
kind: Secret
metadata:
  name: slaanesh
  namespace: slaanesh
type: Opaque
# IGDB API credentials - register at https://api-docs.igdb.com/#account-creation
# FIXME: replace placeholders with real IGDB client id/secret before merging
stringData:
  IGDB_CLIENT_ID: ENC[AES256_GCM,data:AGRsms6cRA1erY90c1bQExUsbTA=,iv:XhqTGyRGEksim6VbgnP8d1ptnhULZXiklOt0pKRHX4s=,tag:TuTjw5NA3x+6hrmlhPP/GA==,type:str]
  IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:wkaMaFi0b9DMR9gbJ/FXDadFrTxWUPF2,iv:toPTWVjD0HCCazuQ+amtQ2gK1USDKSVK4EaNILQiYF4=,tag:3IAKLuE92ztfC8EH5xkv5g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTDd4aTFmMWVFMkZ1V0tT
        MFFTWGhhbGJUNVhsNU5NTjcxQ09kR1pnZkdNCmdQSkRyeEc3Z2NIMGFhRDFrdll2
        R3pmd2xTNlpNV21waVRDSWxzNFRtSUkKLS0tIG9DK1FVdXBNamRmYjljV3JPVExz
        OWZXaElKSVYyR2l2bUdMRFdENEswOVEKuUdh8AsJHNOnm2lnr/2HS5ltH8D6wO1r
        2HcCP5JOdoyZqPzB/ESBds5oShmyl/pj/7I03avjWQS5YNkrX5Myyg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcDl2YUk2UU52WGdjY2px
        K25vdjI2aFgvMWp1YUVLUHl0RmhjdmM4NHhZCks4RjJjdEp0Z29TY0NlYmR5VXVz
        UzhQVUFqNlQ0K2xtTkd0OU44SkxUZHMKLS0tIEQ3aDlxaldHQXZlUnlFMWZYMWgw
        R203OXFqWWdPck1WaVY3UnByR2JlQ0UKdT0Vbn11MNFq9fCNOBL6GkwpZdIVYAbK
        OYENKhIh+HrWCTtOddRj1YsW5Gy5sKIauoQHlDzuA2yHCWJNGMFddA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T03:28:29Z"
  mac: ENC[AES256_GCM,data:DS5hEXz9hhDEeA+YZszrayZOvJEdnHCjjBtPd/b2tJj4nhIbbAjDfvbJQcDMylP/bLVGgsZNa4T4kmqNU2VPl2Mmhmx2Jc8iFryA57DXF7jHJlXSxxB5Xs3Nbehro1mvSwSy2XATfkMzXRBwmY1CPXgxwAknaH4Rx+k5VUL8/RY=,iv:A+yqkTz/zMFz4fOoVyQwF6JO57Spioh4Yo0lDvJl3mc=,tag:liPqAAzNrVa6BlURxZX0qw==,type:str]
  version: 3.13.3
