apiVersion: v1
kind: Namespace
metadata:
  name: watcharr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: watcharr-data
  namespace: watcharr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcharr
  namespace: watcharr
  labels:
    app.kubernetes.io/name: watcharr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: watcharr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: watcharr
    spec:
      containers:
        - name: watcharr
          image: ghcr.io/sbondco/watcharr:v4.1.0@sha256:b4befbcbfd2131f59bd596ed39b4be7612769decbe44df5ae5102a5a90f58ed1
          ports:
            - containerPort: 3080
              name: http
          env:
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: watcharr-data
---
apiVersion: v1
kind: Service
metadata:
  name: watcharr
  namespace: watcharr
  annotations:
    gatus.home-operations.com/endpoint: |
      alerts:
        - type: pushover
spec:
  selector:
    app.kubernetes.io/name: watcharr
  ports:
    - port: 80
      targetPort: 3080
      name: http
