apiVersion: v1
kind: Namespace
metadata:
  name: picard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: picard-config
  namespace: picard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-zfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: picard-music
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    name: picard-music
    namespace: picard
  nfs:
    server: 192.168.8.89
    path: /void/media/music
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: picard-music
  namespace: picard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: picard-music
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: picard-downloads
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    name: picard-downloads
    namespace: picard
  nfs:
    server: 192.168.8.89
    path: /void/media/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: picard-downloads
  namespace: picard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: picard-downloads
  resources:
    requests:
      storage: 500Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: picard
  namespace: picard
  labels:
    app.kubernetes.io/name: picard
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: picard
  template:
    metadata:
      labels:
        app.kubernetes.io/name: picard
    spec:
      securityContext:
        fsGroup: 100000
      containers:
        - name: picard
          image: ghcr.io/minchingtonak/picard:2.13.3@sha256:c98fd975f631a3d89230e6b381a54995a98d75e03f78988d8ab2726e2265ceaf
          env:
            - name: USER_ID
              value: "100000"
            - name: GROUP_ID
              value: "100000"
            - name: TZ
              value: America/New_York
          ports:
            - name: http
              containerPort: 5800
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: music
              mountPath: /music
            - name: downloads
              mountPath: /downloads
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: picard-config
        - name: music
          persistentVolumeClaim:
            claimName: picard-music
        - name: downloads
          persistentVolumeClaim:
            claimName: picard-downloads
---
apiVersion: v1
kind: Service
metadata:
  name: picard
  namespace: picard
  annotations:
    gatus.home-operations.com/endpoint: |
      alerts:
        - type: pushover
spec:
  selector:
    app.kubernetes.io/name: picard
  ports:
    - port: 5800
      targetPort: 5800
      name: http
