apiVersion: v1
kind: Namespace
metadata:
  name: wallos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallos-data
  namespace: wallos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallos
  namespace: wallos
  labels:
    app.kubernetes.io/name: wallos
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: wallos
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wallos
    spec:
      containers:
        - name: wallos
          image: bellamy/wallos:5.1.1@sha256:350d8fe7f963477ed92b6ff96c8b220ed5bfb6c3b9eb8d3229025d132701c04e
          env:
            - name: TZ
              value: America/New_York
            - name: OIDC_ENABLED
              value: true
            - name: OIDC_PROVIDER_NAME
              value: authentik
            - name: OIDC_CLIENT_ID
              value: wallos
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: wallos-oidc
                  key: OIDC_CLIENT_SECRET
            - name: OIDC_ISSUER
              value: https://auth.item.fyi/application/o/wallos/
            # auth, token, and userinfo urls are discovered via issuer endpoint
            # - name: OIDC_AUTH_URL
            #   value: https://auth.item.fyi/application/o/authorize/
            # - name: OIDC_TOKEN_URL
            #   value: https://auth.item.fyi/application/o/token/
            # - name: OIDC_USERINFO_URL
            #   value: https://auth.item.fyi/application/o/userinfo/
            - name: OIDC_REDIRECT_URL
              value: https://wallos.item.fyi/
            - name: OIDC_LOGOUT_URL
              value: https://auth.item.fyi/application/o/wallos/end-session/
            - name: OIDC_USER_IDENTIFIER
              value: email
            - name: OIDC_SCOPES
              value: openid email profile
            - name: OIDC_AUTO_CREATE_USER
              value: false
            - name: OIDC_DISABLE_PASSWORD_LOGIN
              value: false
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/www/html/db
              subPath: db
            - name: data
              mountPath: /var/www/html/images/uploads/logos
              subPath: logos
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "256Mi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wallos-data
---
apiVersion: v1
kind: Service
metadata:
  name: wallos
  namespace: wallos
  annotations:
    gatus.home-operations.com/endpoint: |
      alerts:
        - type: pushover
spec:
  selector:
    app.kubernetes.io/name: wallos
  ports:
    - port: 80
      targetPort: 80
      name: http
