k3s_token: ENC[AES256_GCM,data:DlNXMZMSwd3WhaL4gwiN1aG5eTgwdLASqv8OBTpC1MNzIq/2zRk2InzT/ou74lfEcWX01hk4yUiphjMhC1ZCLw==,iv:fKGqLzsBQ/xHOjBijWzI7tkpCyO1TC9reL/4cOrOG6E=,tag:AGt0cCsq9FbZvFHnwOUImA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dDRBN0x1aEJKZEYyVGxs
        MkpDc3ZNZ0x4NGw4bGdVc2xUK1M3TUwxTEJNClpkaElla3czM2FJdjdsS2hRQmVW
        WE1JN0JQZjlnQi8rYmxURFZXdXNLSVkKLS0tIEREMzNuZGlSMFBFZ2dKb2h5RmFq
        eU5KaUIzRTlldG5RNUIwbDcwWk8wSU0KN20xseLyq2yWPJbu5EYuuxG+FyJqnwo1
        V6knj3AUhqVXqquFjqI3GPyHzzxP7H9l3rZwQlwyBL+1uQ9nK8on6w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  lastmodified: "2026-06-14T19:47:31Z"
  mac: ENC[AES256_GCM,data:DHyV73jsdLLEurh1QbTNI1Kp1redpLT1gz0SQURv5GJxcpv+WOkENCezib3zfGCkhNtfNUpb+5/fMVZG1VaaEGJ7WRrT6CrgFCKbJ7bjiE9noNxKhBc46zs5kI3nz7qfPWDS3kKFMiWTkImI75Rv7zegNB1MZHdsvkwQcLIH2eA=,iv:3c+3O+QSWB9QZPbO7Hy0pUcvFpCPaiu/6ySjLwycLb4=,tag:BDSrFR7p4lLJ8YMjqLWNCg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
