k3s_token: ENC[AES256_GCM,data:DlNXMZMSwd3WhaL4gwiN1aG5eTgwdLASqv8OBTpC1MNzIq/2zRk2InzT/ou74lfEcWX01hk4yUiphjMhC1ZCLw==,iv:fKGqLzsBQ/xHOjBijWzI7tkpCyO1TC9reL/4cOrOG6E=,tag:AGt0cCsq9FbZvFHnwOUImA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MXBFYko0THhjdlVtN2h6
        ejJVeTd4bmlJTXk3ZTViTHZCcDJnR2ppMGhjCllqbjVvS1huN0VZQU1aL1lrUHZ0
        TG1KVWUvZFI5SFhidFYwc1JIV3Bsd0EKLS0tIG1HQmNwbE9DUjJvOFhBS3d0aWhV
        NUJ5UDI1UXNzcDVEZlpaa1hVamtKRUEKP+cI975IEH8SKjHnC7scxRqq4oDW9BfC
        NTpEeOOZN3HCA0bv+3oi6lYIIrWQPOgbyC6KKDvleZcV9C3sw96orA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRGhGQWs4TVhXWVZ1VmE0
        NTZ1NDFxTGJUNGdmSFNSWldSVDV2dDUrWVFrClVQcEp1akhZTjduVGYrUkRvWHM5
        a3ZGYmxJUHhVMXpFVzhadytxQkVXaW8KLS0tIEFMaXJrM0MyeW1XclNoZXdLZVZh
        ejdlaTZSSUdET2NQb1JKbkRjZEhGVDgKjESMm8v9EkGOz3WE1VptEuDm1oHcyqnZ
        mSacfEe/AaUOP87FsaqDFv1fxSg5FygpEZS030OsKEu/lacBrp2ffw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  lastmodified: "2026-06-14T19:47:31Z"
  mac: ENC[AES256_GCM,data:DHyV73jsdLLEurh1QbTNI1Kp1redpLT1gz0SQURv5GJxcpv+WOkENCezib3zfGCkhNtfNUpb+5/fMVZG1VaaEGJ7WRrT6CrgFCKbJ7bjiE9noNxKhBc46zs5kI3nz7qfPWDS3kKFMiWTkImI75Rv7zegNB1MZHdsvkwQcLIH2eA=,iv:3c+3O+QSWB9QZPbO7Hy0pUcvFpCPaiu/6ySjLwycLb4=,tag:BDSrFR7p4lLJ8YMjqLWNCg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
