apiVersion: v1
kind: Secret
metadata:
  name: apprise-vars
  namespace: flux-system
type: Opaque
stringData:
  SECRET_PUSHOVER_USER_KEY: ENC[AES256_GCM,data:P/tDAOgxc7qa7PyjVMQ/JEJLXEGhX9PxYtZ9M1Xg,iv:jxjI1DoWAB1zfHKCTch5SS8lmdiJyUl8SohFsUpwKOY=,tag:AhECFOp71/AD33Uowd/fkA==,type:str]
  SECRET_PUSHOVER_FLUX_TOKEN: ENC[AES256_GCM,data:EcfR6i/xIw4vRsmbMgxxTj99A160iE2QrQC7uQCD,iv:h98/vqtnPLoTTkoemt81Ncwashi0S5BObC4esrHaBvg=,tag:vdl/chWwEzjHgOYYB/fuGg==,type:str]
  SECRET_PUSHOVER_RADARR_TOKEN: ENC[AES256_GCM,data:mgM570ph4spKoVlafI55QCZ98rIF6hjOzR2DNiVp,iv:h9dhFFbLA54r80iOlzpF2fgro0mVA+TGqb6+kSm+IAc=,tag:jErA7pyGs9/miF3GoOin9w==,type:str]
  SECRET_PUSHOVER_SONARR_TOKEN: ENC[AES256_GCM,data:Zd/NIqi5HKRzNJCLllFLg+DxcV2hGM4Y9YzF3rFz,iv:tb+3Jv2/q93JQ8Jm9Xh3xpZ5duR5+QNbnR5MyNAsDnw=,tag:8e5C9/nhjue8ry20GVDe4Q==,type:str]
  SECRET_PUSHOVER_LIDARR_TOKEN: ENC[AES256_GCM,data:V0Z/20W+0eUe2RO+O6re0LB9/Lu+wzHv/3MulylZ,iv:2JlCZEdLWSrhSRWEB8aiomdxVhB8/JUFGn0PWdi0jiI=,tag:i5cLpxPazU+6n23eqNrPdQ==,type:str]
  SECRET_PUSHOVER_PROWLARR_TOKEN: ENC[AES256_GCM,data:Jek8ToGSAJyY0B9TG2mg+pZzWNASoPOTSGLkiNJz,iv:C/nWQPzr+Yv3uQwQLn+HhGI2LSP+YZBYGos4uG2dpHk=,tag:mMnubmEwahFOz0qTM8Mn5w==,type:str]
  SECRET_PUSHOVER_BAZARR_TOKEN: ENC[AES256_GCM,data:4aBV4NKrI9TySXgy+X4g9zUU2EtweUEIjYS2jIrF,iv:vJVb+8LWKEiF1ri1TVCWhdKp6Gt92pYZfOLlNaZl4Cw=,tag:/+0C+1oTQqQKRe+SYr5Gzg==,type:str]
  SECRET_PUSHOVER_HUNTARR_TOKEN: ENC[AES256_GCM,data:Zl0lQYpjnemiOdvhvDinNt41iGgoeMaVb267f33p,iv:SIQ/txJP4OA6Jg5dP0dMGGUdtG8Ou+UXChIeOAFTCSg=,tag:qCs2fIYeDJP5zUeB98dzNA==,type:str]
  SECRET_PUSHOVER_CLEANUPARR_TOKEN: ENC[AES256_GCM,data:joiyjDXCLxv1oLt+RWftiy5/erfcuroJok8Nm//2,iv:9e/cZiNAjrJiUKC0h8t6A30xzodYgx9swjRCrMkOxYE=,tag:O9yCFelvoStYxM+TaFMX8g==,type:str]
  SECRET_PUSHOVER_PROFILARR_TOKEN: ENC[AES256_GCM,data:/5Be0IUROfwhtrbk08se4mzsKpX/5IGGzgUvSZy+,iv:YCZGvk/5rV4rFodYv/wx9qgnhtT00+csy4IZ7SXnquw=,tag:WTii+j7MxScK+nabKYE5sQ==,type:str]
  SECRET_SERVARR_SLACK_WEBHOOK: ENC[AES256_GCM,data:M3YNC1gK9wDKDg7gRrQ1SoplNUlInNbuvCNYKdOI3FcGRrvE47MkMsNw7RRwXU6YxnyimD9opKnLQnR+miTaRbE15YEFik47fP++Ddlvh1RI,iv:92+Zfb8PieI+8zmj5BLOm8G0fUSHZ7OgHyTx9jMJER8=,tag:OQmZVkl+pr9P1MP0pR2Flg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VXYyb1JsbTZPVktrRlpy
        TXJkOE1mMjhodmRjRE1VMEhNek1yUlZnREdRCk9udTFLZDFES05DNTBxY1VHWlRG
        YjlKa0RkZ1VGdGxXeG5tRmUvaHNtUXMKLS0tIE53VzRsV3Vyc292bnBjMWJ2WlZk
        VFRhNmN0MTV5MEdwUnd3TVYveXNYR0UK5I1IZkXoS3SCYledmiRr5Z2wDZorzY1W
        ZmBrsb/27fHWV+oe8VD3/ShDYOdR8wPD/6CE7v1e+K9ZNB1Hb+1yQQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUWw2MWZPZjBOTUoyb2R3
        Vlc3eHBiR1ZpcVhEKzhRajB0M2dONC9uUDBzCnE0OEJNeThJSWk3bzF6V1VCbDRa
        dlRxMVBhUjBrVUo3cTlzSzNFRlMzWVUKLS0tIExTNFlzWUVsdDJVSFVtSGJCOTRo
        dWJsOFJmcm1GbzhJYU9LclhaSEFxMlkKhHDLofrYrie+v7fBIGM0rOH0IO0I4Whv
        s/vQFBIUMWgGnPUDlVY3jlTTrQRa+WmMDq9TdS/9SbW2MTU4cv6qCw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T15:43:41Z"
  mac: ENC[AES256_GCM,data:cnvCCh5Zn9PMJS/B54BuA3rFwB1bKXDna6hkQZ8lZ8WSKX3h9ZP1wBMHI+ZACgSfT8ImsDnQ+Tzy2jn6EwjOzmQRKz2HJegbaY9ibnf6Am79+bDM0YYA6xEmXHQBBpHPUlGO6ZgaMbJF6c9drdfyyMfBawFmg8MZKzMacq3wBUo=,iv:ekVXBKHVmim0YJ70geafLStAXYHq3m4r72Fczgc5g2A=,tag:/HkF7/PNUXtsMr+dWJ92HQ==,type:str]
  version: 3.13.3
