apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: romm
  namespace: romm
spec:
  target:
    service: romm
    port: 80
  rules:
    - hosts:
        - romm.item.fyi
  scalingMetric:
    concurrency:
      targetValue: 30
  timeouts:
    request: 120s
    responseHeader: 60s
    readiness: 60s
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: romm
  namespace: romm
spec:
  scaleTargetRef:
    name: romm
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 600
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
        interceptorRoute: romm
