apiVersion: v1
kind: Secret
metadata:
  name: romm
  namespace: romm
type: Opaque
stringData:
  DB_PASSWD: ENC[AES256_GCM,data:u0LW2WIJfMN0sU8M8wSnk+4hcoEhxG9zjGD5AxaHrMA=,iv:8QvUS9SymS7aMO81cyDdkd9KvfnSgcMni5vEWGFr01o=,tag:xBkefUyA9cPOGiQ0L6SHzA==,type:str]
  MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:ZbLh45ViRYATfrsRJ8W6EuM1JvYxpCnqkAvOQvc=,iv:GZaZ6MMWt2mmPXMYRIgnCHoPB692iEqpyWbB3VDhfc8=,tag:IKEzNT4RNsWfDomlWK2WKw==,type:str]
  ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:bSNfru+AiQ2BOANxT3XQYRyPcUH5sZXJyvFNQWruiyOiP8q3UWiY7VDqJ/TwRv9K7xh1wq2s+otZq/h0bv0g3w==,iv:RWzgBGjnt2Lnmw4RkwXko57bu/YIo6SkGUwuohzMvZM=,tag:Qgrmiu1NG2wJEb5ga5MyEg==,type:str]
  RETROACHIEVEMENTS_API_KEY: ENC[AES256_GCM,data:8reWd/JAapPtxthi1/seEEVXZIxWB3MV3D2YN9YSB/c=,iv:qvOrHxm6NPgqi5+LzHytB1FL0C+Q8UXPZFWe9MApxm4=,tag:Vmf1fL/StnUt55Wlqfcbcw==,type:str]
  STEAMGRIDDB_API_KEY: ENC[AES256_GCM,data:XIa30ta+A2rnSisAJdPr51AHbbVsETxieOFhHC7TOFM=,iv:96O7WVNsLflurnuhmEkDxpayLJzZhGlrPtIK+tJvBGA=,tag:C+nIlB0P2UWRXYIKKf7ILA==,type:str]
  IGDB_CLIENT_ID: ENC[AES256_GCM,data:MSTKEdcJrd/2VmKJ4KyF/rzyBnr7l9CPNZr3ipXE,iv:9u+cIUMbyQhVJy+qAWHH68397B1GMLmGs4bQbWuPxSI=,tag:vWgrkLp0kX2OXPqoi1d8Yw==,type:str]
  IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:bU9eE0OX3rk0KoGcybTJayF8YQ3uRawuowxx2Gzt,iv:dXkOPSdoO2wnBDUpzUdLrfeuLWpOYWkH7s1H6hwlTMU=,tag:zTL5R6Pkzw83VBJavvH7CA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:XZu4eOgM5nSrps9UkBH8qXDsBI2MQ08D1V0ceglj8uTs3EGbE5A4CNFHp7DpYt0inb3nIXJEug0fJRSaDE/8/Q==,iv:TF0rROXfdFQzlzGHskYeKlxeBev8b4WGZ8j2qPYqUFg=,tag:NeXSXTlxnxEXzy9nW6yePw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNzJ0QVdtODVGYUdrVTVT
        MzlKWW40WlNRQkhMRVRiL3N6dGNPK3l0SHlVClJWQjBiWUJRRXd5MjR0NTZCbW5X
        cHAwdFRHZEFFWmxLcTNPSlgyc2VQN3cKLS0tIG0zVGlHWTZ0eFUra05FNFdVTmhT
        UDN0NCtzVVZVZ0tRa2J0NWxwcW91bGMKS56Yigd801AlgbzMgrUkxV/4bNie7yIR
        LKVRVXTjaesYqm1NiM1wz5nJB6vpwBhEWRT8xcl1xHgZQzzXh3EP4Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Si9XZzR1WWZiZGZacjE5
        STlUZ2pxNXBEbUV6UE9OUzFNdmUyanpzTUZZCk1aV0JiVkFHTFhKbysxZ0JCbFpJ
        Mi9ER3FEMTZ3WHB3WUZZSzBmTHZYUk0KLS0tIFlEV2pVK3BkTFBweXE0UlNncHli
        SWtZMGtGSEZsSy9hLzJpWFkvM3J1MWcKoYfIr6vQ217rDp9LueX9oNHv4m/ayKhe
        KYeGu8lEesTXFeHGqsvgyyIDlxL6fCPnuXoSiPrd/A8pN2eiKhZdNA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T01:42:11Z"
  mac: ENC[AES256_GCM,data:Rf9T6r7oRp4zCGqS5syZMkbwkxzl8R0WseqZyxglhRQT88siHg6iN3w5rkGjfUjFFT2OS+nPm4o/oIlC+7xiLNGjwm5WMBMjzmD7POPugI61xrG5l6OSVZ6xhgBDxnYZ6sj8KLYpSyOZidfmR1ya9BKC3kJLtZsT17fpfJFSMvM=,iv:69o8gescz4evNW18TJhVw5q2CMAFbolZbUWlw0vP7vY=,tag:AYdy310070K2B733nguGsw==,type:str]
  version: 3.13.2
