apiVersion: v1
kind: Secret
metadata:
  name: romm
  namespace: romm
type: Opaque
stringData:
  DB_PASSWD: ENC[AES256_GCM,data:u0LW2WIJfMN0sU8M8wSnk+4hcoEhxG9zjGD5AxaHrMA=,iv:8QvUS9SymS7aMO81cyDdkd9KvfnSgcMni5vEWGFr01o=,tag:xBkefUyA9cPOGiQ0L6SHzA==,type:str]
  MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:ZbLh45ViRYATfrsRJ8W6EuM1JvYxpCnqkAvOQvc=,iv:GZaZ6MMWt2mmPXMYRIgnCHoPB692iEqpyWbB3VDhfc8=,tag:IKEzNT4RNsWfDomlWK2WKw==,type:str]
  ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:bSNfru+AiQ2BOANxT3XQYRyPcUH5sZXJyvFNQWruiyOiP8q3UWiY7VDqJ/TwRv9K7xh1wq2s+otZq/h0bv0g3w==,iv:RWzgBGjnt2Lnmw4RkwXko57bu/YIo6SkGUwuohzMvZM=,tag:Qgrmiu1NG2wJEb5ga5MyEg==,type:str]
  RETROACHIEVEMENTS_API_KEY: ENC[AES256_GCM,data:8reWd/JAapPtxthi1/seEEVXZIxWB3MV3D2YN9YSB/c=,iv:qvOrHxm6NPgqi5+LzHytB1FL0C+Q8UXPZFWe9MApxm4=,tag:Vmf1fL/StnUt55Wlqfcbcw==,type:str]
  STEAMGRIDDB_API_KEY: ENC[AES256_GCM,data:XIa30ta+A2rnSisAJdPr51AHbbVsETxieOFhHC7TOFM=,iv:96O7WVNsLflurnuhmEkDxpayLJzZhGlrPtIK+tJvBGA=,tag:C+nIlB0P2UWRXYIKKf7ILA==,type:str]
  IGDB_CLIENT_ID: ENC[AES256_GCM,data:MSTKEdcJrd/2VmKJ4KyF/rzyBnr7l9CPNZr3ipXE,iv:9u+cIUMbyQhVJy+qAWHH68397B1GMLmGs4bQbWuPxSI=,tag:vWgrkLp0kX2OXPqoi1d8Yw==,type:str]
  IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:bU9eE0OX3rk0KoGcybTJayF8YQ3uRawuowxx2Gzt,iv:dXkOPSdoO2wnBDUpzUdLrfeuLWpOYWkH7s1H6hwlTMU=,tag:zTL5R6Pkzw83VBJavvH7CA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMitETjl2dEdiYnAzN0p1
        MzBWcTRVbFBpUS9ZbUQ2aHRXTHdSbU8wNUVrCjhyTm1DbElEQXZBZEhCWlVCei9I
        NjVWbUJtU1RKM0NrZlhaaXBmWHFDUWsKLS0tIEc0M2hSWWpVNzVIOHp1c0x4WVRs
        Z0tEcktjanZHbHVYaktQU2FsRlg4MlkK7lZbuS/Y9EHAFQcMiVsJUXPMprdWx9km
        3yinfXmNj8ZEiLS7T7glWCoBUj0YieeysXBZDqXKpNrzXkYtr0U9fw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-31T21:35:08Z"
  mac: ENC[AES256_GCM,data:mUY1PC+dRA3mB6XQy9xKnLwJbC/iKr5kGUJsmh8lxk5Df7SRkbUDBDxGjpJHLt5D28C7VixXNoRgoE13d5qLr9T5uBl6FIGDN7QBKs482vBCiI9WRvLE9Cd01MrxLMHrXPBli3/zV56PapYfjEKjcu6f18pvgybY1kcnG9Q3QTQ=,iv:JdLufmWz7VmJraFusU3uHJ+WxnykDJuF+Gt8JRvX6Oo=,tag:e+vZMqJF5CTdM4cwWqwS+A==,type:str]
  version: 3.13.2
