apiVersion: v1
kind: Secret
metadata:
  name: romm
  namespace: romm
type: Opaque
stringData:
  DB_PASSWD: ENC[AES256_GCM,data:u0LW2WIJfMN0sU8M8wSnk+4hcoEhxG9zjGD5AxaHrMA=,iv:8QvUS9SymS7aMO81cyDdkd9KvfnSgcMni5vEWGFr01o=,tag:xBkefUyA9cPOGiQ0L6SHzA==,type:str]
  MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:ZbLh45ViRYATfrsRJ8W6EuM1JvYxpCnqkAvOQvc=,iv:GZaZ6MMWt2mmPXMYRIgnCHoPB692iEqpyWbB3VDhfc8=,tag:IKEzNT4RNsWfDomlWK2WKw==,type:str]
  ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:bSNfru+AiQ2BOANxT3XQYRyPcUH5sZXJyvFNQWruiyOiP8q3UWiY7VDqJ/TwRv9K7xh1wq2s+otZq/h0bv0g3w==,iv:RWzgBGjnt2Lnmw4RkwXko57bu/YIo6SkGUwuohzMvZM=,tag:Qgrmiu1NG2wJEb5ga5MyEg==,type:str]
  RETROACHIEVEMENTS_API_KEY: ENC[AES256_GCM,data:8reWd/JAapPtxthi1/seEEVXZIxWB3MV3D2YN9YSB/c=,iv:qvOrHxm6NPgqi5+LzHytB1FL0C+Q8UXPZFWe9MApxm4=,tag:Vmf1fL/StnUt55Wlqfcbcw==,type:str]
  STEAMGRIDDB_API_KEY: ENC[AES256_GCM,data:XIa30ta+A2rnSisAJdPr51AHbbVsETxieOFhHC7TOFM=,iv:96O7WVNsLflurnuhmEkDxpayLJzZhGlrPtIK+tJvBGA=,tag:C+nIlB0P2UWRXYIKKf7ILA==,type:str]
  IGDB_CLIENT_ID: ENC[AES256_GCM,data:GGRCJ4bLUARhtRllbrDNdvIl6lbFgOqvnTvtXjl7,iv:9GBRctvU+B9ZF6rrAOkAgGvGv3P0BMdocwvLIQpWw4k=,tag:Pnem9H6I0alJW0vMH8pg2g==,type:str]
  IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:yTzUb9NXtCs7QgPwTFEEdYWH4YVBl9hxk7XHgIuh,iv:MorYVddpP4Mz3opCxhaO4IJVPalUQvc31VWI3DKyQAc=,tag:EaMSyvNOONykAGlkPolDbg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMitETjl2dEdiYnAzN0p1
        MzBWcTRVbFBpUS9ZbUQ2aHRXTHdSbU8wNUVrCjhyTm1DbElEQXZBZEhCWlVCei9I
        NjVWbUJtU1RKM0NrZlhaaXBmWHFDUWsKLS0tIEc0M2hSWWpVNzVIOHp1c0x4WVRs
        Z0tEcktjanZHbHVYaktQU2FsRlg4MlkK7lZbuS/Y9EHAFQcMiVsJUXPMprdWx9km
        3yinfXmNj8ZEiLS7T7glWCoBUj0YieeysXBZDqXKpNrzXkYtr0U9fw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-31T03:20:36Z"
  mac: ENC[AES256_GCM,data:9ilwt3SqbWKduGtM7+xVC1wrTsldX0pT2dmg6UFDCLI8503EQzDoWRmz1TstvMZmmK4RIiQ11s2DIdXKcnxh5Na5h2lbE+uDNT/1rLXNI1QvfoCP9ASCkNupbM8RCf79T1KNJ9YOFNxiqht6dy5uZDhkttlwsxtHFZcLUyJ4jB4=,iv:XUvHnhsOkbTvosHI2Xd8HjZ5uCTaSzkSLcZLNT6sJIw=,tag:61npExVvCtWCAorA9xj9Dg==,type:str]
  version: 3.13.2
