apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-db
  namespace: romm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-resources
  namespace: romm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-redis
  namespace: romm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-config
  namespace: romm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-assets
  namespace: romm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: romm-library
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    name: romm-library
    namespace: romm
  nfs:
    server: 192.168.20.89
    path: /void/media/roms
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-library
  namespace: romm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: romm-library
  resources:
    requests:
      storage: 500Gi
