apiVersion: v1
kind: Secret
metadata:
  name: homelable-secret
  namespace: homelable
type: Opaque
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:FhliTaaPZ2ZX+jC12oKUtrP0d+2ICukK3vcx0obU9XS312OUct12mH7noJb59z2CLiu46nwtImenjF4gns9ZaA==,iv:ZBUeYMqi7O1fTLFZtsScwqAVXk53THs7HO0JIobXc6k=,tag:lEadLdrePWmCYFEtwtvUhg==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:uZnxumsJxT6Kq8h0b+tzvsdQNN/22I1fEyXZ1alr0MxsgA6Tl3EtxLJ//kYthWn2jNKFIx0lmcvbdRDVfAGDWQ==,iv:MuIaq+SCmkGKiL8jD2jVKc1IfKst0Zr1HivFScQNG74=,tag:xStNbzVal2iWKqnkx56GXQ==,type:str]
  MCP_API_KEY: ENC[AES256_GCM,data:iFwdUFs1gTQxVKuskfXu68/zQ0ysqnMUNlKwwFyUeQDXiegfbsRL3IiPG+K3U62XnIQrMQgiRQ==,iv:tecU/lWfu/nr3x17BNgt7nOdokInxb3BKRqAtDgmM0s=,tag:oIueCV+7AASdN9brNYszZw==,type:str]
  MCP_SERVICE_KEY: ENC[AES256_GCM,data:UYEFGuPOlGpBOIhlNu2IIXMvKZ3VygLRjhsq6VRY0gtLfRHA1RgE6FQSrPADMHnboaM2RQ==,iv:Q+dn+ViwfLMmRGDfOgSsmLU3Jzb0g005PbUzSwBjM54=,tag:ZpmO46KQw0WTz0WBomwkHQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHY1FyK0hvSXJTajBrRjkv
        S2JCd01wVGNVNVg2S2wvQ2l4NVFPRDAwaFI4CnJuZmpFRU53cS96NVJnbEtrREVp
        YXFVZFhVZGNYaDBqd2VEZ08yZGo5WDQKLS0tIGt5MFYxL3Y5UDNHbkZ0endZVWlo
        VU5ONnBWaTIrdFVaRk5WMjhYN282RVEKIeEeiWlS7+ocdzLv05ALPaear4On82n9
        D8Cp9CGmAcSuQiyx2DQ+7a3R7ECGhlBWoGpbwKN3TCHsuwyPGKrf6w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-10T23:44:51Z"
  mac: ENC[AES256_GCM,data:2gx+VoDhZWJ3RInacSt5N2X9uKs6q8g4f0ZAp1gZq8tfg3fLQMqjCnnjuMHDuTwMKDDBMIXpWbzYCPdKnJTZy5I6+gtEUunD58+B/cA/d4AHNxDrEioiQ/TJJwMsUwXDz0LP1i3wErB3eQjk+nVUxcH4u9JLzunSE0hJcMhmytA=,iv:XOLNYfuG7J6gb4rwDd2njkvw06RLiDWzGICy67VS7sg=,tag:jzNC7oQSibYU4LSYDay2Xw==,type:str]
  version: 3.13.3
