apiVersion: v1
kind: Namespace
metadata:
  name: baikal
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baikal-config
  namespace: baikal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baikal-data
  namespace: baikal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baikal
  namespace: baikal
  labels:
    app.kubernetes.io/name: baikal
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: baikal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: baikal
    spec:
      containers:
        - name: baikal
          image: ckulka/baikal:0.10.1@sha256:658e9582f8d418392b4dfe7e816835b003694c8cb54ed0ba598eb5727b58fe22
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /var/www/baikal/config
            - name: data
              mountPath: /var/www/baikal/Specific
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: baikal-config
        - name: data
          persistentVolumeClaim:
            claimName: baikal-data
---
apiVersion: v1
kind: Service
metadata:
  name: baikal
  namespace: baikal
  annotations:
    gatus.home-operations.com/endpoint: |
      alerts:
        - type: pushover
spec:
  selector:
    app.kubernetes.io/name: baikal
  ports:
    - port: 80
      targetPort: 80
      name: http
