---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: porkbun-api-credentials
  namespace: cert-manager
spec:
  encryptedData:
    PORKBUN_API_KEY: AgBHNAP7Z8spvVyk6c0GgB9y2aAGEpGe3+wWg+ovShS7YmJtUkDvNTFcqmiXCUj/eOIE2pb2LisL2Zryta7nZ7z8lgXVsl4bNqPmFVxlpVlyM69GRgo6Gicb6U08/GaABY2sTF6g60M1ucuDcByS3ggT4FEf1+kHN2LztMEr6mSI5SqBtsCCnxDtXDqNZtmQNqXXuFiMbpaMo+RFL3q23saq4o+LOk0eL1voTD4Rw+itfYilRfG866zE6wTLKlHjjPSA7qPW582Os3vIv409DTc1QqP65TtOk76zjj7/q0vUVxuPZQegnp8dvdVYrE6G3cJOpqmMZ9/y3hUASYdb63vbGY+Vjh/x9nvfTvwHVsPtgygmvSJ5eIUYQoJ3VBXXitLyiIMrli4vG42Vk9uWrckwBr3Dv3hWjXrHimznwALbWXOLtfVkSY+zXdWX5GSTWYuvYc2+6ucYasSt2b5FrxExaVpRU/S7SkCdxQaZLb8PUD4BAqWq8AEC0UvzhEhmlX0MkZTHxoTbWt5YFpALogAmad65ErpR5So7AcPONLHdAaP1GOwpdKq47t10whIE/wLeV09xAYExnMtbVxoHz8PFd3L5P0H5jrq8E/G+bXkjHp17wRfzaaWuWEc+KY6LLSW5awmVk+9iARL5yi185fqApJvqxFVIY32ExH8YROgxM7zClBj2Bkd93vBpw7C2xZVpKsqVg/Cdg4B6aMBJ5vmUGyX2S5FBHbmUoXQJxAxWquuBA0Tu1MjzPNJLMlnGD16q83cRuqL5dgLIRe3rY150aG53xg==
    PORKBUN_SECRET_API_KEY: AgALRxDfAl6D12dLCTd0lWbPspA0z3OHGhwhwPWyFlpnBV9WH1qzc5wGxIwjUbnz6oRyD8lfFc+IBEUTP0PUOa0+1WmCo2iF7tDPS58mCzGSLoYhm4HRAnsL/Ywymt/UnL107HV6NS3qcYXVyrKqlG9b2oGcM7QkbWDxANc4p9WxQLosR7XUFFAM0HOOGducZhc9y33yL+nJFtiJM9x7Z+36omYpeNRIoixkNAJEKjXkK68/RKnBR0JH5+n18R3+TCgBZKBC6AHZp5vw5wdoqRV3tfib/N8MjkEtZObePAJajBZfsIOACg/Xw3abVNGi9jz91fDHWGGzv0Cm7Yuw/mbfcys77jZIEIMGg+1tVrod0qsxxEq11TYR2cGZdiOVAajrv/wAHqOdL9tU+BsaJDMmv6Vspy+9lD6E7azU7ZIqfaXZPM6/PLcmQvXEod1Oy3XHd3IG5eUssKyFEKzYfADrrHrd0xCYZRh1d7qbADrB6tuP0a4Xzv3FuqAur0Cb+Z9I5hjCT9s8h6+H0OJbx8SGzOvLF7tmvH9PQIoz+BIOz5QjR3k2BIzSeSGSNsnEnlavR4Dc5ckxIuNlkeP84MAfAymqIME13ncTFtR+wl7FZCYhfF6nqu3AWuPce1Nh4+S68RnWTzgippRSItQH1fXG1Wzqu4LDEHLzWWyBtIK2QezsEUw60yksV1JqZbxthzgtDGv1k3PF05lvsWjJUyawtz+vsk0chfXiLjtrNlM29eNrs3dEx8g3n/2XE08fXQgqk3IR1ddNPEZY+ufOOloHPTk1vw==
  template:
    metadata:
      name: porkbun-api-credentials
      namespace: cert-manager
    type: Opaque
