apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - wow-secret.sops.yaml
  - database.yaml
  - worldserver.yaml
  - authserver.yaml
  - sql-exporter-dsn.sops.yaml
  - sql-exporter.yaml
  - prometheusrule-money.yaml
  - grafana-dashboard.yaml
  - grafana-dashboard-public.yaml
