apiVersion: v1
kind: Secret
metadata:
  name: wow-sql-exporter-dsn
  namespace: wow
type: Opaque
stringData:
  dsn: ENC[AES256_GCM,data:3LyzdRqf0ZZ8RWtDBNaG9dpxTaSmVPPBPIXGiTIbMQLOgtKywXB0sBnEdM4GyK5g5AjQ7ruC/KwfVZLoEwgVMwMjgdyXpWbWlFDMB/Knu6wggEV9ou76+gfZmbhFHWrbn0F/yPiIC7Y=,iv:YdeVYW1C9S4O3mv06KmDKHsspKdoT0T5jLA+/emi98k=,tag:FmaLMWrwrIG5LxHCm+53/g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTDFjTExNL25xRTZKUWFy
        VjJZeXZ3cm1xczFNOVNBbW1IdDF3ZjdVZzBrCmszQUlKM0tZcER2SklIWkE2UzQz
        amZYcFUyVlhLWXBFM29OdTB0cEtkblEKLS0tIHdHWDZVWEJRZjJNMGNkV2VGVTdX
        Sndra281MU9xRjJJK0ZZVXRlTXZjY0kKwMmgsxAZCYtMTD2ua+CjhL+WVGpZwv7G
        O9pnws26uc/tnx73N9AZ0XXVG2QlWa2MadmN52kj72uvj3WMdwyfuQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eSs1Z2lnSWpmRm54U0RL
        MDA4TGxxaTlsY2ZZNTdsaVRRY2tzWDVsekhVClVRcFNibDFtZGRWTG1oZDUvMGlH
        cWs4eTZIMk1GNklrS2NDMzdhQVF6aGMKLS0tIGtQa1U1b3gzK1NBbks0bkwvSFhU
        WHcrQkFqK3JiTkhFakJWZ3ZFQlVMQWMK9EyIMT6/UFOuXihhfTO6k+iwiWInKyE8
        8ua8GyYrNj4lHt7quZDtmQUQFEwnG83zvwtS4iZF1HxJf16vu/CRrg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-29T14:48:24Z"
  mac: ENC[AES256_GCM,data:ETPc+hmth1kRJngqS3/vDWty9JZPq/w7cf+/MIV/HQz5nL7m7Aau/4duYdHZ5lDukXNZiK5IOk3dtwo2NQyU/+kNvnPR7cgl4r4apqE6NzKmhqOMNy4R+vONBZyduj+dQz39IbEQ2d+vomqx1zzPpeF+57g+slLEqgNC6k1fK6U=,iv:lTrnI3rsm9/SfMf0Q1Phvj5hga87MqhSOcNMNTg0fOE=,tag:vlnZWCMR5Btn0Qnn0/yCpA==,type:str]
  version: 3.13.3
