apiVersion: v1
kind: Secret
metadata:
  name: wow-sql-exporter
  namespace: wow
type: Opaque
stringData:
  SQLEXPORTER_TARGET_DSN: ENC[AES256_GCM,data:NTx8QtS+sfoXuMPqhdb9YNRfKu8MD7mXGHOR7crMX/yTXsNkFG5tDZCwcgUAEDh5zOYx7N1xdOG2b/PBWT1ixAN3+fNCbAgvYFhQnvSk+MrXD6MqSSRD,iv:LYRlPA3ES8/mMc1hTZtry0BDMr/AQy7UjJcIdVybNiE=,tag:M7prhKRXLpkzmXnCVgUjyA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZWZ0U0NHdGs0ZExQcWlS
        S0hvSWpZSlVjYUlrZWJzeWdpcUYzdS8rbGxBCitlYkNHaVRzeDdKaDBRZjhPWlc4
        S0tmelh4UTRHeS9IWXFoQkttcElzWXcKLS0tIHdhcHJQTVlLVmhnc1BaYitzMll2
        RTJRUmRhQ1ZZNVBQUEtkU2J2MmJDZFUKWItROILgz9jyRAOCe8ydx+o42UYLmSjV
        v0vy/F+UbI6mjMOLuchaTBxr43xPrKdXR6SuNocK3xyhso75TXmJNA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYnBtNHJGZTVyazJCMTlE
        c0YyWXVZNyt0bHJ3L054djd0d2NOcGJFekZRCjRYaXdVZmF0RDFidGFrMWtWeExm
        QklIVHJTa0xveVNoM3NBRk9DRE5IK2sKLS0tIFpKNmJPN1RSay9VRThrSjRITVZB
        cy9iN1hRa3VzMTBVZHlSRElPOWcwa3cK59hp1p9LI2jaOBhCdBTwA+Qm5JSVqAUI
        ucF9Rls71e3tIPBUJmcZK2FSyOT5r+qEByvt1ZfLSVIPyd5eq/3s2w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-29T06:15:03Z"
  mac: ENC[AES256_GCM,data:PlHipxwTsoiiXn6n2gWTedO/c6sc5Ypi+37M5cVb1j5sHZLCHCGHAVYBneIukvMURZ4YQree93hZykXKM09GPIHLdv+2rs7c54/PKxuSSKwGudKdjF4cypBCObtzOOeWxNeTdgCU/uMIw8gprWgADDUcETImROHFrxf7wuh7XYw=,iv:sbRroYwmmrVdDHzwWvn2wBFbaJWsWDqT67p6hNSJvGw=,tag:15sN+1dnjg7GfTPUqZMrXA==,type:str]
  version: 3.13.3
