apiVersion: v1
kind: Secret
metadata:
  name: wow-sql-exporter
  namespace: wow
type: Opaque
stringData:
  SQLEXPORTER_TARGET_DSN: ENC[AES256_GCM,data:wzZ0OK4kkSdtPs32Ab0xoJVlstypR7kutFsP4Y4M7EQ1DsePD72J5zQ/tg2hJ+u2SXTuwka9RWjqDFmRIHkLFSrgDGwNB6fJC2EZsaN6xEAsmJF5cVdqA9tzxm1B5MwJkVo1+e/Vu6z/hM/lEA==,iv:Ar57Pjw5nArTFhGwnz0p5mUByTbEXJ6jBkbTqDZsmxU=,tag:Ri5rkio8KRs1jdSifsiFAQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eCtyUTZKc3JxNnlaOU5G
        b3R3b0JnRSthK2VoWjkvTGFrSE9YdHBsOGxrCmVETVdWendyc3pkUXo1WTZzSzhm
        Umx3T2RKM1RXeUd6M2F6WkEzZ0lTT1UKLS0tIFNhb2VSZ0JVTS91Szd6bmt4UWZo
        eHEweGQzTThkY1Fidnk5bGVrVWN1NlUKXlRCIVZmuZB6ULugL6Nig1w9w1Vd8l8s
        Skp0X82rON/YwHzbqI5TniYZWp8fq7LlbKUBZMy/2q4oHSpCi/0vqg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldDRMa1YxNGtSUjVVWlk4
        ZFlKZVAyT1VBL1Q0RlV0K3NVcFp5N3hnVFd3ClV2cGxlTzFWVmJpNG5BczNTTjNa
        c3dXa0hpb3V2OHo0azVZSi9xU1Bqb3cKLS0tIFRZSkpRS24wQlZTN2JVdjdKQVd0
        bUlsT0RnRjdHVU1tZ3UrY21iL09uTDQKZrX0XQa/bLWDdfbpZDX5RgWR1A96Q1qh
        Gzmcb/ttVgAKtxUh00vbDxYeGOtEnR1O5VB/6vuAnBhhjOeVsVuHhw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-29T14:26:28Z"
  mac: ENC[AES256_GCM,data:XEhWNIdHvvhV7wVAKZ7YcajkuVG3qUHek9xXUjWNJgaDTXIv89PnO/jWFLZw3LjY1i7MysQDES/GP4ME7YEdilEgnc8qprZeFbguHpuF+QhXmyHbHnepQsdN3s+WmOupdP4vYZ023jErlIAvOS4bNS+/Gt/lGKFuRCyUqjR+Ioc=,iv:Cfd26iE1KRgc0+SJi/gFjWc874l0iUSJFBP3Bjm3rOY=,tag:eM7EFNSycHEjPPxb92DfOQ==,type:str]
  version: 3.13.3
