apiVersion: v1
kind: Secret
metadata:
  name: wow
  namespace: wow
stringData:
  # ENC[AES256_GCM,data:1ILcVnhrrG8KXaX+Ofc7fGoqHh/0Z2bbzktVfen6vg+E2mm7HB6Fs5VH5A3arhplobV5BgM2PFm4zEgzNAnu2H5FxuB/LVAiM3LtQk82UXiRZd93u5i145RUBM+AC4rCCLwtJwV1kJxF2kTQaX3BpNWSLm/ZXH8Fcy83ZpMjeRYy1SkgxGqBMru+X6ZVEIbtxAzSdipwOj5sJjrzLoWYE7d0n8Q3GW+AUORgS6QB8ekZMaSl5dnx0PEegAFG+BdgoXuPIyEEaPdOgCru,iv:Hal/4RgH5vCagcVkSDOot4UqQggW/5ZiL2O/IJSd6Zg=,tag:w7qP1boyM6nFoRfjzK6zFg==,type:comment]
  # ENC[AES256_GCM,data:h7MghBWIPWeE2wNoXFRw86cOSLsomQad3Ri2Lu75JjxmQgXxMXGntuTkHYCMj9PCgBCU/CLJaXEoQPD6G+TZdR4E2VnGKYRMzgZ83kf+wTCbdkOqL3t7lDuxewb9byhj8+Xe/vj0uESDXVL4vYrbk0E2vShycuAGwGDrNPILGJtxwoClL8nFlvPWjeD5LERavC9lL9+jTSPfqY8si2F/WiQsdJAP1qYU8Yp/USffLBg=,iv:+zY+v1+7zEoBXqgZJ7G2+GswF3mpsJEorzxrj2+56t4=,tag:p/ocjwDwsORXZtNlRvQ0uQ==,type:comment]
  MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:NgYag0UIDsdesCGS23a+aazfpnK7GPexyNsklkm6Jzs=,iv:odu2JZbxjOc1vx834IeCr1sgdVuIKuIV7X4jhCdmH4w=,tag:y0RiOclMlM5XfTJkB4uy6Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZUlyRW9iTjQvVGhKQ1JS
        cE1GV0lVSWcwVmtBYVBMaWNCYTZEVnlvSm5ZClpTVHcyNmZNR0xERW5HOGxhZlEz
        NUdGaGh1WmlISU8vQnN4ekJXeWV6L28KLS0tIFlOUklUUncrMjVNVFovV2lYT2Fi
        K3NCTENjK0xRZnVSWGJpcWc2ZitqaGsKmO+BAdoumYNL73aeqKQ2JXLoHLpz/S/D
        xou4CuaIg2raqCxOl3068L1K6LR+b4Si1fkcj8KxmT9d4yWSdipnzw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcmVOcWFJc0NPSytBSGEx
        cWppY1dvQnhVMUptMzdZN0JtNmlaZ0tsQm5FCnJmV2VLQWg5Ym5FMjhaelh0QXRE
        UXJ4TkRhRWN6bmc2ckZlNkpCM2ozbm8KLS0tICtxaUZabGtSejlRNndURTNjTFh1
        ZnRTTi9UUXE3Y0hkRWVhSEhhQXNaeWsKQHuPB/s4ZAopC7HH6AhH40GXTRSmM3hR
        BPR1IQHUijMzMOkSQWxeqwq66R9zyVXDkHVu2l39owDu5XVroK0LzA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-23T23:43:35Z"
  mac: ENC[AES256_GCM,data:5E4dDUrPV9VD3JC9+TkjTkQbOk+MZ14naNSwqSCDK2uDRRi1wqBd8aXTUO7MgO3xLvwWFNSuM9sCpIAvBO1nIXpPiQhlLo6rcTAjcML0N/KtGbGRU51Nh16eCfuyCQzZv3+DrhsYKVpS1tFKNSiSsttmuDPyBmTmVLp22pnPTPQ=,iv:AYd6wtz6gjk0acR2FabilQlw4OC0UBzoHlb2MPrA9zs=,tag:jWOhDihPgfDDSyvMCBbsPg==,type:str]
  version: 3.13.3
