apiVersion: v1
kind: Secret
metadata:
  name: wow
  namespace: wow
stringData:
  # ENC[AES256_GCM,data:Zrsm+iLbkJKiqok9mhKwd/u4KDRBK2wb37jRzd7AwpcCgHguy0a8C9/1W1uE1YmaqpxvYjHAZ9ICO+Xwp/HCa46cb0+b,iv:wu9+guJ9MY0ushY2Y9v4a+esRT/i+ozwVfa6+Ywcsb0=,tag:5Xc7aBLchnmockj1MGumWQ==,type:comment]
  # ENC[AES256_GCM,data:9q+zm63fkibdjUzkoKbmfo4dEJnuZ3a0kv11GFzzaFoL9Vi4zNdJFvS34lR9eLcs,iv:V/tcqVx/6O0rVX1lCmzAxh23DvRZ2bgTUmvqXV91Y7Y=,tag:2PS/0Bt1lbil4OGSTvlrcw==,type:comment]
  MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:KhMb4JmLYSUF5FlYbouz3vK39uJ74w==,iv:CHl5W+V78IvCG//FCqW725OJ5+qZteRpjpFmwEsgmRU=,tag:oius9GIWZHPgMYLv7pssUw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZUlyRW9iTjQvVGhKQ1JS
        cE1GV0lVSWcwVmtBYVBMaWNCYTZEVnlvSm5ZClpTVHcyNmZNR0xERW5HOGxhZlEz
        NUdGaGh1WmlISU8vQnN4ekJXeWV6L28KLS0tIFlOUklUUncrMjVNVFovV2lYT2Fi
        K3NCTENjK0xRZnVSWGJpcWc2ZitqaGsKmO+BAdoumYNL73aeqKQ2JXLoHLpz/S/D
        xou4CuaIg2raqCxOl3068L1K6LR+b4Si1fkcj8KxmT9d4yWSdipnzw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcmVOcWFJc0NPSytBSGEx
        cWppY1dvQnhVMUptMzdZN0JtNmlaZ0tsQm5FCnJmV2VLQWg5Ym5FMjhaelh0QXRE
        UXJ4TkRhRWN6bmc2ckZlNkpCM2ozbm8KLS0tICtxaUZabGtSejlRNndURTNjTFh1
        ZnRTTi9UUXE3Y0hkRWVhSEhhQXNaeWsKQHuPB/s4ZAopC7HH6AhH40GXTRSmM3hR
        BPR1IQHUijMzMOkSQWxeqwq66R9zyVXDkHVu2l39owDu5XVroK0LzA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-23T23:17:22Z"
  mac: ENC[AES256_GCM,data:Sore8gUqUtuZB2nWo/08E106P0CPolQsE0DjibitKB8j6f5BYJSazLOMzDo8XO4llQM/BHN0b4Y80hXlGggtU+6ICunu6zgE49UdZtJbYeahP0K/sWA4Czba58qXNJaZkMUlt5bW/IdC7f06H6FqOumW7RyD42d0zAvknDRK/Yg=,iv:yj60ylT1E16NIrRKp4WCTY3LXDL/KMX112Myr22Upik=,tag:JG7GKte7CbsQgqZgA5BPDw==,type:str]
  version: 3.13.3
