apiVersion: v1
kind: Secret
metadata:
  name: wow
  namespace: wow
stringData:
  # ENC[AES256_GCM,data:nwmuGW1gShvS+3/ZuTccRraPYywez072qNphPbBJ7Udr7Iy+L7PmWlqWaaooyiDLklRGPHKYtslXhhS2qECzkvmfIAueYfNCjUUjLR2m2C3NcPCi6fL2luX55PN7h16qWvfZs2Ezd8JsMd+6mbUDx9gNX8A6DKGQatvfmggaCkprQyWnow/vPCjj24pmLh9jErl6EAqNNsBkSb2FABNwjoHICYOyKIViKeb0JhAN7wmNLemb/DdGn53VBsWJz72lAXDURghieNWMCJMEa80u9yHzZR5q6qzYe+MQE7cmHxREzgstQ7UhbPKZ8f49NuRqZV7EpNSzT8mWUwvdL/HjwEVoKIPkPOTCvS8g9fA5B/3VdP4lBXKeBZp4ErGPhlANTCOvFWSVJEOUDRE3jbq3xsK2M5ujD1IWY65se9qOzcgLFBM7pWvGvzaW1KhX6UCbUhBhx1k/W4vx2mVLR5pDoanxsxxTrZIVltfwl7GooTVAlak0mv9Z5n+Xu/K4fKd8,iv:45tcIP8BmGLizXVeJ3CmfeRXhpSDhooKvFX7CizPJaY=,tag:hpPtkG/fQICflG5ou0Grxw==,type:comment]
  # ENC[AES256_GCM,data:OiiFRr0uGWflCCIbMbo/Juztvoo+4Oyt+VNfuCPD9fn+UMTxBluQzgfn3gFmhIXEcquBwfYuOYSE6qZqC63CydrULg+NbnxFGrDbNUq8a+8dP3jsGZsgIPOtLCeab92/+YE63JVpZHhXqRsoJZ3AzRIKtaPzhi1u4KQo1QYCYdU0lq1Bqk8BHY/nY+fExV9beW+8bkC54oA/iWgiHpsqFVHZpM+mXIl7vTmAvJQ7hz9qf3Xr/zI4a4v2gjUlO0iIGFgGm8WKmUZW5oTMN3zI7+2GTGt2D/iZm/yEsNcRSneFML1HEutnOqTTQb66lZ99cN+D2RoXteM+HbF+XQGPuPId379Ntnox+qATgUzcX0Y4MpjV/EAm0S8BOmqYNP2AKPRS4ocYCcAYkMvamL4tHP/Pl5+P9F5nb/8tHo/EzzrvITzEMgVGtTTuXEdk1KDtNEwpjrOPh/fkgCvP,iv:VJVrvuaHJ0sllYX1CrD3sSqj3Vx4a8Yw/I2o2HTTQv8=,tag:0mpl/gFXJE+skkzzQx+3Kw==,type:comment]
  MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:NgYag0UIDsdesCGS23a+aazfpnK7GPexyNsklkm6Jzs=,iv:odu2JZbxjOc1vx834IeCr1sgdVuIKuIV7X4jhCdmH4w=,tag:y0RiOclMlM5XfTJkB4uy6Q==,type:str]
  TOTP_MASTER_SECRET: ENC[AES256_GCM,data:QxRV3dXjvcMY6oEcEwEPo1+It7JJxyTayVRcABqHM/Q=,iv:cAXIiQ3gEX7qtwPtG8e7zqhsLV66kU7ilR8OmFFuz0k=,tag:9DNCIt4l8q+ITGd6RMQpsA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZUlyRW9iTjQvVGhKQ1JS
        cE1GV0lVSWcwVmtBYVBMaWNCYTZEVnlvSm5ZClpTVHcyNmZNR0xERW5HOGxhZlEz
        NUdGaGh1WmlISU8vQnN4ekJXeWV6L28KLS0tIFlOUklUUncrMjVNVFovV2lYT2Fi
        K3NCTENjK0xRZnVSWGJpcWc2ZitqaGsKmO+BAdoumYNL73aeqKQ2JXLoHLpz/S/D
        xou4CuaIg2raqCxOl3068L1K6LR+b4Si1fkcj8KxmT9d4yWSdipnzw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcmVOcWFJc0NPSytBSGEx
        cWppY1dvQnhVMUptMzdZN0JtNmlaZ0tsQm5FCnJmV2VLQWg5Ym5FMjhaelh0QXRE
        UXJ4TkRhRWN6bmc2ckZlNkpCM2ozbm8KLS0tICtxaUZabGtSejlRNndURTNjTFh1
        ZnRTTi9UUXE3Y0hkRWVhSEhhQXNaeWsKQHuPB/s4ZAopC7HH6AhH40GXTRSmM3hR
        BPR1IQHUijMzMOkSQWxeqwq66R9zyVXDkHVu2l39owDu5XVroK0LzA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-25T23:01:50Z"
  mac: ENC[AES256_GCM,data:Y8ARHCqmSLqQdXJM5Bgk/k7OPROOTlg6TA1ytd8EOuCA2KhugxoLTejUPpPo38YVdbVd3HNmMZS8BQGGeMrjRgCNK3NrtNcevL6I0bvuqu/vCDv6nGRd4YwL2cl4S6suiqO28+zh/k6miGnTu4MLuUH3xl76RBrTzkaTzNIuGCo=,iv:R6sNnnpBNMTTxeOrm5OP6t1P9sEfadKa9odRtTTGHFU=,tag:jYMj+ZhtXSf8LFYqWB/tbQ==,type:str]
  version: 3.13.3
