// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * The provider type for the helm package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'helm';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * The backend storage driver. Values are: configmap, secret, memory, sql
     */
    declare public readonly helmDriver: pulumi.Output<string | undefined>;
    /**
     * The path to the helm plugins directory
     */
    declare public readonly pluginsPath: pulumi.Output<string | undefined>;
    /**
     * The path to the registry config file
     */
    declare public readonly registryConfigPath: pulumi.Output<string | undefined>;
    /**
     * The path to the file containing cached repository indexes
     */
    declare public readonly repositoryCache: pulumi.Output<string | undefined>;
    /**
     * The path to the file containing repository names and URLs
     */
    declare public readonly repositoryConfigPath: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["burstLimit"] = pulumi.output(args?.burstLimit).apply(JSON.stringify);
            resourceInputs["debug"] = pulumi.output(args?.debug).apply(JSON.stringify);
            resourceInputs["experiments"] = pulumi.output(args?.experiments).apply(JSON.stringify);
            resourceInputs["helmDriver"] = args?.helmDriver;
            resourceInputs["kubernetes"] = pulumi.output(args?.kubernetes).apply(JSON.stringify);
            resourceInputs["pluginsPath"] = args?.pluginsPath;
            resourceInputs["qps"] = pulumi.output(args?.qps).apply(JSON.stringify);
            resourceInputs["registries"] = pulumi.output(args?.registries).apply(JSON.stringify);
            resourceInputs["registryConfigPath"] = args?.registryConfigPath;
            resourceInputs["repositoryCache"] = args?.repositoryCache;
            resourceInputs["repositoryConfigPath"] = args?.repositoryConfigPath;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Provider.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }

    /**
     * This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
     */
    terraformConfig(): pulumi.Output<{[key: string]: any}> {
        const result: pulumi.Output<Provider.TerraformConfigResult> = pulumi.runtime.call("pulumi:providers:helm/terraformConfig", {
            "__self__": this,
        }, this, utilities.getPackage());
        return result.result;
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * Helm burst limit. Increase this if you have a cluster with many CRDs
     */
    burstLimit?: pulumi.Input<number>;
    /**
     * Debug indicates whether or not Helm is running in Debug mode.
     */
    debug?: pulumi.Input<boolean>;
    /**
     * Enable and disable experimental features.
     */
    experiments?: pulumi.Input<inputs.ProviderExperiments>;
    /**
     * The backend storage driver. Values are: configmap, secret, memory, sql
     */
    helmDriver?: pulumi.Input<string>;
    /**
     * Kubernetes Configuration
     */
    kubernetes?: pulumi.Input<inputs.ProviderKubernetes>;
    /**
     * The path to the helm plugins directory
     */
    pluginsPath?: pulumi.Input<string>;
    /**
     * Queries per second used when communicating with the Kubernetes API. Can be used to avoid throttling.
     */
    qps?: pulumi.Input<number>;
    /**
     * RegistryClient configuration.
     */
    registries?: pulumi.Input<pulumi.Input<inputs.ProviderRegistry>[]>;
    /**
     * The path to the registry config file
     */
    registryConfigPath?: pulumi.Input<string>;
    /**
     * The path to the file containing cached repository indexes
     */
    repositoryCache?: pulumi.Input<string>;
    /**
     * The path to the file containing repository names and URLs
     */
    repositoryConfigPath?: pulumi.Input<string>;
}

export namespace Provider {
    /**
     * The results of the Provider.terraformConfig method.
     */
    export interface TerraformConfigResult {
        readonly result: {[key: string]: any};
    }

}
