// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Release extends pulumi.CustomResource {
    /**
     * Get an existing Release resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ReleaseState, opts?: pulumi.CustomResourceOptions): Release {
        return new Release(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'helm:index/release:Release';

    /**
     * Returns true if the given object is an instance of Release.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Release {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Release.__pulumiType;
    }

    /**
     * If set, installation process purges chart on fail. The wait flag will be set automatically if atomic is used
     */
    declare public readonly atomic: pulumi.Output<boolean>;
    /**
     * Chart name to be installed. A path may be used
     */
    declare public readonly chart: pulumi.Output<string>;
    /**
     * Allow deletion of new resources created in this upgrade when upgrade fails
     */
    declare public readonly cleanupOnFail: pulumi.Output<boolean>;
    /**
     * Create the namespace if it does not exist
     */
    declare public readonly createNamespace: pulumi.Output<boolean>;
    /**
     * Run helm dependency update before installing the chart
     */
    declare public readonly dependencyUpdate: pulumi.Output<boolean>;
    /**
     * Add a custom description
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Use chart development versions, too. Equivalent to version '>0.0.0-0'. If 'version' is set, this is ignored
     */
    declare public readonly devel: pulumi.Output<boolean | undefined>;
    /**
     * Prevent CRD hooks from running, but run other hooks. See helm install --no-crd-hook
     */
    declare public readonly disableCrdHooks: pulumi.Output<boolean>;
    /**
     * If set, the installation process will not validate rendered templates against the Kubernetes OpenAPI Schema
     */
    declare public readonly disableOpenapiValidation: pulumi.Output<boolean>;
    /**
     * Prevent hooks from running
     */
    declare public readonly disableWebhooks: pulumi.Output<boolean>;
    /**
     * Force resource update through delete/recreate if needed.
     */
    declare public readonly forceUpdate: pulumi.Output<boolean>;
    /**
     * Location of public keys used for verification, Used only if 'verify is true'
     */
    declare public readonly keyring: pulumi.Output<string | undefined>;
    /**
     * Run helm lint when planning
     */
    declare public readonly lint: pulumi.Output<boolean>;
    /**
     * The rendered manifest as JSON.
     */
    declare public /*out*/ readonly manifest: pulumi.Output<string>;
    /**
     * Limit the maximum number of revisions saved per release. Use 0 for no limit
     */
    declare public readonly maxHistory: pulumi.Output<number>;
    /**
     * Status of the deployed release.
     */
    declare public /*out*/ readonly metadata: pulumi.Output<outputs.ReleaseMetadata>;
    /**
     * Release name. The length must not be longer than 53 characters
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Namespace to install the release into
     */
    declare public readonly namespace: pulumi.Output<string>;
    /**
     * Pass credentials to all domains
     */
    declare public readonly passCredentials: pulumi.Output<boolean>;
    /**
     * Postrender command config
     */
    declare public readonly postrender: pulumi.Output<outputs.ReleasePostrender | undefined>;
    /**
     * Perform pods restart during upgrade/rollback
     */
    declare public readonly recreatePods: pulumi.Output<boolean>;
    /**
     * If set, render subchart notes along with the parent
     */
    declare public readonly renderSubchartNotes: pulumi.Output<boolean>;
    /**
     * Re-use the given name, even if that name is already used. This is unsafe in production
     */
    declare public readonly replace: pulumi.Output<boolean>;
    /**
     * Repository where to locate the requested chart. If it is a URL, the chart is installed without installing the repository
     */
    declare public readonly repository: pulumi.Output<string | undefined>;
    /**
     * The Repositories CA file
     */
    declare public readonly repositoryCaFile: pulumi.Output<string | undefined>;
    /**
     * The repositories cert file
     */
    declare public readonly repositoryCertFile: pulumi.Output<string | undefined>;
    /**
     * The repositories cert key file
     */
    declare public readonly repositoryKeyFile: pulumi.Output<string | undefined>;
    /**
     * Password for HTTP basic authentication
     */
    declare public readonly repositoryPassword: pulumi.Output<string | undefined>;
    /**
     * Username for HTTP basic authentication
     */
    declare public readonly repositoryUsername: pulumi.Output<string | undefined>;
    /**
     * When upgrading, reset the values to the ones built into the chart
     */
    declare public readonly resetValues: pulumi.Output<boolean>;
    /**
     * The kubernetes resources created by this release.
     */
    declare public /*out*/ readonly resources: pulumi.Output<{[key: string]: string}>;
    /**
     * When upgrading, reuse the last release's values and merge in any overrides. If 'reset_values' is specified, this is
     * ignored
     */
    declare public readonly reuseValues: pulumi.Output<boolean>;
    /**
     * Custom sensitive values to be merged with the values
     */
    declare public readonly setLists: pulumi.Output<outputs.ReleaseSetList[] | undefined>;
    /**
     * Custom sensitive values to be merged with the values
     */
    declare public readonly setSensitives: pulumi.Output<outputs.ReleaseSetSensitive[] | undefined>;
    declare public readonly setWoRevision: pulumi.Output<number | undefined>;
    /**
     * Custom values to be merged with the values
     */
    declare public readonly setWos: pulumi.Output<outputs.ReleaseSetWo[] | undefined>;
    /**
     * Custom values to be merged with the values
     */
    declare public readonly sets: pulumi.Output<outputs.ReleaseSet[] | undefined>;
    /**
     * If set, no CRDs will be installed. By default, CRDs are installed if not already present
     */
    declare public readonly skipCrds: pulumi.Output<boolean>;
    /**
     * Status of the release
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * If set, Helm will take ownership of resources not already annotated by this release. Useful for migrations or recovery.
     */
    declare public readonly takeOwnership: pulumi.Output<boolean>;
    /**
     * Time in seconds to wait for any individual kubernetes operation
     */
    declare public readonly timeout: pulumi.Output<number>;
    declare public readonly timeouts: pulumi.Output<outputs.ReleaseTimeouts | undefined>;
    /**
     * If true, the provider will install the release at the specified version even if a release not controlled by the provider
     * is present. This is equivalent to running 'helm upgrade --install'. WARNING: this may not be suitable for production use
     * -- see the 'Upgrade Mode' note in the provider documentation. Defaults to `false`.
     */
    declare public readonly upgradeInstall: pulumi.Output<boolean>;
    /**
     * List of values in raw YAML format to pass to helm
     */
    declare public readonly values: pulumi.Output<string[] | undefined>;
    /**
     * Verify the package before installing it.
     */
    declare public readonly verify: pulumi.Output<boolean>;
    /**
     * Specify the exact chart version to install. If this is not specified, the latest version is installed
     */
    declare public readonly version: pulumi.Output<string>;
    /**
     * Will wait until all resources are in a ready state before marking the release as successful.
     */
    declare public readonly wait: pulumi.Output<boolean>;
    /**
     * If wait is enabled, will wait until all Jobs have been completed before marking the release as successful.
     */
    declare public readonly waitForJobs: pulumi.Output<boolean>;

    /**
     * Create a Release resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ReleaseArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ReleaseArgs | ReleaseState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ReleaseState | undefined;
            resourceInputs["atomic"] = state?.atomic;
            resourceInputs["chart"] = state?.chart;
            resourceInputs["cleanupOnFail"] = state?.cleanupOnFail;
            resourceInputs["createNamespace"] = state?.createNamespace;
            resourceInputs["dependencyUpdate"] = state?.dependencyUpdate;
            resourceInputs["description"] = state?.description;
            resourceInputs["devel"] = state?.devel;
            resourceInputs["disableCrdHooks"] = state?.disableCrdHooks;
            resourceInputs["disableOpenapiValidation"] = state?.disableOpenapiValidation;
            resourceInputs["disableWebhooks"] = state?.disableWebhooks;
            resourceInputs["forceUpdate"] = state?.forceUpdate;
            resourceInputs["keyring"] = state?.keyring;
            resourceInputs["lint"] = state?.lint;
            resourceInputs["manifest"] = state?.manifest;
            resourceInputs["maxHistory"] = state?.maxHistory;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["name"] = state?.name;
            resourceInputs["namespace"] = state?.namespace;
            resourceInputs["passCredentials"] = state?.passCredentials;
            resourceInputs["postrender"] = state?.postrender;
            resourceInputs["recreatePods"] = state?.recreatePods;
            resourceInputs["renderSubchartNotes"] = state?.renderSubchartNotes;
            resourceInputs["replace"] = state?.replace;
            resourceInputs["repository"] = state?.repository;
            resourceInputs["repositoryCaFile"] = state?.repositoryCaFile;
            resourceInputs["repositoryCertFile"] = state?.repositoryCertFile;
            resourceInputs["repositoryKeyFile"] = state?.repositoryKeyFile;
            resourceInputs["repositoryPassword"] = state?.repositoryPassword;
            resourceInputs["repositoryUsername"] = state?.repositoryUsername;
            resourceInputs["resetValues"] = state?.resetValues;
            resourceInputs["resources"] = state?.resources;
            resourceInputs["reuseValues"] = state?.reuseValues;
            resourceInputs["setLists"] = state?.setLists;
            resourceInputs["setSensitives"] = state?.setSensitives;
            resourceInputs["setWoRevision"] = state?.setWoRevision;
            resourceInputs["setWos"] = state?.setWos;
            resourceInputs["sets"] = state?.sets;
            resourceInputs["skipCrds"] = state?.skipCrds;
            resourceInputs["status"] = state?.status;
            resourceInputs["takeOwnership"] = state?.takeOwnership;
            resourceInputs["timeout"] = state?.timeout;
            resourceInputs["timeouts"] = state?.timeouts;
            resourceInputs["upgradeInstall"] = state?.upgradeInstall;
            resourceInputs["values"] = state?.values;
            resourceInputs["verify"] = state?.verify;
            resourceInputs["version"] = state?.version;
            resourceInputs["wait"] = state?.wait;
            resourceInputs["waitForJobs"] = state?.waitForJobs;
        } else {
            const args = argsOrState as ReleaseArgs | undefined;
            if (args?.chart === undefined && !opts.urn) {
                throw new Error("Missing required property 'chart'");
            }
            resourceInputs["atomic"] = args?.atomic;
            resourceInputs["chart"] = args?.chart;
            resourceInputs["cleanupOnFail"] = args?.cleanupOnFail;
            resourceInputs["createNamespace"] = args?.createNamespace;
            resourceInputs["dependencyUpdate"] = args?.dependencyUpdate;
            resourceInputs["description"] = args?.description;
            resourceInputs["devel"] = args?.devel;
            resourceInputs["disableCrdHooks"] = args?.disableCrdHooks;
            resourceInputs["disableOpenapiValidation"] = args?.disableOpenapiValidation;
            resourceInputs["disableWebhooks"] = args?.disableWebhooks;
            resourceInputs["forceUpdate"] = args?.forceUpdate;
            resourceInputs["keyring"] = args?.keyring;
            resourceInputs["lint"] = args?.lint;
            resourceInputs["maxHistory"] = args?.maxHistory;
            resourceInputs["name"] = args?.name;
            resourceInputs["namespace"] = args?.namespace;
            resourceInputs["passCredentials"] = args?.passCredentials;
            resourceInputs["postrender"] = args?.postrender;
            resourceInputs["recreatePods"] = args?.recreatePods;
            resourceInputs["renderSubchartNotes"] = args?.renderSubchartNotes;
            resourceInputs["replace"] = args?.replace;
            resourceInputs["repository"] = args?.repository;
            resourceInputs["repositoryCaFile"] = args?.repositoryCaFile;
            resourceInputs["repositoryCertFile"] = args?.repositoryCertFile;
            resourceInputs["repositoryKeyFile"] = args?.repositoryKeyFile;
            resourceInputs["repositoryPassword"] = args?.repositoryPassword ? pulumi.secret(args.repositoryPassword) : undefined;
            resourceInputs["repositoryUsername"] = args?.repositoryUsername;
            resourceInputs["resetValues"] = args?.resetValues;
            resourceInputs["reuseValues"] = args?.reuseValues;
            resourceInputs["setLists"] = args?.setLists;
            resourceInputs["setSensitives"] = args?.setSensitives;
            resourceInputs["setWoRevision"] = args?.setWoRevision;
            resourceInputs["setWos"] = args?.setWos;
            resourceInputs["sets"] = args?.sets;
            resourceInputs["skipCrds"] = args?.skipCrds;
            resourceInputs["takeOwnership"] = args?.takeOwnership;
            resourceInputs["timeout"] = args?.timeout;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["upgradeInstall"] = args?.upgradeInstall;
            resourceInputs["values"] = args?.values;
            resourceInputs["verify"] = args?.verify;
            resourceInputs["version"] = args?.version;
            resourceInputs["wait"] = args?.wait;
            resourceInputs["waitForJobs"] = args?.waitForJobs;
            resourceInputs["manifest"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["resources"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["repositoryPassword"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Release.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Release resources.
 */
export interface ReleaseState {
    /**
     * If set, installation process purges chart on fail. The wait flag will be set automatically if atomic is used
     */
    atomic?: pulumi.Input<boolean>;
    /**
     * Chart name to be installed. A path may be used
     */
    chart?: pulumi.Input<string>;
    /**
     * Allow deletion of new resources created in this upgrade when upgrade fails
     */
    cleanupOnFail?: pulumi.Input<boolean>;
    /**
     * Create the namespace if it does not exist
     */
    createNamespace?: pulumi.Input<boolean>;
    /**
     * Run helm dependency update before installing the chart
     */
    dependencyUpdate?: pulumi.Input<boolean>;
    /**
     * Add a custom description
     */
    description?: pulumi.Input<string>;
    /**
     * Use chart development versions, too. Equivalent to version '>0.0.0-0'. If 'version' is set, this is ignored
     */
    devel?: pulumi.Input<boolean>;
    /**
     * Prevent CRD hooks from running, but run other hooks. See helm install --no-crd-hook
     */
    disableCrdHooks?: pulumi.Input<boolean>;
    /**
     * If set, the installation process will not validate rendered templates against the Kubernetes OpenAPI Schema
     */
    disableOpenapiValidation?: pulumi.Input<boolean>;
    /**
     * Prevent hooks from running
     */
    disableWebhooks?: pulumi.Input<boolean>;
    /**
     * Force resource update through delete/recreate if needed.
     */
    forceUpdate?: pulumi.Input<boolean>;
    /**
     * Location of public keys used for verification, Used only if 'verify is true'
     */
    keyring?: pulumi.Input<string>;
    /**
     * Run helm lint when planning
     */
    lint?: pulumi.Input<boolean>;
    /**
     * The rendered manifest as JSON.
     */
    manifest?: pulumi.Input<string>;
    /**
     * Limit the maximum number of revisions saved per release. Use 0 for no limit
     */
    maxHistory?: pulumi.Input<number>;
    /**
     * Status of the deployed release.
     */
    metadata?: pulumi.Input<inputs.ReleaseMetadata>;
    /**
     * Release name. The length must not be longer than 53 characters
     */
    name?: pulumi.Input<string>;
    /**
     * Namespace to install the release into
     */
    namespace?: pulumi.Input<string>;
    /**
     * Pass credentials to all domains
     */
    passCredentials?: pulumi.Input<boolean>;
    /**
     * Postrender command config
     */
    postrender?: pulumi.Input<inputs.ReleasePostrender>;
    /**
     * Perform pods restart during upgrade/rollback
     */
    recreatePods?: pulumi.Input<boolean>;
    /**
     * If set, render subchart notes along with the parent
     */
    renderSubchartNotes?: pulumi.Input<boolean>;
    /**
     * Re-use the given name, even if that name is already used. This is unsafe in production
     */
    replace?: pulumi.Input<boolean>;
    /**
     * Repository where to locate the requested chart. If it is a URL, the chart is installed without installing the repository
     */
    repository?: pulumi.Input<string>;
    /**
     * The Repositories CA file
     */
    repositoryCaFile?: pulumi.Input<string>;
    /**
     * The repositories cert file
     */
    repositoryCertFile?: pulumi.Input<string>;
    /**
     * The repositories cert key file
     */
    repositoryKeyFile?: pulumi.Input<string>;
    /**
     * Password for HTTP basic authentication
     */
    repositoryPassword?: pulumi.Input<string>;
    /**
     * Username for HTTP basic authentication
     */
    repositoryUsername?: pulumi.Input<string>;
    /**
     * When upgrading, reset the values to the ones built into the chart
     */
    resetValues?: pulumi.Input<boolean>;
    /**
     * The kubernetes resources created by this release.
     */
    resources?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * When upgrading, reuse the last release's values and merge in any overrides. If 'reset_values' is specified, this is
     * ignored
     */
    reuseValues?: pulumi.Input<boolean>;
    /**
     * Custom sensitive values to be merged with the values
     */
    setLists?: pulumi.Input<pulumi.Input<inputs.ReleaseSetList>[]>;
    /**
     * Custom sensitive values to be merged with the values
     */
    setSensitives?: pulumi.Input<pulumi.Input<inputs.ReleaseSetSensitive>[]>;
    setWoRevision?: pulumi.Input<number>;
    /**
     * Custom values to be merged with the values
     */
    setWos?: pulumi.Input<pulumi.Input<inputs.ReleaseSetWo>[]>;
    /**
     * Custom values to be merged with the values
     */
    sets?: pulumi.Input<pulumi.Input<inputs.ReleaseSet>[]>;
    /**
     * If set, no CRDs will be installed. By default, CRDs are installed if not already present
     */
    skipCrds?: pulumi.Input<boolean>;
    /**
     * Status of the release
     */
    status?: pulumi.Input<string>;
    /**
     * If set, Helm will take ownership of resources not already annotated by this release. Useful for migrations or recovery.
     */
    takeOwnership?: pulumi.Input<boolean>;
    /**
     * Time in seconds to wait for any individual kubernetes operation
     */
    timeout?: pulumi.Input<number>;
    timeouts?: pulumi.Input<inputs.ReleaseTimeouts>;
    /**
     * If true, the provider will install the release at the specified version even if a release not controlled by the provider
     * is present. This is equivalent to running 'helm upgrade --install'. WARNING: this may not be suitable for production use
     * -- see the 'Upgrade Mode' note in the provider documentation. Defaults to `false`.
     */
    upgradeInstall?: pulumi.Input<boolean>;
    /**
     * List of values in raw YAML format to pass to helm
     */
    values?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Verify the package before installing it.
     */
    verify?: pulumi.Input<boolean>;
    /**
     * Specify the exact chart version to install. If this is not specified, the latest version is installed
     */
    version?: pulumi.Input<string>;
    /**
     * Will wait until all resources are in a ready state before marking the release as successful.
     */
    wait?: pulumi.Input<boolean>;
    /**
     * If wait is enabled, will wait until all Jobs have been completed before marking the release as successful.
     */
    waitForJobs?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a Release resource.
 */
export interface ReleaseArgs {
    /**
     * If set, installation process purges chart on fail. The wait flag will be set automatically if atomic is used
     */
    atomic?: pulumi.Input<boolean>;
    /**
     * Chart name to be installed. A path may be used
     */
    chart: pulumi.Input<string>;
    /**
     * Allow deletion of new resources created in this upgrade when upgrade fails
     */
    cleanupOnFail?: pulumi.Input<boolean>;
    /**
     * Create the namespace if it does not exist
     */
    createNamespace?: pulumi.Input<boolean>;
    /**
     * Run helm dependency update before installing the chart
     */
    dependencyUpdate?: pulumi.Input<boolean>;
    /**
     * Add a custom description
     */
    description?: pulumi.Input<string>;
    /**
     * Use chart development versions, too. Equivalent to version '>0.0.0-0'. If 'version' is set, this is ignored
     */
    devel?: pulumi.Input<boolean>;
    /**
     * Prevent CRD hooks from running, but run other hooks. See helm install --no-crd-hook
     */
    disableCrdHooks?: pulumi.Input<boolean>;
    /**
     * If set, the installation process will not validate rendered templates against the Kubernetes OpenAPI Schema
     */
    disableOpenapiValidation?: pulumi.Input<boolean>;
    /**
     * Prevent hooks from running
     */
    disableWebhooks?: pulumi.Input<boolean>;
    /**
     * Force resource update through delete/recreate if needed.
     */
    forceUpdate?: pulumi.Input<boolean>;
    /**
     * Location of public keys used for verification, Used only if 'verify is true'
     */
    keyring?: pulumi.Input<string>;
    /**
     * Run helm lint when planning
     */
    lint?: pulumi.Input<boolean>;
    /**
     * Limit the maximum number of revisions saved per release. Use 0 for no limit
     */
    maxHistory?: pulumi.Input<number>;
    /**
     * Release name. The length must not be longer than 53 characters
     */
    name?: pulumi.Input<string>;
    /**
     * Namespace to install the release into
     */
    namespace?: pulumi.Input<string>;
    /**
     * Pass credentials to all domains
     */
    passCredentials?: pulumi.Input<boolean>;
    /**
     * Postrender command config
     */
    postrender?: pulumi.Input<inputs.ReleasePostrender>;
    /**
     * Perform pods restart during upgrade/rollback
     */
    recreatePods?: pulumi.Input<boolean>;
    /**
     * If set, render subchart notes along with the parent
     */
    renderSubchartNotes?: pulumi.Input<boolean>;
    /**
     * Re-use the given name, even if that name is already used. This is unsafe in production
     */
    replace?: pulumi.Input<boolean>;
    /**
     * Repository where to locate the requested chart. If it is a URL, the chart is installed without installing the repository
     */
    repository?: pulumi.Input<string>;
    /**
     * The Repositories CA file
     */
    repositoryCaFile?: pulumi.Input<string>;
    /**
     * The repositories cert file
     */
    repositoryCertFile?: pulumi.Input<string>;
    /**
     * The repositories cert key file
     */
    repositoryKeyFile?: pulumi.Input<string>;
    /**
     * Password for HTTP basic authentication
     */
    repositoryPassword?: pulumi.Input<string>;
    /**
     * Username for HTTP basic authentication
     */
    repositoryUsername?: pulumi.Input<string>;
    /**
     * When upgrading, reset the values to the ones built into the chart
     */
    resetValues?: pulumi.Input<boolean>;
    /**
     * When upgrading, reuse the last release's values and merge in any overrides. If 'reset_values' is specified, this is
     * ignored
     */
    reuseValues?: pulumi.Input<boolean>;
    /**
     * Custom sensitive values to be merged with the values
     */
    setLists?: pulumi.Input<pulumi.Input<inputs.ReleaseSetList>[]>;
    /**
     * Custom sensitive values to be merged with the values
     */
    setSensitives?: pulumi.Input<pulumi.Input<inputs.ReleaseSetSensitive>[]>;
    setWoRevision?: pulumi.Input<number>;
    /**
     * Custom values to be merged with the values
     */
    setWos?: pulumi.Input<pulumi.Input<inputs.ReleaseSetWo>[]>;
    /**
     * Custom values to be merged with the values
     */
    sets?: pulumi.Input<pulumi.Input<inputs.ReleaseSet>[]>;
    /**
     * If set, no CRDs will be installed. By default, CRDs are installed if not already present
     */
    skipCrds?: pulumi.Input<boolean>;
    /**
     * If set, Helm will take ownership of resources not already annotated by this release. Useful for migrations or recovery.
     */
    takeOwnership?: pulumi.Input<boolean>;
    /**
     * Time in seconds to wait for any individual kubernetes operation
     */
    timeout?: pulumi.Input<number>;
    timeouts?: pulumi.Input<inputs.ReleaseTimeouts>;
    /**
     * If true, the provider will install the release at the specified version even if a release not controlled by the provider
     * is present. This is equivalent to running 'helm upgrade --install'. WARNING: this may not be suitable for production use
     * -- see the 'Upgrade Mode' note in the provider documentation. Defaults to `false`.
     */
    upgradeInstall?: pulumi.Input<boolean>;
    /**
     * List of values in raw YAML format to pass to helm
     */
    values?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Verify the package before installing it.
     */
    verify?: pulumi.Input<boolean>;
    /**
     * Specify the exact chart version to install. If this is not specified, the latest version is installed
     */
    version?: pulumi.Input<string>;
    /**
     * Will wait until all resources are in a ready state before marking the release as successful.
     */
    wait?: pulumi.Input<boolean>;
    /**
     * If wait is enabled, will wait until all Jobs have been completed before marking the release as successful.
     */
    waitForJobs?: pulumi.Input<boolean>;
}
