apiVersion: v1
data:
    FORGEJO__database__PASSWD: ENC[AES256_GCM,data:dzXpXcXrKeqz64ggeny/CoWoJQI6nE8m3VaCAQTyy0nXCIdQmr/BURGTET4=,iv:gVy1/ZZLi9ZQP9vhY7J2pLtpyUkaarjpit5ei3EUHYw=,tag:yAlD8x+51lG3Oqb7VCdj2w==,type:str]
    FORGEJO__oauth2__JWT_SECRET: ENC[AES256_GCM,data:aWd1wBl9m7bnNOYk0P8L/xdxfmpQl8tN78PD+vsyLksQ+ZA8SQ1FXjGVGb6VcwGkSFp0Evdiu2yeBuZF,iv:mmKFizK0AsPMZAnmBX7S/IUbnoGqqaA1J8QGP0YB1JM=,tag:o0qK0i/S+yDtmZkk4bz4mQ==,type:str]
    FORGEJO__security__INTERNAL_TOKEN: ENC[AES256_GCM,data:DE4enD6Qkzr7LrLZ/DQtlQb/8zPxc9XgZMPGKnsD3ErEIu8SOS3PRdDFr/kbyUVr+KSM+axGXOXm4xyAP4p0IfhhJr2vdvKRq3HL2EjDJkc5VxlTA0XKWcXGVeqlmSQT/a2nbxP3bJnk94Q5RhdjMlBB5+MoJBCfjj7blbycdiRRpUHoIqgcoE4UzLI=,iv:R0jLuDUfCHyPMHH9IXvnUN5meZYx73bVI09ywiYrIKE=,tag:I0uOZtU5hMbfLq+oatE9uA==,type:str]
    FORGEJO__security__SECRET_KEY: ENC[AES256_GCM,data:ypTu0QjmFXStV+WuntfuxZZ1/boTHFCpBW5kE4T3hrK1KnLyB26KigvP0rAj5WcvyqokhaPi4OXHCVtupniZRtFXePpi55nheU9MZA8p684gVG8UJMUb4w==,iv:R6A3qrKeJT4fTgeeR4QTYrWsbf/BfFAG1C3+BcJB97c=,tag:6oRoeRTvGGv52BTyZjf7KQ==,type:str]
    FORGEJO__server__LFS_JWT_SECRET: ENC[AES256_GCM,data:eFln6nGt+KuNYT9j6zVQ8MzJhxmRCtIapxWbylMkAK9ebRPyGSAQ2R5Z7FG1jOVvGfNiMrnEByCvQiMU,iv:+pWp7lj6zXG+WhDsSeh7sKDjiGUcfG5B4v8on0lp5TE=,tag:d++ZsTYo2CuLZQaAQqVnkQ==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Z8wZb0Aoo5my6SxR17DY37NoUKDvdOWnxwFFrI4PUnNGbEddwc7h4QDwHH8jImaELl95+CSfjpIwcP+w,iv:+kU+W/25W5QFcwmA+Ok6K0iHwbiRHQ+Bq5liJ5Bg770=,tag:bdl9VOVJO2+vkx/135Ipfw==,type:str]
kind: Secret
metadata:
    name: forgejo
    namespace: forgejo
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRnFjSmZ2T2pPUFExTmJu
            Z0Jva0RLR044K2wvelRxVGZ5N0NoRVlCSEVvCmQvaFBoWGpjYmxtRWUrMVJxQ05p
            am00enlOMlEyQ2RwY042dlBXRzJYRUkKLS0tIDhaazIxd1F6NjRNMEY3bDlLcmNG
            ZUF0amx3MCtNZ01KU3VGTWpodVVSK1UKsyyqe2PmXYb/M8mNNPkySWMdv8k12mIr
            FHCMYCTeNPZNwVhiIm2xAZaGWqXQoNcO1pEYuMwvNZOqzgASa6+2ew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:cYzilbDlgZFgzFbrWOfjRHen6RyCG0YwUdP2IbpyXI+6cdJTEHB23CvHJcWOGCR/AJ39Fvzzk7+/3YP3CHJ+aNAO09e6C7g7pA5lQFtt/fjWiDyTXLESY9ZXORU7dAFpbG3sFxkKbfbnVPr7cBZTesuMQKLELDatyVi8el0pXgQ=,iv:eBRd7M+aGCH9YaptYqbqTQial3CgpKTEbHKolR3J64k=,tag:pwSa/etQLT8ipCYixSiAUw==,type:str]
    version: 3.13.1
