apiVersion: v1
kind: Secret
metadata:
    name: forgejo
    namespace: forgejo
type: Opaque
stringData:
    FORGEJO__database__PASSWD: ENC[AES256_GCM,data:pbQ2PHjXtNjo7fexDhQarBrRlojuFdsc8OLAJUf7eeE=,iv:yjBTmqCK3XTHFuU94SVmciFqWb6G0iilTghbfdUivAE=,tag:2jnFm/d31Kd0YcxILVUsiQ==,type:str]
    FORGEJO__oauth2__JWT_SECRET: ENC[AES256_GCM,data:+XtE8V9vObZS7Bev1LVUckWt4uHm4PGNttfkhM+27dJIWeMVYZWVFfPw4w==,iv:sAvR4nV/x0dP2k0VyBV4V9v3GEc01LtLMjNe/ZK+MvA=,tag:B+CFCqPmBjaHFtuBu50i7A==,type:str]
    FORGEJO__security__INTERNAL_TOKEN: ENC[AES256_GCM,data:c4p5SJsDj+2iNYtegHwI1JN3LJA2mxnMx+hEIpK4glqISG9/UyqIKcmyRYwr1OqWB6M7ePNOPCcxrfuvPZAZScUUvyaHfVjtGdbaxI4wLSt4RTdH4+AwaJqMrJ2usOyF6JH+o8OBDwRQ,iv:l1O/H8DgmSiYuZcdDWjJfnXHKCtkGZ0/n7Aoif/0XxI=,tag:HLS7bisQLQ0Qe+anbxqEJQ==,type:str]
    FORGEJO__security__SECRET_KEY: ENC[AES256_GCM,data:wtazrt7UCWg9LY/F06WCSEEVXY976YIXxPnr/mOkzQTAuMRUu682Yc4628fF4qYTyoxsep5BAjdwSt9GVwXC6A==,iv:GdZAHG1bysAPNJJebOtS145O5X5Htzis+3hTHMuV1o4=,tag:oJQhzQFpMasUQF4WW34N5A==,type:str]
    FORGEJO__server__LFS_JWT_SECRET: ENC[AES256_GCM,data:tDeQAMJ6U5IklL2YjQeg2Ikk0lBHV5zcQrTxvyFr4m1c4EZXzDOAL8bCXQ==,iv:RXBFSWruSVfxfu8QbefOlzpOn5wy13Bnooe43jt+Amg=,tag:/0GW/H8AiA0Tem7F4Aow1A==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:3wNcOS3Qr6awYoUDkUfTaSLxSS0hqLM5PW/OO6uIDvFCBMht+YRKNI9igRE=,iv:OFpEnP63T3+axxLyN/riVr+9rKIOgQg1TFlRA9tjK4Y=,tag:DlqwUyPHR2i63ENHFnlGWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeTdLbFRwYlJUYWhVTk85
            ZDBOMC9zd1M3RkdVMTJMOHRWdjBQcEtUV1Q0Cmo1dGQ1djZMTUpaN2dyRUxvRnQw
            cG1udDFwWVJxNHJGazBMK3ROSmlJaWcKLS0tIE1oNkZHUVE1clVlRjRJTXJiWXFs
            eGd5bHhvanZ5ZW8wbnp4Ynl2WjNrR2cKlXhPu7s45a3UJJyIb041we/eiLC0ywWP
            +HCZDW8Yirn/fyaD3eeExxY9aMngE5glV1cWE0IbwFFCyYtfbPKycg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T16:56:38Z"
    mac: ENC[AES256_GCM,data:NOBfecR+NX/oZj3/1EfNu2BQ8TxQZv7xsxs505XyYs0nYAQx4NXPq6wiPfAC0+IFlZqAEcPYr2I/5T7xrwykq2p3v/COIV+fqb5TUYbDKYxx4YYlUVwlNByg8u4Wf1xnhYNc/KsLfl1jnKWeU5n6W6DbdQnyU3lGcIALXoR8GTA=,iv:i1ji98zVYH1U+QiVcAF5KPLJrtQAdyzMt+IP/Y7RFb4=,tag:VcRp+fXvnlOItXd2zQ9ERg==,type:str]
    version: 3.13.1
