apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apprise
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  dependsOn:
    - name: apprise-vars
    - name: cert-manager
    - name: authentik-config
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: k8s/apps/apprise
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: apprise-vars
