---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apprise-config
  namespace: notification
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apprise
  namespace: notification
  labels:
    app.kubernetes.io/name: apprise
  annotations:
    configmap.reloader.stakater.com/reload: apprise-config
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: apprise
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apprise
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 100000
      containers:
        - name: apprise
          image: caronc/apprise:v1.5.1@sha256:1871ed736799f6320d5061b72a60507f62c8747026e830175dc4b9f8adbf78dd
          env:
            - name: APPRISE_WORKER_COUNT
              value: "1"
            - name: APPRISE_STATEFUL_MODE
              value: simple
            - name: APPRISE_DEFAULT_THEME
              value: dark
            - name: APPRISE_DEFAULT_CONFIG_ID
              value: flux
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: config
              mountPath: /config
            - name: apprise-config
              mountPath: /config/flux.yml
              subPath: flux.yml
            - name: attach
              mountPath: /attach
            - name: plugin
              mountPath: /plugin
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: apprise-config
        - name: apprise-config
          configMap:
            name: apprise-config
        - name: attach
          emptyDir: {}
        - name: plugin
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: apprise
  namespace: notification
  annotations:
    gatus.home-operations.com/enabled: "false"
spec:
  selector:
    app.kubernetes.io/name: apprise
  ports:
    - port: 8000
      targetPort: 8000
      name: http
