apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TZ1NQ5btHuwPXvqVWnbHg1T8Ae9HzzHiAQ==,iv:dHJhTe4X74oZJHfK5Ouo7+5W77ym19Q3sQo9pOS3oqY=,tag:V5+V800kM/9K+K34Ud4zcg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:n3pus9ZrUT3YuZ3thtuiKODEIDNxfqV0E1IWRMKJlQ==,iv:Z576+GAprk2mt/3J1SKsYJ1UMC1BMmzesK0vFD64lGY=,tag:HqaWa0KL2f5FGhdsL1vlxA==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:YgMOkP/ADz2zNDrKp+IzunVEAB4vioxnkbB2eU5NNJUt8JYew6M=,iv:GgSwPgZif1+cgOWJxEfea+/2MiVy7yRBnwGOHyuogqI=,tag:cmMVTW7pUPCYgCiEMr8amg==,type:str]
  VIRTUAL_HOSTED_STYLE: ENC[AES256_GCM,data:4Eo7lA==,iv:tAqRvlAcPQgKFuXSDwhG0QsRPUzskH5u98kWWLr4rnk=,tag:uxzDoRPTmG0ss3bfsPvYEw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbzljYW4vejMxMnZSZjNn
        cnUxRFdqZTM5TmloZE9KQjZYcnhlT1hhSlY4CjRvNG1FdXVCOEJuQmlXTlhDSjhH
        WlFVN1hCaUNUbzBSZzJtRnp1enN5NTAKLS0tIGhZb0pYU0lyaitIcjdqSFlhQXNi
        Q1FXUTBiTFUvN2o5MFAwMUQ2TlEwS3cKslhlkJfluejE/EfNHoHiWOGPsgX6VyPh
        bn2cSujxXAwZSVnCvONzsmoYg0yJg3ztsxJB1Zj184xiM7gU5uDQUg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T22:30:38Z"
  mac: ENC[AES256_GCM,data:Qtwr43V0UcavUF456Si5Vwo6RgVIheAI/DS0I63H0ux1lXq0nxewgyUoF494/1mKtCv9CSFnADBINoOozm/TjowdbC9HLqKHpQbqs3bxReghSSQhMHh4cOuuz0HkT+Qwrr7h1i/74ioaO29AaVTyE6ldeXtFn7FLBMUXqPb8JqY=,iv:77m3CydS6y6dXKX/Q/K7QVp9DdhSsvYWwpw7fF6wrTo=,tag:tqSGC+g8q2x7W8yqqq64cQ==,type:str]
  version: 3.13.1
