apiVersion: v1
data:
    token: ENC[AES256_GCM,data:p3N9v02rfRmhX+Aeb45JCWos5K7mJUOW+/bQjzo+GGV6mar1Sgf7zw==,iv:lTWsBNMi+bCGRabHVLC1FcBPL9WV3ZQieh+V+zYK44M=,tag:B26uqP+FXl3FA6Sri1WR8g==,type:str]
    userKey: ENC[AES256_GCM,data:yTn1uFsunnbZzjGSmm6h20uMDLROrc7r0bQXWjsng07a7f7lK5lBtw==,iv:HbMHEyqHfFxSRXelzNugyrPYtb8G8C5TOroq55qSLv8=,tag:ERdLdNkpF+ghuBPRRgZSsA==,type:str]
kind: Secret
metadata:
    name: alertmanager-pushover-credentials
    namespace: monitoring
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSkVvVmpvLzI4bE9keVd6
            ays4UDVwSVFsZnNQZzRWL3A1ajdOaWxSakdBCkhTVlFWZTY5cWJ4Um41SkF5eWVD
            NjQ4dWZVemJ1b0QweTVMNW1BMFo3U0EKLS0tIHBkeEpMT05xRmJWY0RLWXpvWHh4
            SnVWZjBLZ0Y5My9BTVJYN3J3cHRsZkkKRLG2HBv4FP+5bTBWGEqJA6IvxzhsYVtI
            eQURcnLSoIJ89uNWJqsOu7EUfOKZP4XOXPKA1PXaZu1UHVEZEYvpiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:gutTlbvOnPYqKkEUat5pSfVuSZnLC0Ujwo5cl0g24AAq/sCuRtI2zQygS7MhQIaWMjkSYDC1gz0GA3djNPYxkBQTRWWQvuoTgCtSx89bn1HBwKgH/SjBiEULyhoPbFmFK8nf/wD5V0yAM8rqlV3lELUeVzF7X4wSVpMyjzySF+o=,iv:jalTAjnDFnENfP6AfEhV543nCs6qxdAuvWSOh42aTT4=,tag:pJFRSFJ6dUkqS0/I6X18Dg==,type:str]
    version: 3.13.1
