---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-pushover-credentials
  namespace: monitoring
spec:
  encryptedData:
    token: AgBXjDAE5v4lK63gIJToXSNOcK5C84qgQtOBrXPsa5mhPsfT726otOpgZFEoUylhLdlUVFbMofzHesQ2ZhiTMS76TLcKhSDfwLWTrtqce0vPVHjO9ZAaUgTSsXIHALG5+bU38UPGCA+yZsFBuM9PvqLhmqCfrzlC3GqmxE2xY+sET2db5KfVGekq0aHWGRL1SmcMrnVSw+ZSJYGNKIoF2g/Yl+J8HPWDDypJl+bDbDd3WQZD9pRqMKaSxAEetD793Qpnvnz0oA6mawPGjxQIiesFR4dRHNjI4YOKglE/ScomjjxrnuCDVCfjvfQt4B3f29zQSd1I9OubZRc9u9b+psk9hAWiP4LLRxynhJQCugzFoUZNeTiNALE58x+nQ9SGz50wknbnKy7r1YPZhYyfAcZHPgWJM0iCFjPBM9Y9JAV02DhaNN8VuNlXsIjHvrQtfGtMfSUdtMZtlz9YL5IgKViQhpkWePwGRbofiIcHtQf+fBl8t6imiRFm1xDqxS/pl8D3+4zwWY+w4rda36M67OafCT3P2nlzvJ0isk0Cu760tC20fQIS/ScknSClREN9uLofr8gP45/uAnP1TU0e8mIrGkGd+cumyrZt6Mr0lYKWVcEQBLoxDB3DgHnRDY5Govd7tP4NuvplRyF/mDEKnEwgEcVY/O930oSP9ksbAy3KLXiaoPmGjrpFL0urh+Ftnrpk6Dz9/rg6j0gqPqFXsUaxqXOOwo4YpBQUSu8US+E=
    userKey: AgAZMEfLhdt54I1I/xSB7nE72jElkEIs3TbTb1ZxfLThMBkg6jlAqrcPLf1l3xr2V5m9287v07F3AqplVZt+MUh75nF00IWiOdI4XzvBJAqWcHd9HWqkcVuJOZ67EicD3CCGb3TV5KQ5p3MxsJCSZUneOON4fr+x9rUY9Gtc+JqHB7htFcAD6GH0nU74AkWfig6dpmuKKgh8x8Y4tdHK8i3I/SFJpMsscTiXJSZGTgjn/7KU40lhCaRC06gGjlKoW+IqYZx/tSHBR42cJhhHdfstyXVrku8+HoU8bdg+cu8cfFojJLzCyOEIq8ZnhoiqVNQvWN9X8SQb1kRbdcMPjDAKDYmNZci9DWdBG1h+gg3cfJ/gx5Nrge4XF91IkC04DxGwz29x3O2VsX6J2arLV/gaffKJfMHvneS8VApBQYccs1K7Wnjq88mneeSfSDotdH4QSF4cDocaJHcb4s0YqRLdIZTmfaLz4mH7ea9cLh2qW2ViqGebSTnaIlpAUBoXM/i6/QC6xmAKn0oxT91eQoMfOyedMBHLNXongPSPrwh0jEAjnctkSXzPEv/QX9FS4s0hGmr/a/5EO8qHIAIU3jCwwn7L2GUm9wnAumA7ZqWzrMgSEtk69y7qN5vnclTyVOhqS7qzfkX5LPyx23iMeApmFOVjGqehrE6ITfWFeHqSFsZjaS4xLdnDwg8efXSIWTeHszO+Oj04EBMyVs8Fzqlik9ZIBUe9JExezVsqlLk=
  template:
    metadata:
      name: alertmanager-pushover-credentials
      namespace: monitoring
    type: Opaque
# apiVersion: v1
# kind: Secret
# metadata:
#   name: alertmanager-pushover-credentials
#   namespace: monitoring
# type: Opaque
# stringData:
#   token: fixme
#   userKey: fixme
