apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-pushover-credentials
  namespace: monitoring
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:bPNrBhY/jXtaSZZp15yLg4Bc9dF0e5fHuCQvV6M2,iv:UiDiLR0aK/xXSag6D8PwBnC0xX/rMFvGvHL5V1Ww9Ac=,tag:IoNga+AJ63KRNc4Svqv0lg==,type:str]
  userKey: ENC[AES256_GCM,data:CTaKIjYoGe71NJUs3PWOg282XNV0mMHd5aQHwNPd,iv:HjC/y0sDkiZjcgFDQiTaib/rPeWBOrHhJkler/cfW90=,tag:qGql/0R1xMoH7fI4IynvLw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZFhhWXBseXJXNy9ZZmVM
        eDBqWFJacU85Ly9CaUJOd3ZCY1c2SEpXVjBFCmtPTjNpV2lvc05ueEY5Y1J2L012
        STJyZzd4dVdScmRqdWZYM3g1Z2ttK2MKLS0tIEZCSWdzbTNjLytHVmFrV1F1TXhz
        QmNQb1BlekcyTmpkd1FTSWR5VkZVWlEK/kxH6EZJdD/2md+fr5D9Q36HRAlAeYbM
        YdFsyKn//7kopo1ZsvivULfytp5JoLTbEhiH6Cvp/j9QIdu5lSBniA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RzNocGJndDJVNkNvakxy
        bzVKZHB0Z0FXT2IrSDNPWjNrbEcrSXZmYlZRCkZRRHVZdHFCbzE3K2pQbUZpUjQr
        K1NCU3JnMnJ4Nkk2VXpKVnhXMEMwY2sKLS0tIHlkZUdPS1lycTRia0tYRHBiRis2
        OEptVGhwQ3B1SUxTTzJTZGNGNklnWG8KmF/Hc7OjT08lRdZooJr0qJaxgPVCayfl
        x81VyfEfc7itjWqCKBFNhMGUW4CnYWW9ETg+noVYCqi2LlXtn/qgGg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T16:56:38Z"
  mac: ENC[AES256_GCM,data:LlXoK80PxZyg8G/cqdQKV7J+KC1eAR/7n1xfHGjrh5Ld9TDMhvZdgfJ1yV76a8h6NGtLtWZri1n9UDFf7HxnzAux8sh2N1Z7ziKqaDXon3+p70uSn0Yzijdn6u/5W7ANAsQQ0xbRia7ucXGcuMmsQdaTm4Ou8JS54dF0Wo6YG+I=,iv:k0gLz3MvULsJyiwummvu+fn4j1Ivf1F+Tk+fCqHjNLE=,tag:2Zj85E8PBFcYgx0osgFP5Q==,type:str]
  version: 3.13.1
