apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-pushover-credentials
  namespace: monitoring
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:bPNrBhY/jXtaSZZp15yLg4Bc9dF0e5fHuCQvV6M2,iv:UiDiLR0aK/xXSag6D8PwBnC0xX/rMFvGvHL5V1Ww9Ac=,tag:IoNga+AJ63KRNc4Svqv0lg==,type:str]
  userKey: ENC[AES256_GCM,data:CTaKIjYoGe71NJUs3PWOg282XNV0mMHd5aQHwNPd,iv:HjC/y0sDkiZjcgFDQiTaib/rPeWBOrHhJkler/cfW90=,tag:qGql/0R1xMoH7fI4IynvLw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVHhTYnBKS1RLVkJEQ09C
        cHVNUk5RaElPeW5xeVBiZERzSEZYWUxKR1JnClZEdFdXeXF6UlpzY2RaWHlTb2sv
        Zkh1KzRjeHp2NzdTWWRUUmZEcCtvcEEKLS0tIDBoOFNZWDJWRk9iM05wbm5YMTZt
        eGt4S2kwTDJ0Z2Foa0FOdkVzd0pBQjAKc4NbcQdqwVou5osBY57ZaySONTg4jwmj
        ANB7gCGgu1EIHhGP6Fifuc3uzHo/4SdaSBqiLbsNe4qTGNUYS2P6FA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T16:56:38Z"
  mac: ENC[AES256_GCM,data:LlXoK80PxZyg8G/cqdQKV7J+KC1eAR/7n1xfHGjrh5Ld9TDMhvZdgfJ1yV76a8h6NGtLtWZri1n9UDFf7HxnzAux8sh2N1Z7ziKqaDXon3+p70uSn0Yzijdn6u/5W7ANAsQQ0xbRia7ucXGcuMmsQdaTm4Ou8JS54dF0Wo6YG+I=,iv:k0gLz3MvULsJyiwummvu+fn4j1Ivf1F+Tk+fCqHjNLE=,tag:2Zj85E8PBFcYgx0osgFP5Q==,type:str]
  version: 3.13.1
