apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
type: Opaque
stringData:
  admin-password: ENC[AES256_GCM,data:GiNKyA0jJhxQTyX4Idf/rpO5E58=,iv:soAfu0a6IbOgn3ECsP2jmQDqT9a3s4iCWVH/4ejYauA=,tag:QJdBA59X5jRDJWPZPKXPfA==,type:str]
  admin-user: ENC[AES256_GCM,data:xrMfzI0=,iv:oftmSdGj0Vv8VE4Idk5Ep9fCU35qpNh2dyNt5YUgsG4=,tag:O+OIMEVoKaQPyFsAAnh1iQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdTViUFdsSWExb0t0ODRK
        SXRnZU90UXErMXhXd1YrVlFwaXVYQzNlRGpvCmErcmxRY2I0RWVVK3l4d2psTDkx
        cStJNFpYS2F6bnUwT2lzcVVwWDY1UUkKLS0tIFAwRWdKVE9ud04rRjVjTlEydnlU
        ejJqdmN3S05MUjBjS0xoc2JyOWUzZFkKNh7Se2c8Tbvux9tT/Yt/lGeRclF2fSMT
        WFZ5CFf1wcEx56tFEpy34H5r1aJ1LLVCTlMSCrl2R4DR9n5hAfdV1w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYjRsczNESWhPL2VmaDBM
        ZDBSWnIzSUEySis0MGorNFNBbURXNWFYeFRjCnBzSFZhRWd5TjFyM0dLeVFKSStW
        UVg2YWhUQS84SmMwTkl2MHduUjN2UGMKLS0tIFNrQkNRQXJMbmZocnExNDlzZWJ0
        MGVPUUJVNG5TTzhIbXc2RUlPUm8wTGcKRj94TcTwRFtBWnera+N5gKz34BdNuU2X
        Q+iXktNcvxdBtTcuw4w2J9Ribti+TwxCYc6hH9MQ3sFoiluAURXEKQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T16:56:38Z"
  mac: ENC[AES256_GCM,data:t68jzxfIj7+eFPMa4JKIeKc014oLosHP8hZoahlsz7vu+9sgZY0oDEOeBlnzQDXGmgXD2/AmZ84imm6N2mEONFyyqoYjuAbFrIexBcFvUUQQ8cKmQb9+/jcHjnCZ+iCwrbpqGK48mK+xfm9OtB85KzL0daXkLIJjsiwBUmnehXg=,iv:bCk9zNibqBq1bH2o26MzblUVzmSeYtLWy4farvQpCBI=,tag:HdOm6g3kEmEGKYdSrCRrkw==,type:str]
  version: 3.13.1
