apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth2-credentials
  namespace: monitoring
type: Opaque
stringData:
  client_secret: ENC[AES256_GCM,data:ATaKiOOjbDdZbbp91jBZj1+Bc/ONfn7gQ78gCuW+iU9uDfNBPDYUcCGPTE36Nzg0BccHlIqAJlq3O5lDGjDSNA==,iv:G5l8fmM6XoqHt7CftFplhDBGD0j95tveKt6Vbimp18A=,tag:KVTI/QqHxYGO9spOWCcL8Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcnBTdkRnaFJYRy93WDdv
        c2lqZ3FxMXgyUUU2U3Z2djA2blB2VlZuSUNZCm40dTBmeEpaRXFPY2xKSmhTUFpi
        RXhkMVh2ZUhubmlkVzluRk40Kzd3VEkKLS0tIDNhNzRHU0lUYXZQSG1ncCtyQWxQ
        YU5Ta3RUYnpOZ01ub3MySDV4Y21zTGMKiCmxpHvu4HO2ZPPiUcD4PF6cyfFsgAzD
        MagfwVOriD39Mv68IMFYg1OXsIO6QyygNJxoD+qFX/sBb2cYw8alYw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZHZtTVF6alNvMTVTN010
        b0xqOEFHQU8wd1JyeGNKWkczQ3BvWjcrQWlzCmVKcmlNbWlOL1FwbTllazM5VFEv
        d3hna3RUUE95VzdpWE01djR2QkI2cFUKLS0tIFRvT2FKN0NGSmRRNktEN1JFT1VR
        eWQzVmFJSDZFY0xBRFlyMWNUbml6V28K9u2MKRmQt07FC7KM5wV3TnM2YsITLRr/
        NsB3rR/V17bISl6ystdScTPLALxIorrjul2hCuqIAhz2DEwnf+9Esg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T16:56:38Z"
  mac: ENC[AES256_GCM,data:zPju/WWj0e6QW0NDUN5h1hi086RhsQvUZTgTYcih8fZkCMdYEw1KHOPHzJ9u2VHSh7rW7IgcKPPLREx1VUXMc2jkJbS3YUigihg1jE+pGtd2z6p09jgT53Qx/3zisoZTVtUW+VinVaDecVULMyaRygX0q4mvlBRvsj7CW+0ltLo=,iv:D4fPsDUrem15d3rj+xHDoiQpm4eWdo35I5tvGC5346w=,tag:QrnUOEKkjE60nhlzpsiGDw==,type:str]
  version: 3.13.1
