apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:r8aSyz2LdbAOU8so2h9b1DX4lOKe28xE6XOvHg==,iv:Qmel0nZCnVLdGXIjBHsegdyegXYp/AVEAEUmZoaPxFQ=,tag:M3l4bI7W0HuWXiZ/NMVFEA==,type:str]
    admin-user: ENC[AES256_GCM,data:5cfHeFTzJN4=,iv:IH6eX4pnLdWmLHjUo6DGj0yaj9SQFkWD7E1K7s/ydQk=,tag:MWhQ/9eVXsAu4/BE+wE07A==,type:str]
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNb1ozRUJ6Qld2aXNiZnVK
            enBBRkVSM09OWU10SHVOYjllaTNIUTMzUVhzCkFjTTNaY0NQUmp0L2F4bUhKN0F2
            clcyQ2pnQVVnNXJ0UXVyZGFpOWMrbFEKLS0tIENTOCtSaDVIRGNxZlpWampMNkFF
            SVhjUGMzZXpKL044ZkpCM2Izc3M1VHMKSL4p4UeWcnz/RKtji5cukST1VW6e5XMA
            ep0uX925dY4Lxmr1DZ06FZcPvfg7Yus5up/ey6H658cQ5vJXmU7CQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:9cv3p+kPeo7p2hyobcY5JfAcFHSFrpySrO8cJZxwopQukZ6jOy5YqkNp0pxzETxrAjitaZzpurEYta5i5l6Umv+QAwcJllRQ4G/lkezvFSz5QT0TN3L21ltZOMn4V4xghuTg5SnIf64y8WlhHl0t8bz1iff8yDrKhgBpZwXzI9I=,iv:xWDD/P0GUHu3WvN0MJzdJZHM+ck+63nwbGj02gbB0gQ=,tag:zzXqgCg3PcyrBDRxJALOqw==,type:str]
    version: 3.13.1
