---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth2-credentials
  namespace: monitoring
spec:
  encryptedData:
    client_secret: AgAVgQNIusJCi9UNai0dlr/nAlcVvRezhrKCoSHzxe9lPjRZ1WO8jW/Ww1bCaNLUZtyRb5tgtqmXOCOY1OpacXtiy1AnkqG16E6asUPbxv4mupyqGKq80HyLqmptcB94W9IynjHi2x4aTXijLKrXVf/wKDsFFFUJcS9M8piSLMG1K66dxacHPC+JkXB6C23L7JYgcWwZQvEjblF2qlAqjHylJkQvpqvx2p+dDTX9b1m7dFW4+1LTZWF5BaY5zdhIENW46UV+pcpzwB6m6RJ0oMIRfUQJ/7ieNAE4VVcnc3H2yttfqG3yZ5BL+EfO4p6TWe6S4WuDDciPtXAyF0Ll7Ml2bb888pL9WX3Y1BaTiyYuPmFAukNtbW8+oIC/3BN1j51cLM18zVFNyUX0PSwbrsIzJRemXSGqxbntbZy7JqJJ+So1z3YMIU993YaQYZGxh6cZbUYZJOgQLBZbCsKazK/d8vqK6lQjfAXoOPU7trfAYuBWwRgierpyufkCbJyinNBZaUv+/tqepivNRjlvTScgs2NkeaUKqZFJ9CvS8Xb5Pf9WDvMUuMFVNjulq6th1g7OUTF7OR7GueTbVJcGTypYpmB2j/O4b+uf7s8oN8p68SlU7+5acCgie2ibuXaefT84sWTJkemBveGp1jPd6mhSuTPBJxGEdc1jypaNPEsede6WDgPQO3kDfmjjCa2zPo/OwFvQ7xyQHUISAzPrg5qEWcOCanChGp7PqgsmL/7LKaE+Fftw/DY4WZCBjfWT2Pp3u3KTQsiPHdUxxyGDceRo
  template:
    metadata:
      name: grafana-oauth2-credentials
      namespace: monitoring
    type: Opaque
# apiVersion: v1
# kind: Secret
# metadata:
#   name: grafana-oauth2-credentials
#   namespace: monitoring
# type: Opaque
# stringData:
#   client_secret: fixme
