apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth2-credentials
  namespace: monitoring
type: Opaque
stringData:
  client_secret: ENC[AES256_GCM,data:ATaKiOOjbDdZbbp91jBZj1+Bc/ONfn7gQ78gCuW+iU9uDfNBPDYUcCGPTE36Nzg0BccHlIqAJlq3O5lDGjDSNA==,iv:G5l8fmM6XoqHt7CftFplhDBGD0j95tveKt6Vbimp18A=,tag:KVTI/QqHxYGO9spOWCcL8Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNEIwdDFGOW1kUzhqT3RR
        R2M4Ni96WnppWlZyR2lSdzc1ZDBvMkxmVFVrCmNyanUxS284RWp5eFRVMHlWR3lJ
        V2VHTmREbUg0ckorNEZBSmdRRW1WY1EKLS0tIElvM1VobnplRjZ3SDBTd1p5dkNR
        eVF3aXpUU3dvSVZGSjlzWTR3UGJzQUEKIDSZ/tgKss5F70/JuDCGfmAB5dGotVTe
        /cYmJpTXjeL3oW+DkQy5RtW0fV8WDg3e0pzd58CIbriDV17Is5FW6w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T16:56:38Z"
  mac: ENC[AES256_GCM,data:zPju/WWj0e6QW0NDUN5h1hi086RhsQvUZTgTYcih8fZkCMdYEw1KHOPHzJ9u2VHSh7rW7IgcKPPLREx1VUXMc2jkJbS3YUigihg1jE+pGtd2z6p09jgT53Qx/3zisoZTVtUW+VinVaDecVULMyaRygX0q4mvlBRvsj7CW+0ltLo=,iv:D4fPsDUrem15d3rj+xHDoiQpm4eWdo35I5tvGC5346w=,tag:QrnUOEKkjE60nhlzpsiGDw==,type:str]
  version: 3.13.1
