apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
type: Opaque
stringData:
  admin-password: ENC[AES256_GCM,data:GiNKyA0jJhxQTyX4Idf/rpO5E58=,iv:soAfu0a6IbOgn3ECsP2jmQDqT9a3s4iCWVH/4ejYauA=,tag:QJdBA59X5jRDJWPZPKXPfA==,type:str]
  admin-user: ENC[AES256_GCM,data:xrMfzI0=,iv:oftmSdGj0Vv8VE4Idk5Ep9fCU35qpNh2dyNt5YUgsG4=,tag:O+OIMEVoKaQPyFsAAnh1iQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJem54US84bW16cHpLbmNv
        WVBEak0xcXZoU0RJKy9oT2pIQXErdnJ4ZGdzCkd4NnYzRW1XWHNuZ0V3aStUSWQz
        ZWhrVkJZVGhMWlFXTHZSRHBoMndaL0kKLS0tIE84Vk9valgvTXFBWkpjVUc2YTVo
        M1VZWmVxUWVwUXlyQlRQVFg0OGNMaFUKucw7KBAoD+61ATHt5ksHgjEViMZguQ5i
        zqIi0Wyy4WIgynKaiF/VevgebxIStBKjULyPP8p2ppCV/CkaOqnbpg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T16:56:38Z"
  mac: ENC[AES256_GCM,data:t68jzxfIj7+eFPMa4JKIeKc014oLosHP8hZoahlsz7vu+9sgZY0oDEOeBlnzQDXGmgXD2/AmZ84imm6N2mEONFyyqoYjuAbFrIexBcFvUUQQ8cKmQb9+/jcHjnCZ+iCwrbpqGK48mK+xfm9OtB85KzL0daXkLIJjsiwBUmnehXg=,iv:bCk9zNibqBq1bH2o26MzblUVzmSeYtLWy4farvQpCBI=,tag:HdOm6g3kEmEGKYdSrCRrkw==,type:str]
  version: 3.13.1
