---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCZBk/1/ePDoClNjI74zCjyfhcpTXRPRtl+NOI5KLlZZHnFoUvbEHT32a2OPBnUxzYZYvnJ2TwR96Gtu+i7kUdgo9ChqwIK0SBBbsejmBTGOBMBzflxMcesR76RAWz4mOX2NlNZ0RBpaP7Z9VjGebdGHpXVfvArrkxrXXHQXifL0xbCC6ExplyrKH263jJvG+pypQoAAtoLdn/g9+s0rPYouDth5oEohCkUVUBtiyClYHj/gLIXtkj/e8hqI1H2sy364aVkMqUjWUu32+uZzvWO9LYpwMOq0GQufG9tx45VAJozqhU2avTAoa5zgUsvNXdAcUUl2c3bRtPueR876KHjtgOjKhluTiK7v/7UuRalXEODCJfA/kaC2vb+hb5HiR3zF5gnY8fECjRKfB+TL8/vEMjX1agxYxOibL7FbiaGamWPjpExBaJp3PGWXXAgnW2naJ7fHYCEqCrU/3rP4OSShz6OO+kBKBV11DtCARN1AvwhY8SISbIZ3O+FaKjXR2zcekWy/dDzYA8MH6CiM/by5DepUQCsZZY6awLCrTdL4KQSpBwxY27G2fpZwMKUmHkcMCP4KeEIAv3qRrvof0PQtg1lsLTKIet7oTVIDH7+iy719q1JP8/8Y69frBQagpfedVqoM26MaXGsMocoLnC4jcAEOVLQsmWBY5DiFDwF64ErFochAWtBs6PUvyawvm5hvoX+8UxNTtnhMavxivkahk2vFQ==
    admin-user: AgCsVS0kKPbf9UUopz2E355kk5X3f5SUW0uyyqtbGo1j3Xq0nPprWxtRlWrS66np92KeE75dkJNC3CzQ0QAPBcxwrlvJOMZuymD48AUkqQdQKV3MLCAJeP0GfwK7KCRbJPWA8rqdwp9QoV7aUuRKFJ8WNGoace+sOW6buGP2CXEuvlCImbXX7WWd19FjwqD5iaxMRJOZ9CRyDoWIi3+tBb6LajImKQ1O5xeg2wAbFJrDV9z6RR+B6WIF74Rh/Ga17hGB282/VIz7RtYI8gkf4g+xMs4pEebuE2bEiR6PghaRZT10kFs4XbXpd2VqX87hwbo/6yfTcCnlLf8iKOuDO/O3rdFONUDI6nTmbCQOb2H6dnrffs8FS03dHYNiUTI48CCS9DHmdbY6xZk6nQ4HXxBUPrONq4vdM3VZvHh1vHCJr1RAZfPh8CKi4/s3csoEtAKrF9pJE/iGnzKfXEoQo0f1yqHMrI+3V80elE4WDfefvj36UtzfLNFbOP69ZJCtJmgm3hy5nxaa7dgT0QoQddedvLu/4/+Fl1n5ukQ5yElKWF4I81jUPaYCt1qbg+mU5Fcfa1mYGemsPDHeOuOoaqS8fmttlxxg12bjc44yEOIwciqxS+GZ3PVur6z++kT8B5QNqPacVPjkrnggLLj7UooMx7shq8+X1G5qrGeXiJeTeIVJp8e/yCNERcdyJ9BoPrYh2iyhWQ==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
# apiVersion: v1
# kind: Secret
# metadata:
#   name: grafana-admin-credentials
#   namespace: monitoring
# type: Opaque
# stringData:
#   admin-user: admin
#   admin-password: fixme
