apiVersion: v1
data:
    client_secret: ENC[AES256_GCM,data:qHJ17t/liP9yMgZdPLvQTYhrCp7pYSpjjLiq/ekqLy5POMqtcql+mjOvIMLGyYlj1xupGyfv/6hf07RcSZ2DuT6UxNuEk2A07LlQEBIKxAe7yZ5hjqSg3g==,iv:sD4TpCduTugS0LHjlrDNzXGYUMphPb349bBpPR/Jzd0=,tag:0E6BqD5LZGa6mPz0U+G+rQ==,type:str]
kind: Secret
metadata:
    name: grafana-oauth2-credentials
    namespace: monitoring
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MEFXTUVrQUt2ak9KUWNu
            K3ZuTXdIbmwzMDduUlIvaklsYnRxd1ZZUGdnClU0c2RYTzR4djNFZ0dKRkM0ZXhE
            SmMvNnFjQnN2WlgwTXdIajRrTjRBUWsKLS0tIFdFNzlvRkozTHVzTzFpaFc0cDhx
            dlYxVzhRMXlBNnRpMTcrYTBXeXlHWWcKwFkjfdj4Rc1qcf0rAgSdst14VZxTRF18
            mjsPjx6ZY8B+VEllDseKOywU7+1Gk3/WtRG2WaIkP7tvj14H8pKFZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:yZWaB26gfFVhXxfJCklibf5kgbT+Jsj8OKRQN8wPI96VuB8oK+2SksBRHEVmwCdWytgCl66C2JyIITv3ZIzzXMUFDGdApJK1yV1ZaCbln6XQo6CfHmY1aFzCD6ZBtd3HK5S3Wv8YFKyQz60Xa+ShhEpOAIjqIAORlhcg73PU1IE=,iv:VDsKAdNvph+9O72xcZNU2wMLXNq2oJ8KcU+CZS2g3QE=,tag:533vLX4yaEW/+5xKVhvfqw==,type:str]
    version: 3.13.1
