---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: spotizerr
  namespace: spotizerr
spec:
  encryptedData:
    REDIS_PASSWORD: AgAFIvahZyd69zVarEPMlHW76BMiDysUJW8fTs9CifgdWR/UFJLnKRixNpxQqu1MamN2Ue019Lmuj7z8DkFTu/4yO4qhKUoVB184UzJNxGtbgmz4n9Z4hP9jyxWPhtnoCXKzKbMd8ugiNDKq8k99uqn4mOWmmcPmVeAzoaPxfy0+0rGSnn4s6pFC3nqSlykHCvsvKawh3G1ivoa5AwkVLnzx3latmEXc3xG+XmVjNpk4NtYYcIQcyTJQ7OpUErBMTX/lmCCA2sC/EUSlIx3Kt/o0LJOwy7dfAxAS6SaqD3EeoQJagezR4fbCqAq7GZM1j9LT9lipMG17blRzsAdKSfj13C0Rza9zVJx4tsplpxaddOYZi3VWvW+s7FgRpvcTifUbx0gBW8n9egaIERB5SGAS2CZx26Xu0HS387XzgO3Cp8C7805eOzfMMR/aaAOj56WRuwHYWDtbK9/mTU7OP6Qt3ALYPLmbOpNvEpqgwc6PkhsLkSiH+tKcFpVGwiVHuDcgrDu2XRDmE/YrK/oCFmFhWpWxNYjg8L5y2QVfFNpIMzxZ74k4OGL6FNxqFQWnYIlvMxIBQXsGlqMTiF26S9RZP58KcZX9RoSXjOtMAdluugSXwxwGiyxxp+pdPsaSHuW3wlxqF2zzp9exD2eJDMnbJzo/W3P3yga+YKJDxiq8AgESMSW8w3wg2XnDvWKeiyJrC06brGOA2w==
  template:
    metadata:
      name: spotizerr
      namespace: spotizerr
    type: Opaque
