apiVersion: v1
kind: Secret
metadata:
    name: spotizerr
    namespace: spotizerr
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:ohdt3aN4DWw=,iv:U/CPVZSf0HuwcpVv+LO24M/LHiyPmMSsdPnLBusf5fc=,tag:6t0uNjj/PzL8V4tzQ7vR0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dHRSWjJWTS90c2hQK3BB
            TytkcnNwQnhvTFduM2hIVlZHSUJ3akxDU1dvCnBJZUorVm1zVzZXNm9FYWR3UjJB
            bzBoMzZEcG5hQktOeTNtWm0yZm54U00KLS0tIGp2clFhQ2FBWE5NaEJOVXJqcGhz
            YWZZaExiYUJzTlpOcXllT0k3UWpDN1kKD8jxeEysU7x30tp6T+0H+m+ufYIreZha
            /woOnLiQoX//Dq5Z7IQckJtlf0xVDCFTBZEwOIrLAvF6fD7Q3Ucsvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T16:56:38Z"
    mac: ENC[AES256_GCM,data:SdC/7fBT3s/l/r5IdBYkwl2GjIim8FEqie3KZlKrqBkWVnVZIcMSEMBoqPMAT+LFOgjR4zrZoyHRfwuPrjMqoWOWI18o8vGjtw9KloIb2FFtf/8q43r7/mh3SYFm/Mq47pHuyrGkSxU+rdE0k+BjCclhK3x3k/VYYmYjKeLkGac=,iv:Vb3seQezAVE5rL4bO4Nt4Tb9HfqfU15B47DyTCUaZGI=,tag:5LV8gb6T6i+sikTTmz7piA==,type:str]
    version: 3.13.1
