apiVersion: v1
data:
    REDIS_PASSWORD: ENC[AES256_GCM,data:WpLchvocoThM3RP+,iv:S7fbDvSTt/j+d/fLxTcrgPSAfM3pUqKzRP75HGrYIFU=,tag:L/MqqBOH0TGr2UYIhHXdZA==,type:str]
kind: Secret
metadata:
    name: spotizerr
    namespace: spotizerr
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VFlrMDQ4T2RlcEZjem9v
            aGsxL0Y0aUVyWU44WGlQdlN5elFzdlNOeTJjCkZVV0VhYVVFZXZkZ1p2czRxeWRH
            N0RjZ3g4NWVTZDRTWmozaVRPL09CaEkKLS0tIEtWQ05td2krR09BVHU2TnhodHJH
            WUpPNnNyWmRHQlRUazlDQzlzRTI2ZTAKo4rQaowCxRqRwNQdTmQpQuEqMMAHaPc+
            jYpnBj8lmNWEyFDFHHYMF3u/byQ5aimFfV3B2SwckC40GtTbDApKnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:vKeL+tdhnQe4gAGodUS80U5GtNOzYPJtt/EzQ/CeSzXqCIm7lktuy8TryeFmYwcZ2o4fxZzMn0goLbmJdZvkKqoprhuLBahTBElhMNQNsvZhgha62GwgtRRiYXlntxShF74Ykuj7u8OULr+VozZDSs3GEU7Ua+KrQBAuJ8y2q8I=,iv:BHC39zKCpVradHYpdkPX5W6DPHvJgDn0CYGTKLG6jDg=,tag:8/L6ECCEDRt3cqZzuzEYLg==,type:str]
    version: 3.13.1
