apiVersion: v1
kind: Secret
metadata:
    name: spotizerr
    namespace: spotizerr
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:P+7kue3iOi8ZZleV3VBXL9+4eB2dqNMO,iv:ILGHJWP9TNy+SS4p/6GEer92rFui/ftZ5cigwTOiJE4=,tag:owZObhPV6LtoBpsUmZ/VYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYW55a3NTNkhiczBZVTNY
            S25NTGtDcUkwOGIzbHdMYjNPT3U4K2FUM3hNCjYzRW9VY2E5eDRmR2hhZW84YnJv
            d2FhSWdEcmc4cXRlZFdsY1UxMUpSRFEKLS0tIEJwV0tXZGR2TlAwM1FpMjYwZjUx
            YzVkcFRFL1RrU1dzQUlETTFtNWlwZjgKeY0J4GErIt6pnG/jZaILYl2pYFWKE5k3
            8OYBsh7g0AiECHakPVb7y0sv9pIQAb0bbzlyLYNei+ncUgPSueEtNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNmYyejJhWkFvSGtsRGM2
            VncvZ1VnVWMweGxpNkg3bHQ4RVUxWng1SzBJCnFzaW9IZEw0aE5yOVp5c2s1S2lx
            RzB4bVlOa0VIYjcwRW9wVFBrTkJRQ2cKLS0tIDV4NmwrbnJpcW9PSkhobmNmS2VI
            ZUI3S1hSdjdjb0xTemRTcFJrdU9BZUkKsXCEwlTegGhafLwW9yOlWLpjk9es7LuK
            CMRSnNY/A/tetVPSUuP1RXp8Q7iS6C3DQucfpX4i5MfaktPRHDlOnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T03:37:05Z"
    mac: ENC[AES256_GCM,data:org1vCmgVaN4yLr/C7Wu3wi4aa7/8iqzQfR6eugSvKdlo8Lxsc3rR+98mTQRMgynAH9W0ndLXRn553gSzvjubMbNPOcNibYj9UpNbS09SQD9SOzBMV9aSlmafKmMHbXmCkdn/66Hv7PEmKw4qc1oqXNzR9cV2mgWNVTqv8ZfL+U=,iv:mKx+N4pn9Ih6r+6AslTiS2gFTjwkby4DRDyoy4ZO4fA=,tag:F2JSSLtNkbuFGaws2BqjcQ==,type:str]
    version: 3.13.3
