apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Paperless-ngx"
    gethomepage.dev/description: "Document management"
    gethomepage.dev/group: "Life"
    gethomepage.dev/icon: "paperless-ngx.png"
    gethomepage.dev/href: "https://paperless.item.fyi"
    gethomepage.dev/siteMonitor: "https://paperless.item.fyi"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=paperless-ngx"
    gethomepage.dev/widget.type: "paperlessngx"
    gethomepage.dev/widget.url: "http://paperless-ngx.paperless-ngx.svc.cluster.local"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_PAPERLESS_TOKEN}}"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`paperless.item.fyi`)
      services:
        - name: paperless-ngx
          port: 80
  tls: {}
