apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  target:
    service: paperless-ngx
    port: 80
  rules:
    - hosts:
        - paperless.item.fyi
  scalingMetric:
    concurrency:
      targetValue: 20
  timeouts:
    request: 180s
    responseHeader: 60s
    readiness: 90s
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  scaleTargetRef:
    name: paperless-ngx
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 600
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
        interceptorRoute: paperless-ngx
