apiVersion: v1
kind: Secret
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
type: Opaque
stringData:
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:Bppfj012GevwMgnN7C+X0ZToWRo=,iv:xBUbxezlYTPhADrNy1aHnYtuKWUJzI8KpTvjhoL6ZU8=,tag:RjVzbobwb95K0lRC+WJqUQ==,type:str]
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:njVwNWk=,iv:jXwA8FdEAfmvflnfrkOfTwNMc01TLCOekTY5d+YQLIM=,tag:kzvKi0a2t5iMknera4gheA==,type:str]
  PAPERLESS_DBPASS: ENC[AES256_GCM,data:E23taWmzutlZ,iv:mXtEsotiyr1eIHFURx1LPrew+DjnyD0ya1V5yDVNxAk=,tag:q0E/J3XSLYJm1k5gTUIu2Q==,type:str]
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:FdFPnm0iqr1lpi7v4bhkMFk1KNxQKi6EJZ6ugkfiVwGvSckHS92hVyvsu+XQ5sBNRZM17xFsk9rGQlcMRUXUTt9XayX9Srr3OXKfGvn3WxeQZMR6j8X06uUfXu8UbqbZfScff1gC70xJDufhADFiKyutuxzAI5AXISG3o7ZVpw+U/UUiOUPl0gaicKeyhKCv8x/oqrJtKtX97qM9ZFlnZyCY/e3Pg2QT8MnQLcLexcsVOESoWTXPNJnp9MlZS42wow3Jd6uviAzXKW0175iZ2yhQnD3BdkfKdtb+0ZrGdbxAy/Z1yDEZl5kC2d7DFJuMbsekNLcwIX23wGD+gNy27PSN0g==,iv:DL7GDjSCrbBQ8bBCE3ZYzGSWtFyXLIRNkydaH1c64as=,tag:s9O6xbdN9xtNIyZCIv1R1Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK2tlZGhzUlFwazQvWUFJ
        bUxYUnEwTWI2Mzdhamgyb2FzbjJCUjNKclhrCmQrRVBMd1FLNDZXV1lidC81QzJ1
        YUdXWnNTbHJkZVNyelBoODA2TWZqeTQKLS0tIGhJTmlEeGFyOU9YMHVXNlV3ODF5
        VWhiTEVoWXN6OUdOZ1RGZlc2SkNHUWMKw3u256I1icsbmXDnd4y57JkceIi67lVC
        wN7Szqevi1K8e14O+4aaJecxjAaeTsitEEpRnn8nKILDL1+3hdfp+w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T16:56:38Z"
  mac: ENC[AES256_GCM,data:m+a0KrZ/BmRAq/ir/jMrY8uWDRccvS8hVh25Rjm+kzuLq0LCwyd6qepCc0OFtbq0qPW7zF19Deb/gY9WBVqK7DCT+R63+KR9f9s+DByFzWAecIZ1l9gEpTngJ/JXd4HxOXZNAekWNS3RHfuL7qa7pP+C5AnqM18qqb4bZpismtE=,iv:wCAR6CPrn4p9BBIMRnlgPx5NztVfKKyOL3vY7774Kw0=,tag:dL1Xk0IwFnpRw1koEoCgVQ==,type:str]
  version: 3.13.1
