apiVersion: v1
kind: Secret
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
type: Opaque
stringData:
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:Bppfj012GevwMgnN7C+X0ZToWRo=,iv:xBUbxezlYTPhADrNy1aHnYtuKWUJzI8KpTvjhoL6ZU8=,tag:RjVzbobwb95K0lRC+WJqUQ==,type:str]
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:njVwNWk=,iv:jXwA8FdEAfmvflnfrkOfTwNMc01TLCOekTY5d+YQLIM=,tag:kzvKi0a2t5iMknera4gheA==,type:str]
  PAPERLESS_DBPASS: ENC[AES256_GCM,data:E23taWmzutlZ,iv:mXtEsotiyr1eIHFURx1LPrew+DjnyD0ya1V5yDVNxAk=,tag:q0E/J3XSLYJm1k5gTUIu2Q==,type:str]
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:FdFPnm0iqr1lpi7v4bhkMFk1KNxQKi6EJZ6ugkfiVwGvSckHS92hVyvsu+XQ5sBNRZM17xFsk9rGQlcMRUXUTt9XayX9Srr3OXKfGvn3WxeQZMR6j8X06uUfXu8UbqbZfScff1gC70xJDufhADFiKyutuxzAI5AXISG3o7ZVpw+U/UUiOUPl0gaicKeyhKCv8x/oqrJtKtX97qM9ZFlnZyCY/e3Pg2QT8MnQLcLexcsVOESoWTXPNJnp9MlZS42wow3Jd6uviAzXKW0175iZ2yhQnD3BdkfKdtb+0ZrGdbxAy/Z1yDEZl5kC2d7DFJuMbsekNLcwIX23wGD+gNy27PSN0g==,iv:DL7GDjSCrbBQ8bBCE3ZYzGSWtFyXLIRNkydaH1c64as=,tag:s9O6xbdN9xtNIyZCIv1R1Q==,type:str]
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:Bvn3UlgfUbDRxJRUI949aEQ/ElAA3QoWWSBssTVTqk7bowFz0Z6nJ30QFc3UZOO2E+qu21rcB0KGKT/U6XZvE67nrgQDJzU7nTipBzqVQaYFqa4CCBM=,iv:QB1fFAtzZESIwcoJRUj3iMbUunyTxBbcey3d7vXEZdU=,tag:aG6bTJnaHLr0XK2O/Hzf9w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK2tlZGhzUlFwazQvWUFJ
        bUxYUnEwTWI2Mzdhamgyb2FzbjJCUjNKclhrCmQrRVBMd1FLNDZXV1lidC81QzJ1
        YUdXWnNTbHJkZVNyelBoODA2TWZqeTQKLS0tIGhJTmlEeGFyOU9YMHVXNlV3ODF5
        VWhiTEVoWXN6OUdOZ1RGZlc2SkNHUWMKw3u256I1icsbmXDnd4y57JkceIi67lVC
        wN7Szqevi1K8e14O+4aaJecxjAaeTsitEEpRnn8nKILDL1+3hdfp+w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T15:24:33Z"
  mac: ENC[AES256_GCM,data:K806Z6zy70/bT9xRx4d8VZYeZ97YuHfzZOkJcwys7jq3teZ3WXydXX9IExD3rm3jpVxGYezM5DmerlIC0QsNSfH9uuuhgtHdG2RrE7Uy1KdWPp4yuRuOtSB95uQB0HzPPhWjBqSxMVt33763TqsEZp2b+gA9DbH3SMXg2EBz000=,iv:ZfRiKwc0HuILLgvuUPwD9B1NmodudSuHKfgj3MCE0SU=,tag:8aleobFlsTQG/HytZexB6A==,type:str]
  version: 3.13.3
