apiVersion: v1
data:
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:Tv04Dc1qUrMMUqwZ4u542llBbcCz5RwvP/uWmw==,iv:nwFS2RqBfBAVYnsMdXiYBpbSxph9OD5Qn9EHp4uKv6I=,tag:XigYTDy5vuIDlfuEmqNbJg==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:8aKbjwi0gtA=,iv:FtYdoOpD0/WfYIMFGGy/x34252CzqVdJFMEXsZ6Wi88=,tag:Ns5Hw0sA0NVoYJFThIer1g==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:9eNdbnmp3mvIL/2f,iv:oMnDVndsfjVnJRAbg+logcc8gjefu5c+TKzj0W/O7PM=,tag:kdLkyRt1MiH173oGyS0VAg==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:cY7TOBuZUE+AMa+05QNBtt63MR1goq2OJZOvTgulUH3NnRrZXK8d+8p7NMoTc4PWUCyGdu6sMB88nwqoWtXAM8KaNbbIyFvuo7eZkla2SwuSpVNOrTxIMWRol0dmGkUsWr7h5rbwSwEDfZZashrhjIkK3vtUNaPwT7al8hwYagc4SHySLECLklvbhEQyRtVkCMfrxVqzTzFFwLpjTlKGu6Zj9jVpGm6mTGpz5J001iZEsik5zD7EitqzaAdKVDRIuiCM9oRQ3fSKgwYg3ZB5uHPTP6b5RvK3jWWqAJWGnIbog/afK26Aipr8y5suP4z1lhuML2QnjGT22SvaElXNjU7zemYpFvG54d3rUAen+1JWdf1tisOz6s5WTcGDk4Bqe5bh/jdshI9cIQtP4oAdUk1hH9TyRXnlga2CPh8YJWOQhQ/aop5BgmSxzfm+zbAH6f/cSsdIAPqC51cr,iv:BcGk2EAWD5J6hRslWMDmo21OvEgZPHr/pApMjTtd4Uo=,tag:BPuon5Gd8jh8m8ROQlR9nw==,type:str]
kind: Secret
metadata:
    name: paperless-ngx
    namespace: paperless-ngx
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCc2lmZElMdkxZenNubXc0
            dDB4OEdMMjZ5NjJ4cEJmM0pMdjNEQk5pUFVjClpNU3lEZTVmbldPRWMyWEJtY04w
            aGM4OE5La3JzTytSVEYvMWtqWDd6SGMKLS0tIExRTlhlcy9kWVZDN083TE1mbm04
            dXhFNk5FT2EraitwTVhEOEUxWjQwRTQK6bpcZRcIOJNnHSIfiTOF+c//9HAG4+qH
            gFcne+ytHr4h6KYJ0RGNhFD2+AxVph6SpMcrF0o/EcWgKptOhO5AGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:w0jqz1S33/v5CmSOOnHI1D2SR3dIVvTzPwfiTj6CNYGDRUhDWOMhBjWroMPDQyXNiDusK3kyCvANV8+wTMz6xGtCGYVX29SGjtoEKoVVaxtbawm/S7C670FHyFBiB5kLXB1TDT2B/DPUD+YFvPLjTxNAVdYmrDpZzwNB5+Kw3UA=,iv:jPtUzcKyC5RZFr8d/fJpDHdFKKQo3/kC0mdhmsEvX0k=,tag:r9z81AGVwprr7qdH5MHSag==,type:str]
    version: 3.13.1
