apiVersion: v1
kind: Secret
metadata:
  name: audiomuse
  namespace: audiomuse
type: Opaque
stringData:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:3+fMRae9R+fXW72/g86MLs91t3bdmUoQPAqqa8ma8EDhis+LKXovzpXfQ8+DwXZD,iv:pg34MqGsUeYmu493WjiqotiLJbi3Nh5cSuniw9UywUc=,tag:COuJZtTa0g1rdQZh2sHMuA==,type:str]
  NAVIDROME_USER: ENC[AES256_GCM,data:lkcqOtQ=,iv:XFzHvV9BJNFH9QbuC2ihqpcUTQYgFJUvBTnyk/B7kEU=,tag:L9AUZ6CGNC7fDXVIp25DIQ==,type:str]
  NAVIDROME_PASSWORD: ENC[AES256_GCM,data:PPRktLZQbf/zRGySUJaMz8T3tNk=,iv:p0p/Lb+cWQCsgp7Uh1IgMg1CN5kJeM988WwRiPtI5/Y=,tag:aIdBy+y+diyiyOUVUxMeJA==,type:str]
  AUDIOMUSE_USER: ENC[AES256_GCM,data:vPmzBNE=,iv:7WO5hEPCw3hYb3LE0/hRjuJJMYiSxsuL8UmvE0w3mAw=,tag:V0H1s6yJdzkPBwJ+eQMlEA==,type:str]
  AUDIOMUSE_PASSWORD: ENC[AES256_GCM,data:jstVDQM7j2pUVhYM27vmhgyrU+8=,iv:G4ZREozYx5ljg5PqhxK9b8LT1kzThuXmYry3LOWKTAc=,tag:mQck3OkRBqiHdRc+TFUoBg==,type:str]
  API_TOKEN: ENC[AES256_GCM,data:TrAg5FhDGSOR8KzQQQzW7n53SN7hUspt4xKSzi3NYOLlE884AMyASjhaun30R3Vc6SVcwnOgnNEGzTlIbs1H4g==,iv:2YHB8tUYYewW2YWJHiBFLPvUfQU6OsEOcdHtC6CGf58=,tag:lXZw2UpQrr2B3Yj3JhBH8Q==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:SVKYDd1OtVRRFLXZ3zWVr6egN2Knfwrj0zgC5d/Cw/YfPx7C2c6x35VZ9VI4eEvMQ85Cj9ArrAjdKv8R0ULVSg==,iv:EDTvkoMu167/jASBPylhTohXKRpKJgrosvVNg3IrpMA=,tag:6PbAqB/JK4M4nSpkdtlptQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDR0hrSm9CRGVSQktaZTdN
        Q3FEaUwwN3JDeEVVdXZPTk91VitvWldzZFFjCmh0dVJCRjgvWFNQVTlVKysrMmtU
        aUNVZFpZMUhiZVZmNDVySWVYNzM1cGMKLS0tIElhbEIrdk1aWUVnNy9pVjhrNXZp
        YUV6aHlYTnRsMG81WnJHMm9IeHpOd2sK/gjn1XyxpEaU/SDqGXeU/1t/S8NFV0JC
        PWI8KF6YNsoN33DXPBZLKNiJ83QuBgIr8JbLPZM7zgK4jVpmOmLD4w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-19T20:22:20Z"
  mac: ENC[AES256_GCM,data:nPQ9QFXian4wweQBwadzwQ9NhCl5IxaTu6i/FS0RtSwPPigXGOOYdVBRHigRyikUwsGzhzDU8Eznai6+FVIBDl06HVeifRmfUjkoAUIYTfLvTfBO6Upspyh3zRFkYthdJ3Imr/1HsZuLDnFh/BpMQkTjk4vY4BobGUf0tSLxRy8=,iv:0ApyzWcoJFPfjVGSxJdEcIDL2vGBeKAr1oyxHVAet9E=,tag:TK+5LjM1nIMLlJLtOD3bpQ==,type:str]
  version: 3.13.1
