apiVersion: v1
kind: Namespace
metadata:
  name: archiveteam-warrior
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archiveteam-warrior
  namespace: archiveteam-warrior
  labels:
    app.kubernetes.io/name: archiveteam-warrior
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: archiveteam-warrior
  template:
    metadata:
      labels:
        app.kubernetes.io/name: archiveteam-warrior
    spec:
      containers:
        - name: archiveteam-warrior
          image: atdr.meo.ws/archiveteam/warrior-dockerfile:latest@sha256:ef212e47037a8de8425cc3f56629890d3e0aad7b630ddbc8aff0189e3efa2e37
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          env:
            - name: DOWNLOADER
              value: akmin
            - name: SELECTED_PROJECT
              value: auto
            - name: CONCURRENT_ITEMS
              value: "6"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "2000m"
---
apiVersion: v1
kind: Service
metadata:
  name: archiveteam-warrior
  namespace: archiveteam-warrior
  annotations:
    gatus.home-operations.com/endpoint: |
      alerts:
        - type: pushover
spec:
  selector:
    app.kubernetes.io/name: archiveteam-warrior
  ports:
    - port: 80
      targetPort: 8001
      name: http
