apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tandoor
  namespace: tandoor
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Tandoor Recipes"
    gethomepage.dev/description: "Recipe management"
    gethomepage.dev/group: "Life"
    gethomepage.dev/icon: "tandoor-recipes.svg"
    gethomepage.dev/href: "https://tandoor.item.fyi"
    gethomepage.dev/siteMonitor: "https://tandoor.item.fyi"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=tandoor"
    gethomepage.dev/widget.type: "tandoor"
    gethomepage.dev/widget.url: "http://tandoor.tandoor.svc.cluster.local"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_TANDOOR_TOKEN}}"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`tandoor.item.fyi`)
      services:
        - name: tandoor
          port: 80
  tls: {}
