apiVersion: v1
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:LQ2CGt96SNru7ymNS8f552Wl1pHnJYfCFVOObzdVAHMrw+bQEtm6vCbz8sucDirjl57KqEKgYhKGLSrNiIZBCw==,iv:ClgJ5gx0hKPCJASKILfL5m6CDKPibyXtQNcYmoRQnlk=,tag:qrAS+DNKb9IBkB56MAXqkg==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:ZMPpg57wCK7nHsvQlTIBoOFa2V6kB86riLSpVkPHbkrpQ8u9/k33HIFtl56yN3b2+D3T7HP5G918ZQTLUrGioKWfnLY=,iv:kzXVADNHtA+Nr8YeP5/Odl3CBCXV0z5SrW3frALuUbA=,tag:rAF02Um/hgz8EIH3EvJmhw==,type:str]
    SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:FrA6s7JbQ+nW6v1rgayKR24OWqIImKq90EnPv3dHxa+bMHnwe+M7H4Ot0NAhg9m+TV9imDkyvObgPa7Qozf9x/wLPcpqkZOTjpOi3POES2o0tdv7FT3/iiNPyFLQ/Ieyz+4uvLqLX1dIUx7emn9jBMLd5lP5dsMQj66jf392sGtYZr6sclRbOS9HfSrLvjSw8cVSAGdQ4l74fxbwzxjqvlAoWPgQyBI/MXNXW20OjgTeH1EZaVu0mtugaEh2bUXyW0osqEGhykkf8gCoD9O6qHx4zh7ZDnCC71E3EjQfEoNFG9Tm7mC5wrLtOgBI1Fek7QsiGMF8lcVD49QIGho6l5zs2/gNyFM9+uIRv5iw5HHGtw/veG/YUGexwtq65/PsIpzT7PhPuyg9XBUA0JMiUicYM+P8RKw9vOL7f2hdeoLlL/mVOG6zidTmcOg=,iv:vWZS4xkWjJ8GQmJ+QDtZbi3u5Z0qwLAk4KoDdzDQmQg=,tag:Ytm8ynY5b8E6fvz+FyX7OQ==,type:str]
kind: Secret
metadata:
    name: tandoor
    namespace: tandoor
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWnVEV2dTNkw5SXdiRHF4
            RXpTZ1A1clF1OXN1WTNPNkdFMUhMSGVKMVVnCnRTMktSdU9lWVYzUDlqWVA4TVVZ
            WHlEeEZseXhkTGJyamcwd3g1YTErK1EKLS0tIGVBbkJNUGliMEN2YktZUzcwQzdi
            OENHTjZUS2o1cWNGNkNHVEpKOTIvQUEKGFhEmIE6ptWWepCUsnibqG6CZQc8WVes
            0acinS3Q3tmXrcd+UdUqauix91l5r5esiuhZrahD2IgQOP7tqCNS7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:MyWpVsneNHl4MHAkvOeRvXjBA5zwFojGLjCm9QNTVV75ozidWFbJOErnbcvB1QT5qXYUDcjhu5oXCfOmUnunHAWAuuVY0a2gCxGYY9Mt08GKrZ03pSd2ZTOciu7FscM02N4mnkmA+MpxjTfTRkzWWo8vUUlK7H/CpzmjACs6zo4=,iv:6QrG4NujKFSqyQy/vuqB/A3iV45DTJ9kQA5zuRaiXJQ=,tag:usdG+9g5QwfLCAR0cLvqTg==,type:str]
    version: 3.13.1
