---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tandoor
  namespace: tandoor
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCj41NUcF+cGL343b+rUkgV80gW0kvaeqbKc4hkhGafzoMBMzOz6Xkdo7JV8FcmBHh+UCkvCpuunTkowuBHlLfEAob/lR4Sz8LpINqbNLVZzNWNdaXt8iIivfuOTD6E/XsvsKM5mYFCIhM1rCsYNxoVvuTGK85/3TvF1/UhTJzozDVCwGuA8vnhC1Bim3Ooch/PTUHPSo2b7sDpo682lV0+AKnwRZ/fACapsieL0dY1YQR3TVb7md5VQX0Uri0F4GRu8HUEQjZXE5dsKcib/tZC3tlZ5w7JjnNXJt2rQHW9ru54/+vh0V0Budr2fIXOcJLUCTCWtTsc6ArcHK9jMn+heRBIebNeq2vdtzBzg56sPkTeiOB/c21FAwJKyKpDAU33nrFDGahFFhzC2ATM41ktln9sc1N86IGhT+FdHk205nKx3Og7UR0NkaVN6o4t7t1W+XYIRSNP+wMpULtdEmQUTa9XZCuyc0CIb+KItza+g8Lr2B1bRgaoIHg8vrHIcMgd0qy53CbfJTN8kxPfvO0d3eox2bWtU9n1RiwGaGDJe10ittdTTocCWgES7gq/5rqoKAVU8iJ85psbDCQDzhWjICS3ck1BrlrUbUzVACshp63zwrNhMWMqPfSPAm3hVnKr3HSBJQFct18PGO8FHOecow9tYPLx/UI4NwnJM+dZOpKaoosQs4MkG67l4RSccZ9MGH0Se/0dyQxi4v30qmohZSLoevByp6RJK8yFee9ggxvG/lHgoA/C6EymyzkNzA4=
    SECRET_KEY: AgBV8YQN28qrCKvOimQoiM3wc+Y2jnpTKzfH86548M5P3hQdnH+ZRk2ByIC5O/q2W5W9wAayk9E49b+OJr69vNO1T6BbEiXoRQbxyICWSuyehg3tLrvLrJKM4RI5AHMKvPMU/cqXtrk3w6Cx3N0/rMTyLtPb92MRwDU/OLSE+Moqw78XzxppSFg13BXty/BoN21ybx15IQveQ+/uys0zqWrZXBKyaxa8nD3RTXqNH4o5/EgACZ20cSUFFp1DmxjiIon3PSpSQiL61uJlboDw8LkZlo9KwOomVcG9sUojpnoU6ivIp+PSDdk1YsULLhQQGHmgsPze+lnMCLmGAjcS6NS/c3ytPPJblT2iVmWXl/SH5Z9zVbJs4+JPMuC6bdwcSD1M0AbqHn9kzGyFxh2SPZHu6zVovTu/6xahx8IxF7adG8KJy8wndLHXUEuYIljYhKbDe2Ih5emRBWoUwW5MrUU1bgTu9thcbBJ48JrRnYA4cxinO9XHDGdlv/s62AxlafDWqEyrKu2ga94bU1o9N+QVXkQAMY7OvoxxD3+NZwb85Sgmjk1EmUC3SRM01PNm1aeePujG/O+BOIRws9ts0OlObxBKAkOfONAPyU7ZHKJN2NwEoDushO1dox6FOIwB2tvRQw6CS9zTbVu/GIz3av+zDfVKtHGLMbMSDLFm3YiEZ7YUVXqEPzyYHlzYGMmQEU7BZN6c2FWxfZu2/F1Q+MxYNUiJ3x2Eusvts5vXNlkWbd+QgKNCgO0x/0oMgNWejHQ5yQ==
    SOCIALACCOUNT_PROVIDERS: AgB/k5p2zMVWTajzr/VQ1MT2v0MJ1fiBSzT6vGtuob/Ovyp26OteSTiVSEj0Zd+GTKhgvmFMHOUZoGdfbvvQ2sPqmZToEb5GIeLmgzSf+OxVNrJ6oAZVdwJF0hO245LzXfNBirOf1ErGCAehvRkpD+LHd2D2FFboAQRS91FjuU/4iYcJiCYiloPq61lTqjlxendDOK4wqqcS0HD1PSj58M1hB9+gnluD8Pl+1UNBe48HIrVwTRw3iN+T1UXtz4/wyCs0Z49/lFmNf6/X3cvjacgFHBAitcEgNuTbp2sh/bhVgQt4FVVG0mLWhGUVV9r5Lr6KEyJLYjMtPObz4VNn7VJgWU1euAV2YyT7Y0rgbzjCFVQsMgo8XOyPJJi/+LpZaUTS24Mp59ttH+8x9DwwSBkmvfNdjOowXTBPe+ZKys2s2GLD95Ubz7pyIdmyGq39dNl+F2qBKmZwmkHyHI8GOVAELmScLzjS8lDlb/H3SBR9duo9Sz2IS+hkp22jzWEFAnHYTD4dz4H5y8VNmmrRJi3oxoynHpqgX4AnxG7UmEkmxAOrL3K3r+FDKi6PVd8nmfsl8jq+PGqa5mcPtZzY4HLwaXRD9vU0Sap3jag1vSGJC6aeMgpts1SIb/AlPD3xLuHXuDXnc37MZo4Ncucrw3fcFpdiFsol6DZeDkxIdrqjo5Mn4q+EDuZys7rgvyJh1+NS/L2otnG3IZ91Vc56AOCp8hvm8m10Pl0kaGj+MBQK3qCgZBdPcOpHwyahMIN7eSnaL5KcPUdFcy/RNpvmOnyvplHAdVu75gKrSc07veHgWQtHu/DsssAwfRg4igeSYE0ONq0js8VS9kEoOET4Lpfkq3+LQEEJ4M8SKmQlFjEsn1NVSWtZh8jlclgs+PIzg3964kpwd+xnZFzL+AWRCtAOQu0QH5AvJuZbFN0a6mKMS8UJNSeWhkquJil15zncMGkZD7fy9O8wTubD8RTIEfDcp1Rq9qD4Mcw2HrpJGYioukx5So94SOYWmmGJjirbbx65
  template:
    metadata:
      name: tandoor
      namespace: tandoor
    type: Opaque
# apiVersion: v1
# kind: Secret
# metadata:
#   name: tandoor
#   namespace: tandoor
# type: Opaque
# stringData:
#   SECRET_KEY: fixme
#   POSTGRES_PASSWORD: fixme
#   SOCIALACCOUNT_PROVIDERS: '{"openid_connect":{"APPS":[{"provider_id":"pocket-id","name":"Pocket ID","client_id":"fixme","secret":"fixme","settings":{"server_url":"fixme"}}]}}'
