apiVersion: v1
kind: Secret
metadata:
    name: tandoor
    namespace: tandoor
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ITl2A7OwhD10cnzRyeh0YBjHYY4SLnvBlagKMBda5QBddkXOAlZtuTgiMp9Cxhlj,iv:V7bxW/FAcWYytoAKkQPO6EDqYRytWs4MeGFpG378vvQ=,tag:PCuhxmgnidKb0vnL0bvaOw==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:TUVVJ70TZFMLtUE0Qs8jMasJcklR6Lr5rymQkNx26vW9E4zV358Ydg+olMQjDUvP6vY=,iv:NT9RXyJ8JWH6DrzqmgG368o4uCB3pbAe3B1YZij2Eoo=,tag:2eIwQhDX2L4TYs2d/vdSGQ==,type:str]
    SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:Ot7ccVb/h+pQyoi4ZqyjfqkjmU1haLRlBrMXzoklRCrpCBCrepfw7+yXcbPhTPpqhop20uNM7vmy6ODocsUok5moOZXSGvE8xgzkpD5MBNVLDcsC5eq1ZGShL/mynvZKIiRG2KQejWvE/Yain5lO+QLKr72F7YbGLmcZbUaFDvIRFWhwEgrhtGvi+p/dtEoMf24npMD78BNcVDDzp7/eU+/5+0NUAJXpms+94yWCosJGrCMiZyBwF61CwAw/p0x0JxrHIfJsVM+0dlBi4q7QUe4GTOFsq1H3Zjep9CaXTQ3p8Cdx7jUL2Fh/fZEgEDLAuagvvdeA2Q==,iv:/PND5fZbeCziJ+8LgP9GZBr5XPXneIRpwam5VhkfY7E=,tag:SewFzg45ozKRjiiQiXLiGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrL1ZxdFZiUkk2SXNjR1pu
            aTJ2K3BwejFIUDVKNTZSZGJ1NXZPZlZmd1U4CmpmK2FIZmgreHFudDBibzNidmhF
            REI5NW93SXRPMURyQVRIajRoUjk5R0kKLS0tIGg1WUxuRTBJUHVqUmQwZVVwR3BX
            OUF2bVBYRHVDWXdyd0FHbDRDc3JsMWcKLpv9lfL7CzgPV2dO9EakfJQ1IINiPUc8
            EfvWjxQ7XmxihwGtLdBLCMcV9W2QLDHi+Cr0PvhLiv0PKCKYYiPIrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T16:56:38Z"
    mac: ENC[AES256_GCM,data:Pf0xhcc9oi6B7cQD8Ryb8EJ+e5U24RSjMTx/t4kcGVEugrvjOMO4G3axOYLdUKQOnCo8OyQdz0XELMJ9xOCpBA+uKD4n4k1kjbIpnsqC/EuUvMvgcGaLK4QuIfQ4yyQGvLZ+FwxOLCMoYnx4UnS1/FMlelx8SzrZpk2aTp37OEU=,iv:RodK/BtTnS3Df1Dj54+LAsJBne2+iBI0hdxjD0Ep33w=,tag:QRKJTN9k91KEicfflNJfNA==,type:str]
    version: 3.13.1
