apiVersion: v1
kind: Secret
metadata:
  name: tandoor
  namespace: tandoor
type: Opaque
stringData:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:ITl2A7OwhD10cnzRyeh0YBjHYY4SLnvBlagKMBda5QBddkXOAlZtuTgiMp9Cxhlj,iv:V7bxW/FAcWYytoAKkQPO6EDqYRytWs4MeGFpG378vvQ=,tag:PCuhxmgnidKb0vnL0bvaOw==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:TUVVJ70TZFMLtUE0Qs8jMasJcklR6Lr5rymQkNx26vW9E4zV358Ydg+olMQjDUvP6vY=,iv:NT9RXyJ8JWH6DrzqmgG368o4uCB3pbAe3B1YZij2Eoo=,tag:2eIwQhDX2L4TYs2d/vdSGQ==,type:str]
  SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:Ot7ccVb/h+pQyoi4ZqyjfqkjmU1haLRlBrMXzoklRCrpCBCrepfw7+yXcbPhTPpqhop20uNM7vmy6ODocsUok5moOZXSGvE8xgzkpD5MBNVLDcsC5eq1ZGShL/mynvZKIiRG2KQejWvE/Yain5lO+QLKr72F7YbGLmcZbUaFDvIRFWhwEgrhtGvi+p/dtEoMf24npMD78BNcVDDzp7/eU+/5+0NUAJXpms+94yWCosJGrCMiZyBwF61CwAw/p0x0JxrHIfJsVM+0dlBi4q7QUe4GTOFsq1H3Zjep9CaXTQ3p8Cdx7jUL2Fh/fZEgEDLAuagvvdeA2Q==,iv:/PND5fZbeCziJ+8LgP9GZBr5XPXneIRpwam5VhkfY7E=,tag:SewFzg45ozKRjiiQiXLiGw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZS9uVXM4cDArLzdhbjNn
        UnJzWGRlb1NXbUlyMHM1bFllUGxDc1AzZGhzCmtPcXFJcTJjczhNdkxPYytHMllS
        aVFId044WHdFZ1cwT2JBY2RpZ0t1S3cKLS0tIDV5V3dYQ0tNclRsQ1BINWNhSW05
        RlpWV1labFFCUjdTTlRjWXRLRkJzRncKSKb8ds/NfsDHBxkI6/dS4YPqWDCm9Zab
        fMaIAnsM9570qHQTIGTSj9+IlNUBX72c/AQ6MZQONE5cULGCPMz/Kw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNkhNdmZKT1FtMnkvMENn
        MUJVYTkxVWtaemRrYWV5d01iQ1I4aXFRVmdVCk9uNTBqUVFuYzRMdzFtb1NZRTFI
        YXhjTUplamVydE1nS2dYWXpNb0JGWGcKLS0tIDhBMEFwS2ZFNFppYmlKM0NkbXls
        cEdBUDNOOGs5VHkvT3V3cmlPRnhVaGsKUofflYGPqHJDD6MCwfzDWaE3RpwObT8q
        O7aXsovtxnZli4UeN+tOZ/edjH+92MpBhPBLulO8pnsngREuvYjFRg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T16:56:38Z"
  mac: ENC[AES256_GCM,data:Pf0xhcc9oi6B7cQD8Ryb8EJ+e5U24RSjMTx/t4kcGVEugrvjOMO4G3axOYLdUKQOnCo8OyQdz0XELMJ9xOCpBA+uKD4n4k1kjbIpnsqC/EuUvMvgcGaLK4QuIfQ4yyQGvLZ+FwxOLCMoYnx4UnS1/FMlelx8SzrZpk2aTp37OEU=,iv:RodK/BtTnS3Df1Dj54+LAsJBne2+iBI0hdxjD0Ep33w=,tag:QRKJTN9k91KEicfflNJfNA==,type:str]
  version: 3.13.1
