apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 1h
  chart:
    spec:
      chart: traefik
      version: "39.0.7" # https://github.com/traefik/traefik-helm-chart/releases
      sourceRef:
        kind: HelmRepository
        name: traefik
      interval: 1h
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    service:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "*.item.fyi,item.fyi"
    ports:
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        http:
          tls:
            enabled: true
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: true
    ingressRoute:
      dashboard:
        enabled: false  # managed via ingressroute-dashboard.yaml instead
