apiVersion: v1
kind: Secret
metadata:
  name: authentik-credentials
  namespace: authentik
type: Opaque
stringData:
  AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:OQ+lnUpm5yZp4Y5htfMN12SybUSD/k0y3R+gQngn3zw=,iv:IAmm2p20KJ/sNdNBDmNXXguUjmCEqh7DBsXltzTQA8M=,tag:3pex2YG37ghvRx8MjlIgdw==,type:str]
  AUTHENTIK_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:jkwa7G1VTHjHwMpHMDb94xnrmwtPsuRN1H8q+kzhXUE=,iv:aVcOxnsdbqXhK6A8bkev7ory/mgHYiTo9VtYzI/g8P0=,tag:5mVaUZ0LC+T1NcpEwidDbA==,type:str]
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:Y4Mhr10/w0pKx5J84oinmiInBnp09SWOXwXXc3Gm5tfgyZRvYWlivMoJ0ahmi7rkZwGX9JVHz8L6JlYSbYNooQ==,iv:jp3yGcUwfLP3A8NDy4eFDFH6poIXO6KTSdUpE+bJPRA=,tag:4k1hXYSZScz7TgmS9uCbqA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTXo0UHBsQzdKT3JOaWlM
        VkpuS3BwNWVDVmljN2RPVk1jSkluOU83TTBvCkhYS290WVZvTUxrRldGNERPc2gz
        ZzRrbmJaWFZuQVhrRWdFczcwT01zSlkKLS0tIGVXd0lIclZKSWJ0ZW4vd015aHdT
        WjV3NldZWVpienZldEdQRkNIcVkzaUkKOukuq1hJCv5N15HMMvGYT9nmyWOQeOwd
        BwK0+TT9h8BIc+L+O2GHKQCaSqiWB8Vow9VaAT/n0pMk17EKFQb86A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T16:56:38Z"
  mac: ENC[AES256_GCM,data:v7ycfULvSmuXhCQH5ACmG/5TM4zEmzUSQNLoahcyOuz38xVsKGznhMZ+49tW2Y+QBgpdMFx57WX9egPJD7FJQ/sAJwT1EFgZi7JZm81a2Gg6RGtmR5LGNAwIaPM9TA3Dld1uFmVpu3AJ2ZPAL2Ot659izxCOndENl+tCBUXS1n4=,iv:sBgOMMk44TP/U/c0HnUPlMnpPqRLeryVYOBniJtuwGU=,tag:vYnLDivg+9CQJjZ+/owJmg==,type:str]
  version: 3.13.1
