apiVersion: v1
data:
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:E56bw4fnC6lUtbOu71MyT0ou+AbVwhuopSZpzzfXmBXLJ1I0RyMw1VpYfPs=,iv:udnCtG+akPrtVgaK0PcpoXcWVPFXvvfZskwX0rCii3c=,tag:3H2CljGCC+EfxmiR2jXuWQ==,type:str]
    AUTHENTIK_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:cIo7WZR59+iwQbfJGPtpC3B/PIpCysdj46hs3uuR+Opj+hm7/kdF6JeDlm0=,iv:qAEdFcq/crKdnoghKJUe5KqFUvCMzChkhvnySS2IVD0=,tag:XSbzpjdCWK27VRSGbeUPTg==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:PgMjKxPq4Rftq6m1rpX7dvNqm1RwNBSesaq5XdLD52pG5wI7jyAmpfNAZEiayQQuCuJ6ZSC1vGZWBUpg3BV5QuFy9vn8jzYpCRZcTc+xN8mv5BUwLkfogQ==,iv:rq0yhIyhnMpFm6PnKRJRzmuwOCpaDqP5ZbrrWgYFB64=,tag:g/2VaXOFr5gg0XFpRUW0pA==,type:str]
kind: Secret
metadata:
    name: authentik-credentials
    namespace: authentik
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZFc5Zkh6N1lRU05LaXFR
            YmxDMWVyeHdWRnRlQUtxams5dFdudndKRTA4CjVUWXZxWUFrWk5kNkQ5dXNzQTMy
            Q3U1TGJ3cUplNmRwRklPUW1TSkYwRncKLS0tIHJ5VHBRdGNHc3lrK0w0aElrZVdl
            dllIZW15OTBDTzk4anpRVEtzVmUxTFkKZQM98NSPsyWxxrpxtrRjsaxKYE0b8ckt
            6HU6ZJOtbG98P9/Or7Lm5TKFdk0d8qiYMgGjjLY9MURkgbsyzMFVLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:Llv+T57ZlYL0AZlqT4Xb6nDiMGHU4WkBO2RsIkxkNatzpCj4YpLYPK1/ZalIsdwesrRzR97zDBh9McUCRniEFv+AmRa8wRvqBW+X20/cJwFlvqUeTLnFLiNtCGggBFWRIsmMgAn5X+lYdgXFxh67G6DN8/ZfsTn7kzKLOlV1XXY=,iv:Dem0irQ8eC7fWYm1oPgIWU7/5Pr0pfihbypdbnUMhI4=,tag:ibVbq7RkpWCV6LGZavZMRg==,type:str]
    version: 3.13.1
