---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-blueprints-secret
  namespace: authentik
spec:
  encryptedData:
    user-akmin.yaml: AgBQmiNiaktW/IilQOOLAjiMvCd4I+8RmbEocnQwwNWyPyM4un85KbNJTXN8So3mxYyOwr8ULT7ORCap0ctx3d8pfg8UXwmJU0LGkIyn+rUmIEB0DBv+9LpwIyHBh/4KdVh5CP8DYNXxLAKlg37GbA6kepEovy5ZV6VOXYplyYZkcK27AS53c81ulQT9n30ygW7aDS0PDfkIQ95R0QHzC8IYZxXxNQ8yrLW/rAC04phPXAaNXbp0cle7EfUQJaCREddYwGUEURWTzNv1Tg14iA7Iwbwx5L37ElDYO2tC8AjxEGeP9zvDe7yxZ+1RTr8Y7wwmR8/tZgsOs3ExiyjphbDnEN2+7jRoC5pz7K/D2EtogzZDOY2ZEZ7dBjxazUMDgPu8JDgvRn3Ldf56F33gj9JR1bMtCPSjBejielVmGkA/s0kiXtUfyHslsqqAffAxgZYAlAQXCW8/Xuk5JUl8jcvd4HM34jvqKpNntMID0a7f4RYKuwbk26ih3WBRMEEgBr31Osz01kIFnIJFTd4gR+fFmpzlkexqQ+OdFoozxa940zBfuMCcSqi63dESp0PrnHgr1dvFY84LoFMr6jQAAb+2/ieCFUXVqm2nkCes/61p0bIzI3swp74aGKWvSkq7reeafydV5KIAhFtGPKBUC4BzedEWdWvEy0uWuKD7PqRykcKDhj0IMCqgskBaY9odjITI+ymKq/i/oD3I3dXicfcZvHterRQyGP6G7W1Pk83e6OxTqn3Kf0Kun8nX5JutPeHMkfrQAx8xvLKv0IXV2iFYEEJhbllqJW/p52bpn6dvZogcoYw102GnpyraIEa2WBy/cq1TtJDURXR0uB+4r2xXpGpkRMTBQkvhlzsRNarCK7ix6nYtV/00+uJNlEV/MZqqLgU0V26mimEHDVN3yYrTNBUsWzMQztSwwVhWRHIFhrNLZnU3Ojk07ghRGNIpuYdknhsSPYTA7wujgunG250WRVEPVNjL8KTSYpnoObid0iHXtMAHp1HHZtg9REi87OhQPDMUYr5mp0WLhAdW0qxFMlhFXbQX1xoU74LefhYsjWfcqsi4fDwWsBvHcll207KaFSmbBqjSuYXASiIzFlvvMUc=
  template:
    metadata:
      name: authentik-blueprints-secret
      namespace: authentik
    type: Opaque
