---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-blueprints-secret
  namespace: authentik
spec:
  encryptedData:
    grafana-oauth2.yaml: AgCrx3OxXUEX66G+CoqtQdos1+sN51qncjwA/dwkH9tDiQnTn9g5qbAVeoCfisIn8aBhgeLc/rFnYol4T6mm26nUUgTY/1Ouk+DtrIRPnAV8wgD0MZA4hXCe/8jX8qeU9gYBntaEirFrBIzENENaEwted1r6dbRRA/3+8wf7BDbtVpT0tcvTnKshzhmehlCFYgYrhFopYyCpHaikRKBpZaZl/S3jaWzzLSi2jODRmOGWr7hUolHdcXBailfpLNiH5zSOAi/PS4/OwslwNS6x1wCy3EhoLAcKA3BFQBLTpZ9s55Xe3HrS8+F1trrjmwE5JwW40HBFqkzF/xZdw43ltF130Ye91EdRem66Jo+KEaxC7N5RiVFBIUfAHFi4l/NXTDDxW/uwUl4WJBCwJ8W1fKOjpG2Re7uvaD7CZ9if6UMkMabv/ZJab2ALOc5v3P3hOp/F4WmXEiua/xJjChfkCXW02I1eH6kD2CcMbCvRa7dZapW8PIoIaf+fRiDfVOqi9AommUyeY6qZoKJtsPEHFPODmgEslA4ku66q5+tWVYig0axtcXXBL7ikZrn/JTUGysb+/s0JAmZo5Iku0CZm7OnVTVrAL23fUD08VXFu1oYrmwc8yUhQ+ouRj8/Wqk4wg1p+PBZjtxfN1QJLFQc/F/pCGfia8w8LOH9HfKDWHW1USS63Z/SbL5h0PYItHkqeZPK+qNOk/caDith3sn2aUhNnj5Yxc/hRBsdGXzXbx9/ES4jyAQds4Qr9nVS+N6cBWPslqrCP2iTw54ojzfmT1olHHZsa5tCMaBjmavBQvx4UrToeAMZtdZ72GPk8T+v5IugrYyMAfF/RYZVks1oFbOBbjhpMZKDE09fj7RJfkty7li6fPbAu+XXR5aZLMMpm4WPw36vwkD2tYaaKmLIfzTSegtHsc1I3M6a1n/Xoy5ESnrKYMNNnzSvxCNAxqZHc8CapNThHTkJjgt2AE0lPOVXuWkN+jeIm/TyrVWf7rHds0AutR/Tnam9aa2pwdlvcocwELaHtIwOd8wlJTcOba62XssuhX+/1dRJVuaNLbMMULgP8FcF21V+8GO1tJRKVZqOaaz2vkqowvUuOaRJrOo0RyVCGHlPBgTOM28MBErLROVjGKficTpe1sCYL/0Cuyc2cJwJUUGS6fiZemHZqG0adx5GMpeE2utYsjKFpnpqsFMcZdhf+VptO772KnqPxSH/SBQqw9YWq/VlxsQc+E1dUMU/O/fpl5JPBKFG8hfA68yjthw/Arvcvjnk9tXNfXQThHZWdZYQNe3xB4tpL0ZesY8be+mh+rm7X+SBAIBVuwINxyypQ5weGsp8afLZ3horhhyUi5bUWG+6a0+FDuFdW4C7JRTxE+FNyYHcpPwOSQF89EdkY8WU7H98irqhhH3YMD/4rKcJgoE6aKYmR8xpzNQawZUAjsLOS6OP/rRLz8EVI8+lmFsy7TC+F7xkaHECiv/CpEpraN42tILWnlcsnzB6BMp8lQj9Xhz+bPIjIXI23NRC4htKHKI7S3GM3eDToygwzpL5nAJwa7xuibToGvCXSmosP9dTNj/d/MuNvP8ASHPGBBp/HTT5JNSDZyTr19ULFYckfz8vdz1cpYqHUyv4CBQxfwEMGP6Wh01/IaEdHWpnCU5Ab3lnQY2Crm00awinlDGV6BtU+FeG0CIr8/k+uxNQTdZFHQHkBJBP2C2A79+GaRkbkJl97jUVYPSBC1B+yKeV0XUNUs69TDetEUCm8SHbMeaZJcP4I6lzSZ51LMlOCfYgFaL/H3i7HurxHABc8pACxb0c3heiisJlMD3JJIsE+Z7YyihOm/1lBI/ts9bjWexGeRQ7DemRAjowzFgwCiscpvLHRg/4RmldkwO+IBU9PoJZMZ/g3xO95DOB1GNz03aYURe6YoOuhlU9HY+nTcDIhwqp/qgeVhBDSoT1R6LkjHsbUaZVjRDBcZ/VZJw6rimRnt/2C3fZ5Cw5hJnBmGePyETHqPUqe4nRTABQQaGmHLocLISf+zmmVswPGln53EHFJ4LUf1Nv8KskLpv0BqQvr1jEoMV/s1t51LLP5YnOuHkWPiTiDqxUS+hcan66l1/aZuSsIgShBKV5iaVGG+5UxebX8xJWhw/2h9jc9Ys1NbkQ1w7gK8mNDcEh7B8iRsewfecg7xxrGWrjd3Elnh18HqseQ7Zya1zpKbIUTANfN3YMSXv9Tx/lknGOgmO7uZCsFMrXGdAvXsam4hHwNQcVBBhVJoTtojcqbOXWgdJJR3ZiF0ngO8rxjICMTZv8cw+/umU1kS1uBJQmqkd65g3mb4CxFKfWm7unicYqSa3VIQavezEOXlaSwbMwTHNMNQdKGBRjMLOA6UwRHnWjwNwpo1s0dBm8wZxH5m42aK6Y3lFUu2J233ovUrn3X/5MwFyzUeUP9OAlM7tjAQ5FlQjQiKisk0FopGHHargRge49bx27VNEPVVCZ7ysW/UBYNotYGyIuSlct8aV9J+fXQzf9uNqRdwCKwAA==
    user-akmin.yaml: AgBQmiNiaktW/IilQOOLAjiMvCd4I+8RmbEocnQwwNWyPyM4un85KbNJTXN8So3mxYyOwr8ULT7ORCap0ctx3d8pfg8UXwmJU0LGkIyn+rUmIEB0DBv+9LpwIyHBh/4KdVh5CP8DYNXxLAKlg37GbA6kepEovy5ZV6VOXYplyYZkcK27AS53c81ulQT9n30ygW7aDS0PDfkIQ95R0QHzC8IYZxXxNQ8yrLW/rAC04phPXAaNXbp0cle7EfUQJaCREddYwGUEURWTzNv1Tg14iA7Iwbwx5L37ElDYO2tC8AjxEGeP9zvDe7yxZ+1RTr8Y7wwmR8/tZgsOs3ExiyjphbDnEN2+7jRoC5pz7K/D2EtogzZDOY2ZEZ7dBjxazUMDgPu8JDgvRn3Ldf56F33gj9JR1bMtCPSjBejielVmGkA/s0kiXtUfyHslsqqAffAxgZYAlAQXCW8/Xuk5JUl8jcvd4HM34jvqKpNntMID0a7f4RYKuwbk26ih3WBRMEEgBr31Osz01kIFnIJFTd4gR+fFmpzlkexqQ+OdFoozxa940zBfuMCcSqi63dESp0PrnHgr1dvFY84LoFMr6jQAAb+2/ieCFUXVqm2nkCes/61p0bIzI3swp74aGKWvSkq7reeafydV5KIAhFtGPKBUC4BzedEWdWvEy0uWuKD7PqRykcKDhj0IMCqgskBaY9odjITI+ymKq/i/oD3I3dXicfcZvHterRQyGP6G7W1Pk83e6OxTqn3Kf0Kun8nX5JutPeHMkfrQAx8xvLKv0IXV2iFYEEJhbllqJW/p52bpn6dvZogcoYw102GnpyraIEa2WBy/cq1TtJDURXR0uB+4r2xXpGpkRMTBQkvhlzsRNarCK7ix6nYtV/00+uJNlEV/MZqqLgU0V26mimEHDVN3yYrTNBUsWzMQztSwwVhWRHIFhrNLZnU3Ojk07ghRGNIpuYdknhsSPYTA7wujgunG250WRVEPVNjL8KTSYpnoObid0iHXtMAHp1HHZtg9REi87OhQPDMUYr5mp0WLhAdW0qxFMlhFXbQX1xoU74LefhYsjWfcqsi4fDwWsBvHcll207KaFSmbBqjSuYXASiIzFlvvMUc=
  template:
    metadata:
      name: authentik-blueprints-secret
      namespace: authentik
    type: Opaque
# apiVersion: v1
# kind: Secret
# metadata:
#   name: authentik-blueprints-secret
#   namespace: authentik
# type: Opaque
# stringData:
#   grafana-oauth2.yaml: |
#     version: 1
#     metadata:
#       name: grafana oauth2 provider
#       labels:
#         blueprints.goauthentik.io/instantiate: "true"
#     entries:
#       # oauth2 provider for grafana
#       - model: authentik_providers_oauth2.oauth2provider
#         id: grafana-provider
#         identifiers:
#           name: Grafana
#         attrs:
#           client_id: grafana
#           client_secret: fixme
#           client_type: confidential
#           redirect_uris:
#             - url: https://grafana.item.fyi/login/generic_oauth
#               matching_mode: strict
#           authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
#           invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
#           signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
#           property_mappings:
#             - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
#             - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
#             - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
#       # application linked to the oauth2 provider
#       - model: authentik_core.application
#         identifiers:
#           slug: grafana
#         attrs:
#           name: Grafana
#           provider: !KeyOf grafana-provider
#           meta_launch_url: https://grafana.item.fyi
#   user-akmin.yaml: |
#     version: 1
#     metadata:
#       name: akmin user
#       labels:
#         blueprints.goauthentik.io/instantiate: "true"
#     entries:
#       - model: authentik_core.user
#         state: present
#         identifiers:
#           username: akmin
#         attrs:
#           name: akmin
#           password: fixme
#           path: users
#           is_active: true