apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      version: "2026.2.2" # https://artifacthub.io/packages/helm/goauthentik/authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
      interval: 1h
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: authentik-credentials
      valuesKey: AUTHENTIK_SECRET_KEY
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-credentials
      valuesKey: AUTHENTIK_POSTGRESQL_PASSWORD
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-credentials
      valuesKey: AUTHENTIK_POSTGRESQL_PASSWORD
      targetPath: postgresql.auth.password
    - kind: Secret
      name: authentik-credentials
      valuesKey: AUTHENTIK_BOOTSTRAP_PASSWORD
      targetPath: authentik.bootstrap.password
  values:
    authentik:
      bootstrap:
        email: ""
    server:
      podAnnotations:
        configmap.reloader.stakater.com/reload: authentik-blueprints
        secret.reloader.stakater.com/reload: authentik-blueprints-secret
      ingress:
        enabled: false # using IngressRoute instead
      env:
        # reduces memory (~150-200MB) but docs recommend min 2 workers for single-replica:
        # https://docs.goauthentik.io/install-config/configuration/#authentik_web__workers
        - name: AUTHENTIK_WEB__WORKERS
          value: "1"
      resources:
        requests:
          cpu: 50m
          memory: 500Mi
    worker:
      podAnnotations:
        configmap.reloader.stakater.com/reload: authentik-blueprints
        secret.reloader.stakater.com/reload: authentik-blueprints-secret
      resources:
        requests:
          cpu: 50m
          memory: 600Mi
    postgresql:
      enabled: true
      primary:
        persistence:
          storageClass: nfs-zfs
        extendedConfiguration: |
          max_connections = 50
    blueprints:
      configMaps:
        - authentik-blueprints
      secrets:
        - authentik-blueprints-secret
