apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
  namespace: authentik
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Authentik"
    gethomepage.dev/description: "Identity provider"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "authentik.png"
    gethomepage.dev/href: "https://auth.item.fyi"
    gethomepage.dev/siteMonitor: "http://authentik-server.authentik.svc.cluster.local"
    gethomepage.dev/widget.type: "authentik"
    gethomepage.dev/widget.url: "http://authentik-server.authentik.svc.cluster.local"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_AUTHENTIK_TOKEN}}"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`auth.item.fyi`)
      services:
        - name: authentik-server
          port: 80
  tls: {}
