apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - authentik-sealed-secret.yaml
  - blueprint-configmap.yaml
  - blueprint-sealed-secret.yaml
  - ingressroute.yaml
