---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia
  namespace: authelia
spec:
  encryptedData:
    JWT_SECRET: AgAt5+mnSNIWLR7tQKJF5PbccNGCbVt4oxubTmMWomE76lSLHjVCLgJYNjgHl42/HrRJXBUQS/AifV/HFoOPOg5pSaPikmvrEZQ9wakt8Q5XatW4lfownWpoQsawAfxh3TCs61lCWcOIadt7DcoRta2ko0J22ujGOz09VJgAW8Y0gt3AnKOBalNF5TBEkfMYXbHZejdtpLwutGLT1JTCwRAbLCUmfcHE+7XUmFAb3ZPiUEnb9wBO37msVyB2cj1psYQblnaFGf/JQdECv2i7ReEOiIaJaGrj43wcjmXs3kpHQWJ3HKLmZJE1ufb5cah6a9awSd8xCxuSnlFpbOaTuCXIDjK4Tsh6CBoQXV6D9wJUg5zWoVqTB97TOJchSHEg1CWj/9IVBZ6RS6mzoB5C60/hjuDCcPApeloEN23ZrpLEtEUEnu77MLuAXtd+voOObW6yBQ502VvZUzweVrpOkyCiuJgHEGbYNyAufuwdr9ExrNV2ScoSfrrHIQdBTUsjL8Ml8MVIshxhSODrKv1GlNiTCPJwj1KPb+7yX9G90877vXKIGFRMKXAmjkh1UMM51B47eTiWzfvsPKOXelSRMKlidWC+X2jN73zNceaNj8bpBP2Iq2cXoRrIl/cgJm/amy/UBuEIHzgFP2VDGo+wn4BZW1nsDwVJq75VI2eObQMUtuq3PJv/bmGvXfgocSktpx88TNUc03ncmKjDNifBUcCEOi+3gZUta/R6Wj9N3EODhtz6zfXqIa7jAzKmMhA8tdBukzE7Z8TGkfAh8WUvLOFv
    SESSION_SECRET: AgBZ9ZP24EK/8agdaH1kIehhOkwauZf864zy+M/TkDR+blHbzdJxxWVEvMwHPGc15Ds3rBmM42oH0RXkiCXAuUpspn4h9mZFBXrPAQsMp9h15YlHG7RXAQLLWW2wYG5FkTDKn/220ur7eYRfbxbjKovsSmhdbxa8j5KhoUdTU4p1DbRFhMRyeamqCvsj8vaOqpClfaIIDO1IhWnPKaDG3NgXEWS8OKKMK+L/uYinhfmBDgyVX/1RoiD93CrJ0o12bKtaNkc/U7FEzwAVfamW3FPrAyOaTM+QHWptQs/5ps3EiG/jMGKqq5xoteMyCikBL8i7J5begJNyvQl7yrHTOS4NeChAquqSeO27t4hO2/E/3ZI+0lZ4VTXLF46E9b7Oeat7pkMCHWDRdj6udLbaeBsrbIzfPha6+EF/LbLT086HTO8iXJKGUHlvjsU4ae1WgMw5X6/BozHC+0zy1YuW9lgt7pD20eq3i7qREfTvDaUykwwQ3qwSBvioMxDRcpT4xnNHUbWg/C02Gfi5npaMwizIfiuZNpNY2lr8xAzL8mgJKC8Ea00qNg8jV+3ROc2AxKSI9kiiFfOvpPwrsAQ0fKINMy+hbjXO3ufBecYXBmX1oAK7KfHVLJOtMC+Ayo4IBW0yA6hsBJcFZ2U0bOpwy0SIsRjs7rfMke4GFs1T6eEZ9rIB49JKNStsCHBgARVMkIkgRbq0xNsQGi+kHI7qubwx6mHbu/HHQDxRn5I0TF957vM0jmK84FSEVV7yVaG/xWaLgGmsFYomS0+gJMcW8VHe
    STORAGE_ENCRYPTION_KEY: AgA4sJYkGNsishIz3w9rm3T8LWs+ytw2Vdhn853ZNBfZFC60bJrLDVU+JsGNuwVJKbUjzWR5YdUZKUy7uab0ZzZ5ZfE0r2/AI96ZBmM2uVlMbs5oAu/Gwbw2TfNAExGmNHtQCgjRp08ySGCDOtT0TZyFO6dA8wGYZCohakzUtVWJzqshl7CHwHW1fB+aByoeiHtmuNhOW+Qn1IdtFCVNb382sAAA2WuEKceydzaHrsOSYVPvRkW/0iWOIRWkHVWmXBvTG0z+6P5UwvMbJQFGGv65cRRTM4ZY4LyPLTbhIIHjqI/wkquF7PoXKk6/oZyIY8ggTxm2Owj4SJKTR1Ndl4GP3dEwhtvhvgyBEqbXaJy11C3GFe+vOLsbxxVb8PAEBFkoG8nohPF9DD5Pse5hnZIXlam6hrw7G6A/rv/5mha0F00b9AcykaRdr5hcAnamjmZVzmqX1qznGsAN04D2Rp3hfMz05WQ5u16/EI9+VeVvejQZOue5VRO1HVqVsbKQWeeZFYQCKbxYwUwygCA4bRfHIlaVjmaSShAquIlLWDnHuPIO/DdSpw2+on9PSkko4U7VWp0NtbmQ45+YHS+W7K0aPVyskqf0vuZb8cAMfJJK18/yhwkve6o43+aXwUAo504NnMagwr0kDOi8fwRo+ZmblZphMhvCrM1WEPOl+aQ1s+ebrcJKdY5c5YPyjKf7KtJo/4AmjfJCXJAEKzhpp0gEK/enbE+rBHqAqrmTbOMZ96SkvMcK7zUZ5reUJPiN6IyYH5up4Lk9BqeTWlH1X2MF
  template:
    metadata:
      name: authelia
      namespace: authelia
    type: Opaque
# apiVersion: v1
# kind: Secret
# metadata:
#   name: authelia
#   namespace: authelia
# type: Opaque
# stringData:
#   JWT_SECRET: fixme
#   SESSION_SECRET: fixme
#   STORAGE_ENCRYPTION_KEY: fixme
