apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia
  namespace: authelia
data:
  configuration.yml: |
    theme: auto

    server:
      address: tcp://0.0.0.0:9091/

    log:
      level: info

    authentication_backend:
      file:
        path: /config/users.yml

    totp:
      issuer: item.fyi

    webauthn:
      display_name: item.fyi

    session:
      cookies:
        - name: authelia_session
          domain: item.fyi
          authelia_url: https://auth.item.fyi
          expiration: 12h
          inactivity: 1h
          remember_me: 1M

    storage:
      local:
        path: /data/db.sqlite3

    access_control:
      default_policy: one_factor

    notifier:
      filesystem:
        filename: /data/notifications.txt

  users.yml: |
    users:
      akmin:
        disabled: false
        displayname: "akmin"
        password: "$argon2id$v=19$m=65536,t=3,p=4$9v/0TpNg/bMkWxnspQiSWA$iSCle4asxDliDbEEuZwxJ4AmI3Bhz9bRGjGei/qjYM8"
        email: ""
        groups:
          - admins
