apiVersion: v1
kind: Namespace
metadata:
  name: authelia
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-data
  namespace: authelia
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-zfs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: authelia
  labels:
    app.kubernetes.io/name: authelia
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: authelia
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authelia
      annotations:
        configmap.reloader.stakater.com/reload: "authelia"
    spec:
      enableServiceLinks: false
      containers:
        - name: authelia
          image: authelia/authelia:4.39@sha256:0c824dcab1ae97c56bf673c5e77fe8cc6bcd400564555140cc8002a12c6b6463
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
          env:
            - name: AUTHELIA_SESSION_SECRET_FILE
              value: /app/secrets/SESSION_SECRET
            - name: AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
              value: /app/secrets/STORAGE_ENCRYPTION_KEY
            - name: AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE
              value: /app/secrets/JWT_SECRET
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: secrets
              mountPath: /app/secrets
              readOnly: true
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: 32Mi
              cpu: 25m
            limits:
              memory: 256Mi
              cpu: 500m
          readinessProbe:
            httpGet:
              path: /api/health
              port: 9091
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 9091
            initialDelaySeconds: 15
            periodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: authelia
        - name: secrets
          secret:
            secretName: authelia
        - name: data
          persistentVolumeClaim:
            claimName: authelia-data
---
apiVersion: v1
kind: Service
metadata:
  name: authelia
  namespace: authelia
  annotations:
    gatus.home-operations.com/endpoint: |
      alerts:
        - type: pushover
spec:
  selector:
    app.kubernetes.io/name: authelia
  ports:
    - port: 9091
      targetPort: 9091
      name: http
