// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class BootstrapGit extends pulumi.CustomResource {
    /**
     * Get an existing BootstrapGit resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BootstrapGitState, opts?: pulumi.CustomResourceOptions): BootstrapGit {
        return new BootstrapGit(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'flux:index/bootstrapGit:BootstrapGit';

    /**
     * Returns true if the given object is an instance of BootstrapGit.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BootstrapGit {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BootstrapGit.__pulumiType;
    }

    /**
     * The internal cluster domain. Defaults to `cluster.local`
     */
    declare public readonly clusterDomain: pulumi.Output<string>;
    /**
     * Toolkit components to include in the install manifests. Defaults to `[source-controller kustomize-controller
     * helm-controller notification-controller]`
     */
    declare public readonly components: pulumi.Output<string[]>;
    /**
     * List of extra components to include in the install manifests.
     */
    declare public readonly componentsExtras: pulumi.Output<string[] | undefined>;
    /**
     * Delete manifests from git repository. Defaults to `true`.
     */
    declare public readonly deleteGitManifests: pulumi.Output<boolean>;
    /**
     * Use the existing secret for flux controller and don't create one from bootstrap
     */
    declare public readonly disableSecretCreation: pulumi.Output<boolean | undefined>;
    /**
     * When enabled, the Flux manifests will be extracted from the provider binary instead of being downloaded from GitHub.com.
     * Defaults to `false`.
     */
    declare public readonly embeddedManifests: pulumi.Output<boolean>;
    /**
     * Kubernetes secret name used for pulling the toolkit images from a private registry.
     */
    declare public readonly imagePullSecret: pulumi.Output<string | undefined>;
    /**
     * Interval at which to reconcile from bootstrap repository. Defaults to `1m0s`.
     */
    declare public readonly interval: pulumi.Output<string>;
    /**
     * Keep the namespace after uninstalling Flux components. Defaults to `false`.
     */
    declare public readonly keepNamespace: pulumi.Output<boolean>;
    /**
     * Kustomization to override configuration set by default.
     */
    declare public readonly kustomizationOverride: pulumi.Output<string | undefined>;
    /**
     * Log level for toolkit components. Defaults to `info`.
     */
    declare public readonly logLevel: pulumi.Output<string>;
    /**
     * The install manifests are built from a GitHub release or kustomize overlay if using a local path. Defaults to
     * `https://github.com/fluxcd/flux2/releases`.
     *
     * @deprecated Deprecated
     */
    declare public readonly manifestsPath: pulumi.Output<string | undefined>;
    /**
     * The namespace scope for install manifests. Defaults to `flux-system`. It will be created if it does not exist.
     */
    declare public readonly namespace: pulumi.Output<string>;
    /**
     * Deny ingress access to the toolkit controllers from other namespaces using network policies. Defaults to `true`.
     */
    declare public readonly networkPolicy: pulumi.Output<boolean>;
    /**
     * Path relative to the repository root, when specified the cluster sync will be scoped to this path (immutable).
     */
    declare public readonly path: pulumi.Output<string | undefined>;
    /**
     * Configures the GitRepository source to initialize and include Git submodules in the artifact it produces.
     */
    declare public readonly recurseSubmodules: pulumi.Output<boolean | undefined>;
    /**
     * Container registry where the toolkit images are published. Defaults to `ghcr.io/fluxcd`.
     */
    declare public readonly registry: pulumi.Output<string>;
    /**
     * Container registry credentials in the format 'user:password'
     */
    declare public readonly registryCredentials: pulumi.Output<string | undefined>;
    /**
     * Git repository files created and managed by the provider.
     */
    declare public /*out*/ readonly repositoryFiles: pulumi.Output<{[key: string]: string}>;
    /**
     * Name of the secret the sync credentials can be found in or stored to. Defaults to `flux-system`.
     */
    declare public readonly secretName: pulumi.Output<string>;
    declare public readonly timeouts: pulumi.Output<outputs.BootstrapGitTimeouts | undefined>;
    /**
     * List of toleration keys used to schedule the components pods onto nodes with matching taints.
     */
    declare public readonly tolerationKeys: pulumi.Output<string[] | undefined>;
    /**
     * Flux version. Defaults to `v2.8.3`. Has no effect when `embedded_manifests` is enabled.
     */
    declare public readonly version: pulumi.Output<string>;
    /**
     * If true watch for custom resources in all namespaces. Defaults to `true`.
     */
    declare public readonly watchAllNamespaces: pulumi.Output<boolean>;

    /**
     * Create a BootstrapGit resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: BootstrapGitArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BootstrapGitArgs | BootstrapGitState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as BootstrapGitState | undefined;
            resourceInputs["clusterDomain"] = state?.clusterDomain;
            resourceInputs["components"] = state?.components;
            resourceInputs["componentsExtras"] = state?.componentsExtras;
            resourceInputs["deleteGitManifests"] = state?.deleteGitManifests;
            resourceInputs["disableSecretCreation"] = state?.disableSecretCreation;
            resourceInputs["embeddedManifests"] = state?.embeddedManifests;
            resourceInputs["imagePullSecret"] = state?.imagePullSecret;
            resourceInputs["interval"] = state?.interval;
            resourceInputs["keepNamespace"] = state?.keepNamespace;
            resourceInputs["kustomizationOverride"] = state?.kustomizationOverride;
            resourceInputs["logLevel"] = state?.logLevel;
            resourceInputs["manifestsPath"] = state?.manifestsPath;
            resourceInputs["namespace"] = state?.namespace;
            resourceInputs["networkPolicy"] = state?.networkPolicy;
            resourceInputs["path"] = state?.path;
            resourceInputs["recurseSubmodules"] = state?.recurseSubmodules;
            resourceInputs["registry"] = state?.registry;
            resourceInputs["registryCredentials"] = state?.registryCredentials;
            resourceInputs["repositoryFiles"] = state?.repositoryFiles;
            resourceInputs["secretName"] = state?.secretName;
            resourceInputs["timeouts"] = state?.timeouts;
            resourceInputs["tolerationKeys"] = state?.tolerationKeys;
            resourceInputs["version"] = state?.version;
            resourceInputs["watchAllNamespaces"] = state?.watchAllNamespaces;
        } else {
            const args = argsOrState as BootstrapGitArgs | undefined;
            resourceInputs["clusterDomain"] = args?.clusterDomain;
            resourceInputs["components"] = args?.components;
            resourceInputs["componentsExtras"] = args?.componentsExtras;
            resourceInputs["deleteGitManifests"] = args?.deleteGitManifests;
            resourceInputs["disableSecretCreation"] = args?.disableSecretCreation;
            resourceInputs["embeddedManifests"] = args?.embeddedManifests;
            resourceInputs["imagePullSecret"] = args?.imagePullSecret;
            resourceInputs["interval"] = args?.interval;
            resourceInputs["keepNamespace"] = args?.keepNamespace;
            resourceInputs["kustomizationOverride"] = args?.kustomizationOverride;
            resourceInputs["logLevel"] = args?.logLevel;
            resourceInputs["manifestsPath"] = args?.manifestsPath;
            resourceInputs["namespace"] = args?.namespace;
            resourceInputs["networkPolicy"] = args?.networkPolicy;
            resourceInputs["path"] = args?.path;
            resourceInputs["recurseSubmodules"] = args?.recurseSubmodules;
            resourceInputs["registry"] = args?.registry;
            resourceInputs["registryCredentials"] = args?.registryCredentials;
            resourceInputs["secretName"] = args?.secretName;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["tolerationKeys"] = args?.tolerationKeys;
            resourceInputs["version"] = args?.version;
            resourceInputs["watchAllNamespaces"] = args?.watchAllNamespaces;
            resourceInputs["repositoryFiles"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(BootstrapGit.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering BootstrapGit resources.
 */
export interface BootstrapGitState {
    /**
     * The internal cluster domain. Defaults to `cluster.local`
     */
    clusterDomain?: pulumi.Input<string>;
    /**
     * Toolkit components to include in the install manifests. Defaults to `[source-controller kustomize-controller
     * helm-controller notification-controller]`
     */
    components?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * List of extra components to include in the install manifests.
     */
    componentsExtras?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Delete manifests from git repository. Defaults to `true`.
     */
    deleteGitManifests?: pulumi.Input<boolean>;
    /**
     * Use the existing secret for flux controller and don't create one from bootstrap
     */
    disableSecretCreation?: pulumi.Input<boolean>;
    /**
     * When enabled, the Flux manifests will be extracted from the provider binary instead of being downloaded from GitHub.com.
     * Defaults to `false`.
     */
    embeddedManifests?: pulumi.Input<boolean>;
    /**
     * Kubernetes secret name used for pulling the toolkit images from a private registry.
     */
    imagePullSecret?: pulumi.Input<string>;
    /**
     * Interval at which to reconcile from bootstrap repository. Defaults to `1m0s`.
     */
    interval?: pulumi.Input<string>;
    /**
     * Keep the namespace after uninstalling Flux components. Defaults to `false`.
     */
    keepNamespace?: pulumi.Input<boolean>;
    /**
     * Kustomization to override configuration set by default.
     */
    kustomizationOverride?: pulumi.Input<string>;
    /**
     * Log level for toolkit components. Defaults to `info`.
     */
    logLevel?: pulumi.Input<string>;
    /**
     * The install manifests are built from a GitHub release or kustomize overlay if using a local path. Defaults to
     * `https://github.com/fluxcd/flux2/releases`.
     *
     * @deprecated Deprecated
     */
    manifestsPath?: pulumi.Input<string>;
    /**
     * The namespace scope for install manifests. Defaults to `flux-system`. It will be created if it does not exist.
     */
    namespace?: pulumi.Input<string>;
    /**
     * Deny ingress access to the toolkit controllers from other namespaces using network policies. Defaults to `true`.
     */
    networkPolicy?: pulumi.Input<boolean>;
    /**
     * Path relative to the repository root, when specified the cluster sync will be scoped to this path (immutable).
     */
    path?: pulumi.Input<string>;
    /**
     * Configures the GitRepository source to initialize and include Git submodules in the artifact it produces.
     */
    recurseSubmodules?: pulumi.Input<boolean>;
    /**
     * Container registry where the toolkit images are published. Defaults to `ghcr.io/fluxcd`.
     */
    registry?: pulumi.Input<string>;
    /**
     * Container registry credentials in the format 'user:password'
     */
    registryCredentials?: pulumi.Input<string>;
    /**
     * Git repository files created and managed by the provider.
     */
    repositoryFiles?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Name of the secret the sync credentials can be found in or stored to. Defaults to `flux-system`.
     */
    secretName?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.BootstrapGitTimeouts>;
    /**
     * List of toleration keys used to schedule the components pods onto nodes with matching taints.
     */
    tolerationKeys?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Flux version. Defaults to `v2.8.3`. Has no effect when `embedded_manifests` is enabled.
     */
    version?: pulumi.Input<string>;
    /**
     * If true watch for custom resources in all namespaces. Defaults to `true`.
     */
    watchAllNamespaces?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a BootstrapGit resource.
 */
export interface BootstrapGitArgs {
    /**
     * The internal cluster domain. Defaults to `cluster.local`
     */
    clusterDomain?: pulumi.Input<string>;
    /**
     * Toolkit components to include in the install manifests. Defaults to `[source-controller kustomize-controller
     * helm-controller notification-controller]`
     */
    components?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * List of extra components to include in the install manifests.
     */
    componentsExtras?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Delete manifests from git repository. Defaults to `true`.
     */
    deleteGitManifests?: pulumi.Input<boolean>;
    /**
     * Use the existing secret for flux controller and don't create one from bootstrap
     */
    disableSecretCreation?: pulumi.Input<boolean>;
    /**
     * When enabled, the Flux manifests will be extracted from the provider binary instead of being downloaded from GitHub.com.
     * Defaults to `false`.
     */
    embeddedManifests?: pulumi.Input<boolean>;
    /**
     * Kubernetes secret name used for pulling the toolkit images from a private registry.
     */
    imagePullSecret?: pulumi.Input<string>;
    /**
     * Interval at which to reconcile from bootstrap repository. Defaults to `1m0s`.
     */
    interval?: pulumi.Input<string>;
    /**
     * Keep the namespace after uninstalling Flux components. Defaults to `false`.
     */
    keepNamespace?: pulumi.Input<boolean>;
    /**
     * Kustomization to override configuration set by default.
     */
    kustomizationOverride?: pulumi.Input<string>;
    /**
     * Log level for toolkit components. Defaults to `info`.
     */
    logLevel?: pulumi.Input<string>;
    /**
     * The install manifests are built from a GitHub release or kustomize overlay if using a local path. Defaults to
     * `https://github.com/fluxcd/flux2/releases`.
     *
     * @deprecated Deprecated
     */
    manifestsPath?: pulumi.Input<string>;
    /**
     * The namespace scope for install manifests. Defaults to `flux-system`. It will be created if it does not exist.
     */
    namespace?: pulumi.Input<string>;
    /**
     * Deny ingress access to the toolkit controllers from other namespaces using network policies. Defaults to `true`.
     */
    networkPolicy?: pulumi.Input<boolean>;
    /**
     * Path relative to the repository root, when specified the cluster sync will be scoped to this path (immutable).
     */
    path?: pulumi.Input<string>;
    /**
     * Configures the GitRepository source to initialize and include Git submodules in the artifact it produces.
     */
    recurseSubmodules?: pulumi.Input<boolean>;
    /**
     * Container registry where the toolkit images are published. Defaults to `ghcr.io/fluxcd`.
     */
    registry?: pulumi.Input<string>;
    /**
     * Container registry credentials in the format 'user:password'
     */
    registryCredentials?: pulumi.Input<string>;
    /**
     * Name of the secret the sync credentials can be found in or stored to. Defaults to `flux-system`.
     */
    secretName?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.BootstrapGitTimeouts>;
    /**
     * List of toleration keys used to schedule the components pods onto nodes with matching taints.
     */
    tolerationKeys?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Flux version. Defaults to `v2.8.3`. Has no effect when `embedded_manifests` is enabled.
     */
    version?: pulumi.Input<string>;
    /**
     * If true watch for custom resources in all namespaces. Defaults to `true`.
     */
    watchAllNamespaces?: pulumi.Input<boolean>;
}
