apiVersion: v1
data:
    DB_PASSWORD: ENC[AES256_GCM,data:VTkg27/DxsW2WI7ElUq74B/GSOvVECP5rLIgew==,iv:itsNDFZv4+CW9zZ9NIRcE6u4W/55cE0rSWb6rdENu9g=,tag:ZAziR3vDc6a5HoapugrNIA==,type:str]
kind: Secret
metadata:
    name: immich
    namespace: immich
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUVNUODl3WGNEdU13VURo
            eWRzU1JYdmF3SitDWU9tcGx0bThPWkNYSXk4ClpnSjJoSGFJUmNZclVRcFlSSk5C
            ME5ld2dJMzErejY5dnA1Z203L0d4R00KLS0tIHlGTE8rUW9BZ0FPM0hWMEtGc240
            S21uZ3VZRDRob3IrTENqZDgrZWxUUVUKLKLck4VW0C2RQEheGMxbQoSRZc6SR6cS
            CqXPQUJ2er4CEBrFGtUxeL+6pilqdX2ChasCCSb6QIrGjcpg0z5a4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:OqvJbhUDfGTbGOMuBGHR88MZUdpC00lQQgI9FVDMktHUq/TtPiyK6P3Pmou6I7OVn74fZCvZixOcpqMZ6ooQhJpSBnbiHDI4hOpm0K4D+7l1pTq6NQOxTjYPcENvLIDLW13U430gCNQl319qVGD6gNJlTP7XARSoHalXABqV1fk=,iv:Ed0Oj0AlkKU02DueY8bk2fi8R3e+0rcDPNsTQ/LzFe0=,tag:ZZQ6sfn6g6CL/W7+iBf4wg==,type:str]
    version: 3.13.1
