apiVersion: v1
kind: Secret
metadata:
  name: immich
  namespace: immich
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:PtJ3rK07T6Q99wOs3YAr/YCjPUQ=,iv:4OBFdSo4F6xnl34nJJLVjRXuvjlTTght4JgU+zPdWro=,tag:5EZPx0Pteo9zYJu/L/jROQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRzlRN3l5RFhod1FTK0tX
        bll2MHh4UDRSU0MrVkpUQmMySWswcFBvdUZjClR5Mk80MnVZczRvRGFrckNRbkx0
        R0JkQjZrdEsvUUhBajdBS01hUldrYXMKLS0tIHJVZUFETW9yNDFvSHlUclkvSVNU
        Wk52RUF4TUV4VUZXamw4cFdrZW1rL3cK1/1duHTwRQmLLeVeXLdBnvxGar3PvJQ1
        hQHzHUq/6Ap9vYExlcMTO4eWhdJERB/UgLabf67WaUce/vW8j8jYBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TkxSbi9rdnZrVnpNblQw
        WTZEYnFrTVkzK3ppS0xxR0xQOVNnei9ScUFVCkNUSXVBcWRXcWgzb0dzL2tpc0VO
        Z0tZSCt0dnloYXRjRVFuZC93bm0zc2cKLS0tIFNhaFF0OHEzNW5oQWFiTG1uYk1N
        NGwxcWpDd2JIMGFrTzNGN2N3alFxRWsKZnawcpdsv2Dkpn3vR6w7ypWuocZcXm2v
        0QyELzhQQw+uM5XhsZTjroI48WKAifPJiWc7sQjMGMZXYrSjkPTyOQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T16:56:38Z"
  mac: ENC[AES256_GCM,data:2NwISBqO4+LIMK9puo/KTS4Xi0Z4PUMq4YiaQ3wR+l+1P6JSZuTL19nZ9f8mVCiNUM60UxZnVEgCs5kXay0e3PR8ewRd/J7p1aAelJmFT62tVdg8v71szxIpgQaO+JTPjHyhaWO5N2HxE95D+hFXoJD+0hoYKYf6/RcRRnHkS/Q=,iv:E28/WVU0tt9nTAKbBzlYFF7KwU1TFGdER8u/x5bmZo8=,tag:X4fOwfZRN3tyEkiRwb5uWA==,type:str]
  version: 3.13.1
