---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgCj6heK2rmq1qqKcfjdQszAhGi64raQ9BMO7vNqet07T7mo+uC7IQDUCQt6drISNWjwRTXJkOzLQAfsotJF2Edt1dQoXVKC6Gdf3X3U7dH5c2IZpUck/Tv6tsO6ACnyDphAqSiu5DKbpdEEnhXNkQtkkW6Vt7D59mC/3/zmotNHApXawAPX+FI11W111E6nEwHKK1lo5GzPwgqyF0hdNMmfnUnCnVlrKBBKj3uIlEwInO+cKMZTYBzUSPWRWeThDuxmKkkT1PC3L44/X81/krfRiwTCHNj9Gc+jme7QttrS9sJBgiIOEZnn4dTsWCjh3WZBr/dlKWHt2hZ90NwTZlcZlSpmdEllN44/ONn7H6qJzAz1kNUbxFKwgBKMrsopbdQVd2sAURXmDEPlQk513BAD0hmfsbkFhKEznRvmD1V1jpvNY2xdpMRIE97GdHDj/QSLiznKNFtbWwkBx5kmLeV3DUYzsRH/WeX/PV6HXhiOZHQKcCdqjCrpwbcD4COJWVxt+Ovl7yPeg3mG7vsXwJH8LIS5LT2g9vvzf0UafC71OCaKtkKN2ai3y2ANHF8qLRCRbQa+XyXKAgS0TO7I6aKOz91KEyUmTKV17hooRFxVuyh44bxdvDPQ/iJOafYZCeyDIH3HWd26yHlF23aQ/xqDZ0cZBx7Qd7rAZludh6hSEHf1Kxb4mL+Qd/NshvcksiBDBmHA4mYzBo4kwxAuTDDRw3AvFw==
  template:
    metadata:
      name: immich
      namespace: immich
    type: Opaque
# apiVersion: v1
# kind: Secret
# metadata:
#   name: immich
#   namespace: immich
# type: Opaque
# stringData:
#   DB_PASSWORD: <postgres password>
