apiVersion: v1
kind: Secret
metadata:
    name: immich
    namespace: immich
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:PtJ3rK07T6Q99wOs3YAr/YCjPUQ=,iv:4OBFdSo4F6xnl34nJJLVjRXuvjlTTght4JgU+zPdWro=,tag:5EZPx0Pteo9zYJu/L/jROQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWkdGWVlMQkc1amZHK0J6
            ckQwWUpZSXRRbnFIUk80d09kRFVJWi9JUkdrCjdKbS9tcGlqY2ZDeWdtaC94YUxp
            b0RONW1VeHhpTVRUNkNNRkhGbDFoOVkKLS0tIEJ4eWo5aVhuL2I3RUNZZElJMElV
            ZzE4OWVyc1ZFY3UxbXdzaG85RWt3V0UKNI+RpSjmtGcmcyDOiYf6dlWIAVP9GyaI
            ILF7UYyFZ2oh0i1hmJmI2pYFdpFxThVnLtiuJdvh/AnSTb9aakZIog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T16:56:38Z"
    mac: ENC[AES256_GCM,data:2NwISBqO4+LIMK9puo/KTS4Xi0Z4PUMq4YiaQ3wR+l+1P6JSZuTL19nZ9f8mVCiNUM60UxZnVEgCs5kXay0e3PR8ewRd/J7p1aAelJmFT62tVdg8v71szxIpgQaO+JTPjHyhaWO5N2HxE95D+hFXoJD+0hoYKYf6/RcRRnHkS/Q=,iv:E28/WVU0tt9nTAKbBzlYFF7KwU1TFGdER8u/x5bmZo8=,tag:X4fOwfZRN3tyEkiRwb5uWA==,type:str]
    version: 3.13.1
