description: execute appdata + personal files backup scripts
schedule: "0 0 * * *" # 12:00am

handler_on:
  exit: # always runs
    command: rm -rf /tmp/dag-${DAG_RUN_ID}
    type: ssh
    config:
      user: "root"
      host: "192.168.8.89"
      key: /etc/dagu/lxc_ed25519
      strict_host_key: false
      shell: "/bin/bash -e"

steps:
  - name: setup
    script: |
      #!/bin/bash
      set -Eeuxo pipefail

      apt-get -qq update
      DEBIAN_FRONTEND=noninteractive apt-get -y -qq install openssh-client

      WORK_DIR="/tmp/dag-${DAG_RUN_ID}"
      KEY="$WORK_DIR/key"
      mkdir -p "$WORK_DIR"
      install -m 0600 /etc/dagu/lxc_ed25519 "$KEY"

      scp -r -i "$KEY" \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        /dagu/dags/scripts/* root@192.168.8.89:$WORK_DIR

      ssh -i "$KEY" \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        root@192.168.8.89 "chmod +x $WORK_DIR/*.sh"

  - name: run-local-pbs-backup-script
    command: cd /tmp/dag-${DAG_RUN_ID} && ./local-pbs-backup.sh
    shell: bash
    continue_on:
      failure: true
    type: ssh
    config:
      user: "root"
      host: "192.168.8.89"
      key: /etc/dagu/lxc_ed25519
      strict_host_key: false
      shell: "/bin/bash -e"
    depends: setup

  - name: run-cloud-pbs-backup-script
    command: cd /tmp/dag-${DAG_RUN_ID} && ./cloud-pbs-backup.sh
    shell: bash
    type: ssh
    config:
      user: "root"
      host: "192.168.8.89"
      key: /etc/dagu/lxc_ed25519
      strict_host_key: false
      shell: "/bin/bash -e"
    depends: run-local-pbs-backup-script
