---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: porkbun-api-credentials
  namespace: external-dns
spec:
  encryptedData:
    API_KEY: AgAMHSmWjEuKAyBKZx8M2GCd3xrHjP/v8eRxusrS0eE/qDFo3untoPzCImazpzJskt89cIyJXO63/OJksXwlwfVeeTKq4cfDuKmr4ET9LCcpYTMV44Qds71fqAJ1fForzFKr7frYTUsC2xa8M9nPGS6aNZ6dA1W389v+G2hPEMJ82EHZArn9SznRAl5xR1XrMqhGg3+SkVrjCQB4KSL2x6LNPj2H5WZ8JIco7P2j8u58rBe797lfpbZSdL8V/1Dl8fvyX7InDdnlgtpyBmpVv0t7XQzplno/5BQT22oOYz2ioSpFBm46oCMhFK1EH1qtOQkxg+qexLBWPdhcQVzEViTzrzgWOrKLR0aWEmgKydaTLpc7wy1ehYkARCtrg/NtwQHDPA88EzTP+q4idfoCW5iIxXeR7lHfTCndJCXAzUxpCRUOl/jGm81UHIZ1JQqXK8G/jamTkqKa+vyYvNXwt4NiyynFWQS+/mX3Wu1HpncL0/AblHpwZNc8adPS+7pGoDGAs0n1nHaCWynGa7Eqs9/HjxXW7b2HVBVVWO30WZdIhDtwQroMXbdkmAhIpGNJKlJfnRPWLHY3cgIrS0EoL9wV/+9T7isT1nUPCjLyViP1uTway7lsZsx8Zhjn8VaUoZimxJMinmdnGgtiOvLflhAi7+FTmoy3Bi4OvILxSSMzhFHmbdYa8Prw7xIfNDyxkmQF0ehErhjNOMdp/S2HS6NnA1dnnVzHJd0JbJdfthrjr72qraIXDD2kZsX8vASpJVXblXRgN+riO+GcQh28+x1UEXnHQg==
    API_SECRET: AgCrlAcB8CO5Pxg5At5BcsRzZ3VhS43vGmCbj+NGPGZLLvNXgZqGtZGe626L1Iz3xIkmC+In7mU5hwvuYrQyWAwUc0sVWdWvfwqCx+gwAX74bv63YIMl+U2k/jNrJsER73uHOy/PPRDAatbZJQn0zVadVw7wZiQmWEOUCDm1Pp0KMAKtVHwQ3A6FJgtH8gNIkuXfYkHOu52A48zgH2y9tflbNWrrQsyGhpENdSkNqQ0DMXysrwcwWVi8qboIVxy6yF6vRQlao8mJ/e1vqzvjEesg2MB9IZW9cJZbrQP6FDOf30s1mdzgs1vYSyqep4y/UcDcvnPRtiy8zxzYyXPuvqGf7gD0/tzuRY+H5+44M1JiMpnoCJczt2jqH01bitEGs9Bh1Xoon06MAFlHCPPPeFTtbxgkz+58UqfQwASlTTB55YhOur4ulZIgz54p+yA9PFtG/YlCFfk55QeModrvqeZbe9hZ9ZTdqAqkmdrgeYEwnhmmMHILZyLItcmX9p3x71H2Cog9gP4+Nlj5Ffk0YWnosAnRwVMxkog5ibEWuRWR31nANFJ5fX56/7s8j/991kvDZ34NlGd3W4d6Y1wYhzXdUiTGdFUqQB0+k9U9K9EXbjmiMwjcPH2pGtck2lDDXU5Fz8KtgObwIaP2MlPQ9pCpczkiLuPS2ItGijNSeyqI5/a13G+IYawSBg/XvD5w9cFNqvGupVhmleggI8A7SOkLc7AA1Mx6se+hwSOhQwXGonB9qnIemBfe/X+cUoIxwGCiHT1rKvKpffMbBpqigpO7rb5bsQ==
  template:
    metadata:
      name: porkbun-api-credentials
      namespace: external-dns
    type: Opaque
