apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1h
  releaseName: sealed-secrets-controller
  targetNamespace: flux-system
  chart:
    spec:
      chart: sealed-secrets
      version: "2.18.4" # https://artifacthub.io/packages/helm/bitnami-labs/sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  # https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/values.yaml
  values:
    keyrenewperiod: "0"
    metrics:
      service:
        annotations:
          gatus.home-operations.com/enabled: "false"
