// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetTemplatePostrender {
    /**
     * An argument to the post-renderer (can specify multiple)
     */
    args?: string[];
    /**
     * The common binary path
     */
    binaryPath: string;
}

export interface GetTemplateSet {
    name: string;
    type: string;
    value?: string;
}

export interface GetTemplateSetList {
    name?: string;
    values: string[];
}

export interface GetTemplateSetSensitive {
    name: string;
    type?: string;
    value: string;
}

export interface GetTemplateSetWo {
    name: string;
    type?: string;
    value: string;
}

export interface GetTemplateTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    read?: string;
}

export interface ReleaseMetadata {
    /**
     * The version number of the application being deployed
     */
    appVersion: string;
    /**
     * The name of the chart
     */
    chart: string;
    /**
     * FirstDeployed is an int64 which represents timestamp when the release was first deployed.
     */
    firstDeployed: number;
    /**
     * LastDeployed is an int64 which represents timestamp when the release was last deployed.
     */
    lastDeployed: number;
    /**
     * Name is the name of the release
     */
    name: string;
    /**
     * Namespace is the kubernetes namespace of the release
     */
    namespace: string;
    /**
     * Notes is the description of the deployed release, rendered from templates.
     */
    notes: string;
    /**
     * Version is an int32 which represents the version of the release
     */
    revision: number;
    /**
     * Set of extra values. added to the chart. The sensitive data is cloaked. JSON encoded.
     */
    values: string;
    /**
     * A SemVer 2 conformant version string of the chart
     */
    version: string;
}

export interface ReleasePostrender {
    /**
     * An argument to the post-renderer (can specify multiple)
     */
    args?: string[];
    /**
     * The common binary path
     */
    binaryPath: string;
}

export interface ReleaseSet {
    name: string;
    type: string;
    value?: string;
}

export interface ReleaseSetList {
    name: string;
    values: string[];
}

export interface ReleaseSetSensitive {
    name: string;
    type?: string;
    value: string;
}

export interface ReleaseSetWo {
    name: string;
    type?: string;
    value: string;
}

export interface ReleaseTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
     */
    read?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    update?: string;
}

export namespace config {
    export interface Experiments {
        /**
         * Enable full diff by storing the rendered manifest in the state.
         */
        manifest?: boolean;
    }

    export interface Kubernetes {
        /**
         * PEM-encoded client certificate for TLS authentication.
         */
        clientCertificate?: string;
        /**
         * PEM-encoded client certificate key for TLS authentication.
         */
        clientKey?: string;
        /**
         * PEM-encoded root certificates bundle for TLS authentication.
         */
        clusterCaCertificate?: string;
        /**
         * Context to choose from the config file. Can be sourced from KUBE_CTX.
         */
        configContext?: string;
        /**
         * Authentication info context of the kube config (name of the kubeconfig user, --user flag in kubectl). Can be sourced from KUBE_CTX_AUTH_INFO.
         */
        configContextAuthInfo?: string;
        /**
         * Cluster context of the kube config (name of the kubeconfig cluster, --cluster flag in kubectl). Can be sourced from KUBE_CTX_CLUSTER.
         */
        configContextCluster?: string;
        /**
         * Path to the kube config file. Can be set with KUBE_CONFIG_PATH.
         */
        configPath?: string;
        /**
         * A list of paths to kube config files. Can be set with KUBE_CONFIG_PATHS environment variable.
         */
        configPaths?: string[];
        /**
         * Exec configuration for Kubernetes authentication
         */
        exec?: outputs.config.KubernetesExec;
        /**
         * The hostname (in form of URI) of kubernetes master
         */
        host?: string;
        /**
         * Whether server should be accessed without verifying the TLS certificate.
         */
        insecure?: boolean;
        /**
         * The password to use for HTTP basic authentication when accessing the Kubernetes master endpoint.
         */
        password?: string;
        /**
         * URL to the proxy to be used for all API requests.
         */
        proxyUrl?: string;
        /**
         * Server name passed to the server for SNI and is used in the client to check server certificates against.
         */
        tlsServerName?: string;
        /**
         * Token to authenticate a service account.
         */
        token?: string;
        /**
         * The username to use for HTTP basic authentication when accessing the Kubernetes master endpoint
         */
        username?: string;
    }

    export interface KubernetesExec {
        /**
         * API version for the exec plugin.
         */
        apiVersion: string;
        /**
         * Arguments for the exec plugin
         */
        args?: string[];
        /**
         * Command to run for Kubernetes exec plugin
         */
        command: string;
        /**
         * Environment variables for the exec plugin
         */
        env?: {[key: string]: string};
    }

    export interface Registries {
        /**
         * The password to use for the OCI HTTP basic authentication when accessing the Kubernetes master endpoint.
         */
        password: string;
        /**
         * OCI URL in form of oci://host:port or oci://host
         */
        url: string;
        /**
         * The username to use for the OCI HTTP basic authentication when accessing the Kubernetes master endpoint.
         */
        username: string;
    }

}
