apiVersion: v1
data:
    HOMEPAGE_VAR_AUTHENTIK_TOKEN: ENC[AES256_GCM,data:azeTgakRXOmoF7F4i4r/citkHQQlMFAoMPsyiBimybdIjmP65whNlXBt6LOSIrJGDpbqxsD3LjCr5XXqXLanVSFxPhtEW1Q9KuW8/eEo9A8=,iv:9oC/2//aZ5iUB9oNUwsbofwlmVmZzwUuRbVjjzhT+Jk=,tag:NyhBNDRrXhRdvnhTzgZwuQ==,type:str]
    HOMEPAGE_VAR_FORGEJO_TOKEN: ENC[AES256_GCM,data:7ahkOeBtZ6LNMG3Qq4sD7BaWJeM48iIdyaznAjlMeYdZe94HtAK3FNjSL+ugCfTdaI9ZfrOzjW8=,iv:DwtocHbcJfqnhBdR4NEv9NNorg7MxdS4sfDl1jr62d0=,tag:em7/H48VLXeIYzmVhVNYqg==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:xKnMYHzlZ7bT7WN33vMRU86hE1QEXniKID6H9A==,iv:mXQoNVZGniet6Np73yESeHbhlGJLQ5ybNgtmVlqkFpw=,tag:iSeG5ntBRZwvStC122rjkA==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:NX2nW4Zu5eM=,iv:kbdZC3qhZk0U7Li4j3jpvH4DNrwbZqyw+1/qcY9zvzo=,tag:d3QJwE5g/46llshN8/kD9w==,type:str]
    HOMEPAGE_VAR_PAPERLESS_TOKEN: ENC[AES256_GCM,data:DUvxUKZgX/sEacl6NQ+lC2sbYt5xlmwbRMFeknW41jJGua3irrXHSRXXz9+itUMZGOGP4JFAPa0=,iv:OFYp/TnL6auaVCG4DbXbl0FTv+KVmWoHknbJDkRjTTc=,tag:wyRMqc94YXrtE8tJUgME6A==,type:str]
    HOMEPAGE_VAR_TANDOOR_TOKEN: ENC[AES256_GCM,data:GXu9K6VxABxrvp67O0R/ssA4WGgAx/8ox7WUnDlWN8l9rjR226XV6rjrVFcBfDeFqj95rQr2i8o=,iv:ewGt+bHgtyVMEX6Q3vJJp7p9FSk7AOF6m1nmQ3wG1j0=,tag:Kx0BriBJqgWyHM+zrJWDYQ==,type:str]
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WVB0RDVaalFIcE9IMDZB
            amVRSUJsVjA5aUdYTyswUVhWejRjTmxzT1I0CkhHaFI3UllIbGpDUTRuVnlQYnZU
            T1g5a1RLUmdzc3FxRXdtdHAwREJQWUkKLS0tIGlRMnN4OVVYRVI1SEJsR3JRTlho
            cUNwNUZjb1o0Q21rTGZOSmcyMnUxaGcKPYKi5FNHUCrhacIRK6j+o5oqsOKRzd3h
            74Dd+Y44UTzOj6IMo3dQa8o+D33OWQHXJMzzapyR2Qx36EAxPxSLzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:B9IwiQVyFInuPtucBWf17/F4WhVEL5W62LDpFjkBLwEfp++7gdIToQ6zqbNzBHnEX6B7dExS8Jns/nj+zufPUwdULQR5EqqBvvlVHH+TpWvLO2rOr1xmFgKb69crh3mmNV276cWwVZIO1u1B/xKRXEmlGnNRwIJk65776fGc8sY=,iv:fs6PgnweFne2IFEeIbdonFwvqYw0o1xoVZFuwDl4Qcw=,tag:NTqfyz2gRlnwnAmDhqcfZg==,type:str]
    version: 3.13.1
