apiVersion: v1
kind: Secret
metadata:
  name: homepage-secrets
  namespace: homepage
type: Opaque
stringData:
  HOMEPAGE_VAR_AUTHENTIK_TOKEN: ENC[AES256_GCM,data:9DLcHhGUcdF6ajp3BQtupoXYqpeRiaqlMtx2eCpGANhfM/s+oh2iPPOEq6jEv+us1maoE9ehTsAs/Bp5,iv:j4sVMZNweQoe7HBdENRoWr2q0vadvwlHZfh2Iijfl6w=,tag:sjeaJqUIX6XTtRVdPgPkIQ==,type:str]
  HOMEPAGE_VAR_FORGEJO_TOKEN: ENC[AES256_GCM,data:NsketJE3vYNAO4iLYOEgoz6gZBNvto3CMa+/Aif1kVxO7ROtujjy7g==,iv:vq9ycCwOkvL1ES6/xEFJ/1Nwj/F2JBPhOBKSrmCd4U0=,tag:kV6z68MGxy7L3KtzCxn/Zg==,type:str]
  HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:8DIhVgyXIn8MhPtmP6Ne8afWw6E=,iv:YRjwLzXzX4gs+U5QDgVNVep/dNhFDPmjxf3GhAwPB2s=,tag:mViF2Hw4uZzqwIVGjSWrCg==,type:str]
  HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:nB/OoEM=,iv:VTyPGXELaIoBwHlBhixYvn5vvBQM9FtAiwetr62TsZ4=,tag:nxHyH5CDll9dz8Q26ysIrw==,type:str]
  HOMEPAGE_VAR_PAPERLESS_TOKEN: ENC[AES256_GCM,data:grUnhWVSHy4T1WsYSrWysrJIWGOGNg496rt/mFdE7IjTZqP+KKcAMA==,iv:K3Ljh4nK19qwYX77LbsgIcv60QYIxE2do/JjVYwSgnk=,tag:V0qC8KE929rxG0sEjkI/8w==,type:str]
  HOMEPAGE_VAR_TANDOOR_TOKEN: ENC[AES256_GCM,data:TfArAc3Ui7tNMAIPy4SXhFPN2l1uaIqyIwgEQ6eU7NfHm/IOKqLGGw==,iv:EztRqLf2YdqEfbasSxYYMTvrFd5CBoGdgvi4QK6gyY4=,tag:SwiCa+kHfl0GfdbJKGTbLA==,type:str]
  HOMEPAGE_VAR_SEERR_TOKEN: ENC[AES256_GCM,data:tD7sBypvy3qLh4jgFcSHOAsUR1hDX5gR05Dcu8u5DYmVDz030jayosKaxFzgYfx9OfEwmOyyP5+gwx8mR9htMwGRG3o=,iv:hkIOpHhnhGDrVV58ECrwDbTY7/iik6mGbQ7TLJ6d634=,tag:lZwQgA0SPogwcLq8kLGrOQ==,type:str]
  HOMEPAGE_VAR_JELLYFIN_TOKEN: ENC[AES256_GCM,data:kXSVusHFvvab+2SmhCn/mrASHhv+YfMUyMuyeWSl6ag=,iv:06sKEsYvPApFjqMRW96chpp4zm5PVDVB2zcOkm3tHhc=,tag:f407k/3h/KzTfDAR9/vS8w==,type:str]
  HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:0P6RDwmqTLn6rLdnTf8XXRuXVNrJ9G27Is91dDhH2MU=,iv:wCUI+MqES+0WFTOl3sbN9Dt4tWrGEZfZKZtqrW2j9UU=,tag:I8Io+zhgz1nb86uyZshxhw==,type:str]
  HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:KlBXHm++bdBR0ePOzxDpD5XnPQStgYLr7I1jIMi2fys=,iv:STxOxHKetkvxirSRUH5QF8igyJMPV8rmBySCi2bK5qo=,tag:l4fFq8DBO4Rc3/CatyIaQw==,type:str]
  HOMEPAGE_VAR_LIDARR_API_KEY: ENC[AES256_GCM,data:tA1HUt0QBWnvBQsFmG5VLaIClR7e5UJM/KXOUrjgYh8=,iv:DMu0RK0uJ6d6dFgm2ORUiF4FRB7lZNU6AABnL9sXLhM=,tag:4Bgz+GQW0hWT5vl69AdRjw==,type:str]
  HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:Nqo2n+dNnEyC+bJEeeaEXUuzt/o6Ic/2nSFHGGHQGO4=,iv:Z1rpBgxeVj++r/j/Pa6StILxjAL1FMIrjaoQio2W1S4=,tag:C1AqIl4zYlewuonvTsPlRw==,type:str]
  HOMEPAGE_VAR_BAZARR_API_KEY: ENC[AES256_GCM,data:kLwIR21x2npsp61/d9mVK8ne4x/4Dr9A1/bqsoo+88U=,iv:e18/tZCPc2UZnEzpS5MdB1ItwGtzJNXSNgfDraui8W4=,tag:EKA4jJ1xnzsU8VVZm9VCTQ==,type:str]
  HOMEPAGE_VAR_SLSKD_API_KEY: ENC[AES256_GCM,data:DDe2+lFd6vwI4D60q1HCfCivI/jBnscGPFnolKUgYDFr78PIrscoKZtFw+kuB1jSDTgMzOukp8KQFVn15N4Jvg==,iv:Z4MGGtauLKVxzuq0rjYenop+391PQSMWF3hriU5fJc4=,tag:MQC/F5j8XT08i0veYINfXw==,type:str]
  HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:WbNANQk=,iv:bB8Jas0xsrAgnnpJkXXhGOcy0K9kNey5mQL7WlxpYFU=,tag:gjrUIie/uBZ7BI3dKnxnQg==,type:str]
  HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:QoEYz6Wb4jFwhlf6qrjppUlpoRw=,iv:CHrsEx6WimstsNvm6dN0jNVwrU1+hjIOczlHwbN0uQY=,tag:xbTugRPQ9mQ5UUSoks9aVw==,type:str]
  HOMEPAGE_VAR_NZBGET_USERNAME: ENC[AES256_GCM,data:tY443rvW,iv:eVF00iF3eLJmS7iOQIDNMdNOTunt5WqWWw5xs+RA/Pg=,tag:QA3YiKVpn+gM7LjdgX/vlA==,type:str]
  HOMEPAGE_VAR_NZBGET_PASSWORD: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbkwwWTh5MVhhckVMMkpK
        K01EMFhmeG1JNkRSa2gwSGRwNENRYSs4Q21vCmlrMFFaVWI2WnB4T0h4ZzI5akti
        K3p0M1VMMDR5ZjFWYWFOdE0wTUFVUFkKLS0tIDJhSFZpRVcrRS85RG04aWE1VVdi
        RU5RdDRENXJ4TVJ3YWRpLzNZL3pqVkUKXFOdVzL31RZkl9lECmqHRXCsE6GdHtj+
        +EeTpdOWWYn0jZk9NCn9L9L+iahNrOdUybrT1UBw6vkKGT9PIxgIMA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T15:51:31Z"
  mac: ENC[AES256_GCM,data:4xZlS2dX2bWcJEcLXaA7tySbQzwou3iFza8O/s3+flhH+S0Kv3LwAahUKcc3D7qqPXhkQEJii/99RmSJhhVqdTQPUi11C1RTsgqS46/1cHLTaPFOPKGnps3aBgrDaNCqc3EAYRLZr+pe+xONyVO073N4evWWEYVvdYOxtjqDWhs=,iv:WUOEa+GyvxDqQvxQfKifb2YjLptLR99yftQqSlI9OPM=,tag:HwEeMChImW7I0oOLJX6X9g==,type:str]
  version: 3.13.1
