apiVersion: v1
kind: Secret
metadata:
  name: homepage-secrets
  namespace: homepage
type: Opaque
stringData:
  HOMEPAGE_VAR_AUTHENTIK_TOKEN: ENC[AES256_GCM,data:EBekXjccX1h+o1usWpHQvdOqVuds8UkIzfzWT4dKiAxRjfKJkUSh3f3wYSw1ZNpXOFhJLjH2VcqYfC47,iv:/IYHiFWE15zuZUXPs3eThanjcX3/Fl/JkX2YCPruzk0=,tag:L8JiJO2FSK4bqYqjPxIV6Q==,type:str]
  HOMEPAGE_VAR_FORGEJO_TOKEN: ENC[AES256_GCM,data:kDPtip03K+ihMHqzNOsitt8LimbWdb6ow/+1h1N/vBHZ8Z5DgF1j5w==,iv:5PaZ58CbPebdwL/m0w3P76hwl+LqTAtweOR9/CCbhI0=,tag:17IixDqb2cCI7q3fpc7khA==,type:str]
  HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:fYaKMEI8GEIGOtn3g2663J+dgPQ=,iv:g3WBDqkQJwSL5S19ECQCOrj+A1JbD3vLYzrwIRlOG2A=,tag:gWgW9d+ma4uq83ENz6emBA==,type:str]
  HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:VC0PcTI=,iv:UcsZV6hodPpdJB8PgHZAOXoQkGHhxylaIwZ2d+0AiEQ=,tag:0LcnqvJKxJYa5WmkU3DDLQ==,type:str]
  HOMEPAGE_VAR_PAPERLESS_TOKEN: ENC[AES256_GCM,data:upxwMYOIBaTr2KS18HyxQ6AGfRDPyzqgDskY70sfn6a1MNpaxrUOxQ==,iv:HzBHUETQi+xC+PcM4FKe69XBE6hOYyoPFOaxWSMvNqE=,tag:3CtKXIbmrKgD0DMKMAC0Sw==,type:str]
  HOMEPAGE_VAR_TANDOOR_TOKEN: ENC[AES256_GCM,data:StefKRBeqWdz92C2JEOxGzFIDfiYusRGwlOJJ6w0UtEx2krtGm0Hpg==,iv:ntrNEx/RYhL2txzrIXi/ihHQ19/ZtGvu48Zq3ybM5WY=,tag:weY5AVUsTnuV+17/nUZY1w==,type:str]
  HOMEPAGE_VAR_SEERR_TOKEN: ENC[AES256_GCM,data:NjPj0VdY7FxAi+7cQCqzXsLmThPWuiYt72K4Xu31dcAD57SG7XmLf/zuTaYEyF+6wkNHrT2ggxqNA8uktGSLWRBTklU=,iv:+T41cMN4SESnjVdeI2HSXa0XAOBVJp/jmBReFoKIybg=,tag:XQSpMMncnN1jQleDVJmtLA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MmJudlF2QUx5WGczb3Ri
        UmVJQzl5UFhEMEU1M25QUUd1VXRqRmpqZUVjCnpDcXE2Mkl3U1NKMk40cng2Ykpo
        aWQ1OTIyU0JRWTBmT1RXSGpXTVpNaW8KLS0tIDk4ZzFmUExYRktBSmYzQldrYk1k
        WGNMdWhLbUk5eno1cHM5SUE0OGU2STgKfCEFaZ/4wmi5SbnC+piPktc+H+mFZawX
        xVtd2KUWedJ5Q1g2nwW7aH0O9MjTIDADfSgBfaagOeFHxLjylHtStg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T16:22:10Z"
  mac: ENC[AES256_GCM,data:u7aA20387oBBoYo7IuNl6i1JTehPN+x4VlDvLpR2F8yAqVKg2fZliXGXNX1Uyu7V02J2APB3xZOS4EY+HZphsrTw74hdXCvDbu6lMIeY0wMauBdcg5Rsqie0zLBgcZ7c3Wez+gwwagCtUup1BQPuuVUVK9B2hYXpkkeWV31XJNc=,iv:K4aBsEcdQrNYvSHEPva2i6zUbofFKlN80R1kLOVM4+w=,tag:Vh21MtOcrNk0vplhgXg6Xw==,type:str]
  version: 3.13.1
