---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apprise-config
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apprise
  namespace: servarr
  labels:
    app.kubernetes.io/name: apprise
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apprise
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apprise
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 100000
      containers:
        - name: apprise
          image: caronc/apprise:v1.4.1@sha256:25e0577915c2f06233ae1dce077f05c0fc9ba4f0ea89de5aee18a32b2ee9a75c
          env:
            - name: APPRISE_WORKER_COUNT
              value: "1"
            - name: APPRISE_STATEFUL_MODE
              value: simple
            - name: APPRISE_DEFAULT_THEME
              value: dark
            - name: APPRISE_DEFAULT_CONFIG_ID
              value: homelab
            - name: APPRISE_CONFIG_LOCK
              value: "no"
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: config
              mountPath: /config
            - name: apprise-secret
              mountPath: /config/homelab.yml
              subPath: homelab.yml
            - name: attach
              mountPath: /attach
            - name: plugin
              mountPath: /plugin
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: apprise-config
        - name: apprise-secret
          configMap:
            name: apprise-config
        - name: attach
          emptyDir: {}
        - name: plugin
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: apprise
  namespace: servarr
  annotations:
    gatus.home-operations.com/endpoint: |
      alerts:
        - type: pushover
spec:
  selector:
    app.kubernetes.io/name: apprise
  ports:
    - port: 8000
      targetPort: 8000
      name: http
