---
apiVersion: v1
kind: Service
metadata:
  name: apprise
  namespace: servarr
  annotations:
    gatus.home-operations.com/enabled: "false"
spec:
  type: ExternalName
  externalName: apprise.notification.svc.cluster.local
  ports:
    - port: 8000
      name: http
