apiVersion: v1
kind: Secret
metadata:
    name: gluetun-wireguard
    namespace: servarr
type: Opaque
stringData:
    addresses: ENC[AES256_GCM,data:7+gby3aeI1a7DY/sSV6iqSM=,iv:c0SmopJh1cfThsLMmd417VnL3ryy0k1xufCs88plP8Y=,tag:AvhR+MFD8vWPEX99ZKjjxQ==,type:str]
    preshared_key: ENC[AES256_GCM,data:kaeD7sqwd1J0bApLAduaQARR7Z8RY4zu+p49FSf0T6Zwgcr74zmnsULy6hY=,iv:aiCnnwV8PL3Mft2pAoQzbR+z8ztm/MJ7SLp6opJxuxw=,tag:TMtBLIA84A8ZjtAKY9XIsQ==,type:str]
    private_key: ENC[AES256_GCM,data:DmJQ03bVU5K+5rPatv1Zn64Ti8Ryge8ZWerAHKJP62+5mqxPoy/mpBxrFTU=,iv:AabV05Jhvx1S2Sy/B/rOsp6LHkEamTs4yf6tnSm1Bec=,tag:38LSzROX1XyBhByCIj7DDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcGFtamhNSzFzWXNpb0RJ
            N3FXUlRPTGNKejVCYkFnM2Y3RVhyc1o3Ym1jCmpXcDNWbDY2QnVkTk9kSmxNK3dT
            OTNmcE9Xa3NSOWkvZXROZlZwUjg5dUUKLS0tIE1uRitjSHRSTjNYc3FuQUNYelJS
            ZUNKMk5SL2VSa3poSzVBMzRCYzlDcDAKjuUtBzdYGJpzAZtrr+JGSW0+tF/mWHEC
            s/IvP87iBZLO1ebDwEXm3KJODsCHnJ6i7UxbkpcqWZ47FiyrASEO5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T16:56:38Z"
    mac: ENC[AES256_GCM,data:bzMj8yAZzKast6frwTz7I5Mgid0aPhkI9P4syzsTx4hdlUzBvTAZwUvrbxUDWmWPMLGlRYQV2bIV6VojQrcrpfEg/xlSmus4TUc639W//u5jAYWkR/YlD+QZa2VS7Ie11sFDB0I9P8Uf4shz51hPnvfl2UZ3etmfu4ZCM+nOVH4=,iv:SwUX83DCem2wZSVQPc/enGxXgm/5GwME1N3B1qnrcVc=,tag:u5c48O7xJr/X/ngCEWNaXw==,type:str]
    version: 3.13.1
