apiVersion: v1
data:
    addresses: ENC[AES256_GCM,data:TtSUDgKYkRqbN+8mCEg28wqeVBxCfpY4,iv:z4gD10eIVhgO5pK19taB0IEX5ZoYiX8eJRix2adkHGs=,tag:J5fVvnKtRpUDRMXozOPKIw==,type:str]
    preshared_key: ENC[AES256_GCM,data:p2kttCc2TR+W5UMIGNX7iux7f0tCC1IDL3TILfeEkrwE9lIBQihSxCPlUJw/EESG1xAP9EwoAnxYbL+U,iv:CfeZ6m9k0/jRUjgIaNbnhtCNnEvov6KknxWL+T+EU/Q=,tag:4K55X1Eeye0b/sdct8f0Zg==,type:str]
    private_key: ENC[AES256_GCM,data:5KYsSDAXjrkAiAYKvxVtM9n0PgWTAkKGFWqWAOwLqx89pFfryyYDPONqK61QDvDGgzrGXaShk+AKrLOe,iv:oizVuEZHPvKSpLkoi8nIO4uUxV2t9ZxK23xQCkNYwpc=,tag:VULqMo2oI/9bQs8BtYePJQ==,type:str]
kind: Secret
metadata:
    name: gluetun-wireguard
    namespace: servarr
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQ0JiNFVzV0V1S1RTUkRK
            L1hXR2NKK1RzWHJzTExaMjRYdjI2NlAxM1c0ClBZOHh6RmNVYXlaQkFYRFNLb1N4
            TTZ3dGsyUDk0clJNV2o4MkVkeHU3N2sKLS0tIE12MjVmZy95WDl6eFhFL1o1WjV0
            MjFNV1FiUjdtYTYvb0FZUmxOOGFBaE0KKg6KaKvpF3vefg8m0jGcOS5B6NmmOGlv
            zVbCtHDofl+fyu8q01mLN+hx3q5GeurCEJqCof5Obr/aI2O39NZKaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:T+GFT+WZj5QjT/0S+PhR5xGg/n3HjYM3rhccZovltfBjT8p8oGyy27DT2ulXAsmApgDdKTY7RaALbGh/MxQhE7zlNVsMwsH6YOoZx4BsNBZ5+cMDZlzifGokILdLTbOigXNlHrT5Bebhh0lsKrUT3G7FXavdUQj+NLrFxQHBGZg=,iv:eCKfeQn9OtAJ7IX695HTLaFqiKUTOosV80n/lBECst4=,tag:h7gvri36nQwnMYU55BDR1g==,type:str]
    version: 3.13.1
