apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - secrets.yaml
  - gluetun-wireguard-secret.sops.yaml
  - downloaders.yaml
  - prowlarr.yaml
  - sonarr.yaml
  - radarr.yaml
  - lidarr.yaml
  - beets.yaml
  - triggarr.yaml
  - listenarr.yaml
  - bazarr.yaml
  - subsyncarr.yaml
  - profilarr.yaml
  - cleanuparr.yaml
  - ingressroutes.yaml
