---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-zfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: servarr
  labels:
    app.kubernetes.io/name: lidarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lidarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lidarr
    spec:
      securityContext:
        fsGroup: 100000
      containers:
        - name: lidarr
          image: ghcr.io/hotio/lidarr:pr-plugins-3.1.2.4913@sha256:ae0b3b14769fdfeb73fe5d9e61ebcda04edf202244bcbd6323d2fe1381154f57
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: America/New_York
          ports:
            - name: http
              containerPort: 8686
          livenessProbe:
            httpGet:
              path: /ping
              port: 8686
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 4
            timeoutSeconds: 4
          readinessProbe:
            httpGet:
              path: /ping
              port: 8686
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 4
          volumeMounts:
            - name: config
              mountPath: /config
            - name: music
              mountPath: /data/music
            - name: downloads
              mountPath: /data/downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: lidarr-config
        - name: music
          persistentVolumeClaim:
            claimName: servarr-music
        - name: downloads
          persistentVolumeClaim:
            claimName: servarr-downloads
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: servarr
  annotations:
    gatus.home-operations.com/endpoint: |
      alerts:
        - type: pushover
spec:
  selector:
    app.kubernetes.io/name: lidarr
  ports:
    - port: 8686
      targetPort: 8686
      name: http
