---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: listenarr-config
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listenarr
  namespace: servarr
  labels:
    app.kubernetes.io/name: listenarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: listenarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: listenarr
    spec:
      securityContext:
        fsGroup: 100000
      containers:
        - name: listenarr
          image: ghcr.io/listenarrs/listenarr:canary-1.0.11@sha256:1634dd5b218cb13564785de9dfcc201fe6ec576b93ccf1de5ca38cc9c100abc8
          env:
            - name: PUID
              value: "100000"
            - name: PGID
              value: "100000"
            - name: UMASK
              value: "022"
          ports:
            - name: http
              containerPort: 4545
          readinessProbe:
            tcpSocket:
              port: 4545
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 4545
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: audiobooks
              mountPath: /data/audiobooks
            - name: downloads
              mountPath: /data/downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: listenarr-config
        - name: audiobooks
          persistentVolumeClaim:
            claimName: servarr-audiobooks
        - name: downloads
          persistentVolumeClaim:
            claimName: servarr-downloads
---
apiVersion: v1
kind: Service
metadata:
  name: listenarr
  namespace: servarr
  annotations:
    gatus.home-operations.com/endpoint: |
      alerts:
        - type: pushover
spec:
  selector:
    app.kubernetes.io/name: listenarr
  ports:
    - port: 4545
      targetPort: 4545
      name: http
