---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profilarr-config
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profilarr
  namespace: servarr
  labels:
    app.kubernetes.io/name: profilarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: profilarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: profilarr
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 100000
      containers:
        - name: profilarr
          image: santiagosayshey/profilarr:v1.1.4@sha256:8a514f8429cd33885166facc9eb6504fa9ded056c737609e5e8ef32ae0afb350
          env:
            - name: TZ
              value: America/New_York
          ports:
            - name: http
              containerPort: 6868
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: profilarr-config
---
apiVersion: v1
kind: Service
metadata:
  name: profilarr
  namespace: servarr
  annotations:
    gatus.home-operations.com/endpoint: |
      alerts:
        - type: pushover
spec:
  selector:
    app.kubernetes.io/name: profilarr
  ports:
    - port: 6868
      targetPort: 6868
      name: http
