apiVersion: v1
kind: ConfigMap
metadata:
  name: slskd-config
  namespace: servarr
data:
  slskd.yml: |
    directories:
      incomplete: /data/downloads/slskd/incomplete
      downloads: /data/downloads/slskd/complete
    web:
      port: 5030
      https:
        disabled: true
      url_base: /
      logging: false
      authentication:
        disabled: true
        username: ${SECRET_SLSKD_USERNAME}
        password: ${SECRET_SLSKD_PASSWORD}
        jwt:
          key: ~
          ttl: 604800000
        api_keys:
          homepage_widget:
            key: ${SECRET_SLSKD_API_KEY}
            role: readonly
            cidr: 0.0.0.0/0,::0
    soulseek:
      address: vps.slsknet.org
      port: 2416
      username: ${SECRET_SOULSEEK_USER}
      password: ${SECRET_SOULSEEK_PASSWORD}
      description: |
        A slskd user. https://github.com/slskd/slskd
      listen_ip_address: 0.0.0.0
      listen_port: 50300
      diagnostic_level: Info
      distributed_network:
        disabled: false
        disable_children: false
        child_limit: 25
        logging: false
      connection:
        timeout:
          connect: 10000
          inactivity: 15000
          transfer: 60000
        buffer:
          read: 16384
          write: 16384
          transfer: 262144
          write_queue: 250
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: triggarr-config
  namespace: servarr
data:
  triggarr.toml: |
    [general]
    log_level = "info"
    hard_max_per_cycle = 0
    max_history_rows = 0
    request_timeout = 60
    page_size = 50
    tracking_window_minutes = 60
    tracking_delay_seconds = 90
    skip_unreleased = true

    [auth]
    method = "External"

    [radarr.Default]
    url = "http://radarr.servarr.svc.cluster.local:7878"
    api_key = "${SECRET_RADARR_API_KEY}"
    enabled = true
    search_interval = 30
    search_missing_count = 2
    search_cutoff_count = 1

    [sonarr.Default]
    url = "http://sonarr.servarr.svc.cluster.local:8989"
    api_key = "${SECRET_SONARR_API_KEY}"
    enabled = true
    search_interval = 30
    search_missing_count = 2
    search_cutoff_count = 1
---
apiVersion: v1
kind: Service
metadata:
  name: apprise
  namespace: servarr
spec:
  type: ExternalName
  externalName: apprise.notification.svc.cluster.local
  ports:
    - port: 8000
      name: http
