---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: servarr
  labels:
    app.kubernetes.io/name: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarr
    spec:
      securityContext:
        fsGroup: 100000
      containers:
        - name: sonarr
          image: ghcr.io/linuxserver/sonarr:4.0.17@sha256:02bc962946fef994e67a38152446df25c10a52f8583aefeeb6467f9dd44cab99
          env:
            - name: PUID
              value: "100000"
            - name: PGID
              value: "100000"
            - name: TZ
              value: America/New_York
          ports:
            - name: http
              containerPort: 8989
          livenessProbe:
            httpGet:
              path: /ping
              port: 8989
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 4
            timeoutSeconds: 4
          readinessProbe:
            httpGet:
              path: /ping
              port: 8989
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 4
          volumeMounts:
            - name: config
              mountPath: /config
            - name: tv
              mountPath: /data/tv
            - name: movies
              mountPath: /data/movies
            - name: downloads
              mountPath: /data/downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: tv
          persistentVolumeClaim:
            claimName: servarr-tv
        - name: movies
          persistentVolumeClaim:
            claimName: servarr-movies
        - name: downloads
          persistentVolumeClaim:
            claimName: servarr-downloads
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: servarr
  annotations:
    gatus.home-operations.com/endpoint: |
      alerts:
        - type: pushover
spec:
  selector:
    app.kubernetes.io/name: sonarr
  ports:
    - port: 8989
      targetPort: 8989
      name: http
