---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: servarr-tv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    name: servarr-tv
    namespace: servarr
  nfs:
    server: 192.168.20.89
    path: /void/media/tv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servarr-tv
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: servarr-tv
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: servarr-movies
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    name: servarr-movies
    namespace: servarr
  nfs:
    server: 192.168.20.89
    path: /void/media/movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servarr-movies
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: servarr-movies
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: servarr-music
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    name: servarr-music
    namespace: servarr
  nfs:
    server: 192.168.20.89
    path: /void/media/music
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servarr-music
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: servarr-music
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: servarr-downloads
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    name: servarr-downloads
    namespace: servarr
  nfs:
    server: 192.168.20.89
    path: /void/media/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servarr-downloads
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: servarr-downloads
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: servarr-audiobooks
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    name: servarr-audiobooks
    namespace: servarr
  nfs:
    server: 192.168.20.89
    path: /void/media/audiobooks
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servarr-audiobooks
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: servarr-audiobooks
  resources:
    requests:
      storage: 500Gi
