---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subsyncarr
  namespace: servarr
  labels:
    app.kubernetes.io/name: subsyncarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: subsyncarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: subsyncarr
    spec:
      securityContext:
        fsGroup: 100000
      containers:
        - name: subsyncarr
          image: mrorbitman/subsyncarr:1.3.0@sha256:0fde5901345dfb95c6b072eb85699f10c6c3aa7eb49caa1ccc4221cb55157d02
          env:
            - name: PUID
              value: "100000"
            - name: PGID
              value: "100000"
            - name: TZ
              value: America/New_York
            - name: CRON_SCHEDULE
              value: "0 */2 * * *"
            - name: SCAN_PATHS
              value: /movies,/tv
            - name: MAX_CONCURRENT_SYNC_TASKS
              value: "1"
            - name: INCLUDE_ENGINES
              value: ffsubsync,autosubsync
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: movies
              mountPath: /movies
            - name: tv
              mountPath: /tv
      volumes:
        - name: movies
          persistentVolumeClaim:
            claimName: servarr-movies
        - name: tv
          persistentVolumeClaim:
            claimName: servarr-tv
---
apiVersion: v1
kind: Service
metadata:
  name: subsyncarr
  namespace: servarr
  annotations:
    gatus.home-operations.com/endpoint: |
      alerts:
        - type: pushover
spec:
  selector:
    app.kubernetes.io/name: subsyncarr
  ports:
    - port: 3000
      targetPort: 3000
      name: http
