kernel.unprivileged_bpf_disabled = 1
kernel.sched_autogroup_enabled = 0
kernel.keys.maxkeys = 2000
fs.inotify.max_queued_events = 8388608
fs.inotify.max_user_instances = 65536
fs.inotify.max_user_watches = 4194304
