apiVersion: v1
kind: Secret
metadata:
  name: gatus-pushover-credentials
  namespace: gatus
type: Opaque
stringData:
  PUSHOVER_TOKEN: ENC[AES256_GCM,data:zho70f+l06JecOLHZrpDh4MY1Qf/afWN6nv6mQzi,iv:C97PdMlEJSD6WLL7dUpcCtSxAHCtF4GD/4u3eSXhnFw=,tag:NsI3Z8ld7QGXVp/ZrPKTIQ==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:aiLSqb2YhzgTESyCHyEkU1HKCE1pI7wjy6h4xNwU,iv:HJNwB3R81bUP/q/T5Q1Jzu/F5V76k3Q5L4q0jrDt5rY=,tag:gItA2FIu4z2ALq3q/X9cRw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMXI2TUIvTnRYbGJaQm5T
        Z2Uza3VXZFoyODI0RlBEMFptVXdwNzRxbHdNClBUVmJ1bVNYS2hCODFqQjBPcytM
        a0xUM2UyRWFwSFJ4YXBqYWxwTnVyeFEKLS0tIGxWMmJmWDR4enZUZldYWFJidWNq
        VGNuT2tYRFQwblBLbWgrQU53aitiajQKvZNmIWJ6ZcE2KzaEvQEYimP3ip8mBlTX
        5tDWg4zBe4z04HqwqSeUwHdIXfAi8w/E3xjUrRP+X7MffYVsNOEkZA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVzNOdXhKckthUEkxNk9m
        NXhpQnRNVWE4bnZ6RDZvK0ZtbmMvODl0L0ZBClljTzM5bjc1eFVtMVNDQ3BjUHBB
        VGpLQUpuR25WcW9JM3NPWG9RM3l4OTQKLS0tIDc5K3R5VTY1LzEwNmxFMVBpNW05
        WktlcE5zbDI2MVZxNDFPWk1TUjNtQ3cKfjivPYhJjG1ZKCS5v9Ar4p0KO4vd3G+M
        jb5KTqWZHh2r8LuqAqoMTZE1OG+9zwaANrdckOstJXamVPMcvZZ/9Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T16:56:38Z"
  mac: ENC[AES256_GCM,data:6PCoAHsVSikDkEuWxLfB8tb5RxWxs3qL5KmSwqOW0vVZhWJt0BswjJtvVOH1kyHDxWwu1Hp1a+Axhy02gnXZpn5i3EkcA71khafkEMJmevG1blvpz+lDvVNCb4uVvFBOLsnFEUVgRM87LxXjiJf11kx7eZzAY/cmmGCKVl/jXX0=,iv:d+uK9w9b8euhClnAooxFRVl7cXGwLonz6DLw5VAPLeo=,tag:hqACeSTHUS3lEJswEi1U9g==,type:str]
  version: 3.13.1
