---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gatus-pushover-credentials
  namespace: gatus
spec:
  encryptedData:
    PUSHOVER_TOKEN: AgCCmdJC9QvmJauIrqhQJTWqlQ0TJ6Kwo2mItaSKN3a58BIHFsR2BcGriV6djeSXkOo1cEnYvUz2gH4pTp4OYR2P52Vhkk6oztXPbQFldw2H8OJmp5DFRVVm2Fp1KWe/cAJYDn/a7ljAeHEqHzU4P51c2r43eOcbx/qxz8qO258midka3v4UcIqZ1+CjDBJvGvqvisptpNZwRwhzV4m743ALO1fDDb8vxF1SYGlIIzCXZfd0vahAOYGwyQtC3IjiFW/SLV+lVOfnR8SXJAHahlcABMOtB47WDU5o7BT1fWRFum8pwr2Wp93XWp4j25juF4uG42MMV2/Rs/PeuBZBKH1VjHKchJ0yf4tcgeGTxwtoyEeLvh0MKtBOivIdyLUyEwb9kP43vWyGr+plw4BjBQ9oXJLcJqxhsmg/tfgiMVk/liSb13XQu7s8k22Pj9/z7UQATx7DdaLB5HG6BReQlwUNqeI/wmWh/8yxkaNL7E5KPaZG8iI3sASob01Ea1pV+FxD5utk0ueqQaRKbjfMmucqFwDdHagLnpXSalbgacB1rPFtIrMm9/Bp+lukfsCG2+GZb7rToUCVf/zxqJtQQREnSfCsqQJkzW4k11n7uEZWYZ1vQ9HePYjcBZ7F4yDkHOP0drwpGgbs9Nwc4wa+XOzs7xSUlfMAaE5gZWN1tJaeD5C0iH8uO73EegVUNK0DDZkXyOYdRzNdoxqObL1RSsX2UcqNr8EdwLAsVv5ugow=
    PUSHOVER_USER_KEY: AgCWdXzc1nAiENHDmh2bgIz8K3AkcYgn1KWt+C7QwYmhkDdk2R/IQTGmum2UebjubIXaBJrnvkzOb74fouUTIQl+tW7wJLXC3T3OvTahqLIoLN+6A28LCG2QSskVKy2X8FKGBxJ8FbghXU2vxT+W2mjRgUJ4/C/izw2Eaj5qb5UvfngK5N6azJS2AYIu2YAHszI3+VNF14BKCdLASqxNXEQXKD+vds0LvRX1+88AGnTadbAAz9JW/raua37l3jTv8GFeZRZ3SNCQSoIEF1oJvvRBdk3Tlpc9jRtOCm9arBNHEMgkDhmByCT/bXY5rAwOjXbOGMWNneQh9sPixF0gi3M4zACqGsbl2X4wQC4egPzPiRyftUNKsfXNQ0qvW7FwirDRB7cij1e03IiNTyPRoCszTYXwTdabJB/hk81bDC7L+Pv9///SIoNmS5AnC23qjey1hkSR/nadUV3tSfSN08hL7DOMZLwjuUgvLzXycNCNGQueljhqWrm5qnKSyvAi8DYRnBzgxrMc8UgaOjewt3o6rDXCBzq/P3tFm3HLPTGqfzGXVfAm8f4sW6DLJvGzz9hx2inIenr8K1XetrpJZVcEaq+augYAI/ly7FoLYr16kRjJoC49FigRongQp0kvIpRj1X5n08h4fyNb5zDsmYil2+UEs34X4P4T0IEUnqV5DXq47feBo94ZNkpirJMB/3/IEKexOOGz/6P+JvXKuTOkBAHabQm8TDthnGCEEc4=
  template:
    metadata:
      name: gatus-pushover-credentials
      namespace: gatus
    type: Opaque
# apiVersion: v1
# kind: Secret
# metadata:
#   name: gatus-pushover-credentials
#   namespace: gatus
# type: Opaque
# stringData:
#   PUSHOVER_USER_KEY: fixme
#   PUSHOVER_TOKEN: fixme
