apiVersion: v1
kind: Secret
metadata:
    name: gatus-pushover-credentials
    namespace: gatus
type: Opaque
stringData:
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:zho70f+l06JecOLHZrpDh4MY1Qf/afWN6nv6mQzi,iv:C97PdMlEJSD6WLL7dUpcCtSxAHCtF4GD/4u3eSXhnFw=,tag:NsI3Z8ld7QGXVp/ZrPKTIQ==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:aiLSqb2YhzgTESyCHyEkU1HKCE1pI7wjy6h4xNwU,iv:HJNwB3R81bUP/q/T5Q1Jzu/F5V76k3Q5L4q0jrDt5rY=,tag:gItA2FIu4z2ALq3q/X9cRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZVA3cVNTd09TdTB1YjZS
            SlM3TkVhL0IxZngzK0JkMlJNa2syLzJXMjNJClBCd2g3M25jSTh3Skdnd3dETENW
            UjNwcVBrMjQvNW50d1BYT2crWGtvZEUKLS0tIFZ2bXpoRDZTSS9ydUdYalk3cldv
            cjNycjdGVWZuVzc0S0IyekhkOFNEVXMKuI3dsTF98pl2QdOiU0zfKrExUbKxM2Oi
            VZ1LQgf0JmrdHbc77+tEgiRpht+kNuCOGB2dqexGbNwTvpcxgBdkYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T16:56:38Z"
    mac: ENC[AES256_GCM,data:6PCoAHsVSikDkEuWxLfB8tb5RxWxs3qL5KmSwqOW0vVZhWJt0BswjJtvVOH1kyHDxWwu1Hp1a+Axhy02gnXZpn5i3EkcA71khafkEMJmevG1blvpz+lDvVNCb4uVvFBOLsnFEUVgRM87LxXjiJf11kx7eZzAY/cmmGCKVl/jXX0=,iv:d+uK9w9b8euhClnAooxFRVl7cXGwLonz6DLw5VAPLeo=,tag:hqACeSTHUS3lEJswEi1U9g==,type:str]
    version: 3.13.1
