apiVersion: v1
data:
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:yYOaiL4pzQZjnBjgHGwJ3Bs0a82HSTBaWIJXicon+MyUYitz6kPRVA==,iv:nHbQtW6i2ZrPJMdmzBCfxl5pXT1jtT6B+cY3HsGdKRs=,tag:fvc+LM03aYWklat5F6FjpA==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:1SeMxk8lh3k4hUYT5uR/uB3fLacz3QrpazwSQ9TSh5w/bPWgxHXTeg==,iv:e1Fd38oG0PO7StMRFXpB9A5dC0KPNutm1FGkvypjMO8=,tag:gMoK6UD+LUUNWT4rUxZ4Ww==,type:str]
kind: Secret
metadata:
    name: gatus-pushover-credentials
    namespace: gatus
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WGU0UENOd04zeDZQd256
            c09uOFlhZGVYZjJrMldmOHE3YXM3OVQwWHhNCkNWTGxOaE5oK0doTEJEUGU3U0Yy
            VFh5Qk9halM5dHpUelRWejZnMUgvZG8KLS0tIHV5aERwbis5cXJkVmJNdXBmaUpQ
            OFdDYjFXYThkNDFnSmZyL2VYSzBLRlkK3iNpYHtorOZwWUU5D+Y8+Rz6MNvnhgqZ
            fK7sqOXhFS2LgDHNSDS/tBqoC37kKNdIfQeYqV/gC5u4Sdr4wFP99A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:0lZWdp5UcnMivMErGN1FLiPkV1VcQNFW+JW4JeNgqiKoU098DlbtsgkYiYTkW+oPHUNosZdHuMynt44uGt7N7kqNg22UEloS8csOKckc8+AToHpiJClNXW9ktwHOxC86KFtQ5rSHGKDhB0glbEf9nbjwACqsXLAjEfnE2fbLuNs=,iv:WZ/fQy5PZXKRJFQ+PN4WkQn/pIcCJICiLDs+AH835hI=,tag:7EgS3LBZ0BrGU/DcSliOGw==,type:str]
    version: 3.13.1
