apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: your-spotify-server
  namespace: your-spotify
spec:
  target:
    service: your-spotify-server
    port: 8080
  rules:
    - hosts:
        - your-spotify-api.item.fyi
  scalingMetric:
    concurrency:
      targetValue: 30
  timeouts:
    request: 300s
    responseHeader: 120s
    readiness: 180s
---
apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: your-spotify-web
  namespace: your-spotify
spec:
  target:
    service: your-spotify-web
    port: 3000
  rules:
    - hosts:
        - your-spotify.item.fyi
  scalingMetric:
    concurrency:
      targetValue: 30
  timeouts:
    request: 120s
    responseHeader: 60s
    readiness: 90s
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: your-spotify-server
  namespace: your-spotify
spec:
  scaleTargetRef:
    name: your-spotify-server
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 600
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
        interceptorRoute: your-spotify-server
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: your-spotify-web
  namespace: your-spotify
spec:
  scaleTargetRef:
    name: your-spotify-web
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 600
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
        interceptorRoute: your-spotify-web
