apiVersion: v1
kind: Secret
metadata:
    name: your-spotify
    namespace: your-spotify
type: Opaque
stringData:
    SPOTIFY_PUBLIC: ENC[AES256_GCM,data:zZijnzJL7/LG6qfH7mBY6NiZNZKHBdvsIQXkcNk8lkc=,iv:GEwUtqNNQqVvmleVqP+0oWqIBnARvKRntmY2jwLD3mg=,tag:69i8ueeacpVEYBW6DEGhFQ==,type:str]
    SPOTIFY_SECRET: ENC[AES256_GCM,data:MDzYQEHS6DRJaYl110suZFj69hMON36XGh+cN9F0MXg=,iv:1x1/UJHRVcf41rhghurOcVo4lV35kSrdaRBhftU6ZfM=,tag:ee5jvSPbPTSENLWfRia2yg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6V21IV0swZ2drakgyV2JS
            THdTYllHaGo3YWkwMUFEa3dGeTFSU3lQeGxJCjVFZUZMTXlWUTZUcHBUSjE0L05F
            TTc3SG12OXhXRUpFSnBjT3hRT3VxQ0kKLS0tIHRHYWtLdE9yNmNGTHdXc1ZDcGJ2
            eUhLMmtHWFRxMklYZnArVGR3NFA5RUUKKyYcSwkdD4mAfHecqANr3swPPTLay1ia
            RKJLbebS22Ykq7ACiUWvHXT3jCKKIpzGblPa0UNfZJaaXPwyqbDR+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T16:56:38Z"
    mac: ENC[AES256_GCM,data:qD2dkyrFgxwELaeL6aO1H6C+MBz3yMo44713qcwcHgJTjibweZTiKa8bHwXuiTxmM/DoLyrOnu0AxuZEEMyY0mdmakCH6eF4ufmp4Zb7ao/jqvfdcMQKXd4z0/vPINDl66irQ0LDH6qi8PPYFgCIDKbCDi6V0KftFhG+XnQ/z0k=,iv:PARhOtGuDrr3MkDA8HHJsiD8e/iHQkISwgzNzSi+X30=,tag:m6lN/04QtK930GJI4Jdu/g==,type:str]
    version: 3.13.1
