apiVersion: v1
kind: Secret
metadata:
  name: your-spotify
  namespace: your-spotify
type: Opaque
stringData:
  SPOTIFY_PUBLIC: ENC[AES256_GCM,data:zZijnzJL7/LG6qfH7mBY6NiZNZKHBdvsIQXkcNk8lkc=,iv:GEwUtqNNQqVvmleVqP+0oWqIBnARvKRntmY2jwLD3mg=,tag:69i8ueeacpVEYBW6DEGhFQ==,type:str]
  SPOTIFY_SECRET: ENC[AES256_GCM,data:MDzYQEHS6DRJaYl110suZFj69hMON36XGh+cN9F0MXg=,iv:1x1/UJHRVcf41rhghurOcVo4lV35kSrdaRBhftU6ZfM=,tag:ee5jvSPbPTSENLWfRia2yg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRc0RGMnRMT0VNdmF1c0t5
        MFgvSGJuMXJnS3dWTDdXZ0k3cGpjUFdnV3o4CmcrUmtLQU5BcC84czJBMmozVW5O
        QlVXRDh0VUlrY2Q3UEVUb0FvSnBJZ00KLS0tIFZGWmFZTGJnMWFxVHhNU0RSc1cw
        N2wvbng2Z0tsNkVQL1AyeFQ2QllMM0kKYLHNHc4qkdxjI5vOvFb8Nqz5FgEmvZg7
        e3KrGfZ/qvQmWfCOK0Be/b1SUMwJBmRhQFqdiOhmeQPMhV1X6h0F/w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDV1VBSFdkZk9YamVJK0x2
        SFJvTjVpS29YeGdyd042M0ZLZFY4NnZGRFZFCjFjeDhJT1NIb3ovQm1IaGYrT1FF
        ckcvWFh1SFI0aWIxNkNqWHBId29TUmMKLS0tIDhRdmpIM29KOGZySE9kYlRveGVW
        QXJ5VXB0VXJNMUtoamFzd25pc2lES0UKApGwDUtBx5kPnGozp0T6oXO93V670XEk
        YLDcFlUXfTkyqtPwaLTCylkGyfvAH5vhcWHV3W8LAAlrN67GmV02Vw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T16:56:38Z"
  mac: ENC[AES256_GCM,data:qD2dkyrFgxwELaeL6aO1H6C+MBz3yMo44713qcwcHgJTjibweZTiKa8bHwXuiTxmM/DoLyrOnu0AxuZEEMyY0mdmakCH6eF4ufmp4Zb7ao/jqvfdcMQKXd4z0/vPINDl66irQ0LDH6qi8PPYFgCIDKbCDi6V0KftFhG+XnQ/z0k=,iv:PARhOtGuDrr3MkDA8HHJsiD8e/iHQkISwgzNzSi+X30=,tag:m6lN/04QtK930GJI4Jdu/g==,type:str]
  version: 3.13.1
