apiVersion: v1
data:
    SPOTIFY_PUBLIC: ENC[AES256_GCM,data:s5sCVOCgB4b2Hlugp1vewCDsxD2ofzIpCXZyPWGhRooUNv7sJHnWLXO2pto=,iv:DEFSZUkPFw6OTVsIY4fYft3692By7EzvbQ4MnZ6ulOw=,tag:dgxaGujADis4iDIJbjhPIA==,type:str]
    SPOTIFY_SECRET: ENC[AES256_GCM,data:mIEjFcQs4Arq35vDkyyXZTrmc0bfCKiSPo50SvxCDkyJQTdZ2UAz2/Xu+GU=,iv:nwopcmuHr+kGr/Dd/WYnqmg9gKH2lNuTHHBwPbDHObE=,tag:iqCl5BdWZmIKonQjBFN5Nw==,type:str]
kind: Secret
metadata:
    name: your-spotify
    namespace: your-spotify
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MEZCaDl3UFkvS0FpVmta
            VnVselV1RXp2b3o0QTRsNklobkpUVVdRUjBrClBpb1V6L20vbzZnTTZwTTVGdHY2
            d0JBTkEyYmxyc3haeEZWUGlFQkZKN3MKLS0tIGp5UXpxc0RjVnp2WGs1TCtwOHZJ
            NUsrUUFaakpxOEI2MWpzSU81UVN5aUEK9GWHYx/9OZRWIRJAp7a+sA/BRu4oFnQx
            KD9XW7SdmbKtT/b4M5u0rMupCxU3pREK45bWeY40y6UsFlKb7hsN0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:UMpRmFoelcPc8IEOIDUf4txrAA6smpNs4Ts+PxJBsEV+7VC96FgdOhibM2j327gsCAv8EPxowkhptmuGvfydfYFFH1nUP533ozj1jKl0FTX0j5WU5oLE7y1hYYeT4X8Mgiz5B6pJnkj7P5qkfeZoLLqIePi7PXHw2Z+Fu3BVmgI=,iv:EpuB5ACvlMg0kO9lXUi4LH4hlDGJFRqk2/0XomuNbeA=,tag:QrxolHBdk1LGqQAyGenn/g==,type:str]
    version: 3.13.1
