---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: your-spotify
  namespace: your-spotify
spec:
  encryptedData:
    SPOTIFY_PUBLIC: AgBcDngNowNw27BWN2eGEedWFWLUMwKdIWoYO75rpyLJiCFpS8QMPEIKa9lBimwwtzIlzkpEL92kw7eIzPdSPNJkKzUWlTS6GrNwqg4JYm4cXWPLOdixtkH6YQVdjUCUTnNgtd0PsaCT4thUoYF9k9ehGd33le5kb0NWLmvZeOws5p4x2WjDe+OzXeBmZf4LcmKOrQ9OvKdprSDfvvcckCf4K9ql3a1T0luAbLHThaoHBg5oLVkYoBuPKCGnolmkvCaSy/zhT3gHyiiICF3HtjHbbO0GjQbXAmWRRLQUnQK9Dia7k46gWdWyjxqOIGUNDBB3K6klBzWhdAwvOJsj2zvEhvknKlBhtPwVg4+aP+XnJ94lD1IYjWkJMwmGYMRUTv0HFpsF4bmloCuquwGkBu6xpqFmAm5FsQzN4HeZXKBA2mLN9S3h2sXhUTr60WSD2z5qKW4ANRqNn6VLorOrwA729tRbw32xuAlTdOZn+hGRQUYDTRKO17RVgWWsT3XEaThRDqqKpLbxisVcaV5SG2r7lOzPAlLsEnW0mW7AdExRAv/qd+r9Vz0GnmGRrExbOM5G8fbtpUu1Y1lBuluCScK0Vpe5Hv7yX3JE2py85/q1IjRZZRRPbORZuDc3eUFSQ34jekjj+xhdl+BqBrSNNZI7stt/ueYenKkMngWoEjZn8IPhEtlCXaXo/3T1+qCK0z9zzGVFI6owU9WhLDU1/o8b/ZPOPZI95hv8bbi8SuRLjA==
    SPOTIFY_SECRET: AgBb/65vLpCWQsxV4t1iMobpvuTsc+29CqfNDHHuxw+TCryP8j6nAumtH7sAAZTvujlfqloBjtl9J2+FY/U5raVhLVPKonfw9fYGseXddBjUugVeKZoAqMAt1QNcJPwVGDOvovYVbTuvO+jOR8QNwP1d5b+Fl6XN/0J0l/k9td0zre+v/GVU4ASYdwLBcynwyzs7eKWc3Gg22VwbtHKqiDO5qd4uC7bJDxuwFgrviRDc1cbBttbE1pZ2nOIyzRNawal7UU+m4izn0umrb4hBOcYmK/IUe8MHr1XiKvEjPzuz3ie8OLOi99vAfBAL7uJFF6MHMVQqpHNHO8/XAlrTL8zhkPwoAH2LX6tYwZB6ej8R1FhKyIoWTKM4dikr6mlIJJ0M4sgbdZwCWo4twdA/dgHXMe1ClyRjaquk+bmO+diuLFguIGAEZWSH9GW8oePKG6/jPPe+kUuDGAT6w65fRs1wV77tvI9cmN2AQ9T1dJrasrQID6NjwFiLfPwiJYpOBaiJqGZoT9tG7UDBTjFNt1eVctQ3JnlWnBIAOzt/Sh60ATzmznoWPpX+gMqSzLw7fMeZvod2vemeinzfaiaRWj6fRE6OsINXLshwJ+sh9mLLQdy0/c6jGANVvzVIBxkXNcoDeAYXlZ6bJTvDKRglPVnyTyaEcHBJjSG9q1OBOrCx8sAa2RODq+lntob4EpLg8gZM58roNygyo7bjrcGu40wbrc415iVNhf6d3v+jFsYDLQ==
  template:
    metadata:
      name: your-spotify
      namespace: your-spotify
    type: Opaque
# apiVersion: v1
# kind: Secret
# metadata:
#   name: your-spotify
#   namespace: your-spotify
# type: Opaque
# stringData:
#   SPOTIFY_PUBLIC: fixme
#   SPOTIFY_SECRET: fixme
