apiVersion: v1
kind: Secret
metadata:
  name: servarr-config-vars
  namespace: flux-system
type: Opaque
stringData:
  SECRET_PUSHOVER_BAZARR_TOKEN: ENC[AES256_GCM,data:C6HEzeVuLoI3PQ7+sflsOBsg4K7PJaXLdbpC0CkZ,iv:R5WBgDV5dZTvTOZU1/ocG5Wej6EW28rb5hbEjVOICgA=,tag:sRLXRFOJLunLRIGZurHkdQ==,type:str]
  SECRET_PUSHOVER_CLEANUPARR_TOKEN: ENC[AES256_GCM,data:z54FkmVBIlbW0STRG89UQ1f7gtYv00I6Xyd8xtId,iv:xPdlTsHG7G39bBvTgqPNVuCW1numqQqXRkcJs3D3n4w=,tag:NBl9+o8lUekzom3/ArXZ0w==,type:str]
  SECRET_PUSHOVER_HUNTARR_TOKEN: ENC[AES256_GCM,data:5v0bSj4RJeNNGYFxSdb80J/h3sYH3zxcQlikii3p,iv:QSbGDszW2eFb9FmPFj4jjJ5YgYjQhnlFAcM0Q7hcnK4=,tag:dehqDRZZUy+hEPdCSWLHlQ==,type:str]
  SECRET_PUSHOVER_LIDARR_TOKEN: ENC[AES256_GCM,data:kZdauDl9Drehikbd67bq4uHQ1gukY7Wz50VEV9k8,iv:qosfPVrlrCmzP8ijCXY5txm/bCiQj1oZUjBhu9MJOWU=,tag:WWTkiMj31FNav5xZnQXvSw==,type:str]
  SECRET_PUSHOVER_RADARR_TOKEN: ENC[AES256_GCM,data:pOiRjVsrsuQi4n5dZ/B43eXQU5HOV21P2GdA4Of3,iv:mvqABeYDJsszn56ZzUGO3e02TS1m7brWFbC1AGRFVgo=,tag:x4XuhVZoC4uFHAboWL5oaw==,type:str]
  SECRET_PUSHOVER_SONARR_TOKEN: ENC[AES256_GCM,data:47KKKVer+Y9TfKkBvbbkvdO7+lfrLPlVwEhzofFc,iv:AWOC8ZLBJ+Okh7M+S92Sl9yFj1fcA7RjDqc+YAnnH0M=,tag:QtZLHYzsGvOwKVwlZWoMpw==,type:str]
  SECRET_PUSHOVER_PROWLARR_TOKEN: ENC[AES256_GCM,data:FP4o/kwLmfki2jeMKJ7IW7lifqCMgiV+zNs9SZYp,iv:CsE4M15LgERTmZX2DPrB5R5X0sT8UiuIieFZ/nYrqdw=,tag:DTXsQjP3T+xwl+E9tYQdSA==,type:str]
  SECRET_RADARR_API_KEY: ENC[AES256_GCM,data:EQ8c27mil+nyxP64Pg7PXbwbJftg0hqcCkEeAyMmBZA=,iv:0oDJ+/5gsr1B48Z/fVPYgw5vgvf169bK1joX2S7A7U0=,tag:5eC42nBy+eyqSfOJgEempg==,type:str]
  SECRET_SERVARR_SLACK_WEBHOOK: ENC[AES256_GCM,data:LhNBsedGu0fvbMOnEMObAT0M4UXUARZE2ieA9RyCiO61OE+smQsEvJ+/xpf+Cbt2hgbi0YeJEl6glQhMoHPR029mSYTCTrwu+s9n4eJTRbqx,iv:3Ud9+C46VftVyofQGJSRHv18XIX7x0G4GBvDbe5RFVw=,tag:Evy3mtl7QTSLXNcoD1MF0A==,type:str]
  SECRET_SLSKD_API_KEY: ENC[AES256_GCM,data:spNu8BUTNYrTCpgaMIY1xlKFpDOy9pxAlCHvP76q8Ki7UkskqBKlI4nuKpH0wdrQ2lGD0s2ewYFNFjq3ISW3Ag==,iv:uywd/fdxcGTIMTElJoZyoj1fvPitBBzWoIeVXZI69T0=,tag:KyEoPPd+asKZbYahvjRCMQ==,type:str]
  SECRET_SLSKD_PASSWORD: ENC[AES256_GCM,data:shwK/g4=,iv:ncH/ymVu1BVX+8r1a9CULig+eh/GK83KWbPZJph7K8k=,tag:ytVzHNMmny59gWjj9UFMKg==,type:str]
  SECRET_SLSKD_USERNAME: ENC[AES256_GCM,data:jKoNlPA=,iv:EJuNupWz70er+NfeAaorEIuxkm3gTcQjJjSYaFh2KUg=,tag:yUU/Tu3Q0bWn/gR/7yjCbw==,type:str]
  SECRET_SONARR_API_KEY: ENC[AES256_GCM,data:QjF2Z+Un3HFIku3LKKrenoD4Ow87+egzaMrHjqVy0JM=,iv:hn4WAOAwYfhhp7wLsCpZKdqQDHZe5A8T9ifGhAeq3xY=,tag:gSEUa1Ys0pTqvn/XuwAMog==,type:str]
  SECRET_SOULSEEK_PASSWORD: ENC[AES256_GCM,data:M0IwOkY4oRavvKi5m/qg1m7tuEk=,iv:soJnzvl76HbNahHc2ojb8DtbaN4j+0+QTx8wSKaNo1w=,tag:HS1Nr+GL89bz6a7/IUCavA==,type:str]
  SECRET_SOULSEEK_USER: ENC[AES256_GCM,data:G4kDSqof,iv:yaZwm/FZG4Y01lWNXHwwxRnDIoM6LTxpRmXS5ZxLqiQ=,tag:/BBff5MRprUnFT3evi3TeA==,type:str]
  SECRET_USER_TOKEN: ENC[AES256_GCM,data:H2r7KNLo/nI2u/5tGWD5rSqMiUuEGZG6GiaQZOxf,iv:S5CsA+VwufQjNxmHj5+uBviYlXiZXJlMYMNyV+nVToU=,tag:SLMRBzf/RBVLCmQGtPzBtA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NUcvc2pqZXhxcytRVmlS
        ZFNLMnRocmdBRHpmd2orQTRia0FqVjk5TmhJCnlRS0FQeCttN3dQc0VKRSs5ajk1
        UGsrR3UyRUJEYS9SNjZZNkZ2V21TZ3cKLS0tIHlLVDNJUlFKUnhKY2MxeWdYSDI4
        aHBCdTJVa242NGRRcmhkbzcwN3ByZDAKFy4a9X0Y5GBlJ4fj82uK0BvbFbhnu1KT
        VsplkAzZZ4UhpFFVjpepjeQs6vqZcmnYtvE3nt1EjE2mIjAK0WwIbQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-17T21:37:51Z"
  mac: ENC[AES256_GCM,data:0N/wUn64EoTuw7RZLSEteTZxxTLRo94z5YYesHG4lWXaf4QWhMc7L6Ji43B6VGR6mQFeWvaTzw2n6XGZoE2HJe1YcPjx8MYYJioaw2suO+tAlBH2l8Si4NB1gqpIWjJj9ixvQCJlevjz13mWlXa6Jo2/uYXhWjR4MuE73OI8t6U=,iv:USGity3E0qXy3X0KgwlEYwk4te6Y5Kg15XgxyNS+bmo=,tag:STVgMfseVYxntO1PjfoSdA==,type:str]
  version: 3.13.1
