apiVersion: v1
kind: Secret
metadata:
  name: servarr-config-vars
  namespace: flux-system
type: Opaque
stringData:
  SECRET_RADARR_API_KEY: ENC[AES256_GCM,data:M20wBiw3k4a5W8yxQ38z7cDKCc07s/1AC5NMZvIpBIc=,iv:zJ4nuaUbYRhjtwOEJLH+nNCBs55X39H5L153wxLntHE=,tag:afqojZwSke7wQCt+klvKPQ==,type:str]
  SECRET_SLSKD_API_KEY: ENC[AES256_GCM,data:hoK/Xv02QngGJF41GsugGwfrfsA3kic2xy+UQc8OKGaycxp8aNyARaU3fI5BiJ5AVLscXSXSyL/rWq4o5P8AkA==,iv:Ir+/cSxD/cOONiouDlM4KLhz/SKZZHwQdLG2Zo0K4+I=,tag:J0D9e3e9nRHiPqsBiS23iA==,type:str]
  SECRET_SLSKD_PASSWORD: ENC[AES256_GCM,data:nVBg82c=,iv:bXo2Oei0Pk01egcAANwz8geSMscSWyFQWHbF54gNW8I=,tag:X2ylWCuDTJc2ob2fqh9E9A==,type:str]
  SECRET_SLSKD_USERNAME: ENC[AES256_GCM,data:B3Jozj8=,iv:BUxSZpBfS71b7P02ywKZLeN8pdO54XaijQvWdoTmLnI=,tag:5pLiRfdtrUHw5YmuwumObg==,type:str]
  SECRET_SONARR_API_KEY: ENC[AES256_GCM,data:cnYm6R9vXcDM1CLkiHR4Y19F/hZ1hdPVzT2e/SmeJqM=,iv:YXzM5YyRZpbQo/rET+nVVVQQFJwoX7uKzXJQEY55Pq0=,tag:jGDvQcMT8bBkJ8+SwxZ41Q==,type:str]
  SECRET_SOULSEEK_PASSWORD: ENC[AES256_GCM,data:JwfzhV9UiT6RIQTYZsaeAed8rFs=,iv:oz7jj1oR1NhU1x/+J16rWbAm2R4voicjqa+CeT8ene0=,tag:OImwi9Sh4WOrSnGKVDRVLA==,type:str]
  SECRET_SOULSEEK_USER: ENC[AES256_GCM,data:dFcSeCsh,iv:AGu3RdRw/6YBF2F73cH3Ybu+0NsW9dxDgtNh9AF7ZGk=,tag:QPd2WNBhv0rwI9dM4dDd4w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSmw5Q1VZM2N1QkVvM1Nv
        WmNZQUwzSXkzU04yenZPMStoL2tUR1FGQ1ZjCmcyRUZ3aHhBam9nMG0vZFpoNno5
        V2tPT3ZnNmZXVFUrNW44SVFtWWI0SUUKLS0tIFUyb08zRGwzb0xYZ2NGUFFpN1Nq
        RjdjbGtmajkzbkVMU29IZnNJVDJmUGsK354ChOcXggQzQLCLQyujsGjzO4cUePcU
        MaHBb8Lsl462NlQHDoiBpJ2vGL+vKQikUHCX28+bOA/s2Dv6pcJjUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-19T22:53:26Z"
  mac: ENC[AES256_GCM,data:a8aRTB0+QGFkbbIXBvF4E/RyVo1ZMRCuz29nFdBm2vf48UBNm4Kk+X0dutEgdPR1aBEK+6aWwTXhzmUsb2UPyuJCe747PSRXguNpuiQpoUFIoC1HxPdNniXgaA3N2pi9kWrYFCWxzuAKziClYn6LpRge9NHQxmJUhN066Rm32yM=,iv:8wE+6AKAa7z7p8Fni0nTQnt8vDSUMUWMAQv0kLq+XvA=,tag:wYiIwhT94xpicYz9NxNCag==,type:str]
  version: 3.13.2
