apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: metube
  namespace: metube
spec:
  target:
    service: metube
    port: 80
  rules:
    - hosts:
        - metube.item.fyi
  scalingMetric:
    concurrency:
      targetValue: 30
  timeouts:
    request: 120s
    responseHeader: 60s
    readiness: 90s
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: metube
  namespace: metube
spec:
  scaleTargetRef:
    name: metube
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 7200
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
        interceptorRoute: metube
