apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alloy
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  dependsOn:
    - name: loki
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: k8s/infrastructure/alloy
  prune: true
  wait: true
  timeout: 5m
