apiVersion: v1
kind: Secret
metadata:
  name: windmill-sync-secret
  namespace: windmill
stringData:
  # ENC[AES256_GCM,data:9U7f4Ht2xt90DFjiAo7ANWzIdZJQ9aY9T+egNNrBtiUN4n5SiuRnDdSpWUSYcILcbfI3tUfhwC1zSidwmve++9vwCOtGr3K9p8NABQkQqvcYUi8OvztdjMgOyb5oM2Fea1GgBqmTXNtwSkTY9r03VSulHQX5HlHts9FB0ojhn7TUckYsyLbrODOPWqYUGDEJgjmas25O2W6mD1tVs3oqR/5X8cyMdIWjTGE8g8oLnqfoNV9Z5hfivq+pkVDxMhSg/nPvSYAHapS/08cm,iv:vIf3utaojxEh1y1LGus6uSML9XGD15i+nAj1RB+jBfE=,tag:5fJnGCoz9BVfHyMdtd8bAw==,type:comment]
  # ENC[AES256_GCM,data:qTuCh+bDn3JFnxb5G82gFqTKTVLBemPnc/Av8XyTvEBS05Dup3rpuwFoKt7Te/6THu4jl/jbGWJXj43Ty6pUbCNxS3BCrOwY0+9CcYvh4wPQgQTXrBQPt7ICSaX06kc+4SMeqLaibwA+XOSeeeAfReORUV1m9UzyXNs5VUkmJH4YhCBkV3krtOgEsx5vMrvZLEa33+oS5vPlJnE30V0M2HqzmeKn9cS/txnleE81xudtI3bG/yS66U0P24Q=,iv:IYSaJ0C2CFm+k7AGaZaiEHJcvCjumfS4iLR1+zVYvPY=,tag:pUfVd4tUI3mHXwjszX8Lsw==,type:comment]
  WMILL_TOKEN: ENC[AES256_GCM,data:vpK/SCiNHQy0lFIf33UthD9JY9ngwEOtlmA6BGXooeE=,iv:OhDn+hBjfSZClPcOVLFsFflixuMBv4DTQUNNqjD+u94=,tag:6e8PCoEuEMeCNbbqSs9ucA==,type:str]
  # ENC[AES256_GCM,data:LzihNzLMksI70ZnJRPo4TbFpuaWjKZi44/vxylKS7W+pGkw+eoWwB/drOYFiHzbVDOIcqPEVEUObQ45Nf7Jib2d4WfOwCbliLxmwAdT6A2g8kRpLAs8cynPjInCPFl6MD8u3xgmsi2TQ2FPnjnfgosHwKyMQW93+qz9n8YBcW56i0izlvc3/b/WF5INs0VlCGM0WL+Z/tIjp1jRkzWOkbUIjxE4lZpsAaYlvos4kZrwcWVBnDAYoCu+VefSBZqAtwaQcPKzuPfSFR45YCtukTA==,iv:z+e0uGDSUQ40waKm+eMi5K+aZPwhL+a3WBxSV8R0o/0=,tag:3pIxp7wsjsSyrtfe4ABoYw==,type:comment]
  # ENC[AES256_GCM,data:qTFtDko0bms0fJlzTysVbjoSM+W0sdoazWIwSRP20HVogBwRDrsjYp86kqrbGTIj74pk/w2yZqUg1lUEJbPUKHvzWEgfJ+MTHDZsBUxUfmTLhrV8WTFC/LEqJRQd1T713xQvzC0mE6zYE/+jBiYINP5wDtq6d7bh3YADNQxPSVYpw/yvy+llIVr0Qv0PInN4r5wu67LuSz5DjEfZhwkemd9qqEeT8gkSg6JQu5cmBD7MAz4mJwXYkdrpBwpjlNyeHu1WRJa0jNaHf2dsSlrSkQ==,iv:PGYyMSqqnRtXDblTlWMSX+nYOaynYEwtioUxyrhTXGA=,tag:gQ6O9IaR5FJ/zUJUhcujSQ==,type:comment]
  SSH_PRIVATE_KEY: ENC[AES256_GCM,data:+RrOgYn1Y/z4tQ+hq78IBI8Cx06pP9WAni2tE44THlOSXhcNSU2gLXQ0R2Nb6p2FMpxbVww13E6A6f7wOYkTjt1/hjdnuDIW5lWsr5mCZ7KlQvDOTkMk8bLSgyEm1k4xo348GirMKpxdz89i64wdtxsdZNGAVtd8GGQSQCLwhJkSUoUUmLfoMfEwLyWcUzZTNeEyRarKGnD3lXsrD0yzge6pH4BF3WaM53mkVpVp23htSnF2F/0d9c4sTY7x9xJwCwbxG8VfdIH9RjYhOrbPJQqJnqZ2Jh52btT33GpaDQhAOgS7cgyXie/xySCACQ6X9Az+GvP7fITpm1gzFTjohLg5rIEvDW/h0SPmAwXk/q4sc2erM8Af9JNAehWCwJElEuXHGEEK3eu/NxcuDMeMz83BGOq2qDR/kPSq0wTJD/RLS4+ITlAnnwD6tq7JMEy8H7fv1FrnLO+ug9LJ+CSQaWuAYOsLDyYcu+CpT4uv9jI2hFvNRhwAdXhFIed8bJVYpy0XD2Nr20lg3z/qowhYRGz8nRzbcqsy900kzYtTWPMxbk8=,iv:RTxCbfVC5u5FodrGL9yH/M29auSinORWE6R/Mvnby30=,tag:IQLnkElX5HeZULDhRJlSUw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnS1FCUmljVnUwdng5Y2pM
        QS9mOHovVldQazFNeDRkYnJydWVvemxQOENRCitndkpNY2RLRW9ObjlkdnNiQXEv
        L21PeVR4Tm5XM2xsaXdzZ2hGSFBreEkKLS0tIDZMSnRtQ0tWRnZuSXhVYjhCVmxt
        Um1tNDZqb0VoOXh0YWZRQVhheWh5cTQKiuRSz7f/rlLYd46qPzfDvZqNOWUup6IO
        VOUyyq3C22Io3iu5MsvGS8WkhN/W7RixX/WKHvmEU0iOS7I3bBHo8A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkT2xCRGRIekIvdTQzbHlM
        YjB5M0g4MndhS3VXZ2NGTlpWYUo1RXBQMVRRCm0xd1lPQWtZRTFlc21VU3dtN3lL
        czJiL25hNnk2ZW5KY3ZHcHhYMGNvMmMKLS0tIFBjZmN6OGdERUhKbWR3c00yTWRN
        RXhQNitTVEFCSWxNZ1E3VzVzQ1l1cEUKc69tbsEBAATaC3P1pE1NLO2EkyWLZN1S
        9NFRhPRCLP55dlf42hE8vqbiyU3U/k00y3DKGmsjjJ9ZoZcPRvQKxg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T01:32:51Z"
  mac: ENC[AES256_GCM,data:HKpg0Kvotmj6Kec+uS6mdhaR2JpEYLOUFLsbuiUrmThZExRmejjoWocSYanw4ZY0BE+iyo+DNUBsgBw/6OKHHjsrkjVQftZVB3K0k+N7k7kgDFtP6Ut5EwjsTAa9HDAFcLYz7RGCgiNVmzwS7RpekjTyg8VmNvyJCUrPGYul3D8=,iv:rDND+7iWH5JCKpvVLw6QYLZgMiI2DSCsV2zaF+u1w1Q=,tag:9HfIpYrLoz62HaQjJ0pHsA==,type:str]
  version: 3.13.3
