---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: windmill
  namespace: windmill
spec:
  encryptedData:
    DATABASE_URL: AgBhfMuexPJW7x581gTLvMCeevR2HonZlrt6XuPyVK0mQHN3AmV0VD6SL+UmAiR5DBI9gVe9mdkzVMdUYBsc1OKz93BnzILA0caFxH2Y4VW6Bw7kU2N+PQdXF6vL29QFZvJjxumIHhSaKdwPjWyP0LbcUt8oSLLH+qiPpnPAM5UXxe+p1zTMBFpNUlt0vzbvOn1Y62C2RCFbsHvDnxl4Is2QGTsMriFMn7TgLRUUf598OvES+FaGO9Hf7oYdnhlJQuYWQuJeaTISfeewJlmfVxaF+j92M9sLPw+uvUKSbzHU3BSgQmfh0MMxg3CpB50NvXjEe25JO6L8ZS64gVDzgbM8nB8FcBvZFnC80eezyb88+h2RUu8qnr8zhh+QzKG3Z+SK0HAAs22Fxqj8MT9BeoRPXyMyivAGrC9XC2WpiyBjXpZRcDG77PVmC/C1hXQZo1pSJ06u90+gOnLQPPeVpG72A70dofWhPEk0dIu8g6+1gA3qIHc6+HxvY7h8TM56SuWRNaGLeoWvBptbB8oIYY5vrQvvTgs5jbqThxrQ6W+ktQ09kcJAIKq20qpDNjljgd19kx0CvxRLhSgSU2dHimy52wwaU5PapSxIXOAvP3vHQvexrmJNoz2PPJh7P6VIqbNTQlkZ1zqLpeY+YeeEFL1ANlF+yNwbpzJXMuhkugTToART5rnspU2JP1fczF7ThimPW9r5rxy2AYB7HyU8GZyOjY8Ar12hBFkFVa/9ziJr6rh9LQ3qX7TNyyc0IXM91Jjz6CxM1uhA+6ZGnQRWb8kKQqKzih8bxgLAAmH9Hf+xHXmanL9j3DN72QL+uoecMfM5H8Iq1N0c025X
    POSTGRES_PASSWORD: AgAX/p6egelZbaXxxFFN9OirdW1z25ID87cQ5JAeabQ16bvT/1c/dDlk33YpiuyRMEj76k4bJ2jNhgOMGDCDn0wKmCwMvGPMfowx73B2pHjkL/fhfFoQvUdXD2Bb6LoeTYesgCzqeDOIf1Uz3OJoGManAZcIpqHJQpYWllP02y3rLnKAyP5yXcUFjHcTQ4Z4/qptIRX6PYhbzXE4MTKzel+WOSRVKF3I7DWxFk2xKnKAxQL4hu/fpIpY5HLEbN5AFtls70EICMT2zJCnZmfq4jbhjqy9/58Z3VaPjhNIr3ZkP1is3dBNdhguizQYQ1aOL14OKQnW60XBfNCGTru+Kv3xifXB2Ps7hTS0ciTl2yfR0jtK+unHCQ1QBS8QL+BmW95VgEFDOzhRD3VhC7AQtnmyoQwONMI2Vxt+cJAn1UK0WMjKTOorQuWcqSoFJWqQyBfgeoYhiGKc4L45MESnRUCL/UFiGap8zga27fiH8No+GBm7ZfP3WR6gZFsGTCj0mUZMTK9CUHee4xFryLniGTqzrGyG3gWiLEAdUXIgNAuI7H9JltugMHlJeGnd+sapvuKrVmixkj3JeJ+uTkJWOGC4H8ZhTX/sqOqrESKOxM2mRdcFBkuoEmVEd2ynwsGcdS8O4o2Cehwb95wnmvG3ju1o50WaG10h/uZwOrO/aRR8kfARRKryko/TxI7PGQjS8Ox06FXfo0mXl5RubIqqvlwUe6UAAiWIl1PRe//iX3s=
  template:
    metadata:
      name: windmill
      namespace: windmill
    type: Opaque
# apiVersion: v1
# kind: Secret
# metadata:
#   name: windmill
#   namespace: windmill
# type: Opaque
# stringData:
#   POSTGRES_PASSWORD: fixme
#   DATABASE_URL: postgres://postgres:<POSTGRES_PASSWORD>@windmill-postgres:5432/windmill?sslmode=disable
