apiVersion: v1
data:
    DATABASE_URL: ENC[AES256_GCM,data:IY5thvIycEef7ZpcO7t6TaUdI6X0lq5DXVgOAbCoDfeuGk2u6GL+cnK2+sK6YnY1R7ojli+INcX1jnlfTH/+SkRxFUqO3Qqx2Qy7mMO9QHN50Vw2dQFS5UFyNZYawLHDGbE28WdRKhwrckCqYg6kZlzLGkDBILRRcStZpLKuzFhtgUsKL3V7bfmmimI3t1eF,iv:GexNYzzskpHOgAkebOeLMUEbq3RTPcPppOHaaEdxFWQ=,tag:gkiUyA6E0LNVZKUUU/x1og==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:36rBRlgUn0onvHlYS+2D4T6RfFKvsC6WhmB2ouX7vue6SgJSoGwJ8g==,iv:Dpp+emY+7ktK0C8UOc/wGnQsnJDllDT+H/fXcgfWp40=,tag:DcjkPtMZC7dyW4LP5aOzzA==,type:str]
kind: Secret
metadata:
    name: windmill
    namespace: windmill
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1T0ZnNFBKYUVBL2RQSHB3
            bVVIdFhYUjZnbW9TeEFzUzFUUlk1YS9NWlNVCnI1dnZaRG1Rb1JYdWUxUS9hUGwz
            eEVqLzM4V2loUzRvU3plZFliYm5YdnMKLS0tIC9MMEtlcjdjeFJoYUNVNkFwOUw0
            VlVFNWxFeXFuY0pvSWVia29YYnRjbFkKcnWFE5DVeHYX0bERTqkMbMeNTgWfWpzR
            Fe9P6xJuElj/eN5VZ6WR62MbrSIusQQjpRhXGAr4gyLRLDe7+Q8hfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:xdc5XtN3SOzzSO7aH9ShK8VVPa7s6jQQsEa+aL0fEEpNF+l1M/h19oncJpYK/y3DfIwzeVXaZx+ttNEjw/Ra+oPN82Y1l/d1KKbVii8eV9n6xARt1r8E9NQiXA27A5hK1zTmmOhHzMGgFz3XGCQkEuXqwcy0RJiDKpJoBtjSUi0=,iv:oPJyUyY9/nmNNEozLaS8pnk7JM9TR294KhM2R1IEtEg=,tag:uAoevdv6oBDXmZyoSJFfYQ==,type:str]
    version: 3.13.1
