apiVersion: v1
kind: Secret
metadata:
  name: windmill
  namespace: windmill
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:0cOpp2ML35wJJ7wwtha1pMikotkVC0Dz1kHU9o32MkGb9lmHQTzDOC7KWaM5E1V91Z2Jg81Ejsku+Yv5EnRdvKgs84HsWno2eRgVIU+ExaM5A/6pD1+y9nU9OprotAwbF1Q1vJStqudVqg==,iv:aFFCxaoH0a5zXvq2dQs42oRsApLOdeq76hdw2fXPJQo=,tag:E1wrwZBCaWtAWzxO4rEUPw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:EsWK8n3bY5dEFp/8c8iuKJr+YJoy3AqH6lgItEV6,iv:1MOHkrFZVMChe49bpSvczqm+DUEj/8x9PfX3LvLGoa0=,tag:4/XFlBY6Q4FzRl6g8QQiYg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbkZOT05KS0piWWRzNnVY
        UGh2dU4yV2JqMDZTODhZN3N4Rk8vRXA0dnpVCm14dmRVK0NhOE9CWjQzQjVVcUpq
        N2t2L3hQWkE1ZzNFbkpSemJCd3FmcjQKLS0tIDE3TElNWm5Md294bk5aNkIyY0xU
        MElPcHhweUJ3aS9Ycng2TmNmd0JRaWMKbNuFQTpVgYhAeiE9FbhxIj+gENzbaPNy
        qx7+nAlHcuLmECuEmTx/4yISGIXCApJKKrBPlcv+mmQN7YtA6Xaw6w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T16:56:38Z"
  mac: ENC[AES256_GCM,data:Q5/bWhhD0Gb+nTgkTOjOY6ZUV1KdwiN8eNhd9U73h9MaBCz6m6Mw8ZR1sUnK5frHPcOf3pEThhio08XrM5MR8n5yfCy4zDlrJpbPPkts6MLHHTUv7OS/GoFxAG5YpMhwpS9G8gPDxegKUeyzQPON8W0PPGMJjecH1uRrX93IuQY=,iv:akaBzgjJo3pA8KOsGO6RB8vyszjF4dZDcs0wjFOz9d4=,tag:Y4iIS1vHln1R2IJZLYeBLw==,type:str]
  version: 3.13.1
