apiVersion: v1
data:
    APP_SECRET_KEY: ENC[AES256_GCM,data:/oRBt5PreU89tD/iEC8Hzm3tTUM9cdfDAVKH6/GABdSCsiqI22CieA==,iv:Zv09ODZcaxJiXD37gzpg+Fn49XGjaPjeK9pyDhGewro=,tag:p02ZuEc0laoiGudWl/Qprg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:vjTQPb4KSMyTaAOnng86zL8We/BUowB5tyWzGSjbjxxeK9zT3XPy6TRc9CgBV01inT3u44urdnauqpGHI/Qd/GJt7uhPjkoTqfGwVSthIrNGaCfyf17/kZz9jxLcz43DEUGZUmJg1xAJ7zLOFnEXYT45I1bjKxJK,iv:ECr+oqSaBkonA76Zg9a+3QJuHROrsfp+CpT2AJURNaY=,tag:XVnCZw+9BITjyuntpB0Z1Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:oF9w5loGWrvYTZIozkhA32XqCN7dN1RmOQHIeB7QLTHmsQYMvPu38A==,iv:HLlPaCvn4RAlbGFGEKsU4iQDy1WmsdKlHUrbDvCphAc=,tag:ew33YNdpzFRII3jBTfbG+w==,type:str]
kind: Secret
metadata:
    name: fittrackee
    namespace: fittrackee
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1R0JIT3ZaVEh0TWlEeTNT
            K2VDaHJEUkZycSthekhZMGlPYWlJNXI1dWlZClF0aGd2RDNSS094WXFhTi9TQjBv
            SzIxVVl3R0t0bnJ5Nlp4ZDR2VGpacUUKLS0tIE1DWVI2S1FPemptZFZHQWJ4bG1a
            NDRwNkxHRGxiQ2lkaUh5d3RtOTQ4OWsKpzmy6vWgAwdh/eINhOlyBYaAc9vZfz+c
            1uSaS0+Ub2RP3ZyvJvmJQwu8F1wpZagLziYypFeWpV0eNIqmqpLjMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:gisFqL5+yzTDfP7U0bsLlm81IOepzVJzLRj4Ba79oEfuxWCHrjHxeKTpuM+1A9seIqD7CSzFqVUZOrE5k8A9Y3sI3jZor+MlUeDt4gS+8+DMDI4rq3yp2QyRTHq90Behy4Xt1t5cy35jbL5UYT/NaRGqvDWFLJv93vCFBYp0TSA=,iv:sW44uvfQyxVdimKTUyTF6VyzUDIMClkQtz+R4jnMsV4=,tag:d3EzfSzx8JWVnjjZ78Uktw==,type:str]
    version: 3.13.1
