apiVersion: v1
kind: Secret
metadata:
  name: fittrackee
  namespace: fittrackee
type: Opaque
stringData:
  APP_SECRET_KEY: ENC[AES256_GCM,data:Yg0U4uM4AbxnS6YO1kX+XgG2li8M7+04TEhgITug,iv:Oeu4Bl3EmlshmS2pbBett0dKsVPJxnGfukrZqG4oxKY=,tag:HUbFi04mBXLoDhafYJJRaA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:r3H/Ijosr42Ti9Vzs7KW/t/wKhxbbNhL8vJWWzH+PrEoZcciUFKrbd5rsh1BddHfqTiD6/vvtSE3274653+YMvIBt94HxhPU+u5YGMLaHrrWmQpIE0bXpA==,iv:TdacTf/b1mL1eGuIfBGtrfiMPP1kNknT8ynANIiQnk0=,tag:5fAyO8+pnK7k4g0YsCn/pw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:Ec4kg8wml8Q9NZmpB5ztLcT6iSqlDnSEUzpryQ==,iv:PdUEKlhhI5LHlxoIbgDVOoyx1wf/8T6KBM2qW1pA1BQ=,tag:GT7SIoTRY+yck8BfJ+s5BQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcWNaVVhwbVlua2ljVzZF
        Q0s4ZEFUczFOWHhGRWdPWHlBRVR2bGZxL1FNClMxVDFUTE5SUmh1YjZKS1Z3eFZm
        TUpNMUFBcXYyaEIzUnk1b0Q3T2puUDQKLS0tIDZnU2tTSkYzVUZmZS90K3kvZDRW
        QlNKK1VsR2J2YlB3ejBLMnBIUzRnS1UKTZeYWPMfsZk0AsXNnN7ELWqU4Ij0as3h
        TjQtTFJ7XH3Nc9zBB21W3piVtODrxvjhzXPi0AuV4rPCsSdEzk753Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERXZGd1c0Mlg2YjFpcmZx
        ZHFEVlMwT25YT3BJZXZha2lWc2h4UjRQa1ZZCmF4d2JBZlNHT2JkcjZuRDBVc1kw
        bi9zWGdCaityU2gvcytQdnp0TVRyNncKLS0tIDFGZ0RiajVvZDM1b1NZczBzQ2hX
        OHBycDk2cDFPN3JFZlRtVTBRUGY1elkKHtZXa+cq2hubTGCDqaTVZC68Fh2VBe/w
        HvdLHNfBVciT+M65M0WtFKIW/ZNFr568d/OBxzIRbdhzoXmDcE9Rhw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T16:56:38Z"
  mac: ENC[AES256_GCM,data:HUKiiF4TpURi9oFu8wBb5tjAQuRnNrr1oibEqTgGv62T8bO+qttS1K/9+vhGH30xeh0E2rucrcgBY0v1JY3uWmLNXvp1g+tiCvY3Uv4JbtzapnCLQAJQRhE1fOBfbpZf/lTt6n55JfprCpsMvnMtuQt4K/96b0db8jE1HDmCm64=,iv:Ja+hSlM4hhaPc2eDAI5JzuU51+kJaQ5zRGsz4RGw3UA=,tag:wcs33VyIqaHRPXKx9pNbyA==,type:str]
  version: 3.13.1
