---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fittrackee
  namespace: fittrackee
spec:
  encryptedData:
    APP_SECRET_KEY: AgCZP0Xvu+ppv9e/0vjiF6LzkzHgo0ScXK0JV19oaPboO8UKYDB5ofLFmwrcIMpyen+S58oAj+YkII+gv1ois3U7kGeCPu+JVTOps8BAALYX6vuvsZJSalwtvqDNEMm/9FwTO3fwwioK27PlD2nWu8XfHq97Dk+TSNzu9+jitAYedMXjsemGgIAmEqmoyPCwsLi1QdCcgE2IseV96ZjVxiMc3N4MZWIIOobd8ivaBoZjNjN4GZU8Kjy29XkvTCLWzr0ZLndbdLeCw0bUmKG3QxNCFJ5AcAeywaCbOBUEAmyL0evJb9VocatJQxFWSFuAsDe7xzBqSi6x2MNpF7xn03r3ubAotANMRrDMG00d7du5C1Ai+rSLuPV9FR8It87bnb+cQNfcp6TwCgreVVPy2ZnVz4spCGwXUpfrqxONxPGBAkIoZ5SbfAj8fY4a741yK+Lr8rc2g92Eu+5Ik/Wvk33cHkTP2qGKt28mOUb820lZG/TNHQ+zOumFnJ15MK0F2AgVupqZ/gLp3Jh7yjpUfgH128Tz4l6biO0TXtIDP2QnHAGgQO6Ho02smoVTMU0uKgmdU2xtk2PbwELiC2jQvLKF97a5tR82ltgNTl9hNbl2vH/PEyzRlhaqeHCiwUcC9b7gc5Dyba6Y4f/kYQ3QWITXjojOZSJSNH2vAbN4gFKdWnKLkmR4zUR0l5TMQqfX7zte2mo6jhXF6E0ydgnBShoxCPBTYflWsJU1L63ve0Q=
    DATABASE_URL: AgBU/dT1lEJyp4lwtHkRpAnnd+09qR5lQi27ZitiIc79cAATqu2sAigDC+fCPzZMF4zMm20qTuA46aatIYRvCey+WBduZDZ53REOswdr/i/OswmwogY+gbtAK+rBLRsZGIGaOpYEYJdIuFRALdHaHolv4dWopAUFyiKx6I73N39RzxQth9xf1iNrSGLbQyOSoYgJtXUZ/A0wmXOrhH+/5anhzkycUxNbNoZzNY/aYuJBHGBLoKUqxWBo/KycdogDvA8GHlchb6HVTAEcr/tbcWw/aLyvgBYAgyihuHouOOa2dopjs634S1wrmjEKi34+pe6la9+10fje11qGbowv+q/dHWFoKd3NQpXRTmhIF55CMoWz6yASxV0ieqPCkoPOn4+x3b6HkLSoywbeuUsKkb85NrPX+nq8qDM7nDb4qEXmsg5k6CJFJeniyvZjAIRNM8Yy8mB4Ioys/kUZZ2D9G07WpH6zPCXoqWLth0SARswTF9+erq7UaGkvNgMW43WSQiHxoRjBWjpBSi5TofcU+/XWJR+7vBX/ZSslbovYpVqOY2ZZoMdGMD8ApbAz1CPaM5hDpDTyomD79n0O2BNpnpLNvbTY9BcJw36OKOc0ZYbtYNwez+hlq8R8OEPC3zjNiYh1xQJXc/PavR22wwQg0wLkYB+UjoFtnrp5nmsgB5IiuuoQDslGTAYXFI6XOPc8OBIG8TB43TXhqTxORbNbSJX9qhrLgMpvjOupBiEWR5ItABq61UpVGf7vdOKm/WRZBw03q3mbNnI7wMiJVoXBSaIfTKD2kxfYPK4C/b5NAffRjwnPOjR0vHZ3
    POSTGRES_PASSWORD: AgB3nlPts1O6/tRlzKrRnwpM9aenT9mSTHP4g3fO2K0MXZQBucfPpr/tN5gLP4YjOiCESLiw9sQk2eY5AJeQXkiQEMEle9T9BSIEaqA1svRS8QW/9pvh49DfcBcM1leAJ8udf8yLyf78FgNzVjjggDvgFcAgCnVOyabTXQ7xOGU33PU9txOCyX21rMngKI0s6rLUamz/82FkMRDKKqcz2DgybZYAVxmFs8BmDfQTzLSHd125LSy9Vve7GndWwCmBp2L1TEwgTizxkKKTaypz1vGN5GmEh3T6BtxrdN52DUbjY6bRZcmOjZZy7rkrKDQYlhElLre6Df0xV+MKxFhHnheIJzkY8eZbyiV+8vGAyKGWhGL/2B2qSsGhz63/PiwLiySJo3RPxT6SySb7ozNXhrr5lb2cH5DB/npPYGM/epB+ScS5MZz0f9EvgAzyi3ypC74P1MF0Y0nSIAhXKIufpfNnebu5zJbwEP9uT3TL03U6YDcVWkdzqureZ/6vBidKBDlB6Hr3+iwWMmqbovTwQWaP26ZwMTBYidl4+Urzhe1Gqyb+S9DdQ8v0LqDuELeZ8gBI4UmalLGqf1Un8/oHfp4mSzhLR24EzhdP991lDILQPAUpwQNmOLf7VFeVPI1XqSRYqjs8rqzRjFBfXQPxeT+mgWGYshA80aNTtIhEuerTdTJZEk+sLR2HEFJvOrGEOOSuRy8tp1TH0QK3MYxnBoQJvvJQ3Gu1fi6shJks
  template:
    metadata:
      name: fittrackee
      namespace: fittrackee
    type: Opaque
# apiVersion: v1
# kind: Secret
# metadata:
#   name: fittrackee
#   namespace: fittrackee
# type: Opaque
# stringData:
#   APP_SECRET_KEY: fixme
#   POSTGRES_PASSWORD: fixme
#   DATABASE_URL: postgresql://fittrackee:<POSTGRES_PASSWORD>@fittrackee-postgres:5432/fittrackee
