apiVersion: v1
kind: Secret
metadata:
    name: dagu-vars
    namespace: flux-system
type: Opaque
stringData:
    SECRET_BACKUP_SCRIPT_SLACK_WEBHOOK: ENC[AES256_GCM,data:qOTWiSCFa+47TT1shqkOzFwHGdcQXNJnWLhflbLI82A9TmmTnUAhiZjkk8h48Jiv73j5G0GhjjzGfijmroftQmAH1INu/i8UQkfO5P76DusD,iv:ggopjG/C2cDMWAskdvRTC7kZAYOhumjw8FyAcQ9pgeo=,tag:EpcGQiIObFpdlWrADMBtFQ==,type:str]
    SECRET_PUSHOVER_BACKUP_JOB_TOKEN: ENC[AES256_GCM,data:tRFGsmoyBOmh0qHzryCvLX8DJTm7eWA0nM4C1F1j,iv:Hu2ic8nOpJIiE4uS+tuDtnHO0Vt0hBqiJpWI0FXVA90=,tag:JRbTOOn1YgAsdYmHnrguBw==,type:str]
    SECRET_PUSHOVER_USER_TOKEN: ENC[AES256_GCM,data:OnukxRhj0oQDQVarjr2cCzGNxSxlMYztDi1OILSV,iv:xubaHlDhLH9VhxQ0bjeRnb5uUk144cK8cEW9Smv53Vs=,tag:fAHIPgYt0g4vU2/22f4Y6A==,type:str]
    SECRET_LOCAL_PBS_FINGERPRINT: ENC[AES256_GCM,data:kunjTBgKbptsYyNYyz7ZgI22k67uyuFt7Fc25DCB2zdYQuGNztZOenl9UqLMRCBNscKr483PCVQXi034aEglfoUOZrkqhZS5wLhlzph/ekOeExhLXxpaV4Vgn2cQFNo=,iv:uZIVgOuIUNJ0xDGTH++HWdV90Bc7tPOUEnifUAIBLAk=,tag:Yk6+4RN37AZXp3o0lY5XLQ==,type:str]
    SECRET_EDSAC_PBS_PASSWORD: ENC[AES256_GCM,data:TE3OdmMHjOpYcA==,iv:kNGKHoEa5uQlNSnUl2x+hN12COInJbpsyUQc3D+dUBQ=,tag:wCq/6NRBC+tHM7y6u2bcYw==,type:str]
    SECRET_CLOUD_PBS_API_TOKEN_SECRET: ENC[AES256_GCM,data:m946e99A6frbZVl97CFT/1eAoBYO7c/ey6yp9HjPL2cwuhAd,iv:mKV9TlMcQZ4t+4MJ6YGGjhGboNiwKjhAT8kEzVwEsL0=,tag:fHH0hQMUpS3m9RfEGJoooQ==,type:str]
    SECRET_APPDATA_ENCRYPTION_PASSWORD: ENC[AES256_GCM,data:42vgoJnA4maxVDBc7OGkawZrdpIu5j7ed+cQcNh+Kwg=,iv:arKgakMGYmZACaNjcoTN/0F20sHakuArv5LtSRKfW6E=,tag:k40wHUaDDyzQOeKVo8/l5Q==,type:str]
    SECRET_PERSONAL_FILES_AND_CLOUD_PBS_ENCRYPTION_PASSWORD: ENC[AES256_GCM,data:baiu8dyWZzFqOP1Gp2riyJB2z9J2TlQW4alUEJp0,iv:jPDSH5Ka1TGeXfLXPox5tGjMGhxXNsFzXS0WQP+fTSI=,tag:/ne7yYYLCUTp6qFLo0Yzvg==,type:str]
    SECRET_K3S_NFS_ENCRYPTION_PASSWORD: ENC[AES256_GCM,data:KI2Lh0YoH6hrjgw+LH0XN/Zc9sk=,iv:lq2iJT2NXalXCv8fnq1sGLXsX1ET3Tx353V3W6ptsHI=,tag:Y5ai4qiX3pdAmA3HOPsNTw==,type:str]
    SECRET_APPDATA_HEALTHCHECK_URL: ENC[AES256_GCM,data:XhXCupatgGNePLvISPxloiSBuXpiSoubHtkcK4MTCtN2mtgnyjk2xgHwpppdkBF5Mddm7i1x0tA=,iv:o0Y7UPkOmHiwJiSeGCsg9Un3oQshPEniCHP6MBffMxs=,tag:k31OvzFpbNTU8Y9n8E4IGA==,type:str]
    SECRET_PERSONAL_FILES_HEALTHCHECK_URL: ENC[AES256_GCM,data:3rLuRdpA+ER+Hpibs5qkRZ++MP5MVT6ZY5gI0z+b/yKvNLE3V17ykFIF/tjBzNMeF1mQMJ6vAMc=,iv:szKnGA+JJIY3zrSyLGNOfqTy+OE/2+/KeCLSsKlaPMw=,tag:SefV57m2UeyGayo1ke8KJA==,type:str]
    SECRET_MUSIC_HEALTHCHECK_URL: ENC[AES256_GCM,data:QlqnO2vUmd7c53Mz2RXc+3gQ2kutk8bUYjDEx50rFL8GO7dWq+fei4LTz+ME7GMstA9EX+ndZhw=,iv:I3mnG0ozmEx6zcaQ14mE8wcew6h3VPDoADKurXDncoQ=,tag:6o8BYGn9bqYvmmTT84+UgQ==,type:str]
    SECRET_CLOUD_PBS_BACKUP_HEALTHCHECK_URL: ENC[AES256_GCM,data:w1esBpaOIR1h2TqS/zbsxk40Fzhu7HfoRy2s5bdQNta5BsyzBvwMZZVtapQH1luC8s4nu0EvJjE=,iv:MmdoRs2EjWOjOXM+UVCn9Cq91k0bZ5ob+FHP1qGcZko=,tag:g+1L2XsArDoIlTw8+B5HFQ==,type:str]
    SECRET_K3S_NFS_HEALTHCHECK_URL: ENC[AES256_GCM,data:BoOmH6bw7fs1//Febp+Mjd6vJBHkRePQwpDfTJby3g/4rOf0verEhEGWxhb+mIffCYpulxl+Evk=,iv:yAheOwudngv/G+FKGRa6HnaAIXGescEKf7zBbzVXVk4=,tag:5BljXX1jpMZqsuEzj2JXOw==,type:str]
    SECRET_K3S_NFS_CLOUD_HEALTHCHECK_URL: ENC[AES256_GCM,data:8lVmIPQd+fjtNtcljnQD762xg270FDiwQEJ7MNdsaB4qxRLbGj4SQh1bL5TZIo3TMa/AkVTelf0=,iv:NyDvhD1/7vLSaGX5ysdNPXbQjMwU5aYcC1dOg116UQo=,tag:ES09TCMPGdLteCQLnp/FPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUFdOdGZ0RDFkczM1N0pH
            QVlxbGJwWkVKRnU0RWpQVmZvL0t3bFZTOVU0CmxlempNcWlnbG9FSWltbnd2cU1h
            ZERuL3lYclpKSWRIdzlyeURZaHYzQ0EKLS0tICtEcGRnTTFqYWVoOVExb1ZaZzEv
            bVJOcDFCRGhXQkE4d2NFN3MyeUFyY2sKIaIFK4l9eSlet4ylHCiS8th2TgEP6kDj
            0jZRJ4L1jQ0h04kR6WORQfFMyhjI2tJJAi2U7we4TIYkMRLrJQ4agw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T20:26:34Z"
    mac: ENC[AES256_GCM,data:Bt/amzpolI9C60r6GR+BZCKgZmZznt4haRTKgDN724mn76pd3vej4CkAXE+kHFI6dfJ9r6B2bcyDduL5u8Jrm3YOARMQFQaA5/DDbPE21ACnyaetzpRGxciVHkn2gDPn5ULRJSCGT+l5B+dNOkwhwoocGbtmajyFDL+RVadCPDM=,iv:IngAsPinaZOqk+82sdVGPOwy99zExCMNGyWigbvLW90=,tag:BR3gCVjcLH6jcC9KzoKGZw==,type:str]
    version: 3.13.1
