apiVersion: v1
kind: Secret
metadata:
  name: tailscale
  namespace: tailscale
type: Opaque
stringData:
  TS_AUTHKEY: ENC[AES256_GCM,data:hQ27eJ2fHGzORG8ODHei/1uV2TtCB7IF7/qzx3Vr7laOBQ1OQevw99lUmfV3teAJ/Np+RPNBFy/z7XSnXg==,iv:c3C/82xODLpeSYxbjvttcQetFhzgyXZrvsQdqS2xuF8=,tag:eqnn+Z1Z5Y2QpYpR4I4P8w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WThUVFlPL1phbG1qSThI
        ZjluaXdocG0xd0FkZHhlay9FWi9zVSt5cFhRCnphYUVtVTl1RklVZVJHMFluMHdX
        aHdMcXhvSHpBdmxkSkp6dC9NT1ZNQU0KLS0tIC9MaDN3MnB6V056K0d0dTdiblhl
        KysvM2RQTUN4b0trTGFIc3dJWHRPRHcKC8rFHV8okPfQbubhFyWJqphw+iyG8Cqk
        QdUiT++ZKoiFEXWXHwfouA6OpXY5mIJedFOq5U6FLy+mnr6hXP6nBg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T13:50:02Z"
  mac: ENC[AES256_GCM,data:1fLXbEDTeMwB2qXBcIX5ksEi1gXr4R1ZIgSXt+6qkPA78WLiYb1MTaYj39AAvgPMt4sOyAd0ArX837fsmEGjJ3ueSs6KsoRx0H4thLPHmIVAdTAnrX8qUwlLVhlog9tSpEFVcVrtlOWD5LEhN1nnxjidZaV2NHWS/HRVp/jltY8=,iv:Tt36mYVCbVQEQQHjlCFH2Ek2rR60ppJNwOlprCcQ0V0=,tag:w3T3wrX7wzy5Ol1DB6h8TA==,type:str]
  version: 3.13.1
