apiVersion: v1
kind: Secret
metadata:
  name: tailscale
  namespace: tailscale
type: Opaque
stringData:
  TS_AUTHKEY: ENC[AES256_GCM,data:0C4N+0hD9SK25XRFj7aOw8cH3oIeXd/9Yhtyq/1H9H4ZLWFFm+seN+gI97fWFVd6E0wdfJV1jrh3Nr82PA==,iv:7tnNE/Z7OVrwRMWmQM90X5FQS6h6xQ0HGNtMsWQrNr0=,tag:hXnPByxkWLOIR3qa59j+DQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WThUVFlPL1phbG1qSThI
        ZjluaXdocG0xd0FkZHhlay9FWi9zVSt5cFhRCnphYUVtVTl1RklVZVJHMFluMHdX
        aHdMcXhvSHpBdmxkSkp6dC9NT1ZNQU0KLS0tIC9MaDN3MnB6V056K0d0dTdiblhl
        KysvM2RQTUN4b0trTGFIc3dJWHRPRHcKC8rFHV8okPfQbubhFyWJqphw+iyG8Cqk
        QdUiT++ZKoiFEXWXHwfouA6OpXY5mIJedFOq5U6FLy+mnr6hXP6nBg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T12:19:42Z"
  mac: ENC[AES256_GCM,data:Tp01DYOEaqjTpm3IvbRtPJIqB0q+qfWTbMePdazhxoDLjov9y5YJkxUDPDm5hJtzsMsQzkwmSN3mD+G9L+fPvsNoEjxc24dwYVkgKZHvs5JhSh0B65pp4V/t3WEP/1Jz6r4u0LVbLyQBT/vOHOR9NAIkn5dO0cHG2ZDpgOIbdT4=,iv:4T+tZROdXaD7yp9fXhQg5QJi1Au2VEhzoM0P5/bwMWc=,tag:0yHNdwadERbrTM3AMSj4rA==,type:str]
  version: 3.13.1
