# Pushover credentials for the backup-verify CronJob.
# PUSHOVER_USER_KEY is the shared user key from gatus.
apiVersion: v1
kind: Secret
metadata:
  name: backup-verify-secret
  namespace: dagu
type: Opaque
stringData:
  # ENC[AES256_GCM,data:N+4i23I18+3hFQt9f/3uJo+50ea/uM4aPFuwO2qY0IrQltEtsfu+40pvHTFcIYz8iOH8LYjhd4CCFiSoBX45fGEbQjwj6ZldRP2YHoFhzMqDCiwgWc7zPbgFoyzSiV+ZnK/Ns9Sj4LpoceEq6JUeuHtCOjyl0yNLS+Kk38wY0HQ7geQos2wsL/UIGNSbshyHp8dRffrvDH7E0e/cPNGS0tHaDa+u+Lo01MaQokhnHVOlA20ljQ9Krewp+YU=,iv:SKMsVooWgYxjCKIibvb39dGMYe2PTipvoUDbMt5Q6q0=,tag:CtQ8k4I3iuLNKJeEU4gN1g==,type:comment]
  PUSHOVER_TOKEN: ENC[AES256_GCM,data:7QcdOBJXGlIDYP9fDA7GbnPd8O1YHbPbYXVKoHSa,iv:RadYoFqg4EujUznxLp6zyV1B2H2DVgp/++rhRl2OSC8=,tag:N03elOw9XZNVptNjYW2b5A==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:AhrMdHyJBaBSVCZysvD9qENHqsYyMHUu7zuH51tr,iv:chukJ9EW4GI1+LdBu16/PeJvUOQnyA0dqoG8iIv6QuQ=,tag:W6Z6d1j4tyDobyqomknCdw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbnU3R1ErVkhXOUM1OE50
        bSs0eWRDMy9nRHI3TGE3eXBTcWVoSVdoamhFCjkwaFYzcjVNY1FyOWRhQVlUdEo0
        T0luSGxONFE0NGpwVDF4ay9SMHhNV2MKLS0tIDFEVHR6K0p5QXM3UUpWM3Uvd1JV
        ZUF3cEY4a3dsQXlqcDZMNHN1aVNXWjQKziosztTeqKG292cxIEqoZ3FU5SJJar6V
        UNZ2goaJ5TssPLgb8DUlzgXeGMdDau19xLjAe58A/65HTtVewApIng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQnJLaklET3JHNU5keENm
        MVFKREpHQkVqTmJTTisxemtWSzBobGF0eFNvCnlsTUVNTlhKRFN4aWpObWQ1ME1Y
        TDI4N2xGQjJ5WW1ETGdyTjRVeGlWSjQKLS0tIHlDOG1kVzB2QjRtYUZlOG5Vc3ph
        dy9qOUZGY2pZNmR3bTRhZHR4RGk4cVkKQJUD0hzrE2ZNkLjGmMJccca4g94tEqfD
        j2q17Drk5t5lb37gOPUNnYyE3OC9g/mmyhBmQ9X3jLNY01sMwQUIiA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-26T22:54:39Z"
  mac: ENC[AES256_GCM,data:N818+fbiV5al1Y5ekEsCQ6FwKp3eVgzSCQyVCJc2GAB6Iz6vVhGKGdTqINnvJycb6mUwUKlGovAVJNtd3tlSeVc5I9QhnnnzOCbTm1m9PPO3+S3G21Lkbzc623egsjfLhBII2gg9lI/pah9TAktLcOj1W7OzozZGPga7A2C1LE0=,iv:Chut6M/F6WfkyHA5BbTh5OaxaeT9ISYWVP+RfU6Cgoo=,tag:ajpQlF6f2gXzT5VMWnO4+g==,type:str]
  version: 3.13.3
