apiVersion: v1
kind: Secret
metadata:
    name: dagu-ssh
    namespace: dagu
type: Opaque
stringData:
    proxmox_ed25519: ENC[AES256_GCM,data:RjE8DlfepJi4ReSgMgF2afRDP9q4wglxLi0Y8HG7o7zJRj0QP9c+XaCNvd8yHIfSQkWuQwLfolMOzQnEtJLR2CM/bMjOgMArwPFTRnXzH/1qUQJG4Q00tobmFt+QUMw9P1CascWxAuWgNrxtbUPuOrRI987P54AuM2RqNeGOOB0CQJTQdP6DHhMVlMMYvpAN3wabyVtZRFrU2oySOr389lg6KPOH032wKIDsaBtyC3biUdh2sQBlbyjmuobkfCZ3IBmoaIoze3hoFsgvI3He/NVLymdVldF1CpcN60/QA4L7GZ6RRm+DVr6OeHg7G7z1U4CB49Fe6YBuZHsdHdPTFnrg6+Ob0hlBsI5NsJ+8YWWa0yIB4a1WQ1+CJdbumCFGEcdGCsEH7llpsw5RRqVh5VwN8H302igL4gKprpCpDXKckQT6lGUQQJIDpnJ1uggzXef0YR/yjipH8He6XAWHYk4iPe/BI77NI70wcsPp5RHhHHG2Szft1CuT8QtwQdmErVX822sWQ3cUucsbSuXA,iv:EFTTwHpC2PLQdHxdrAKe4ACl+/vWoJaxAhZi7dcl9DI=,tag:+pnNxzUQGoQEKsXwnOPutw==,type:str]
    proxmox_ed25519.pub: ENC[AES256_GCM,data:jP4ng0uN62SqgWbz7oH7BxnNmkT3W65/6LwKP0q2TNEiCQ7UXezvpmvOa1Vxtrks+8CyTYMG2CKsUYJnr/lu8/yPhvXduC3+gLd99Biv693aLvNYGrco+m17KT+k,iv:e3biGrh6TVUebkTJQXujXbJfSRTF92eky0i12PelBIk=,tag:MfOc5Y2jRBXqeXF+3mAUPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTHFIaWxqSDE0bUd3RVNG
            TG5sNll4YjdiQnNaUm95TDJmK0hpdThtVlRzCnFmVUhva1UxWnowMy9XM1lISk42
            WndzNTh3dTM1NWJkM2trdldOLy9yRDAKLS0tIFNxc3krNzladEplRHB1MFJHdS9h
            N3doUWxmeExENWtCR3haMjdKUDFNTlkKMlt0k3fQKLa4XkdLDKCY7lv49C0Byk+R
            Rigc/fetg3LCUO5xiwFh2W7x0zukmeIIi2N5AOsR60xDUnfCwa2AKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T01:47:56Z"
    mac: ENC[AES256_GCM,data:+xdnIVG4CzehIuslNh+c8X8U7+JCtnsydlnRXuSVBrYy2VQkJ2QbtiIJ/4GoXy+rp2Gwxl3NfzChLljYXNF309QAT2rd6MVr83rR98CLLVxFT+03E1/UF+7Yi7jOywX+mYKUpROw7o9qklmBPrlGJ/f60Abvq4hQEU5Y9Z9WrGs=,iv:8bUvZdOYCjnX6fLHkCJ2WiPnJQCVnR7AHEzLps5pNYY=,tag:Kxp14guovrHP2l65k4w5hw==,type:str]
    version: 3.13.1
