apiVersion: v1
kind: Secret
metadata:
    name: dagu-ssh
    namespace: dagu
type: Opaque
stringData:
    id_ed25519: ENC[AES256_GCM,data:9GMwWtJ3hQUCQBLrhLmTQ+t98JyzN7OP8kStg3002XgzFxi1vwi2ARgG0xZTWwOvpkQl4khmUe5CUqxLSv2YqYfj1iV84GBDjLoJlVEc/aedidtoyQn9sahBEA19fueixa+BEtoT3Ma3WkrhefFWlXLaVFqvuHJdbbK9+rphbKIQ35a2bbAdPaBj7iJx1bO4ige9QG7DrlxyTPfbxsOdysGZkb2EEScTwxdH/Ry7C7SfL9okZdzdSHu+gl8+4QQQqR8rRnyS9s/+Hz7ZPVQV4GJHCs0/nvO3w0w8ZG4iVfrRUqeQwE8r44LqtJ09vZD6Yy41KhJcieAvDGorikVB7+MvDaij1jkQohI2HS1w2HzRzheCAIDooF0JtsZMileIINgMQ2+1MSFdFkpmZ9MOv+Jw+Vd4oZ6FTISez+XdCLQFvuN0o+5HqgBD3aBwKwpuqZUSboTZBYpUNxlES9zMJvYn8H3IZ/TnKcuAO9BYIpqe4PmjaQBYgpYZbooaFvvlLPaT5qPLoYIVhcZ1AkXG,iv:rs9V57Sbi3QeFynttOmB5xInri+0wKZhN9c0BagaTpA=,tag:o+pEI3MkSmRmgcTCvHMVaQ==,type:str]
    id_ed25519.pub: ENC[AES256_GCM,data:+wSuoLHTU+P2i54ps5NlGQ/hEUywofrSc9Pw43d0lGa7ACCpwcVRx9fjG4DvSg/ZxDRg2s0w0nh6BbmHmpB6mvhaSZ/V1vYPOZ+Zk8XD56xzZmvr3788LONp+bCY,iv:Vp0ji2FkZ4V5MKjj2h2+C/2fbPqr0WbIlYYCWbR+kTQ=,tag:Ao70lPbXXNVHcl2w2Jqk9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaU5VMDNpRkFsT2paY2ZX
            ZE91eUQwOHRLeXZNSklCOTVtV04zOXh6VGdnCk42emZYZEx3OEZrMzVBNllrcUdn
            QkpBRGVlUlFQYk9uZEZKUHJxSkprRHcKLS0tIGdVa2lrTDBIYVU3RHJVU3dONmpv
            TnJnVm5rQzhSQjFDZElDM3lORkk1WWsKx5WUwKa15jEQ/zigMG74is1225ka58Zv
            MH0EBkpbc0AG97PohRzuT7FbMENl7rWoquF7o7hgVxJucA4tzr1OLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T20:26:34Z"
    mac: ENC[AES256_GCM,data:uB+JJ3vGgsCw6PAYqhgLGj5H2TX+cZwnuPjUOk4P/8FNM5gGgVQKUUdEm7+j6V8tzNbxnaEsDtS9N9/3C8PbhOSwxErlYS+C5nmMWbt9OS+9YHKDtbs/kjzm3zGAgjigPsOfKokzkmfElCoMKZVRRyAjPEwP6RHaLgz4JBFM9/I=,iv:TIyW8nNxKmxL8q7pU/C/hKss7KJziUeVJK3JmVm/Krc=,tag:cbAZ6t18ihf43PNIlnz4vw==,type:str]
    version: 3.13.1
