apiVersion: v1
kind: Secret
metadata:
  name: dagu-ssh
  namespace: dagu
type: Opaque
stringData:
  proxmox_ed25519: ENC[AES256_GCM,data:RjE8DlfepJi4ReSgMgF2afRDP9q4wglxLi0Y8HG7o7zJRj0QP9c+XaCNvd8yHIfSQkWuQwLfolMOzQnEtJLR2CM/bMjOgMArwPFTRnXzH/1qUQJG4Q00tobmFt+QUMw9P1CascWxAuWgNrxtbUPuOrRI987P54AuM2RqNeGOOB0CQJTQdP6DHhMVlMMYvpAN3wabyVtZRFrU2oySOr389lg6KPOH032wKIDsaBtyC3biUdh2sQBlbyjmuobkfCZ3IBmoaIoze3hoFsgvI3He/NVLymdVldF1CpcN60/QA4L7GZ6RRm+DVr6OeHg7G7z1U4CB49Fe6YBuZHsdHdPTFnrg6+Ob0hlBsI5NsJ+8YWWa0yIB4a1WQ1+CJdbumCFGEcdGCsEH7llpsw5RRqVh5VwN8H302igL4gKprpCpDXKckQT6lGUQQJIDpnJ1uggzXef0YR/yjipH8He6XAWHYk4iPe/BI77NI70wcsPp5RHhHHG2Szft1CuT8QtwQdmErVX822sWQ3cUucsbSuXA,iv:EFTTwHpC2PLQdHxdrAKe4ACl+/vWoJaxAhZi7dcl9DI=,tag:+pnNxzUQGoQEKsXwnOPutw==,type:str]
  proxmox_ed25519.pub: ENC[AES256_GCM,data:jP4ng0uN62SqgWbz7oH7BxnNmkT3W65/6LwKP0q2TNEiCQ7UXezvpmvOa1Vxtrks+8CyTYMG2CKsUYJnr/lu8/yPhvXduC3+gLd99Biv693aLvNYGrco+m17KT+k,iv:e3biGrh6TVUebkTJQXujXbJfSRTF92eky0i12PelBIk=,tag:MfOc5Y2jRBXqeXF+3mAUPg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WWxkejVlMkpIRm1Kb1JK
        dzdoNUxYOUs5SW1VdUE5YnBkZS9KaGF1OHdJCnZucHdPb1RNYXhpZFNnNXpzNHcx
        eU5LZS80azBpaFNGTWxTNkg3bUI0UEkKLS0tIG5tZko2NTB3R3BwUWJFNCs5SW9P
        ZkxSb3VvOWJyN01JME5LRGFuNUZ2REUKpVUwm3X4nDdNHk+pKMt8D34lKMCJ8A3s
        ITzvei579IE7IJGU0bVIFSxu9FwxHHK9mNn9SFv1whTsKIm5/Lv3Ag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSUR5SHJrZGgzeDhTWnJa
        NytMbGlmNW5OcU93bWNvdmtvZ0w2TjJwVmhVCkNzb2lxaVhuTGNUWnlOVkRGL0t2
        UDBROUdsM3NxcDZYNTdtQ25nOWVWTlUKLS0tIFZ5LzhuQ08vZHFzMm81aGZrclAx
        WW5FbHN4bSthMzMyOWQ5Q1hUSHdOcDQKsg6KM/k/D5uuI7FppxS8UapB2LdR/ACb
        b0jn92+bTEdETxPeJrxAK3sv+otIk/HNfSISDWs7xJgUitLk6jP5DQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T01:47:56Z"
  mac: ENC[AES256_GCM,data:+xdnIVG4CzehIuslNh+c8X8U7+JCtnsydlnRXuSVBrYy2VQkJ2QbtiIJ/4GoXy+rp2Gwxl3NfzChLljYXNF309QAT2rd6MVr83rR98CLLVxFT+03E1/UF+7Yi7jOywX+mYKUpROw7o9qklmBPrlGJ/f60Abvq4hQEU5Y9Z9WrGs=,iv:8bUvZdOYCjnX6fLHkCJ2WiPnJQCVnR7AHEzLps5pNYY=,tag:Kxp14guovrHP2l65k4w5hw==,type:str]
  version: 3.13.1
