apiVersion: v1
data:
    API_KEY: ENC[AES256_GCM,data:v93MsZCp01YHpyFY2X7M9q21MwacsNfTj9scmw37sh/+r3/ID+KgKqq35uVFowZ2oCxHTeZM7hSYvyJNnihvmtt5pYrqJRp/1+/f6/3xoukqSIUJrSXsRGrp0/4=,iv:dMe2M/tq1m2yTNaRLfSWrmhXbAIBCes3k8nA1T3fNFs=,tag:olLRSF14DocgWHi//7POMQ==,type:str]
    API_SECRET: ENC[AES256_GCM,data:m8ZPA4z3L6y3Dk0PcZrRb0RNzopA6hIQ3WgQTP9p+NSsl5XGHAvlQDsRH92lbij5tlIdZH7yW7ZJmfaLjjSOkwB9qk2BUm6vgLmNjBseZcnRRgG9VKDVrOQjIRg=,iv:CcMEli94mRxxm5wIJgiRaULFtnwZlVxU3xZ/Mu3wRJk=,tag:o6eUc4es3otwITLWwGDDkw==,type:str]
kind: Secret
metadata:
    name: porkbun-api-credentials
    namespace: external-dns
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQllOREJ4ZTA2VXYzV0k2
            Wk1pbDdzRlZEYktva3pvWFhwdmFBR0tMelVFCnlTbHpqTEJlQVR2VU5VK05iZUhC
            QXRWNE00d0s2UVhWbDIwM0h5MzNlQm8KLS0tIDd2UWVGMDU3aWE3WVBUSFY2RUhw
            YXlEZWxZdlpxZFhraXB1STByU1NBczAKLvMjc9Cw68uDwmVELC2t3x4ZpXGCE3fc
            +qk0HvCgWRqoBf7bYT+YHaZeiVfZWlZYlyF2Mbu66+rcF3+9S+nS0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T15:35:34Z"
    mac: ENC[AES256_GCM,data:+k6FBfxEK+0fVD/QKrA304hZ0fgn/Kze9pNT5//HW8fuDSUv+kyScr1N8IBhW15Z22yAttBXXJxgDZTAi6x9DgXdn9Ytr0KJ9S9+rq+DXPsVdNrqVA7YhmQKz3h93DmSI64b3ck2NeuC9n1SPDXhLJZBhIAgHDL1clkuM0ZoUBQ=,iv:YbOW2FHa/CTbvb9rfKODfq1s4T9aMQtf/o377D+6Hds=,tag:fnhDuxfjM6BcRwm4RZc01Q==,type:str]
    version: 3.13.1
