apiVersion: v1
kind: Secret
metadata:
    name: porkbun-api-credentials
    namespace: external-dns
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:bWxwJWoEGtui3Fm+uElJ6TM/rZiaIqTYA6rDwzZQcBiFXNwtu5CNQb6PWvXk6cwe8JH3c6t/SqbAZslRS3D5RAKPbdw=,iv:lKAl/FoEhYLWjsri2pjP1dyNnJ4lyH8RrlDIqv/hczY=,tag:y1U25qlyeVRTHrKYLY28hA==,type:str]
    API_SECRET: ENC[AES256_GCM,data:GII5dWkA+IKtf+UfKm4/UQ4N/Fid0DSvuBCmCm86cbqgMoMYU44FsApxtF4Ym+w7j/bUPylTb3I9E9UeUc7qjpqY+jM=,iv:+/XODqyx6UKxshbKdncB+DmEySEq4NzCPA/UlmC2WYk=,tag:7tn8npsOSHXLMhPdPd7RcQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvejNVUUxXSEUwT0N5MmdS
            OWJBOFdKRytjTlBXZlZrajIwamJ1Y0JJa0I0CnBsdzhZWGxldGkwQWJ4ZGZoVjRu
            b3JnVzY3S3YxQ1ZhVEJkLzJydEhQbFUKLS0tIHJaUmZqT2NzeStMSG9wU20vLzUy
            UVpaZ2ZZRHhjSDQ1N2pMRFpZdVYwZEUKCI2zADSJYS5xykVYqLAO46os2n2joPmr
            eN2OP4XZZaZVST6k/N07svjzViTLcu7dtfbjRGkWPY+DLEUZpY0f5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T16:56:38Z"
    mac: ENC[AES256_GCM,data:IeWBBsAFfBnOf/YgWQ7dKqbff5Iuw4QjG5beKuxW2zXXnBoEkDRcK4AtG1P38Ui0ds9MqZomubo1zTyPZNIj2b8JzUzofCogTHiZ7HeFgMkODRhZhnSfAZmXA0oHxfH8vFv/63OqpVsFuKZQ0OkgFO2O/obrMlaFlwseFIMNiEg=,iv:f4yhCblAgDJZzL/8oJ1uNtX6Jg37iAy2ykIt6IBpSd0=,tag:D7Z46L7yBFSugQr7x75yxQ==,type:str]
    version: 3.13.1
