apiVersion: v1
kind: Secret
metadata:
  name: porkbun-api-credentials
  namespace: external-dns
type: Opaque
stringData:
  API_KEY: ENC[AES256_GCM,data:bWxwJWoEGtui3Fm+uElJ6TM/rZiaIqTYA6rDwzZQcBiFXNwtu5CNQb6PWvXk6cwe8JH3c6t/SqbAZslRS3D5RAKPbdw=,iv:lKAl/FoEhYLWjsri2pjP1dyNnJ4lyH8RrlDIqv/hczY=,tag:y1U25qlyeVRTHrKYLY28hA==,type:str]
  API_SECRET: ENC[AES256_GCM,data:GII5dWkA+IKtf+UfKm4/UQ4N/Fid0DSvuBCmCm86cbqgMoMYU44FsApxtF4Ym+w7j/bUPylTb3I9E9UeUc7qjpqY+jM=,iv:+/XODqyx6UKxshbKdncB+DmEySEq4NzCPA/UlmC2WYk=,tag:7tn8npsOSHXLMhPdPd7RcQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpREk5TXhZaW83QmlXU1lS
        cGZvcm1vMWh2SFI4Mi9FWXNGTmJ2QTFld0dnCnY0NjEvU3dPRHQ0TEcrY2YxU3VS
        aU1vZkhlYUp5M0JNaFNvcEI2TDF5M1kKLS0tIHdoNVM3cVJ6OVE5Tys1MzN6VUVv
        Vnl3OFNFVVdaY3BMVlQ2enhBWHpZT0kKzxEhLtQ0T4Xb21FEYrowmitoKnk3g94A
        IMoJ9oXztKKdx8ZrwCYlapRtgQo3FfsImrJu0E/O5vBgMTxgiIgSaw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwM1NDMWxMKzREdXFXalUv
        ZXI5WHFsdURUcVJIVVBXV25TRkJMVFZ2NEhnClZXMWRqNWNlWmxvL3Jka21peS80
        Wmd2cG5jajFNVUNrM1pzQ0Fsb2dkWmMKLS0tIGNwbmNQU2k1Qi9LeU9pZzA5ZEdu
        aXFWVXFOVUI2SGs0b3BINVcxMmkvMjQKyb4ECznO3Jhf2WDofr9wLThK1eLDT4+4
        6u7TMhk0tVpijCEQHtTGpb+feM1ryp2NBo8tYKVxfgDOBVzFm8dQ7Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T16:56:38Z"
  mac: ENC[AES256_GCM,data:IeWBBsAFfBnOf/YgWQ7dKqbff5Iuw4QjG5beKuxW2zXXnBoEkDRcK4AtG1P38Ui0ds9MqZomubo1zTyPZNIj2b8JzUzofCogTHiZ7HeFgMkODRhZhnSfAZmXA0oHxfH8vFv/63OqpVsFuKZQ0OkgFO2O/obrMlaFlwseFIMNiEg=,iv:f4yhCblAgDJZzL/8oJ1uNtX6Jg37iAy2ykIt6IBpSd0=,tag:D7Z46L7yBFSugQr7x75yxQ==,type:str]
  version: 3.13.1
