apiVersion: v1
kind: Secret
metadata:
  name: unifi-api-credentials
  namespace: external-dns
type: Opaque
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:U3K5Fk6OgUSkSa65CsDHcj0qBSjZCYQ9h+dT0xFseM4=,iv:ioEuMB6NrcGj0PWirTWiGDCSmPR7TyEm4J+Fzvbewcc=,tag:NHDYYRWAoYsbaid5MmkuSQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQ2x0YUl1enNMYmtvY3NE
        VGlEcDdjS1ZzTzdzWm1YVDA5TFBQQ09pRzBvCkNOZWV3OGljNFlhcENOWlBja3Ni
        MXgzUitid2c1K0ZTY1NRUENDdndFR2sKLS0tIHF2dTAxVXJNaStOQkgrUDRXaTZO
        d1dYbU1JblhPazg1UjB4QXh2bFNTb2MKfOnSXxRFodOgEgCSOGJg49LAMZyFyCkT
        jSQ7sfnqzeO+VUOpud+SHiZBm064URtF5fCby48bIIKpT/l8FNczLg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NWIzVE1qMWJ6V3RFS0N2
        VTQyMTNhY1hlbEE0YUIwN0hTMlVVay8xdEhBClkxVE1RWk8rY3NoQ3JoWmswdkp3
        RmZIMWJVSC91WWljQ1lVcTN5UCtad1kKLS0tIFgrZ2JNMEJSKzF3eDBEK1BxeGd4
        Q2dKbkovVzdVNkpzMmF1NXZrajZDMGsKj2oJN1mKVwRprIKm+jBsjaFNiIUrIeI3
        pNP4+vcko2BsS5kGfnGDVhsCiOAaM69LtHYJZA0XxRrr31iXDg2JDA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z4st65rqt3su5rzqw2jvps3d9fjpaygvs263qh9c734m26xedfvsdfzvm7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T00:06:22Z"
  mac: ENC[AES256_GCM,data:p17Cmmohve0j8s56jJkDJFw0xBvVZ9Gluje1ND7Y3xVNDg2Dlc4gN5dNZCvURdiETSLmhoOZa7rvlrp08TokhpZhtLxYt2WZxe7hT/fmm2pXpyBH5PYjk4yeqhfGVgfwhZDpsb17E/2tOJ9n9IHh6V8u1/aoFMZ5aiDrfhYOixU=,iv:EXUmlwFs3d92eAOrorC05sQV4ZUKtUuVoVibPfUmLO0=,tag:LgIeK9YSRHps8tNZ3s+pFw==,type:str]
  version: 3.13.3
