apiVersion: v1
kind: Secret
metadata:
  name: unifi-api-credentials
  namespace: external-dns
type: Opaque
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:U3K5Fk6OgUSkSa65CsDHcj0qBSjZCYQ9h+dT0xFseM4=,iv:ioEuMB6NrcGj0PWirTWiGDCSmPR7TyEm4J+Fzvbewcc=,tag:NHDYYRWAoYsbaid5MmkuSQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBic242TmRJMElwdGkyL3M4
        UzVGRzQwazNKUVYvYnp5NHVvcFhZeXZFOENvClBqUXJRbHJadWJVWXFucmJjeFNL
        WHZYVHNFYkxpZWZQRGpmaVpRbEo2aGcKLS0tIE01WFNMbG5uZ3NlTDg4Q1V5UWlC
        dHh2eFJhWng1dTNxSVZmNzQ1OUo0LzgKSmM0HbkV0BV7DoAEEfHEPlUVzNPnWulf
        SeklX17h6tZPA/QU41QYfIorSmOz0F8wXmY0isP9AX1axgrEngFEuA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1whm4tsad6ku4u4sdhnaa54tklt8hd9fzvelwem86pxfs9hzk0pjskru2jj
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T00:06:22Z"
  mac: ENC[AES256_GCM,data:p17Cmmohve0j8s56jJkDJFw0xBvVZ9Gluje1ND7Y3xVNDg2Dlc4gN5dNZCvURdiETSLmhoOZa7rvlrp08TokhpZhtLxYt2WZxe7hT/fmm2pXpyBH5PYjk4yeqhfGVgfwhZDpsb17E/2tOJ9n9IHh6V8u1/aoFMZ5aiDrfhYOixU=,iv:EXUmlwFs3d92eAOrorC05sQV4ZUKtUuVoVibPfUmLO0=,tag:LgIeK9YSRHps8tNZ3s+pFw==,type:str]
  version: 3.13.3
