# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Flux Test

on:
  push:
    branches:
      - main
    paths:
      - k8s/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Flux Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run flux-local test
        uses: docker://ghcr.io/allenporter/flux-local:v8.2.0
        with:
          args: >-
            test
            --all-namespaces
            --enable-helm
            --path /github/workspace/k8s/clusters/homelab
            --sources flux-system
            --verbose
