name: label-sync

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/labels.yaml

jobs:
  label-sync:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yaml
          delete-other-labels: true
          token: ${{ secrets.GITHUB_TOKEN }}
